package com.example.wetravel.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Test;

class AccountTest {
    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link Account#Account()}
     *   <li>{@link Account#setAccountId(Long)}
     *   <li>{@link Account#setCommentList(List)}
     *   <li>{@link Account#setEmail(String)}
     *   <li>{@link Account#setFeedbackList(List)}
     *   <li>{@link Account#setIsBlock(Boolean)}
     *   <li>{@link Account#setPartner(Partner)}
     *   <li>{@link Account#setPassWord(String)}
     *   <li>{@link Account#setRoleId(Role)}
     *   <li>{@link Account#setTourList(List)}
     *   <li>{@link Account#setUser(User)}
     *   <li>{@link Account#setUserBookingList(List)}
     *   <li>{@link Account#getAccountId()}
     *   <li>{@link Account#getCommentList()}
     *   <li>{@link Account#getTourList()}
     *   <li>{@link Account#getUserBookingList()}
     *   <li>{@link Account#getEmail()}
     *   <li>{@link Account#getFeedbackList()}
     *   <li>{@link Account#getIsBlock()}
     *   <li>{@link Account#getPartner()}
     *   <li>{@link Account#getPassWord()}
     *   <li>{@link Account#getRoleId()}
     *   <li>{@link Account#getUser()}
     * </ul>
     */
    @Test
    void testConstructor() {
        Account actualAccount = new Account();
        actualAccount.setAccountId(1234567890L);
        ArrayList<Comment> commentList = new ArrayList<>();
        actualAccount.setCommentList(commentList);
        actualAccount.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList = new ArrayList<>();
        actualAccount.setFeedbackList(feedbackList);
        actualAccount.setIsBlock(true);
        Account account = new Account();
        account.setAccountId(1234567890L);
        ArrayList<Comment> commentList1 = new ArrayList<>();
        account.setCommentList(commentList1);
        account.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList1 = new ArrayList<>();
        account.setFeedbackList(feedbackList1);
        account.setIsBlock(true);
        account.setPartner(new Partner());
        account.setPassWord("Pass Word");
        account.setRoleId(new Role());
        ArrayList<Tour> tourList = new ArrayList<>();
        account.setTourList(tourList);
        account.setUser(new User());
        ArrayList<UserBooking> userBookingList = new ArrayList<>();
        account.setUserBookingList(userBookingList);
        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(new Partner());
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");
        ServiceCategory serviceCategory = new ServiceCategory();
        ArrayList<Partner> partnerList = new ArrayList<>();
        serviceCategory.setPartnerList(partnerList);
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList = new ArrayList<>();
        serviceCategory.setServiceList(serviceList);
        Partner partner = new Partner();
        partner.setAccountId(account);
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(companyPartner);
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(serviceCategory);
        ArrayList<Service> serviceList1 = new ArrayList<>();
        partner.setServiceList(serviceList1);
        Role role = new Role();
        ArrayList<Account> accountList = new ArrayList<>();
        role.setAccountList(accountList);
        role.setRoleId(123);
        role.setRoleName("Role Name");
        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        ArrayList<Comment> commentList2 = new ArrayList<>();
        account1.setCommentList(commentList2);
        account1.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList2 = new ArrayList<>();
        account1.setFeedbackList(feedbackList2);
        account1.setIsBlock(true);
        account1.setPartner(new Partner());
        account1.setPassWord("Pass Word");
        account1.setRoleId(new Role());
        ArrayList<Tour> tourList1 = new ArrayList<>();
        account1.setTourList(tourList1);
        account1.setUser(new User());
        ArrayList<UserBooking> userBookingList1 = new ArrayList<>();
        account1.setUserBookingList(userBookingList1);
        User user = new User();
        user.setAccountId(account1);
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);
        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        ArrayList<Comment> commentList3 = new ArrayList<>();
        account2.setCommentList(commentList3);
        account2.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList3 = new ArrayList<>();
        account2.setFeedbackList(feedbackList3);
        account2.setIsBlock(true);
        account2.setPartner(partner);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role);
        ArrayList<Tour> tourList2 = new ArrayList<>();
        account2.setTourList(tourList2);
        account2.setUser(user);
        ArrayList<UserBooking> userBookingList2 = new ArrayList<>();
        account2.setUserBookingList(userBookingList2);
        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        ArrayList<Comment> commentList4 = new ArrayList<>();
        account3.setCommentList(commentList4);
        account3.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList4 = new ArrayList<>();
        account3.setFeedbackList(feedbackList4);
        account3.setIsBlock(true);
        account3.setPartner(new Partner());
        account3.setPassWord("Pass Word");
        account3.setRoleId(new Role());
        ArrayList<Tour> tourList3 = new ArrayList<>();
        account3.setTourList(tourList3);
        account3.setUser(new User());
        ArrayList<UserBooking> userBookingList3 = new ArrayList<>();
        account3.setUserBookingList(userBookingList3);
        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(new Partner());
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");
        ServiceCategory serviceCategory1 = new ServiceCategory();
        ArrayList<Partner> partnerList1 = new ArrayList<>();
        serviceCategory1.setPartnerList(partnerList1);
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList2 = new ArrayList<>();
        serviceCategory1.setServiceList(serviceList2);
        Partner partner1 = new Partner();
        partner1.setAccountId(account3);
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(companyPartner1);
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(serviceCategory1);
        ArrayList<Service> serviceList3 = new ArrayList<>();
        partner1.setServiceList(serviceList3);
        CompanyPartner companyPartner2 = new CompanyPartner();
        companyPartner2.setAddress("42 Main St");
        companyPartner2.setBusinessCode("Business Code");
        companyPartner2.setCity("Oxford");
        companyPartner2.setCompanyName("Company Name");
        companyPartner2.setCompanyPartnerId(123L);
        companyPartner2.setEmail("jane.doe@example.org");
        companyPartner2.setFax("Fax");
        companyPartner2.setIncorporationDate("2020-03-01");
        companyPartner2.setPartnerId(partner1);
        companyPartner2.setPhone("4105551212");
        companyPartner2.setRegistrationDate("2020-03-01");
        companyPartner2.setShortName("Short Name");
        companyPartner2.setTaxCode("Tax Code");
        companyPartner2.setWebsite("Website");
        ServiceCategory serviceCategory2 = new ServiceCategory();
        ArrayList<Partner> partnerList2 = new ArrayList<>();
        serviceCategory2.setPartnerList(partnerList2);
        serviceCategory2.setServiceCategoryId(123L);
        serviceCategory2.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList4 = new ArrayList<>();
        serviceCategory2.setServiceList(serviceList4);
        Partner partner2 = new Partner();
        partner2.setAccountId(account2);
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(companyPartner2);
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(serviceCategory2);
        ArrayList<Service> serviceList5 = new ArrayList<>();
        partner2.setServiceList(serviceList5);
        actualAccount.setPartner(partner2);
        actualAccount.setPassWord("Pass Word");
        Role role1 = new Role();
        ArrayList<Account> accountList1 = new ArrayList<>();
        role1.setAccountList(accountList1);
        role1.setRoleId(123);
        role1.setRoleName("Role Name");
        actualAccount.setRoleId(role1);
        ArrayList<Tour> tourList4 = new ArrayList<>();
        actualAccount.setTourList(tourList4);
        Account account4 = new Account();
        account4.setAccountId(1234567890L);
        ArrayList<Comment> commentList5 = new ArrayList<>();
        account4.setCommentList(commentList5);
        account4.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList5 = new ArrayList<>();
        account4.setFeedbackList(feedbackList5);
        account4.setIsBlock(true);
        account4.setPartner(new Partner());
        account4.setPassWord("Pass Word");
        account4.setRoleId(new Role());
        ArrayList<Tour> tourList5 = new ArrayList<>();
        account4.setTourList(tourList5);
        account4.setUser(new User());
        ArrayList<UserBooking> userBookingList4 = new ArrayList<>();
        account4.setUserBookingList(userBookingList4);
        CompanyPartner companyPartner3 = new CompanyPartner();
        companyPartner3.setAddress("42 Main St");
        companyPartner3.setBusinessCode("Business Code");
        companyPartner3.setCity("Oxford");
        companyPartner3.setCompanyName("Company Name");
        companyPartner3.setCompanyPartnerId(123L);
        companyPartner3.setEmail("jane.doe@example.org");
        companyPartner3.setFax("Fax");
        companyPartner3.setIncorporationDate("2020-03-01");
        companyPartner3.setPartnerId(new Partner());
        companyPartner3.setPhone("4105551212");
        companyPartner3.setRegistrationDate("2020-03-01");
        companyPartner3.setShortName("Short Name");
        companyPartner3.setTaxCode("Tax Code");
        companyPartner3.setWebsite("Website");
        ServiceCategory serviceCategory3 = new ServiceCategory();
        ArrayList<Partner> partnerList3 = new ArrayList<>();
        serviceCategory3.setPartnerList(partnerList3);
        serviceCategory3.setServiceCategoryId(123L);
        serviceCategory3.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList6 = new ArrayList<>();
        serviceCategory3.setServiceList(serviceList6);
        Partner partner3 = new Partner();
        partner3.setAccountId(account4);
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(companyPartner3);
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(serviceCategory3);
        ArrayList<Service> serviceList7 = new ArrayList<>();
        partner3.setServiceList(serviceList7);
        Role role2 = new Role();
        ArrayList<Account> accountList2 = new ArrayList<>();
        role2.setAccountList(accountList2);
        role2.setRoleId(123);
        role2.setRoleName("Role Name");
        Account account5 = new Account();
        account5.setAccountId(1234567890L);
        ArrayList<Comment> commentList6 = new ArrayList<>();
        account5.setCommentList(commentList6);
        account5.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList6 = new ArrayList<>();
        account5.setFeedbackList(feedbackList6);
        account5.setIsBlock(true);
        account5.setPartner(new Partner());
        account5.setPassWord("Pass Word");
        account5.setRoleId(new Role());
        ArrayList<Tour> tourList6 = new ArrayList<>();
        account5.setTourList(tourList6);
        account5.setUser(new User());
        ArrayList<UserBooking> userBookingList5 = new ArrayList<>();
        account5.setUserBookingList(userBookingList5);
        User user1 = new User();
        user1.setAccountId(account5);
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);
        Account account6 = new Account();
        account6.setAccountId(1234567890L);
        ArrayList<Comment> commentList7 = new ArrayList<>();
        account6.setCommentList(commentList7);
        account6.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList7 = new ArrayList<>();
        account6.setFeedbackList(feedbackList7);
        account6.setIsBlock(true);
        account6.setPartner(partner3);
        account6.setPassWord("Pass Word");
        account6.setRoleId(role2);
        ArrayList<Tour> tourList7 = new ArrayList<>();
        account6.setTourList(tourList7);
        account6.setUser(user1);
        ArrayList<UserBooking> userBookingList6 = new ArrayList<>();
        account6.setUserBookingList(userBookingList6);
        User user2 = new User();
        user2.setAccountId(account6);
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);
        actualAccount.setUser(user2);
        ArrayList<UserBooking> userBookingList7 = new ArrayList<>();
        actualAccount.setUserBookingList(userBookingList7);
        assertEquals(1234567890L, actualAccount.getAccountId().longValue());
        List<Comment> commentList8 = actualAccount.getCommentList();
        assertSame(commentList, commentList8);
        assertEquals(feedbackList, commentList8);
        assertEquals(commentList3, commentList8);
        assertEquals(feedbackList3, commentList8);
        assertEquals(commentList1, commentList8);
        assertEquals(feedbackList1, commentList8);
        assertEquals(tourList, commentList8);
        assertEquals(userBookingList, commentList8);
        assertEquals(partnerList, commentList8);
        assertEquals(serviceList, commentList8);
        assertEquals(serviceList1, commentList8);
        assertEquals(accountList, commentList8);
        assertEquals(tourList2, commentList8);
        assertEquals(commentList2, commentList8);
        assertEquals(feedbackList2, commentList8);
        assertEquals(tourList1, commentList8);
        assertEquals(userBookingList1, commentList8);
        assertEquals(userBookingList2, commentList8);
        assertEquals(commentList4, commentList8);
        assertEquals(feedbackList4, commentList8);
        assertEquals(tourList3, commentList8);
        assertEquals(userBookingList3, commentList8);
        assertEquals(partnerList1, commentList8);
        assertEquals(serviceList2, commentList8);
        assertEquals(serviceList3, commentList8);
        assertEquals(partnerList2, commentList8);
        assertEquals(serviceList4, commentList8);
        assertEquals(serviceList5, commentList8);
        assertEquals(accountList1, commentList8);
        assertEquals(commentList7, commentList8);
        assertEquals(feedbackList7, commentList8);
        assertEquals(commentList5, commentList8);
        assertEquals(feedbackList5, commentList8);
        assertEquals(tourList5, commentList8);
        assertEquals(userBookingList4, commentList8);
        assertEquals(partnerList3, commentList8);
        assertEquals(serviceList6, commentList8);
        assertEquals(serviceList7, commentList8);
        assertEquals(accountList2, commentList8);
        assertEquals(tourList7, commentList8);
        assertEquals(commentList6, commentList8);
        assertEquals(feedbackList6, commentList8);
        assertEquals(tourList6, commentList8);
        assertEquals(userBookingList5, commentList8);
        assertEquals(userBookingList6, commentList8);
        List<Tour> tourList8 = actualAccount.getTourList();
        assertEquals(tourList8, commentList8);
        List<UserBooking> userBookingList8 = actualAccount.getUserBookingList();
        assertEquals(userBookingList8, commentList8);
        assertEquals("jane.doe@example.org", actualAccount.getEmail());
        List<Feedback> feedbackList8 = actualAccount.getFeedbackList();
        assertSame(feedbackList, feedbackList8);
        assertEquals(commentList3, feedbackList8);
        assertEquals(feedbackList3, feedbackList8);
        assertEquals(commentList1, feedbackList8);
        assertEquals(feedbackList1, feedbackList8);
        assertEquals(tourList, feedbackList8);
        assertEquals(userBookingList, feedbackList8);
        assertEquals(partnerList, feedbackList8);
        assertEquals(serviceList, feedbackList8);
        assertEquals(serviceList1, feedbackList8);
        assertEquals(accountList, feedbackList8);
        assertEquals(tourList2, feedbackList8);
        assertEquals(commentList2, feedbackList8);
        assertEquals(feedbackList2, feedbackList8);
        assertEquals(tourList1, feedbackList8);
        assertEquals(userBookingList1, feedbackList8);
        assertEquals(userBookingList2, feedbackList8);
        assertEquals(commentList4, feedbackList8);
        assertEquals(feedbackList4, feedbackList8);
        assertEquals(tourList3, feedbackList8);
        assertEquals(userBookingList3, feedbackList8);
        assertEquals(partnerList1, feedbackList8);
        assertEquals(serviceList2, feedbackList8);
        assertEquals(serviceList3, feedbackList8);
        assertEquals(partnerList2, feedbackList8);
        assertEquals(serviceList4, feedbackList8);
        assertEquals(serviceList5, feedbackList8);
        assertEquals(accountList1, feedbackList8);
        assertEquals(commentList7, feedbackList8);
        assertEquals(feedbackList7, feedbackList8);
        assertEquals(commentList5, feedbackList8);
        assertEquals(feedbackList5, feedbackList8);
        assertEquals(tourList5, feedbackList8);
        assertEquals(userBookingList4, feedbackList8);
        assertEquals(partnerList3, feedbackList8);
        assertEquals(serviceList6, feedbackList8);
        assertEquals(serviceList7, feedbackList8);
        assertEquals(accountList2, feedbackList8);
        assertEquals(tourList7, feedbackList8);
        assertEquals(commentList6, feedbackList8);
        assertEquals(feedbackList6, feedbackList8);
        assertEquals(tourList6, feedbackList8);
        assertEquals(userBookingList5, feedbackList8);
        assertEquals(userBookingList6, feedbackList8);
        assertEquals(commentList8, feedbackList8);
        assertEquals(tourList8, feedbackList8);
        assertEquals(userBookingList8, feedbackList8);
        assertTrue(actualAccount.getIsBlock());
        assertSame(partner2, actualAccount.getPartner());
        assertEquals("Pass Word", actualAccount.getPassWord());
        assertSame(role1, actualAccount.getRoleId());
        assertSame(tourList4, tourList8);
        assertEquals(commentList, tourList8);
        assertEquals(feedbackList, tourList8);
        assertEquals(commentList3, tourList8);
        assertEquals(feedbackList3, tourList8);
        assertEquals(commentList1, tourList8);
        assertEquals(feedbackList1, tourList8);
        assertEquals(tourList, tourList8);
        assertEquals(userBookingList, tourList8);
        assertEquals(partnerList, tourList8);
        assertEquals(serviceList, tourList8);
        assertEquals(serviceList1, tourList8);
        assertEquals(accountList, tourList8);
        assertEquals(tourList2, tourList8);
        assertEquals(commentList2, tourList8);
        assertEquals(feedbackList2, tourList8);
        assertEquals(tourList1, tourList8);
        assertEquals(userBookingList1, tourList8);
        assertEquals(userBookingList2, tourList8);
        assertEquals(commentList4, tourList8);
        assertEquals(feedbackList4, tourList8);
        assertEquals(tourList3, tourList8);
        assertEquals(userBookingList3, tourList8);
        assertEquals(partnerList1, tourList8);
        assertEquals(serviceList2, tourList8);
        assertEquals(serviceList3, tourList8);
        assertEquals(partnerList2, tourList8);
        assertEquals(serviceList4, tourList8);
        assertEquals(serviceList5, tourList8);
        assertEquals(accountList1, tourList8);
        assertEquals(commentList7, tourList8);
        assertEquals(feedbackList7, tourList8);
        assertEquals(commentList5, tourList8);
        assertEquals(feedbackList5, tourList8);
        assertEquals(tourList5, tourList8);
        assertEquals(userBookingList4, tourList8);
        assertEquals(partnerList3, tourList8);
        assertEquals(serviceList6, tourList8);
        assertEquals(serviceList7, tourList8);
        assertEquals(accountList2, tourList8);
        assertEquals(tourList7, tourList8);
        assertEquals(commentList6, tourList8);
        assertEquals(feedbackList6, tourList8);
        assertEquals(tourList6, tourList8);
        assertEquals(userBookingList5, tourList8);
        assertEquals(userBookingList6, tourList8);
        assertEquals(userBookingList8, tourList8);
        assertSame(user2, actualAccount.getUser());
        assertSame(userBookingList7, userBookingList8);
        assertEquals(commentList, userBookingList8);
        assertEquals(feedbackList, userBookingList8);
        assertEquals(commentList3, userBookingList8);
        assertEquals(feedbackList3, userBookingList8);
        assertEquals(commentList1, userBookingList8);
        assertEquals(feedbackList1, userBookingList8);
        assertEquals(tourList, userBookingList8);
        assertEquals(userBookingList, userBookingList8);
        assertEquals(partnerList, userBookingList8);
        assertEquals(serviceList, userBookingList8);
        assertEquals(serviceList1, userBookingList8);
        assertEquals(accountList, userBookingList8);
        assertEquals(tourList2, userBookingList8);
        assertEquals(commentList2, userBookingList8);
        assertEquals(feedbackList2, userBookingList8);
        assertEquals(tourList1, userBookingList8);
        assertEquals(userBookingList1, userBookingList8);
        assertEquals(userBookingList2, userBookingList8);
        assertEquals(commentList4, userBookingList8);
        assertEquals(feedbackList4, userBookingList8);
        assertEquals(tourList3, userBookingList8);
        assertEquals(userBookingList3, userBookingList8);
        assertEquals(partnerList1, userBookingList8);
        assertEquals(serviceList2, userBookingList8);
        assertEquals(serviceList3, userBookingList8);
        assertEquals(partnerList2, userBookingList8);
        assertEquals(serviceList4, userBookingList8);
        assertEquals(serviceList5, userBookingList8);
        assertEquals(accountList1, userBookingList8);
        assertEquals(tourList4, userBookingList8);
        assertEquals(commentList7, userBookingList8);
        assertEquals(feedbackList7, userBookingList8);
        assertEquals(commentList5, userBookingList8);
        assertEquals(feedbackList5, userBookingList8);
        assertEquals(tourList5, userBookingList8);
        assertEquals(userBookingList4, userBookingList8);
        assertEquals(partnerList3, userBookingList8);
        assertEquals(serviceList6, userBookingList8);
        assertEquals(serviceList7, userBookingList8);
        assertEquals(accountList2, userBookingList8);
        assertEquals(tourList7, userBookingList8);
        assertEquals(commentList6, userBookingList8);
        assertEquals(feedbackList6, userBookingList8);
        assertEquals(tourList6, userBookingList8);
        assertEquals(userBookingList5, userBookingList8);
        assertEquals(userBookingList6, userBookingList8);
    }

    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link Account#Account(Long, String, String, Boolean, Role, User, Partner, List, List, List, List)}
     *   <li>{@link Account#Account()}
     *   <li>{@link Account#setAccountId(Long)}
     *   <li>{@link Account#setCommentList(List)}
     *   <li>{@link Account#setEmail(String)}
     *   <li>{@link Account#setFeedbackList(List)}
     *   <li>{@link Account#setIsBlock(Boolean)}
     *   <li>{@link Account#setPartner(Partner)}
     *   <li>{@link Account#setPassWord(String)}
     *   <li>{@link Account#setRoleId(Role)}
     *   <li>{@link Account#setTourList(List)}
     *   <li>{@link Account#setUser(User)}
     *   <li>{@link Account#setUserBookingList(List)}
     *   <li>{@link Account#getAccountId()}
     *   <li>{@link Account#getCommentList()}
     *   <li>{@link Account#getTourList()}
     *   <li>{@link Account#getUserBookingList()}
     *   <li>{@link Account#getEmail()}
     *   <li>{@link Account#getFeedbackList()}
     *   <li>{@link Account#getIsBlock()}
     *   <li>{@link Account#getPartner()}
     *   <li>{@link Account#getPassWord()}
     *   <li>{@link Account#getRoleId()}
     *   <li>{@link Account#getUser()}
     * </ul>
     */
    @Test
    void testConstructor2() {
        Role role = new Role();
        ArrayList<Account> accountList = new ArrayList<>();
        role.setAccountList(accountList);
        role.setRoleId(123);
        role.setRoleName("Role Name");

        Account account = new Account();
        account.setAccountId(1234567890L);
        ArrayList<Comment> commentList = new ArrayList<>();
        account.setCommentList(commentList);
        account.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList = new ArrayList<>();
        account.setFeedbackList(feedbackList);
        account.setIsBlock(true);
        account.setPartner(new Partner());
        account.setPassWord("Pass Word");
        account.setRoleId(new Role());
        ArrayList<Tour> tourList = new ArrayList<>();
        account.setTourList(tourList);
        account.setUser(new User());
        ArrayList<UserBooking> userBookingList = new ArrayList<>();
        account.setUserBookingList(userBookingList);

        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(new Partner());
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");

        ServiceCategory serviceCategory = new ServiceCategory();
        ArrayList<Partner> partnerList = new ArrayList<>();
        serviceCategory.setPartnerList(partnerList);
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList = new ArrayList<>();
        serviceCategory.setServiceList(serviceList);

        Partner partner = new Partner();
        partner.setAccountId(account);
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(companyPartner);
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(serviceCategory);
        ArrayList<Service> serviceList1 = new ArrayList<>();
        partner.setServiceList(serviceList1);

        Role role1 = new Role();
        ArrayList<Account> accountList1 = new ArrayList<>();
        role1.setAccountList(accountList1);
        role1.setRoleId(123);
        role1.setRoleName("Role Name");

        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        ArrayList<Comment> commentList1 = new ArrayList<>();
        account1.setCommentList(commentList1);
        account1.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList1 = new ArrayList<>();
        account1.setFeedbackList(feedbackList1);
        account1.setIsBlock(true);
        account1.setPartner(new Partner());
        account1.setPassWord("Pass Word");
        account1.setRoleId(new Role());
        ArrayList<Tour> tourList1 = new ArrayList<>();
        account1.setTourList(tourList1);
        account1.setUser(new User());
        ArrayList<UserBooking> userBookingList1 = new ArrayList<>();
        account1.setUserBookingList(userBookingList1);

        User user = new User();
        user.setAccountId(account1);
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);

        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        ArrayList<Comment> commentList2 = new ArrayList<>();
        account2.setCommentList(commentList2);
        account2.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList2 = new ArrayList<>();
        account2.setFeedbackList(feedbackList2);
        account2.setIsBlock(true);
        account2.setPartner(partner);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role1);
        ArrayList<Tour> tourList2 = new ArrayList<>();
        account2.setTourList(tourList2);
        account2.setUser(user);
        ArrayList<UserBooking> userBookingList2 = new ArrayList<>();
        account2.setUserBookingList(userBookingList2);

        User user1 = new User();
        user1.setAccountId(account2);
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);

        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        ArrayList<Comment> commentList3 = new ArrayList<>();
        account3.setCommentList(commentList3);
        account3.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList3 = new ArrayList<>();
        account3.setFeedbackList(feedbackList3);
        account3.setIsBlock(true);
        account3.setPartner(new Partner());
        account3.setPassWord("Pass Word");
        account3.setRoleId(new Role());
        ArrayList<Tour> tourList3 = new ArrayList<>();
        account3.setTourList(tourList3);
        account3.setUser(new User());
        ArrayList<UserBooking> userBookingList3 = new ArrayList<>();
        account3.setUserBookingList(userBookingList3);

        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(new Partner());
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");

        ServiceCategory serviceCategory1 = new ServiceCategory();
        ArrayList<Partner> partnerList1 = new ArrayList<>();
        serviceCategory1.setPartnerList(partnerList1);
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList2 = new ArrayList<>();
        serviceCategory1.setServiceList(serviceList2);

        Partner partner1 = new Partner();
        partner1.setAccountId(account3);
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(companyPartner1);
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(serviceCategory1);
        ArrayList<Service> serviceList3 = new ArrayList<>();
        partner1.setServiceList(serviceList3);

        Role role2 = new Role();
        ArrayList<Account> accountList2 = new ArrayList<>();
        role2.setAccountList(accountList2);
        role2.setRoleId(123);
        role2.setRoleName("Role Name");

        Account account4 = new Account();
        account4.setAccountId(1234567890L);
        ArrayList<Comment> commentList4 = new ArrayList<>();
        account4.setCommentList(commentList4);
        account4.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList4 = new ArrayList<>();
        account4.setFeedbackList(feedbackList4);
        account4.setIsBlock(true);
        account4.setPartner(new Partner());
        account4.setPassWord("Pass Word");
        account4.setRoleId(new Role());
        ArrayList<Tour> tourList4 = new ArrayList<>();
        account4.setTourList(tourList4);
        account4.setUser(new User());
        ArrayList<UserBooking> userBookingList4 = new ArrayList<>();
        account4.setUserBookingList(userBookingList4);

        User user2 = new User();
        user2.setAccountId(account4);
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);

        Account account5 = new Account();
        account5.setAccountId(1234567890L);
        ArrayList<Comment> commentList5 = new ArrayList<>();
        account5.setCommentList(commentList5);
        account5.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList5 = new ArrayList<>();
        account5.setFeedbackList(feedbackList5);
        account5.setIsBlock(true);
        account5.setPartner(partner1);
        account5.setPassWord("Pass Word");
        account5.setRoleId(role2);
        ArrayList<Tour> tourList5 = new ArrayList<>();
        account5.setTourList(tourList5);
        account5.setUser(user2);
        ArrayList<UserBooking> userBookingList5 = new ArrayList<>();
        account5.setUserBookingList(userBookingList5);

        Account account6 = new Account();
        account6.setAccountId(1234567890L);
        ArrayList<Comment> commentList6 = new ArrayList<>();
        account6.setCommentList(commentList6);
        account6.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList6 = new ArrayList<>();
        account6.setFeedbackList(feedbackList6);
        account6.setIsBlock(true);
        account6.setPartner(new Partner());
        account6.setPassWord("Pass Word");
        account6.setRoleId(new Role());
        ArrayList<Tour> tourList6 = new ArrayList<>();
        account6.setTourList(tourList6);
        account6.setUser(new User());
        ArrayList<UserBooking> userBookingList6 = new ArrayList<>();
        account6.setUserBookingList(userBookingList6);

        CompanyPartner companyPartner2 = new CompanyPartner();
        companyPartner2.setAddress("42 Main St");
        companyPartner2.setBusinessCode("Business Code");
        companyPartner2.setCity("Oxford");
        companyPartner2.setCompanyName("Company Name");
        companyPartner2.setCompanyPartnerId(123L);
        companyPartner2.setEmail("jane.doe@example.org");
        companyPartner2.setFax("Fax");
        companyPartner2.setIncorporationDate("2020-03-01");
        companyPartner2.setPartnerId(new Partner());
        companyPartner2.setPhone("4105551212");
        companyPartner2.setRegistrationDate("2020-03-01");
        companyPartner2.setShortName("Short Name");
        companyPartner2.setTaxCode("Tax Code");
        companyPartner2.setWebsite("Website");

        ServiceCategory serviceCategory2 = new ServiceCategory();
        ArrayList<Partner> partnerList2 = new ArrayList<>();
        serviceCategory2.setPartnerList(partnerList2);
        serviceCategory2.setServiceCategoryId(123L);
        serviceCategory2.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList4 = new ArrayList<>();
        serviceCategory2.setServiceList(serviceList4);

        Partner partner2 = new Partner();
        partner2.setAccountId(account6);
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(companyPartner2);
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(serviceCategory2);
        ArrayList<Service> serviceList5 = new ArrayList<>();
        partner2.setServiceList(serviceList5);

        CompanyPartner companyPartner3 = new CompanyPartner();
        companyPartner3.setAddress("42 Main St");
        companyPartner3.setBusinessCode("Business Code");
        companyPartner3.setCity("Oxford");
        companyPartner3.setCompanyName("Company Name");
        companyPartner3.setCompanyPartnerId(123L);
        companyPartner3.setEmail("jane.doe@example.org");
        companyPartner3.setFax("Fax");
        companyPartner3.setIncorporationDate("2020-03-01");
        companyPartner3.setPartnerId(partner2);
        companyPartner3.setPhone("4105551212");
        companyPartner3.setRegistrationDate("2020-03-01");
        companyPartner3.setShortName("Short Name");
        companyPartner3.setTaxCode("Tax Code");
        companyPartner3.setWebsite("Website");

        ServiceCategory serviceCategory3 = new ServiceCategory();
        ArrayList<Partner> partnerList3 = new ArrayList<>();
        serviceCategory3.setPartnerList(partnerList3);
        serviceCategory3.setServiceCategoryId(123L);
        serviceCategory3.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList6 = new ArrayList<>();
        serviceCategory3.setServiceList(serviceList6);

        Partner partner3 = new Partner();
        partner3.setAccountId(account5);
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(companyPartner3);
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(serviceCategory3);
        ArrayList<Service> serviceList7 = new ArrayList<>();
        partner3.setServiceList(serviceList7);
        ArrayList<UserBooking> userBookingList7 = new ArrayList<>();
        ArrayList<Tour> tourList7 = new ArrayList<>();
        ArrayList<Feedback> feedbackList7 = new ArrayList<>();
        ArrayList<Comment> commentList7 = new ArrayList<>();
        Account actualAccount = new Account(1234567890L, "jane.doe@example.org", "Pass Word", true, role, user1, partner3,
                userBookingList7, tourList7, feedbackList7, commentList7);
        actualAccount.setAccountId(1234567890L);
        ArrayList<Comment> commentList8 = new ArrayList<>();
        actualAccount.setCommentList(commentList8);
        actualAccount.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList8 = new ArrayList<>();
        actualAccount.setFeedbackList(feedbackList8);
        actualAccount.setIsBlock(true);
        Account account7 = new Account();
        account7.setAccountId(1234567890L);
        ArrayList<Comment> commentList9 = new ArrayList<>();
        account7.setCommentList(commentList9);
        account7.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList9 = new ArrayList<>();
        account7.setFeedbackList(feedbackList9);
        account7.setIsBlock(true);
        account7.setPartner(new Partner());
        account7.setPassWord("Pass Word");
        account7.setRoleId(new Role());
        ArrayList<Tour> tourList8 = new ArrayList<>();
        account7.setTourList(tourList8);
        account7.setUser(new User());
        ArrayList<UserBooking> userBookingList8 = new ArrayList<>();
        account7.setUserBookingList(userBookingList8);
        CompanyPartner companyPartner4 = new CompanyPartner();
        companyPartner4.setAddress("42 Main St");
        companyPartner4.setBusinessCode("Business Code");
        companyPartner4.setCity("Oxford");
        companyPartner4.setCompanyName("Company Name");
        companyPartner4.setCompanyPartnerId(123L);
        companyPartner4.setEmail("jane.doe@example.org");
        companyPartner4.setFax("Fax");
        companyPartner4.setIncorporationDate("2020-03-01");
        companyPartner4.setPartnerId(new Partner());
        companyPartner4.setPhone("4105551212");
        companyPartner4.setRegistrationDate("2020-03-01");
        companyPartner4.setShortName("Short Name");
        companyPartner4.setTaxCode("Tax Code");
        companyPartner4.setWebsite("Website");
        ServiceCategory serviceCategory4 = new ServiceCategory();
        ArrayList<Partner> partnerList4 = new ArrayList<>();
        serviceCategory4.setPartnerList(partnerList4);
        serviceCategory4.setServiceCategoryId(123L);
        serviceCategory4.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList8 = new ArrayList<>();
        serviceCategory4.setServiceList(serviceList8);
        Partner partner4 = new Partner();
        partner4.setAccountId(account7);
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(companyPartner4);
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(serviceCategory4);
        ArrayList<Service> serviceList9 = new ArrayList<>();
        partner4.setServiceList(serviceList9);
        Role role3 = new Role();
        ArrayList<Account> accountList3 = new ArrayList<>();
        role3.setAccountList(accountList3);
        role3.setRoleId(123);
        role3.setRoleName("Role Name");
        Account account8 = new Account();
        account8.setAccountId(1234567890L);
        ArrayList<Comment> commentList10 = new ArrayList<>();
        account8.setCommentList(commentList10);
        account8.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList10 = new ArrayList<>();
        account8.setFeedbackList(feedbackList10);
        account8.setIsBlock(true);
        account8.setPartner(new Partner());
        account8.setPassWord("Pass Word");
        account8.setRoleId(new Role());
        ArrayList<Tour> tourList9 = new ArrayList<>();
        account8.setTourList(tourList9);
        account8.setUser(new User());
        ArrayList<UserBooking> userBookingList9 = new ArrayList<>();
        account8.setUserBookingList(userBookingList9);
        User user3 = new User();
        user3.setAccountId(account8);
        user3.setAddress("42 Main St");
        user3.setBirthDate("2020-03-01");
        user3.setCity("Oxford");
        user3.setFirstName("Jane");
        user3.setGender("Gender");
        user3.setIsPrivate(true);
        user3.setLastName("Doe");
        user3.setPhone("4105551212");
        user3.setRankPoint(1);
        user3.setUserId(123L);
        Account account9 = new Account();
        account9.setAccountId(1234567890L);
        ArrayList<Comment> commentList11 = new ArrayList<>();
        account9.setCommentList(commentList11);
        account9.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList11 = new ArrayList<>();
        account9.setFeedbackList(feedbackList11);
        account9.setIsBlock(true);
        account9.setPartner(partner4);
        account9.setPassWord("Pass Word");
        account9.setRoleId(role3);
        ArrayList<Tour> tourList10 = new ArrayList<>();
        account9.setTourList(tourList10);
        account9.setUser(user3);
        ArrayList<UserBooking> userBookingList10 = new ArrayList<>();
        account9.setUserBookingList(userBookingList10);
        Account account10 = new Account();
        account10.setAccountId(1234567890L);
        ArrayList<Comment> commentList12 = new ArrayList<>();
        account10.setCommentList(commentList12);
        account10.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList12 = new ArrayList<>();
        account10.setFeedbackList(feedbackList12);
        account10.setIsBlock(true);
        account10.setPartner(new Partner());
        account10.setPassWord("Pass Word");
        account10.setRoleId(new Role());
        ArrayList<Tour> tourList11 = new ArrayList<>();
        account10.setTourList(tourList11);
        account10.setUser(new User());
        ArrayList<UserBooking> userBookingList11 = new ArrayList<>();
        account10.setUserBookingList(userBookingList11);
        CompanyPartner companyPartner5 = new CompanyPartner();
        companyPartner5.setAddress("42 Main St");
        companyPartner5.setBusinessCode("Business Code");
        companyPartner5.setCity("Oxford");
        companyPartner5.setCompanyName("Company Name");
        companyPartner5.setCompanyPartnerId(123L);
        companyPartner5.setEmail("jane.doe@example.org");
        companyPartner5.setFax("Fax");
        companyPartner5.setIncorporationDate("2020-03-01");
        companyPartner5.setPartnerId(new Partner());
        companyPartner5.setPhone("4105551212");
        companyPartner5.setRegistrationDate("2020-03-01");
        companyPartner5.setShortName("Short Name");
        companyPartner5.setTaxCode("Tax Code");
        companyPartner5.setWebsite("Website");
        ServiceCategory serviceCategory5 = new ServiceCategory();
        ArrayList<Partner> partnerList5 = new ArrayList<>();
        serviceCategory5.setPartnerList(partnerList5);
        serviceCategory5.setServiceCategoryId(123L);
        serviceCategory5.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList10 = new ArrayList<>();
        serviceCategory5.setServiceList(serviceList10);
        Partner partner5 = new Partner();
        partner5.setAccountId(account10);
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(companyPartner5);
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(serviceCategory5);
        ArrayList<Service> serviceList11 = new ArrayList<>();
        partner5.setServiceList(serviceList11);
        CompanyPartner companyPartner6 = new CompanyPartner();
        companyPartner6.setAddress("42 Main St");
        companyPartner6.setBusinessCode("Business Code");
        companyPartner6.setCity("Oxford");
        companyPartner6.setCompanyName("Company Name");
        companyPartner6.setCompanyPartnerId(123L);
        companyPartner6.setEmail("jane.doe@example.org");
        companyPartner6.setFax("Fax");
        companyPartner6.setIncorporationDate("2020-03-01");
        companyPartner6.setPartnerId(partner5);
        companyPartner6.setPhone("4105551212");
        companyPartner6.setRegistrationDate("2020-03-01");
        companyPartner6.setShortName("Short Name");
        companyPartner6.setTaxCode("Tax Code");
        companyPartner6.setWebsite("Website");
        ServiceCategory serviceCategory6 = new ServiceCategory();
        ArrayList<Partner> partnerList6 = new ArrayList<>();
        serviceCategory6.setPartnerList(partnerList6);
        serviceCategory6.setServiceCategoryId(123L);
        serviceCategory6.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList12 = new ArrayList<>();
        serviceCategory6.setServiceList(serviceList12);
        Partner partner6 = new Partner();
        partner6.setAccountId(account9);
        partner6.setAddress("42 Main St");
        partner6.setBirthDate("2020-03-01");
        partner6.setCity("Oxford");
        partner6.setCompanyPartnerId(companyPartner6);
        partner6.setDateIssue("2020-03-01");
        partner6.setDepartment("Department");
        partner6.setEmail("jane.doe@example.org");
        partner6.setFirstName("Jane");
        partner6.setGender("Gender");
        partner6.setLastName("Doe");
        partner6.setNumberIdCard("42");
        partner6.setPartnerId(123L);
        partner6.setPhone("4105551212");
        partner6.setPlaceIssue("Place Issue");
        partner6.setPosition("Position");
        partner6.setServiceCategoryId(serviceCategory6);
        ArrayList<Service> serviceList13 = new ArrayList<>();
        partner6.setServiceList(serviceList13);
        actualAccount.setPartner(partner6);
        actualAccount.setPassWord("Pass Word");
        Role role4 = new Role();
        ArrayList<Account> accountList4 = new ArrayList<>();
        role4.setAccountList(accountList4);
        role4.setRoleId(123);
        role4.setRoleName("Role Name");
        actualAccount.setRoleId(role4);
        ArrayList<Tour> tourList12 = new ArrayList<>();
        actualAccount.setTourList(tourList12);
        Account account11 = new Account();
        account11.setAccountId(1234567890L);
        ArrayList<Comment> commentList13 = new ArrayList<>();
        account11.setCommentList(commentList13);
        account11.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList13 = new ArrayList<>();
        account11.setFeedbackList(feedbackList13);
        account11.setIsBlock(true);
        account11.setPartner(new Partner());
        account11.setPassWord("Pass Word");
        account11.setRoleId(new Role());
        ArrayList<Tour> tourList13 = new ArrayList<>();
        account11.setTourList(tourList13);
        account11.setUser(new User());
        ArrayList<UserBooking> userBookingList12 = new ArrayList<>();
        account11.setUserBookingList(userBookingList12);
        CompanyPartner companyPartner7 = new CompanyPartner();
        companyPartner7.setAddress("42 Main St");
        companyPartner7.setBusinessCode("Business Code");
        companyPartner7.setCity("Oxford");
        companyPartner7.setCompanyName("Company Name");
        companyPartner7.setCompanyPartnerId(123L);
        companyPartner7.setEmail("jane.doe@example.org");
        companyPartner7.setFax("Fax");
        companyPartner7.setIncorporationDate("2020-03-01");
        companyPartner7.setPartnerId(new Partner());
        companyPartner7.setPhone("4105551212");
        companyPartner7.setRegistrationDate("2020-03-01");
        companyPartner7.setShortName("Short Name");
        companyPartner7.setTaxCode("Tax Code");
        companyPartner7.setWebsite("Website");
        ServiceCategory serviceCategory7 = new ServiceCategory();
        ArrayList<Partner> partnerList7 = new ArrayList<>();
        serviceCategory7.setPartnerList(partnerList7);
        serviceCategory7.setServiceCategoryId(123L);
        serviceCategory7.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList14 = new ArrayList<>();
        serviceCategory7.setServiceList(serviceList14);
        Partner partner7 = new Partner();
        partner7.setAccountId(account11);
        partner7.setAddress("42 Main St");
        partner7.setBirthDate("2020-03-01");
        partner7.setCity("Oxford");
        partner7.setCompanyPartnerId(companyPartner7);
        partner7.setDateIssue("2020-03-01");
        partner7.setDepartment("Department");
        partner7.setEmail("jane.doe@example.org");
        partner7.setFirstName("Jane");
        partner7.setGender("Gender");
        partner7.setLastName("Doe");
        partner7.setNumberIdCard("42");
        partner7.setPartnerId(123L);
        partner7.setPhone("4105551212");
        partner7.setPlaceIssue("Place Issue");
        partner7.setPosition("Position");
        partner7.setServiceCategoryId(serviceCategory7);
        ArrayList<Service> serviceList15 = new ArrayList<>();
        partner7.setServiceList(serviceList15);
        Role role5 = new Role();
        ArrayList<Account> accountList5 = new ArrayList<>();
        role5.setAccountList(accountList5);
        role5.setRoleId(123);
        role5.setRoleName("Role Name");
        Account account12 = new Account();
        account12.setAccountId(1234567890L);
        ArrayList<Comment> commentList14 = new ArrayList<>();
        account12.setCommentList(commentList14);
        account12.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList14 = new ArrayList<>();
        account12.setFeedbackList(feedbackList14);
        account12.setIsBlock(true);
        account12.setPartner(new Partner());
        account12.setPassWord("Pass Word");
        account12.setRoleId(new Role());
        ArrayList<Tour> tourList14 = new ArrayList<>();
        account12.setTourList(tourList14);
        account12.setUser(new User());
        ArrayList<UserBooking> userBookingList13 = new ArrayList<>();
        account12.setUserBookingList(userBookingList13);
        User user4 = new User();
        user4.setAccountId(account12);
        user4.setAddress("42 Main St");
        user4.setBirthDate("2020-03-01");
        user4.setCity("Oxford");
        user4.setFirstName("Jane");
        user4.setGender("Gender");
        user4.setIsPrivate(true);
        user4.setLastName("Doe");
        user4.setPhone("4105551212");
        user4.setRankPoint(1);
        user4.setUserId(123L);
        Account account13 = new Account();
        account13.setAccountId(1234567890L);
        ArrayList<Comment> commentList15 = new ArrayList<>();
        account13.setCommentList(commentList15);
        account13.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList15 = new ArrayList<>();
        account13.setFeedbackList(feedbackList15);
        account13.setIsBlock(true);
        account13.setPartner(partner7);
        account13.setPassWord("Pass Word");
        account13.setRoleId(role5);
        ArrayList<Tour> tourList15 = new ArrayList<>();
        account13.setTourList(tourList15);
        account13.setUser(user4);
        ArrayList<UserBooking> userBookingList14 = new ArrayList<>();
        account13.setUserBookingList(userBookingList14);
        User user5 = new User();
        user5.setAccountId(account13);
        user5.setAddress("42 Main St");
        user5.setBirthDate("2020-03-01");
        user5.setCity("Oxford");
        user5.setFirstName("Jane");
        user5.setGender("Gender");
        user5.setIsPrivate(true);
        user5.setLastName("Doe");
        user5.setPhone("4105551212");
        user5.setRankPoint(1);
        user5.setUserId(123L);
        actualAccount.setUser(user5);
        ArrayList<UserBooking> userBookingList15 = new ArrayList<>();
        actualAccount.setUserBookingList(userBookingList15);
        assertEquals(1234567890L, actualAccount.getAccountId().longValue());
        List<Comment> commentList16 = actualAccount.getCommentList();
        assertSame(commentList8, commentList16);
        assertEquals(accountList, commentList16);
        assertEquals(commentList2, commentList16);
        assertEquals(feedbackList2, commentList16);
        assertEquals(commentList, commentList16);
        assertEquals(feedbackList, commentList16);
        assertEquals(tourList, commentList16);
        assertEquals(userBookingList, commentList16);
        assertEquals(partnerList, commentList16);
        assertEquals(serviceList, commentList16);
        assertEquals(serviceList1, commentList16);
        assertEquals(accountList1, commentList16);
        assertEquals(tourList2, commentList16);
        assertEquals(commentList1, commentList16);
        assertEquals(feedbackList1, commentList16);
        assertEquals(tourList1, commentList16);
        assertEquals(userBookingList1, commentList16);
        assertEquals(userBookingList2, commentList16);
        assertEquals(commentList5, commentList16);
        assertEquals(feedbackList5, commentList16);
        assertEquals(commentList3, commentList16);
        assertEquals(feedbackList3, commentList16);
        assertEquals(tourList3, commentList16);
        assertEquals(userBookingList3, commentList16);
        assertEquals(partnerList1, commentList16);
        assertEquals(serviceList2, commentList16);
        assertEquals(serviceList3, commentList16);
        assertEquals(accountList2, commentList16);
        assertEquals(tourList5, commentList16);
        assertEquals(commentList4, commentList16);
        assertEquals(feedbackList4, commentList16);
        assertEquals(tourList4, commentList16);
        assertEquals(userBookingList4, commentList16);
        assertEquals(userBookingList5, commentList16);
        assertEquals(commentList6, commentList16);
        assertEquals(feedbackList6, commentList16);
        assertEquals(tourList6, commentList16);
        assertEquals(userBookingList6, commentList16);
        assertEquals(partnerList2, commentList16);
        assertEquals(serviceList4, commentList16);
        assertEquals(serviceList5, commentList16);
        assertEquals(partnerList3, commentList16);
        assertEquals(serviceList6, commentList16);
        assertEquals(serviceList7, commentList16);
        assertEquals(userBookingList7, commentList16);
        assertEquals(tourList7, commentList16);
        assertEquals(feedbackList7, commentList16);
        assertEquals(commentList7, commentList16);
        assertEquals(feedbackList8, commentList16);
        assertEquals(commentList11, commentList16);
        assertEquals(feedbackList11, commentList16);
        assertEquals(commentList9, commentList16);
        assertEquals(feedbackList9, commentList16);
        assertEquals(tourList8, commentList16);
        assertEquals(userBookingList8, commentList16);
        assertEquals(partnerList4, commentList16);
        assertEquals(serviceList8, commentList16);
        assertEquals(serviceList9, commentList16);
        assertEquals(accountList3, commentList16);
        assertEquals(tourList10, commentList16);
        assertEquals(commentList10, commentList16);
        assertEquals(feedbackList10, commentList16);
        assertEquals(tourList9, commentList16);
        assertEquals(userBookingList9, commentList16);
        assertEquals(userBookingList10, commentList16);
        assertEquals(commentList12, commentList16);
        assertEquals(feedbackList12, commentList16);
        assertEquals(tourList11, commentList16);
        assertEquals(userBookingList11, commentList16);
        assertEquals(partnerList5, commentList16);
        assertEquals(serviceList10, commentList16);
        assertEquals(serviceList11, commentList16);
        assertEquals(partnerList6, commentList16);
        assertEquals(serviceList12, commentList16);
        assertEquals(serviceList13, commentList16);
        assertEquals(accountList4, commentList16);
        assertEquals(commentList15, commentList16);
        assertEquals(feedbackList15, commentList16);
        assertEquals(commentList13, commentList16);
        assertEquals(feedbackList13, commentList16);
        assertEquals(tourList13, commentList16);
        assertEquals(userBookingList12, commentList16);
        assertEquals(partnerList7, commentList16);
        assertEquals(serviceList14, commentList16);
        assertEquals(serviceList15, commentList16);
        assertEquals(accountList5, commentList16);
        assertEquals(tourList15, commentList16);
        assertEquals(commentList14, commentList16);
        assertEquals(feedbackList14, commentList16);
        assertEquals(tourList14, commentList16);
        assertEquals(userBookingList13, commentList16);
        assertEquals(userBookingList14, commentList16);
        List<Tour> tourList16 = actualAccount.getTourList();
        assertEquals(tourList16, commentList16);
        List<UserBooking> userBookingList16 = actualAccount.getUserBookingList();
        assertEquals(userBookingList16, commentList16);
        assertEquals("jane.doe@example.org", actualAccount.getEmail());
        List<Feedback> feedbackList16 = actualAccount.getFeedbackList();
        assertSame(feedbackList8, feedbackList16);
        assertEquals(accountList, feedbackList16);
        assertEquals(commentList2, feedbackList16);
        assertEquals(feedbackList2, feedbackList16);
        assertEquals(commentList, feedbackList16);
        assertEquals(feedbackList, feedbackList16);
        assertEquals(tourList, feedbackList16);
        assertEquals(userBookingList, feedbackList16);
        assertEquals(partnerList, feedbackList16);
        assertEquals(serviceList, feedbackList16);
        assertEquals(serviceList1, feedbackList16);
        assertEquals(accountList1, feedbackList16);
        assertEquals(tourList2, feedbackList16);
        assertEquals(commentList1, feedbackList16);
        assertEquals(feedbackList1, feedbackList16);
        assertEquals(tourList1, feedbackList16);
        assertEquals(userBookingList1, feedbackList16);
        assertEquals(userBookingList2, feedbackList16);
        assertEquals(commentList5, feedbackList16);
        assertEquals(feedbackList5, feedbackList16);
        assertEquals(commentList3, feedbackList16);
        assertEquals(feedbackList3, feedbackList16);
        assertEquals(tourList3, feedbackList16);
        assertEquals(userBookingList3, feedbackList16);
        assertEquals(partnerList1, feedbackList16);
        assertEquals(serviceList2, feedbackList16);
        assertEquals(serviceList3, feedbackList16);
        assertEquals(accountList2, feedbackList16);
        assertEquals(tourList5, feedbackList16);
        assertEquals(commentList4, feedbackList16);
        assertEquals(feedbackList4, feedbackList16);
        assertEquals(tourList4, feedbackList16);
        assertEquals(userBookingList4, feedbackList16);
        assertEquals(userBookingList5, feedbackList16);
        assertEquals(commentList6, feedbackList16);
        assertEquals(feedbackList6, feedbackList16);
        assertEquals(tourList6, feedbackList16);
        assertEquals(userBookingList6, feedbackList16);
        assertEquals(partnerList2, feedbackList16);
        assertEquals(serviceList4, feedbackList16);
        assertEquals(serviceList5, feedbackList16);
        assertEquals(partnerList3, feedbackList16);
        assertEquals(serviceList6, feedbackList16);
        assertEquals(serviceList7, feedbackList16);
        assertEquals(userBookingList7, feedbackList16);
        assertEquals(tourList7, feedbackList16);
        assertEquals(feedbackList7, feedbackList16);
        assertEquals(commentList7, feedbackList16);
        assertEquals(commentList11, feedbackList16);
        assertEquals(feedbackList11, feedbackList16);
        assertEquals(commentList9, feedbackList16);
        assertEquals(feedbackList9, feedbackList16);
        assertEquals(tourList8, feedbackList16);
        assertEquals(userBookingList8, feedbackList16);
        assertEquals(partnerList4, feedbackList16);
        assertEquals(serviceList8, feedbackList16);
        assertEquals(serviceList9, feedbackList16);
        assertEquals(accountList3, feedbackList16);
        assertEquals(tourList10, feedbackList16);
        assertEquals(commentList10, feedbackList16);
        assertEquals(feedbackList10, feedbackList16);
        assertEquals(tourList9, feedbackList16);
        assertEquals(userBookingList9, feedbackList16);
        assertEquals(userBookingList10, feedbackList16);
        assertEquals(commentList12, feedbackList16);
        assertEquals(feedbackList12, feedbackList16);
        assertEquals(tourList11, feedbackList16);
        assertEquals(userBookingList11, feedbackList16);
        assertEquals(partnerList5, feedbackList16);
        assertEquals(serviceList10, feedbackList16);
        assertEquals(serviceList11, feedbackList16);
        assertEquals(partnerList6, feedbackList16);
        assertEquals(serviceList12, feedbackList16);
        assertEquals(serviceList13, feedbackList16);
        assertEquals(accountList4, feedbackList16);
        assertEquals(commentList15, feedbackList16);
        assertEquals(feedbackList15, feedbackList16);
        assertEquals(commentList13, feedbackList16);
        assertEquals(feedbackList13, feedbackList16);
        assertEquals(tourList13, feedbackList16);
        assertEquals(userBookingList12, feedbackList16);
        assertEquals(partnerList7, feedbackList16);
        assertEquals(serviceList14, feedbackList16);
        assertEquals(serviceList15, feedbackList16);
        assertEquals(accountList5, feedbackList16);
        assertEquals(tourList15, feedbackList16);
        assertEquals(commentList14, feedbackList16);
        assertEquals(feedbackList14, feedbackList16);
        assertEquals(tourList14, feedbackList16);
        assertEquals(userBookingList13, feedbackList16);
        assertEquals(userBookingList14, feedbackList16);
        assertEquals(commentList16, feedbackList16);
        assertEquals(tourList16, feedbackList16);
        assertEquals(userBookingList16, feedbackList16);
        assertTrue(actualAccount.getIsBlock());
        assertSame(partner6, actualAccount.getPartner());
        assertEquals("Pass Word", actualAccount.getPassWord());
        assertSame(role4, actualAccount.getRoleId());
        assertSame(tourList12, tourList16);
        assertEquals(accountList, tourList16);
        assertEquals(commentList2, tourList16);
        assertEquals(feedbackList2, tourList16);
        assertEquals(commentList, tourList16);
        assertEquals(feedbackList, tourList16);
        assertEquals(tourList, tourList16);
        assertEquals(userBookingList, tourList16);
        assertEquals(partnerList, tourList16);
        assertEquals(serviceList, tourList16);
        assertEquals(serviceList1, tourList16);
        assertEquals(accountList1, tourList16);
        assertEquals(tourList2, tourList16);
        assertEquals(commentList1, tourList16);
        assertEquals(feedbackList1, tourList16);
        assertEquals(tourList1, tourList16);
        assertEquals(userBookingList1, tourList16);
        assertEquals(userBookingList2, tourList16);
        assertEquals(commentList5, tourList16);
        assertEquals(feedbackList5, tourList16);
        assertEquals(commentList3, tourList16);
        assertEquals(feedbackList3, tourList16);
        assertEquals(tourList3, tourList16);
        assertEquals(userBookingList3, tourList16);
        assertEquals(partnerList1, tourList16);
        assertEquals(serviceList2, tourList16);
        assertEquals(serviceList3, tourList16);
        assertEquals(accountList2, tourList16);
        assertEquals(tourList5, tourList16);
        assertEquals(commentList4, tourList16);
        assertEquals(feedbackList4, tourList16);
        assertEquals(tourList4, tourList16);
        assertEquals(userBookingList4, tourList16);
        assertEquals(userBookingList5, tourList16);
        assertEquals(commentList6, tourList16);
        assertEquals(feedbackList6, tourList16);
        assertEquals(tourList6, tourList16);
        assertEquals(userBookingList6, tourList16);
        assertEquals(partnerList2, tourList16);
        assertEquals(serviceList4, tourList16);
        assertEquals(serviceList5, tourList16);
        assertEquals(partnerList3, tourList16);
        assertEquals(serviceList6, tourList16);
        assertEquals(serviceList7, tourList16);
        assertEquals(userBookingList7, tourList16);
        assertEquals(tourList7, tourList16);
        assertEquals(feedbackList7, tourList16);
        assertEquals(commentList7, tourList16);
        assertEquals(commentList8, tourList16);
        assertEquals(feedbackList8, tourList16);
        assertEquals(commentList11, tourList16);
        assertEquals(feedbackList11, tourList16);
        assertEquals(commentList9, tourList16);
        assertEquals(feedbackList9, tourList16);
        assertEquals(tourList8, tourList16);
        assertEquals(userBookingList8, tourList16);
        assertEquals(partnerList4, tourList16);
        assertEquals(serviceList8, tourList16);
        assertEquals(serviceList9, tourList16);
        assertEquals(accountList3, tourList16);
        assertEquals(tourList10, tourList16);
        assertEquals(commentList10, tourList16);
        assertEquals(feedbackList10, tourList16);
        assertEquals(tourList9, tourList16);
        assertEquals(userBookingList9, tourList16);
        assertEquals(userBookingList10, tourList16);
        assertEquals(commentList12, tourList16);
        assertEquals(feedbackList12, tourList16);
        assertEquals(tourList11, tourList16);
        assertEquals(userBookingList11, tourList16);
        assertEquals(partnerList5, tourList16);
        assertEquals(serviceList10, tourList16);
        assertEquals(serviceList11, tourList16);
        assertEquals(partnerList6, tourList16);
        assertEquals(serviceList12, tourList16);
        assertEquals(serviceList13, tourList16);
        assertEquals(accountList4, tourList16);
        assertEquals(commentList15, tourList16);
        assertEquals(feedbackList15, tourList16);
        assertEquals(commentList13, tourList16);
        assertEquals(feedbackList13, tourList16);
        assertEquals(tourList13, tourList16);
        assertEquals(userBookingList12, tourList16);
        assertEquals(partnerList7, tourList16);
        assertEquals(serviceList14, tourList16);
        assertEquals(serviceList15, tourList16);
        assertEquals(accountList5, tourList16);
        assertEquals(tourList15, tourList16);
        assertEquals(commentList14, tourList16);
        assertEquals(feedbackList14, tourList16);
        assertEquals(tourList14, tourList16);
        assertEquals(userBookingList13, tourList16);
        assertEquals(userBookingList14, tourList16);
        assertEquals(userBookingList16, tourList16);
        assertSame(user5, actualAccount.getUser());
        assertSame(userBookingList15, userBookingList16);
        assertEquals(accountList, userBookingList16);
        assertEquals(commentList2, userBookingList16);
        assertEquals(feedbackList2, userBookingList16);
        assertEquals(commentList, userBookingList16);
        assertEquals(feedbackList, userBookingList16);
        assertEquals(tourList, userBookingList16);
        assertEquals(userBookingList, userBookingList16);
        assertEquals(partnerList, userBookingList16);
        assertEquals(serviceList, userBookingList16);
        assertEquals(serviceList1, userBookingList16);
        assertEquals(accountList1, userBookingList16);
        assertEquals(tourList2, userBookingList16);
        assertEquals(commentList1, userBookingList16);
        assertEquals(feedbackList1, userBookingList16);
        assertEquals(tourList1, userBookingList16);
        assertEquals(userBookingList1, userBookingList16);
        assertEquals(userBookingList2, userBookingList16);
        assertEquals(commentList5, userBookingList16);
        assertEquals(feedbackList5, userBookingList16);
        assertEquals(commentList3, userBookingList16);
        assertEquals(feedbackList3, userBookingList16);
        assertEquals(tourList3, userBookingList16);
        assertEquals(userBookingList3, userBookingList16);
        assertEquals(partnerList1, userBookingList16);
        assertEquals(serviceList2, userBookingList16);
        assertEquals(serviceList3, userBookingList16);
        assertEquals(accountList2, userBookingList16);
        assertEquals(tourList5, userBookingList16);
        assertEquals(commentList4, userBookingList16);
        assertEquals(feedbackList4, userBookingList16);
        assertEquals(tourList4, userBookingList16);
        assertEquals(userBookingList4, userBookingList16);
        assertEquals(userBookingList5, userBookingList16);
        assertEquals(commentList6, userBookingList16);
        assertEquals(feedbackList6, userBookingList16);
        assertEquals(tourList6, userBookingList16);
        assertEquals(userBookingList6, userBookingList16);
        assertEquals(partnerList2, userBookingList16);
        assertEquals(serviceList4, userBookingList16);
        assertEquals(serviceList5, userBookingList16);
        assertEquals(partnerList3, userBookingList16);
        assertEquals(serviceList6, userBookingList16);
        assertEquals(serviceList7, userBookingList16);
        assertEquals(userBookingList7, userBookingList16);
        assertEquals(tourList7, userBookingList16);
        assertEquals(feedbackList7, userBookingList16);
        assertEquals(commentList7, userBookingList16);
        assertEquals(commentList8, userBookingList16);
        assertEquals(feedbackList8, userBookingList16);
        assertEquals(commentList11, userBookingList16);
        assertEquals(feedbackList11, userBookingList16);
        assertEquals(commentList9, userBookingList16);
        assertEquals(feedbackList9, userBookingList16);
        assertEquals(tourList8, userBookingList16);
        assertEquals(userBookingList8, userBookingList16);
        assertEquals(partnerList4, userBookingList16);
        assertEquals(serviceList8, userBookingList16);
        assertEquals(serviceList9, userBookingList16);
        assertEquals(accountList3, userBookingList16);
        assertEquals(tourList10, userBookingList16);
        assertEquals(commentList10, userBookingList16);
        assertEquals(feedbackList10, userBookingList16);
        assertEquals(tourList9, userBookingList16);
        assertEquals(userBookingList9, userBookingList16);
        assertEquals(userBookingList10, userBookingList16);
        assertEquals(commentList12, userBookingList16);
        assertEquals(feedbackList12, userBookingList16);
        assertEquals(tourList11, userBookingList16);
        assertEquals(userBookingList11, userBookingList16);
        assertEquals(partnerList5, userBookingList16);
        assertEquals(serviceList10, userBookingList16);
        assertEquals(serviceList11, userBookingList16);
        assertEquals(partnerList6, userBookingList16);
        assertEquals(serviceList12, userBookingList16);
        assertEquals(serviceList13, userBookingList16);
        assertEquals(accountList4, userBookingList16);
        assertEquals(tourList12, userBookingList16);
        assertEquals(commentList15, userBookingList16);
        assertEquals(feedbackList15, userBookingList16);
        assertEquals(commentList13, userBookingList16);
        assertEquals(feedbackList13, userBookingList16);
        assertEquals(tourList13, userBookingList16);
        assertEquals(userBookingList12, userBookingList16);
        assertEquals(partnerList7, userBookingList16);
        assertEquals(serviceList14, userBookingList16);
        assertEquals(serviceList15, userBookingList16);
        assertEquals(accountList5, userBookingList16);
        assertEquals(tourList15, userBookingList16);
        assertEquals(commentList14, userBookingList16);
        assertEquals(feedbackList14, userBookingList16);
        assertEquals(tourList14, userBookingList16);
        assertEquals(userBookingList13, userBookingList16);
        assertEquals(userBookingList14, userBookingList16);
    }
}

