package com.example.wetravel.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;

import org.junit.jupiter.api.Test;

class EntertainmentTest {
    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link Entertainment#Entertainment()}
     *   <li>{@link Entertainment#setDescription(String)}
     *   <li>{@link Entertainment#setDowOpen(String)}
     *   <li>{@link Entertainment#setEntertainmentId(Long)}
     *   <li>{@link Entertainment#setEntertainmentType(String)}
     *   <li>{@link Entertainment#setPriceTicketAdult(Float)}
     *   <li>{@link Entertainment#setPriceTicketChildren(Float)}
     *   <li>{@link Entertainment#setServiceId(Service)}
     *   <li>{@link Entertainment#setTimeClose(LocalTime)}
     *   <li>{@link Entertainment#setTimeOpen(LocalTime)}
     *   <li>{@link Entertainment#getDescription()}
     *   <li>{@link Entertainment#getDowOpen()}
     *   <li>{@link Entertainment#getEntertainmentId()}
     *   <li>{@link Entertainment#getEntertainmentType()}
     *   <li>{@link Entertainment#getPriceTicketAdult()}
     *   <li>{@link Entertainment#getPriceTicketChildren()}
     *   <li>{@link Entertainment#getServiceId()}
     *   <li>{@link Entertainment#getTimeClose()}
     *   <li>{@link Entertainment#getTimeOpen()}
     * </ul>
     */
    @Test
    void testConstructor() {
        Entertainment actualEntertainment = new Entertainment();
        actualEntertainment.setDescription("The characteristics of someone or something");
        actualEntertainment.setDowOpen("Dow Open");
        actualEntertainment.setEntertainmentId(123L);
        actualEntertainment.setEntertainmentType("Entertainment Type");
        actualEntertainment.setPriceTicketAdult(10.0f);
        actualEntertainment.setPriceTicketChildren(10.0f);
        Accommodation accommodation = new Accommodation();
        accommodation.setAccommodationId(123L);
        accommodation.setAccommodationType("Accommodation Type");
        accommodation.setDescription("The characteristics of someone or something");
        accommodation.setNumberFloors(10);
        accommodation.setRate(10.0f);
        accommodation.setRoomList(new ArrayList<>());
        accommodation.setServiceId(new Service());
        Entertainment entertainment = new Entertainment();
        entertainment.setDescription("The characteristics of someone or something");
        entertainment.setDowOpen("Dow Open");
        entertainment.setEntertainmentId(123L);
        entertainment.setEntertainmentType("Entertainment Type");
        entertainment.setPriceTicketAdult(10.0f);
        entertainment.setPriceTicketChildren(10.0f);
        entertainment.setServiceId(new Service());
        entertainment.setTimeClose(null);
        entertainment.setTimeOpen(null);
        Partner partner = new Partner();
        partner.setAccountId(new Account());
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(new CompanyPartner());
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(new ServiceCategory());
        partner.setServiceList(new ArrayList<>());
        Restaurant restaurant = new Restaurant();
        restaurant.setDescription("The characteristics of someone or something");
        restaurant.setRate(10.0f);
        restaurant.setRestaurantId(123L);
        restaurant.setRestaurantServiceType("Restaurant Service Type");
        restaurant.setServiceId(new Service());
        restaurant.setTimeClose(null);
        restaurant.setTimeOpen(null);
        restaurant.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory = new ServiceCategory();
        serviceCategory.setPartnerList(new ArrayList<>());
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        serviceCategory.setServiceList(new ArrayList<>());
        Service service = new Service();
        service.setAccommodation(accommodation);
        service.setAddress("42 Main St");
        service.setCity("Oxford");
        service.setDateRegister(LocalDate.ofEpochDay(1L));
        service.setEmail("jane.doe@example.org");
        service.setEntertainment(entertainment);
        service.setFax("Fax");
        service.setIsActive(true);
        service.setIsBlock(true);
        service.setLink("Link");
        service.setPartnerId(partner);
        service.setPhone("4105551212");
        service.setPostList(new ArrayList<>());
        service.setRestaurant(restaurant);
        service.setServiceCategoryId(serviceCategory);
        service.setServiceId(123L);
        service.setServiceName("Service Name");
        service.setStatus(1);
        service.setTaxCode("Tax Code");
        service.setUtilitiesServiceList(new ArrayList<>());
        Accommodation accommodation1 = new Accommodation();
        accommodation1.setAccommodationId(123L);
        accommodation1.setAccommodationType("Accommodation Type");
        accommodation1.setDescription("The characteristics of someone or something");
        accommodation1.setNumberFloors(10);
        accommodation1.setRate(10.0f);
        accommodation1.setRoomList(new ArrayList<>());
        accommodation1.setServiceId(service);
        Accommodation accommodation2 = new Accommodation();
        accommodation2.setAccommodationId(123L);
        accommodation2.setAccommodationType("Accommodation Type");
        accommodation2.setDescription("The characteristics of someone or something");
        accommodation2.setNumberFloors(10);
        accommodation2.setRate(10.0f);
        accommodation2.setRoomList(new ArrayList<>());
        accommodation2.setServiceId(new Service());
        Entertainment entertainment1 = new Entertainment();
        entertainment1.setDescription("The characteristics of someone or something");
        entertainment1.setDowOpen("Dow Open");
        entertainment1.setEntertainmentId(123L);
        entertainment1.setEntertainmentType("Entertainment Type");
        entertainment1.setPriceTicketAdult(10.0f);
        entertainment1.setPriceTicketChildren(10.0f);
        entertainment1.setServiceId(new Service());
        entertainment1.setTimeClose(null);
        entertainment1.setTimeOpen(null);
        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        partner1.setServiceList(new ArrayList<>());
        Restaurant restaurant1 = new Restaurant();
        restaurant1.setDescription("The characteristics of someone or something");
        restaurant1.setRate(10.0f);
        restaurant1.setRestaurantId(123L);
        restaurant1.setRestaurantServiceType("Restaurant Service Type");
        restaurant1.setServiceId(new Service());
        restaurant1.setTimeClose(null);
        restaurant1.setTimeOpen(null);
        restaurant1.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory1 = new ServiceCategory();
        serviceCategory1.setPartnerList(new ArrayList<>());
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        serviceCategory1.setServiceList(new ArrayList<>());
        Service service1 = new Service();
        service1.setAccommodation(accommodation2);
        service1.setAddress("42 Main St");
        service1.setCity("Oxford");
        service1.setDateRegister(LocalDate.ofEpochDay(1L));
        service1.setEmail("jane.doe@example.org");
        service1.setEntertainment(entertainment1);
        service1.setFax("Fax");
        service1.setIsActive(true);
        service1.setIsBlock(true);
        service1.setLink("Link");
        service1.setPartnerId(partner1);
        service1.setPhone("4105551212");
        service1.setPostList(new ArrayList<>());
        service1.setRestaurant(restaurant1);
        service1.setServiceCategoryId(serviceCategory1);
        service1.setServiceId(123L);
        service1.setServiceName("Service Name");
        service1.setStatus(1);
        service1.setTaxCode("Tax Code");
        service1.setUtilitiesServiceList(new ArrayList<>());
        Entertainment entertainment2 = new Entertainment();
        entertainment2.setDescription("The characteristics of someone or something");
        entertainment2.setDowOpen("Dow Open");
        entertainment2.setEntertainmentId(123L);
        entertainment2.setEntertainmentType("Entertainment Type");
        entertainment2.setPriceTicketAdult(10.0f);
        entertainment2.setPriceTicketChildren(10.0f);
        entertainment2.setServiceId(service1);
        entertainment2.setTimeClose(LocalTime.of(1, 1));
        entertainment2.setTimeOpen(LocalTime.of(1, 1));
        Partner partner2 = new Partner();
        partner2.setAccountId(new Account());
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(new CompanyPartner());
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(new ServiceCategory());
        partner2.setServiceList(new ArrayList<>());
        Role role = new Role();
        role.setAccountList(new ArrayList<>());
        role.setRoleId(123);
        role.setRoleName("Role Name");
        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);
        Account account = new Account();
        account.setAccountId(1234567890L);
        account.setCommentList(new ArrayList<>());
        account.setEmail("jane.doe@example.org");
        account.setFeedbackList(new ArrayList<>());
        account.setIsBlock(true);
        account.setPartner(partner2);
        account.setPassWord("Pass Word");
        account.setRoleId(role);
        account.setTourList(new ArrayList<>());
        account.setUser(user);
        account.setUserBookingList(new ArrayList<>());
        Partner partner3 = new Partner();
        partner3.setAccountId(new Account());
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(new CompanyPartner());
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(new ServiceCategory());
        partner3.setServiceList(new ArrayList<>());
        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(partner3);
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");
        ServiceCategory serviceCategory2 = new ServiceCategory();
        serviceCategory2.setPartnerList(new ArrayList<>());
        serviceCategory2.setServiceCategoryId(123L);
        serviceCategory2.setServiceCategoryName("Service Category Name");
        serviceCategory2.setServiceList(new ArrayList<>());
        Partner partner4 = new Partner();
        partner4.setAccountId(account);
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(companyPartner);
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(serviceCategory2);
        partner4.setServiceList(new ArrayList<>());
        Accommodation accommodation3 = new Accommodation();
        accommodation3.setAccommodationId(123L);
        accommodation3.setAccommodationType("Accommodation Type");
        accommodation3.setDescription("The characteristics of someone or something");
        accommodation3.setNumberFloors(10);
        accommodation3.setRate(10.0f);
        accommodation3.setRoomList(new ArrayList<>());
        accommodation3.setServiceId(new Service());
        Entertainment entertainment3 = new Entertainment();
        entertainment3.setDescription("The characteristics of someone or something");
        entertainment3.setDowOpen("Dow Open");
        entertainment3.setEntertainmentId(123L);
        entertainment3.setEntertainmentType("Entertainment Type");
        entertainment3.setPriceTicketAdult(10.0f);
        entertainment3.setPriceTicketChildren(10.0f);
        entertainment3.setServiceId(new Service());
        entertainment3.setTimeClose(null);
        entertainment3.setTimeOpen(null);
        Partner partner5 = new Partner();
        partner5.setAccountId(new Account());
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(new CompanyPartner());
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(new ServiceCategory());
        partner5.setServiceList(new ArrayList<>());
        Restaurant restaurant2 = new Restaurant();
        restaurant2.setDescription("The characteristics of someone or something");
        restaurant2.setRate(10.0f);
        restaurant2.setRestaurantId(123L);
        restaurant2.setRestaurantServiceType("Restaurant Service Type");
        restaurant2.setServiceId(new Service());
        restaurant2.setTimeClose(null);
        restaurant2.setTimeOpen(null);
        restaurant2.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory3 = new ServiceCategory();
        serviceCategory3.setPartnerList(new ArrayList<>());
        serviceCategory3.setServiceCategoryId(123L);
        serviceCategory3.setServiceCategoryName("Service Category Name");
        serviceCategory3.setServiceList(new ArrayList<>());
        Service service2 = new Service();
        service2.setAccommodation(accommodation3);
        service2.setAddress("42 Main St");
        service2.setCity("Oxford");
        service2.setDateRegister(LocalDate.ofEpochDay(1L));
        service2.setEmail("jane.doe@example.org");
        service2.setEntertainment(entertainment3);
        service2.setFax("Fax");
        service2.setIsActive(true);
        service2.setIsBlock(true);
        service2.setLink("Link");
        service2.setPartnerId(partner5);
        service2.setPhone("4105551212");
        service2.setPostList(new ArrayList<>());
        service2.setRestaurant(restaurant2);
        service2.setServiceCategoryId(serviceCategory3);
        service2.setServiceId(123L);
        service2.setServiceName("Service Name");
        service2.setStatus(1);
        service2.setTaxCode("Tax Code");
        service2.setUtilitiesServiceList(new ArrayList<>());
        Restaurant restaurant3 = new Restaurant();
        restaurant3.setDescription("The characteristics of someone or something");
        restaurant3.setRate(10.0f);
        restaurant3.setRestaurantId(123L);
        restaurant3.setRestaurantServiceType("Restaurant Service Type");
        restaurant3.setServiceId(service2);
        restaurant3.setTimeClose(LocalTime.of(1, 1));
        restaurant3.setTimeOpen(LocalTime.of(1, 1));
        restaurant3.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory4 = new ServiceCategory();
        serviceCategory4.setPartnerList(new ArrayList<>());
        serviceCategory4.setServiceCategoryId(123L);
        serviceCategory4.setServiceCategoryName("Service Category Name");
        serviceCategory4.setServiceList(new ArrayList<>());
        Service service3 = new Service();
        service3.setAccommodation(accommodation1);
        service3.setAddress("42 Main St");
        service3.setCity("Oxford");
        service3.setDateRegister(LocalDate.ofEpochDay(1L));
        service3.setEmail("jane.doe@example.org");
        service3.setEntertainment(entertainment2);
        service3.setFax("Fax");
        service3.setIsActive(true);
        service3.setIsBlock(true);
        service3.setLink("Link");
        service3.setPartnerId(partner4);
        service3.setPhone("4105551212");
        service3.setPostList(new ArrayList<>());
        service3.setRestaurant(restaurant3);
        service3.setServiceCategoryId(serviceCategory4);
        service3.setServiceId(123L);
        service3.setServiceName("Service Name");
        service3.setStatus(1);
        service3.setTaxCode("Tax Code");
        service3.setUtilitiesServiceList(new ArrayList<>());
        actualEntertainment.setServiceId(service3);
        LocalTime ofResult = LocalTime.of(1, 1);
        actualEntertainment.setTimeClose(ofResult);
        LocalTime ofResult1 = LocalTime.of(1, 1);
        actualEntertainment.setTimeOpen(ofResult1);
        assertEquals("The characteristics of someone or something", actualEntertainment.getDescription());
        assertEquals("Dow Open", actualEntertainment.getDowOpen());
        assertEquals(123L, actualEntertainment.getEntertainmentId().longValue());
        assertEquals("Entertainment Type", actualEntertainment.getEntertainmentType());
        assertEquals(10.0f, actualEntertainment.getPriceTicketAdult().floatValue());
        assertEquals(10.0f, actualEntertainment.getPriceTicketChildren().floatValue());
        assertSame(service3, actualEntertainment.getServiceId());
        assertSame(ofResult, actualEntertainment.getTimeClose());
        assertSame(ofResult1, actualEntertainment.getTimeOpen());
    }

    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link Entertainment#Entertainment(Long, String, String, LocalTime, LocalTime, Float, Float, String, Service)}
     *   <li>{@link Entertainment#Entertainment()}
     *   <li>{@link Entertainment#setDescription(String)}
     *   <li>{@link Entertainment#setDowOpen(String)}
     *   <li>{@link Entertainment#setEntertainmentId(Long)}
     *   <li>{@link Entertainment#setEntertainmentType(String)}
     *   <li>{@link Entertainment#setPriceTicketAdult(Float)}
     *   <li>{@link Entertainment#setPriceTicketChildren(Float)}
     *   <li>{@link Entertainment#setServiceId(Service)}
     *   <li>{@link Entertainment#setTimeClose(LocalTime)}
     *   <li>{@link Entertainment#setTimeOpen(LocalTime)}
     *   <li>{@link Entertainment#getDescription()}
     *   <li>{@link Entertainment#getDowOpen()}
     *   <li>{@link Entertainment#getEntertainmentId()}
     *   <li>{@link Entertainment#getEntertainmentType()}
     *   <li>{@link Entertainment#getPriceTicketAdult()}
     *   <li>{@link Entertainment#getPriceTicketChildren()}
     *   <li>{@link Entertainment#getServiceId()}
     *   <li>{@link Entertainment#getTimeClose()}
     *   <li>{@link Entertainment#getTimeOpen()}
     * </ul>
     */
    @Test
    void testConstructor2() {
        LocalTime timeOpen = LocalTime.of(1, 1);
        LocalTime timeClose = LocalTime.of(1, 1);

        Accommodation accommodation = new Accommodation();
        accommodation.setAccommodationId(123L);
        accommodation.setAccommodationType("Accommodation Type");
        accommodation.setDescription("The characteristics of someone or something");
        accommodation.setNumberFloors(10);
        accommodation.setRate(10.0f);
        accommodation.setRoomList(new ArrayList<>());
        accommodation.setServiceId(new Service());

        Entertainment entertainment = new Entertainment();
        entertainment.setDescription("The characteristics of someone or something");
        entertainment.setDowOpen("Dow Open");
        entertainment.setEntertainmentId(123L);
        entertainment.setEntertainmentType("Entertainment Type");
        entertainment.setPriceTicketAdult(10.0f);
        entertainment.setPriceTicketChildren(10.0f);
        entertainment.setServiceId(new Service());
        entertainment.setTimeClose(null);
        entertainment.setTimeOpen(null);

        Partner partner = new Partner();
        partner.setAccountId(new Account());
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(new CompanyPartner());
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(new ServiceCategory());
        partner.setServiceList(new ArrayList<>());

        Restaurant restaurant = new Restaurant();
        restaurant.setDescription("The characteristics of someone or something");
        restaurant.setRate(10.0f);
        restaurant.setRestaurantId(123L);
        restaurant.setRestaurantServiceType("Restaurant Service Type");
        restaurant.setServiceId(new Service());
        restaurant.setTimeClose(null);
        restaurant.setTimeOpen(null);
        restaurant.setTypeOfCuisineServiceList(new ArrayList<>());

        ServiceCategory serviceCategory = new ServiceCategory();
        serviceCategory.setPartnerList(new ArrayList<>());
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        serviceCategory.setServiceList(new ArrayList<>());

        Service service = new Service();
        service.setAccommodation(accommodation);
        service.setAddress("42 Main St");
        service.setCity("Oxford");
        service.setDateRegister(LocalDate.ofEpochDay(1L));
        service.setEmail("jane.doe@example.org");
        service.setEntertainment(entertainment);
        service.setFax("Fax");
        service.setIsActive(true);
        service.setIsBlock(true);
        service.setLink("Link");
        service.setPartnerId(partner);
        service.setPhone("4105551212");
        service.setPostList(new ArrayList<>());
        service.setRestaurant(restaurant);
        service.setServiceCategoryId(serviceCategory);
        service.setServiceId(123L);
        service.setServiceName("Service Name");
        service.setStatus(1);
        service.setTaxCode("Tax Code");
        service.setUtilitiesServiceList(new ArrayList<>());

        Accommodation accommodation1 = new Accommodation();
        accommodation1.setAccommodationId(123L);
        accommodation1.setAccommodationType("Accommodation Type");
        accommodation1.setDescription("The characteristics of someone or something");
        accommodation1.setNumberFloors(10);
        accommodation1.setRate(10.0f);
        accommodation1.setRoomList(new ArrayList<>());
        accommodation1.setServiceId(service);

        Accommodation accommodation2 = new Accommodation();
        accommodation2.setAccommodationId(123L);
        accommodation2.setAccommodationType("Accommodation Type");
        accommodation2.setDescription("The characteristics of someone or something");
        accommodation2.setNumberFloors(10);
        accommodation2.setRate(10.0f);
        accommodation2.setRoomList(new ArrayList<>());
        accommodation2.setServiceId(new Service());

        Entertainment entertainment1 = new Entertainment();
        entertainment1.setDescription("The characteristics of someone or something");
        entertainment1.setDowOpen("Dow Open");
        entertainment1.setEntertainmentId(123L);
        entertainment1.setEntertainmentType("Entertainment Type");
        entertainment1.setPriceTicketAdult(10.0f);
        entertainment1.setPriceTicketChildren(10.0f);
        entertainment1.setServiceId(new Service());
        entertainment1.setTimeClose(null);
        entertainment1.setTimeOpen(null);

        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        partner1.setServiceList(new ArrayList<>());

        Restaurant restaurant1 = new Restaurant();
        restaurant1.setDescription("The characteristics of someone or something");
        restaurant1.setRate(10.0f);
        restaurant1.setRestaurantId(123L);
        restaurant1.setRestaurantServiceType("Restaurant Service Type");
        restaurant1.setServiceId(new Service());
        restaurant1.setTimeClose(null);
        restaurant1.setTimeOpen(null);
        restaurant1.setTypeOfCuisineServiceList(new ArrayList<>());

        ServiceCategory serviceCategory1 = new ServiceCategory();
        serviceCategory1.setPartnerList(new ArrayList<>());
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        serviceCategory1.setServiceList(new ArrayList<>());

        Service service1 = new Service();
        service1.setAccommodation(accommodation2);
        service1.setAddress("42 Main St");
        service1.setCity("Oxford");
        service1.setDateRegister(LocalDate.ofEpochDay(1L));
        service1.setEmail("jane.doe@example.org");
        service1.setEntertainment(entertainment1);
        service1.setFax("Fax");
        service1.setIsActive(true);
        service1.setIsBlock(true);
        service1.setLink("Link");
        service1.setPartnerId(partner1);
        service1.setPhone("4105551212");
        service1.setPostList(new ArrayList<>());
        service1.setRestaurant(restaurant1);
        service1.setServiceCategoryId(serviceCategory1);
        service1.setServiceId(123L);
        service1.setServiceName("Service Name");
        service1.setStatus(1);
        service1.setTaxCode("Tax Code");
        service1.setUtilitiesServiceList(new ArrayList<>());

        Entertainment entertainment2 = new Entertainment();
        entertainment2.setDescription("The characteristics of someone or something");
        entertainment2.setDowOpen("Dow Open");
        entertainment2.setEntertainmentId(123L);
        entertainment2.setEntertainmentType("Entertainment Type");
        entertainment2.setPriceTicketAdult(10.0f);
        entertainment2.setPriceTicketChildren(10.0f);
        entertainment2.setServiceId(service1);
        entertainment2.setTimeClose(LocalTime.of(1, 1));
        entertainment2.setTimeOpen(LocalTime.of(1, 1));

        Partner partner2 = new Partner();
        partner2.setAccountId(new Account());
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(new CompanyPartner());
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(new ServiceCategory());
        partner2.setServiceList(new ArrayList<>());

        Role role = new Role();
        role.setAccountList(new ArrayList<>());
        role.setRoleId(123);
        role.setRoleName("Role Name");

        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);

        Account account = new Account();
        account.setAccountId(1234567890L);
        account.setCommentList(new ArrayList<>());
        account.setEmail("jane.doe@example.org");
        account.setFeedbackList(new ArrayList<>());
        account.setIsBlock(true);
        account.setPartner(partner2);
        account.setPassWord("Pass Word");
        account.setRoleId(role);
        account.setTourList(new ArrayList<>());
        account.setUser(user);
        account.setUserBookingList(new ArrayList<>());

        Partner partner3 = new Partner();
        partner3.setAccountId(new Account());
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(new CompanyPartner());
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(new ServiceCategory());
        partner3.setServiceList(new ArrayList<>());

        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(partner3);
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");

        ServiceCategory serviceCategory2 = new ServiceCategory();
        serviceCategory2.setPartnerList(new ArrayList<>());
        serviceCategory2.setServiceCategoryId(123L);
        serviceCategory2.setServiceCategoryName("Service Category Name");
        serviceCategory2.setServiceList(new ArrayList<>());

        Partner partner4 = new Partner();
        partner4.setAccountId(account);
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(companyPartner);
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(serviceCategory2);
        partner4.setServiceList(new ArrayList<>());

        Accommodation accommodation3 = new Accommodation();
        accommodation3.setAccommodationId(123L);
        accommodation3.setAccommodationType("Accommodation Type");
        accommodation3.setDescription("The characteristics of someone or something");
        accommodation3.setNumberFloors(10);
        accommodation3.setRate(10.0f);
        accommodation3.setRoomList(new ArrayList<>());
        accommodation3.setServiceId(new Service());

        Entertainment entertainment3 = new Entertainment();
        entertainment3.setDescription("The characteristics of someone or something");
        entertainment3.setDowOpen("Dow Open");
        entertainment3.setEntertainmentId(123L);
        entertainment3.setEntertainmentType("Entertainment Type");
        entertainment3.setPriceTicketAdult(10.0f);
        entertainment3.setPriceTicketChildren(10.0f);
        entertainment3.setServiceId(new Service());
        entertainment3.setTimeClose(null);
        entertainment3.setTimeOpen(null);

        Partner partner5 = new Partner();
        partner5.setAccountId(new Account());
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(new CompanyPartner());
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(new ServiceCategory());
        partner5.setServiceList(new ArrayList<>());

        Restaurant restaurant2 = new Restaurant();
        restaurant2.setDescription("The characteristics of someone or something");
        restaurant2.setRate(10.0f);
        restaurant2.setRestaurantId(123L);
        restaurant2.setRestaurantServiceType("Restaurant Service Type");
        restaurant2.setServiceId(new Service());
        restaurant2.setTimeClose(null);
        restaurant2.setTimeOpen(null);
        restaurant2.setTypeOfCuisineServiceList(new ArrayList<>());

        ServiceCategory serviceCategory3 = new ServiceCategory();
        serviceCategory3.setPartnerList(new ArrayList<>());
        serviceCategory3.setServiceCategoryId(123L);
        serviceCategory3.setServiceCategoryName("Service Category Name");
        serviceCategory3.setServiceList(new ArrayList<>());

        Service service2 = new Service();
        service2.setAccommodation(accommodation3);
        service2.setAddress("42 Main St");
        service2.setCity("Oxford");
        service2.setDateRegister(LocalDate.ofEpochDay(1L));
        service2.setEmail("jane.doe@example.org");
        service2.setEntertainment(entertainment3);
        service2.setFax("Fax");
        service2.setIsActive(true);
        service2.setIsBlock(true);
        service2.setLink("Link");
        service2.setPartnerId(partner5);
        service2.setPhone("4105551212");
        service2.setPostList(new ArrayList<>());
        service2.setRestaurant(restaurant2);
        service2.setServiceCategoryId(serviceCategory3);
        service2.setServiceId(123L);
        service2.setServiceName("Service Name");
        service2.setStatus(1);
        service2.setTaxCode("Tax Code");
        service2.setUtilitiesServiceList(new ArrayList<>());

        Restaurant restaurant3 = new Restaurant();
        restaurant3.setDescription("The characteristics of someone or something");
        restaurant3.setRate(10.0f);
        restaurant3.setRestaurantId(123L);
        restaurant3.setRestaurantServiceType("Restaurant Service Type");
        restaurant3.setServiceId(service2);
        restaurant3.setTimeClose(LocalTime.of(1, 1));
        restaurant3.setTimeOpen(LocalTime.of(1, 1));
        restaurant3.setTypeOfCuisineServiceList(new ArrayList<>());

        ServiceCategory serviceCategory4 = new ServiceCategory();
        serviceCategory4.setPartnerList(new ArrayList<>());
        serviceCategory4.setServiceCategoryId(123L);
        serviceCategory4.setServiceCategoryName("Service Category Name");
        serviceCategory4.setServiceList(new ArrayList<>());

        Service service3 = new Service();
        service3.setAccommodation(accommodation1);
        service3.setAddress("42 Main St");
        service3.setCity("Oxford");
        service3.setDateRegister(LocalDate.ofEpochDay(1L));
        service3.setEmail("jane.doe@example.org");
        service3.setEntertainment(entertainment2);
        service3.setFax("Fax");
        service3.setIsActive(true);
        service3.setIsBlock(true);
        service3.setLink("Link");
        service3.setPartnerId(partner4);
        service3.setPhone("4105551212");
        service3.setPostList(new ArrayList<>());
        service3.setRestaurant(restaurant3);
        service3.setServiceCategoryId(serviceCategory4);
        service3.setServiceId(123L);
        service3.setServiceName("Service Name");
        service3.setStatus(1);
        service3.setTaxCode("Tax Code");
        service3.setUtilitiesServiceList(new ArrayList<>());
        Entertainment actualEntertainment = new Entertainment(123L, "Entertainment Type", "Dow Open", timeOpen, timeClose,
                10.0f, 10.0f, "The characteristics of someone or something", service3);
        actualEntertainment.setDescription("The characteristics of someone or something");
        actualEntertainment.setDowOpen("Dow Open");
        actualEntertainment.setEntertainmentId(123L);
        actualEntertainment.setEntertainmentType("Entertainment Type");
        actualEntertainment.setPriceTicketAdult(10.0f);
        actualEntertainment.setPriceTicketChildren(10.0f);
        Accommodation accommodation4 = new Accommodation();
        accommodation4.setAccommodationId(123L);
        accommodation4.setAccommodationType("Accommodation Type");
        accommodation4.setDescription("The characteristics of someone or something");
        accommodation4.setNumberFloors(10);
        accommodation4.setRate(10.0f);
        accommodation4.setRoomList(new ArrayList<>());
        accommodation4.setServiceId(new Service());
        Entertainment entertainment4 = new Entertainment();
        entertainment4.setDescription("The characteristics of someone or something");
        entertainment4.setDowOpen("Dow Open");
        entertainment4.setEntertainmentId(123L);
        entertainment4.setEntertainmentType("Entertainment Type");
        entertainment4.setPriceTicketAdult(10.0f);
        entertainment4.setPriceTicketChildren(10.0f);
        entertainment4.setServiceId(new Service());
        entertainment4.setTimeClose(null);
        entertainment4.setTimeOpen(null);
        Partner partner6 = new Partner();
        partner6.setAccountId(new Account());
        partner6.setAddress("42 Main St");
        partner6.setBirthDate("2020-03-01");
        partner6.setCity("Oxford");
        partner6.setCompanyPartnerId(new CompanyPartner());
        partner6.setDateIssue("2020-03-01");
        partner6.setDepartment("Department");
        partner6.setEmail("jane.doe@example.org");
        partner6.setFirstName("Jane");
        partner6.setGender("Gender");
        partner6.setLastName("Doe");
        partner6.setNumberIdCard("42");
        partner6.setPartnerId(123L);
        partner6.setPhone("4105551212");
        partner6.setPlaceIssue("Place Issue");
        partner6.setPosition("Position");
        partner6.setServiceCategoryId(new ServiceCategory());
        partner6.setServiceList(new ArrayList<>());
        Restaurant restaurant4 = new Restaurant();
        restaurant4.setDescription("The characteristics of someone or something");
        restaurant4.setRate(10.0f);
        restaurant4.setRestaurantId(123L);
        restaurant4.setRestaurantServiceType("Restaurant Service Type");
        restaurant4.setServiceId(new Service());
        restaurant4.setTimeClose(null);
        restaurant4.setTimeOpen(null);
        restaurant4.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory5 = new ServiceCategory();
        serviceCategory5.setPartnerList(new ArrayList<>());
        serviceCategory5.setServiceCategoryId(123L);
        serviceCategory5.setServiceCategoryName("Service Category Name");
        serviceCategory5.setServiceList(new ArrayList<>());
        Service service4 = new Service();
        service4.setAccommodation(accommodation4);
        service4.setAddress("42 Main St");
        service4.setCity("Oxford");
        service4.setDateRegister(LocalDate.ofEpochDay(1L));
        service4.setEmail("jane.doe@example.org");
        service4.setEntertainment(entertainment4);
        service4.setFax("Fax");
        service4.setIsActive(true);
        service4.setIsBlock(true);
        service4.setLink("Link");
        service4.setPartnerId(partner6);
        service4.setPhone("4105551212");
        service4.setPostList(new ArrayList<>());
        service4.setRestaurant(restaurant4);
        service4.setServiceCategoryId(serviceCategory5);
        service4.setServiceId(123L);
        service4.setServiceName("Service Name");
        service4.setStatus(1);
        service4.setTaxCode("Tax Code");
        service4.setUtilitiesServiceList(new ArrayList<>());
        Accommodation accommodation5 = new Accommodation();
        accommodation5.setAccommodationId(123L);
        accommodation5.setAccommodationType("Accommodation Type");
        accommodation5.setDescription("The characteristics of someone or something");
        accommodation5.setNumberFloors(10);
        accommodation5.setRate(10.0f);
        accommodation5.setRoomList(new ArrayList<>());
        accommodation5.setServiceId(service4);
        Accommodation accommodation6 = new Accommodation();
        accommodation6.setAccommodationId(123L);
        accommodation6.setAccommodationType("Accommodation Type");
        accommodation6.setDescription("The characteristics of someone or something");
        accommodation6.setNumberFloors(10);
        accommodation6.setRate(10.0f);
        accommodation6.setRoomList(new ArrayList<>());
        accommodation6.setServiceId(new Service());
        Entertainment entertainment5 = new Entertainment();
        entertainment5.setDescription("The characteristics of someone or something");
        entertainment5.setDowOpen("Dow Open");
        entertainment5.setEntertainmentId(123L);
        entertainment5.setEntertainmentType("Entertainment Type");
        entertainment5.setPriceTicketAdult(10.0f);
        entertainment5.setPriceTicketChildren(10.0f);
        entertainment5.setServiceId(new Service());
        entertainment5.setTimeClose(null);
        entertainment5.setTimeOpen(null);
        Partner partner7 = new Partner();
        partner7.setAccountId(new Account());
        partner7.setAddress("42 Main St");
        partner7.setBirthDate("2020-03-01");
        partner7.setCity("Oxford");
        partner7.setCompanyPartnerId(new CompanyPartner());
        partner7.setDateIssue("2020-03-01");
        partner7.setDepartment("Department");
        partner7.setEmail("jane.doe@example.org");
        partner7.setFirstName("Jane");
        partner7.setGender("Gender");
        partner7.setLastName("Doe");
        partner7.setNumberIdCard("42");
        partner7.setPartnerId(123L);
        partner7.setPhone("4105551212");
        partner7.setPlaceIssue("Place Issue");
        partner7.setPosition("Position");
        partner7.setServiceCategoryId(new ServiceCategory());
        partner7.setServiceList(new ArrayList<>());
        Restaurant restaurant5 = new Restaurant();
        restaurant5.setDescription("The characteristics of someone or something");
        restaurant5.setRate(10.0f);
        restaurant5.setRestaurantId(123L);
        restaurant5.setRestaurantServiceType("Restaurant Service Type");
        restaurant5.setServiceId(new Service());
        restaurant5.setTimeClose(null);
        restaurant5.setTimeOpen(null);
        restaurant5.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory6 = new ServiceCategory();
        serviceCategory6.setPartnerList(new ArrayList<>());
        serviceCategory6.setServiceCategoryId(123L);
        serviceCategory6.setServiceCategoryName("Service Category Name");
        serviceCategory6.setServiceList(new ArrayList<>());
        Service service5 = new Service();
        service5.setAccommodation(accommodation6);
        service5.setAddress("42 Main St");
        service5.setCity("Oxford");
        service5.setDateRegister(LocalDate.ofEpochDay(1L));
        service5.setEmail("jane.doe@example.org");
        service5.setEntertainment(entertainment5);
        service5.setFax("Fax");
        service5.setIsActive(true);
        service5.setIsBlock(true);
        service5.setLink("Link");
        service5.setPartnerId(partner7);
        service5.setPhone("4105551212");
        service5.setPostList(new ArrayList<>());
        service5.setRestaurant(restaurant5);
        service5.setServiceCategoryId(serviceCategory6);
        service5.setServiceId(123L);
        service5.setServiceName("Service Name");
        service5.setStatus(1);
        service5.setTaxCode("Tax Code");
        service5.setUtilitiesServiceList(new ArrayList<>());
        Entertainment entertainment6 = new Entertainment();
        entertainment6.setDescription("The characteristics of someone or something");
        entertainment6.setDowOpen("Dow Open");
        entertainment6.setEntertainmentId(123L);
        entertainment6.setEntertainmentType("Entertainment Type");
        entertainment6.setPriceTicketAdult(10.0f);
        entertainment6.setPriceTicketChildren(10.0f);
        entertainment6.setServiceId(service5);
        entertainment6.setTimeClose(LocalTime.of(1, 1));
        entertainment6.setTimeOpen(LocalTime.of(1, 1));
        Partner partner8 = new Partner();
        partner8.setAccountId(new Account());
        partner8.setAddress("42 Main St");
        partner8.setBirthDate("2020-03-01");
        partner8.setCity("Oxford");
        partner8.setCompanyPartnerId(new CompanyPartner());
        partner8.setDateIssue("2020-03-01");
        partner8.setDepartment("Department");
        partner8.setEmail("jane.doe@example.org");
        partner8.setFirstName("Jane");
        partner8.setGender("Gender");
        partner8.setLastName("Doe");
        partner8.setNumberIdCard("42");
        partner8.setPartnerId(123L);
        partner8.setPhone("4105551212");
        partner8.setPlaceIssue("Place Issue");
        partner8.setPosition("Position");
        partner8.setServiceCategoryId(new ServiceCategory());
        partner8.setServiceList(new ArrayList<>());
        Role role1 = new Role();
        role1.setAccountList(new ArrayList<>());
        role1.setRoleId(123);
        role1.setRoleName("Role Name");
        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);
        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        account1.setCommentList(new ArrayList<>());
        account1.setEmail("jane.doe@example.org");
        account1.setFeedbackList(new ArrayList<>());
        account1.setIsBlock(true);
        account1.setPartner(partner8);
        account1.setPassWord("Pass Word");
        account1.setRoleId(role1);
        account1.setTourList(new ArrayList<>());
        account1.setUser(user1);
        account1.setUserBookingList(new ArrayList<>());
        Partner partner9 = new Partner();
        partner9.setAccountId(new Account());
        partner9.setAddress("42 Main St");
        partner9.setBirthDate("2020-03-01");
        partner9.setCity("Oxford");
        partner9.setCompanyPartnerId(new CompanyPartner());
        partner9.setDateIssue("2020-03-01");
        partner9.setDepartment("Department");
        partner9.setEmail("jane.doe@example.org");
        partner9.setFirstName("Jane");
        partner9.setGender("Gender");
        partner9.setLastName("Doe");
        partner9.setNumberIdCard("42");
        partner9.setPartnerId(123L);
        partner9.setPhone("4105551212");
        partner9.setPlaceIssue("Place Issue");
        partner9.setPosition("Position");
        partner9.setServiceCategoryId(new ServiceCategory());
        partner9.setServiceList(new ArrayList<>());
        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(partner9);
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");
        ServiceCategory serviceCategory7 = new ServiceCategory();
        serviceCategory7.setPartnerList(new ArrayList<>());
        serviceCategory7.setServiceCategoryId(123L);
        serviceCategory7.setServiceCategoryName("Service Category Name");
        serviceCategory7.setServiceList(new ArrayList<>());
        Partner partner10 = new Partner();
        partner10.setAccountId(account1);
        partner10.setAddress("42 Main St");
        partner10.setBirthDate("2020-03-01");
        partner10.setCity("Oxford");
        partner10.setCompanyPartnerId(companyPartner1);
        partner10.setDateIssue("2020-03-01");
        partner10.setDepartment("Department");
        partner10.setEmail("jane.doe@example.org");
        partner10.setFirstName("Jane");
        partner10.setGender("Gender");
        partner10.setLastName("Doe");
        partner10.setNumberIdCard("42");
        partner10.setPartnerId(123L);
        partner10.setPhone("4105551212");
        partner10.setPlaceIssue("Place Issue");
        partner10.setPosition("Position");
        partner10.setServiceCategoryId(serviceCategory7);
        partner10.setServiceList(new ArrayList<>());
        Accommodation accommodation7 = new Accommodation();
        accommodation7.setAccommodationId(123L);
        accommodation7.setAccommodationType("Accommodation Type");
        accommodation7.setDescription("The characteristics of someone or something");
        accommodation7.setNumberFloors(10);
        accommodation7.setRate(10.0f);
        accommodation7.setRoomList(new ArrayList<>());
        accommodation7.setServiceId(new Service());
        Entertainment entertainment7 = new Entertainment();
        entertainment7.setDescription("The characteristics of someone or something");
        entertainment7.setDowOpen("Dow Open");
        entertainment7.setEntertainmentId(123L);
        entertainment7.setEntertainmentType("Entertainment Type");
        entertainment7.setPriceTicketAdult(10.0f);
        entertainment7.setPriceTicketChildren(10.0f);
        entertainment7.setServiceId(new Service());
        entertainment7.setTimeClose(null);
        entertainment7.setTimeOpen(null);
        Partner partner11 = new Partner();
        partner11.setAccountId(new Account());
        partner11.setAddress("42 Main St");
        partner11.setBirthDate("2020-03-01");
        partner11.setCity("Oxford");
        partner11.setCompanyPartnerId(new CompanyPartner());
        partner11.setDateIssue("2020-03-01");
        partner11.setDepartment("Department");
        partner11.setEmail("jane.doe@example.org");
        partner11.setFirstName("Jane");
        partner11.setGender("Gender");
        partner11.setLastName("Doe");
        partner11.setNumberIdCard("42");
        partner11.setPartnerId(123L);
        partner11.setPhone("4105551212");
        partner11.setPlaceIssue("Place Issue");
        partner11.setPosition("Position");
        partner11.setServiceCategoryId(new ServiceCategory());
        partner11.setServiceList(new ArrayList<>());
        Restaurant restaurant6 = new Restaurant();
        restaurant6.setDescription("The characteristics of someone or something");
        restaurant6.setRate(10.0f);
        restaurant6.setRestaurantId(123L);
        restaurant6.setRestaurantServiceType("Restaurant Service Type");
        restaurant6.setServiceId(new Service());
        restaurant6.setTimeClose(null);
        restaurant6.setTimeOpen(null);
        restaurant6.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory8 = new ServiceCategory();
        serviceCategory8.setPartnerList(new ArrayList<>());
        serviceCategory8.setServiceCategoryId(123L);
        serviceCategory8.setServiceCategoryName("Service Category Name");
        serviceCategory8.setServiceList(new ArrayList<>());
        Service service6 = new Service();
        service6.setAccommodation(accommodation7);
        service6.setAddress("42 Main St");
        service6.setCity("Oxford");
        service6.setDateRegister(LocalDate.ofEpochDay(1L));
        service6.setEmail("jane.doe@example.org");
        service6.setEntertainment(entertainment7);
        service6.setFax("Fax");
        service6.setIsActive(true);
        service6.setIsBlock(true);
        service6.setLink("Link");
        service6.setPartnerId(partner11);
        service6.setPhone("4105551212");
        service6.setPostList(new ArrayList<>());
        service6.setRestaurant(restaurant6);
        service6.setServiceCategoryId(serviceCategory8);
        service6.setServiceId(123L);
        service6.setServiceName("Service Name");
        service6.setStatus(1);
        service6.setTaxCode("Tax Code");
        service6.setUtilitiesServiceList(new ArrayList<>());
        Restaurant restaurant7 = new Restaurant();
        restaurant7.setDescription("The characteristics of someone or something");
        restaurant7.setRate(10.0f);
        restaurant7.setRestaurantId(123L);
        restaurant7.setRestaurantServiceType("Restaurant Service Type");
        restaurant7.setServiceId(service6);
        restaurant7.setTimeClose(LocalTime.of(1, 1));
        restaurant7.setTimeOpen(LocalTime.of(1, 1));
        restaurant7.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory9 = new ServiceCategory();
        serviceCategory9.setPartnerList(new ArrayList<>());
        serviceCategory9.setServiceCategoryId(123L);
        serviceCategory9.setServiceCategoryName("Service Category Name");
        serviceCategory9.setServiceList(new ArrayList<>());
        Service service7 = new Service();
        service7.setAccommodation(accommodation5);
        service7.setAddress("42 Main St");
        service7.setCity("Oxford");
        service7.setDateRegister(LocalDate.ofEpochDay(1L));
        service7.setEmail("jane.doe@example.org");
        service7.setEntertainment(entertainment6);
        service7.setFax("Fax");
        service7.setIsActive(true);
        service7.setIsBlock(true);
        service7.setLink("Link");
        service7.setPartnerId(partner10);
        service7.setPhone("4105551212");
        service7.setPostList(new ArrayList<>());
        service7.setRestaurant(restaurant7);
        service7.setServiceCategoryId(serviceCategory9);
        service7.setServiceId(123L);
        service7.setServiceName("Service Name");
        service7.setStatus(1);
        service7.setTaxCode("Tax Code");
        service7.setUtilitiesServiceList(new ArrayList<>());
        actualEntertainment.setServiceId(service7);
        LocalTime ofResult = LocalTime.of(1, 1);
        actualEntertainment.setTimeClose(ofResult);
        LocalTime ofResult1 = LocalTime.of(1, 1);
        actualEntertainment.setTimeOpen(ofResult1);
        assertEquals("The characteristics of someone or something", actualEntertainment.getDescription());
        assertEquals("Dow Open", actualEntertainment.getDowOpen());
        assertEquals(123L, actualEntertainment.getEntertainmentId().longValue());
        assertEquals("Entertainment Type", actualEntertainment.getEntertainmentType());
        assertEquals(10.0f, actualEntertainment.getPriceTicketAdult().floatValue());
        assertEquals(10.0f, actualEntertainment.getPriceTicketChildren().floatValue());
        assertSame(service7, actualEntertainment.getServiceId());
        assertSame(ofResult, actualEntertainment.getTimeClose());
        assertSame(ofResult1, actualEntertainment.getTimeOpen());
    }
}

