package com.example.wetravel.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;

import org.junit.jupiter.api.Test;

class ReportPostTest {
    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link ReportPost#ReportPost()}
     *   <li>{@link ReportPost#setAccountId(Account)}
     *   <li>{@link ReportPost#setPostId(Post)}
     *   <li>{@link ReportPost#setReasonReportPostId(ReasonReportPost)}
     *   <li>{@link ReportPost#setReportPostId(Long)}
     *   <li>{@link ReportPost#getAccountId()}
     *   <li>{@link ReportPost#getPostId()}
     *   <li>{@link ReportPost#getReasonReportPostId()}
     *   <li>{@link ReportPost#getReportPostId()}
     * </ul>
     */
    @Test
    void testConstructor() {
        ReportPost actualReportPost = new ReportPost();
        Partner partner = new Partner();
        partner.setAccountId(new Account());
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(new CompanyPartner());
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(new ServiceCategory());
        partner.setServiceList(new ArrayList<>());
        Role role = new Role();
        role.setAccountList(new ArrayList<>());
        role.setRoleId(123);
        role.setRoleName("Role Name");
        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);
        Account account = new Account();
        account.setAccountId(1234567890L);
        account.setCommentList(new ArrayList<>());
        account.setEmail("jane.doe@example.org");
        account.setFeedbackList(new ArrayList<>());
        account.setIsBlock(true);
        account.setPartner(partner);
        account.setPassWord("Pass Word");
        account.setRoleId(role);
        account.setTourList(new ArrayList<>());
        account.setUser(user);
        account.setUserBookingList(new ArrayList<>());
        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        partner1.setServiceList(new ArrayList<>());
        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(partner1);
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");
        ServiceCategory serviceCategory = new ServiceCategory();
        serviceCategory.setPartnerList(new ArrayList<>());
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        serviceCategory.setServiceList(new ArrayList<>());
        Partner partner2 = new Partner();
        partner2.setAccountId(account);
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(companyPartner);
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(serviceCategory);
        partner2.setServiceList(new ArrayList<>());
        Role role1 = new Role();
        role1.setAccountList(new ArrayList<>());
        role1.setRoleId(123);
        role1.setRoleName("Role Name");
        Partner partner3 = new Partner();
        partner3.setAccountId(new Account());
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(new CompanyPartner());
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(new ServiceCategory());
        partner3.setServiceList(new ArrayList<>());
        Role role2 = new Role();
        role2.setAccountList(new ArrayList<>());
        role2.setRoleId(123);
        role2.setRoleName("Role Name");
        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);
        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        account1.setCommentList(new ArrayList<>());
        account1.setEmail("jane.doe@example.org");
        account1.setFeedbackList(new ArrayList<>());
        account1.setIsBlock(true);
        account1.setPartner(partner3);
        account1.setPassWord("Pass Word");
        account1.setRoleId(role2);
        account1.setTourList(new ArrayList<>());
        account1.setUser(user1);
        account1.setUserBookingList(new ArrayList<>());
        User user2 = new User();
        user2.setAccountId(account1);
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);
        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        account2.setCommentList(new ArrayList<>());
        account2.setEmail("jane.doe@example.org");
        account2.setFeedbackList(new ArrayList<>());
        account2.setIsBlock(true);
        account2.setPartner(partner2);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role1);
        account2.setTourList(new ArrayList<>());
        account2.setUser(user2);
        account2.setUserBookingList(new ArrayList<>());
        actualReportPost.setAccountId(account2);
        Service service = new Service();
        service.setAccommodation(new Accommodation());
        service.setAddress("42 Main St");
        service.setCity("Oxford");
        service.setDateRegister(null);
        service.setEmail("jane.doe@example.org");
        service.setEntertainment(new Entertainment());
        service.setFax("Fax");
        service.setIsActive(true);
        service.setIsBlock(true);
        service.setLink("Link");
        service.setPartnerId(new Partner());
        service.setPhone("4105551212");
        service.setPostList(new ArrayList<>());
        service.setRestaurant(new Restaurant());
        service.setServiceCategoryId(new ServiceCategory());
        service.setServiceId(123L);
        service.setServiceName("Service Name");
        service.setStatus(1);
        service.setTaxCode("Tax Code");
        service.setUtilitiesServiceList(new ArrayList<>());
        Accommodation accommodation = new Accommodation();
        accommodation.setAccommodationId(123L);
        accommodation.setAccommodationType("Accommodation Type");
        accommodation.setDescription("The characteristics of someone or something");
        accommodation.setNumberFloors(10);
        accommodation.setRate(10.0f);
        accommodation.setRoomList(new ArrayList<>());
        accommodation.setServiceId(service);
        Service service1 = new Service();
        service1.setAccommodation(new Accommodation());
        service1.setAddress("42 Main St");
        service1.setCity("Oxford");
        service1.setDateRegister(null);
        service1.setEmail("jane.doe@example.org");
        service1.setEntertainment(new Entertainment());
        service1.setFax("Fax");
        service1.setIsActive(true);
        service1.setIsBlock(true);
        service1.setLink("Link");
        service1.setPartnerId(new Partner());
        service1.setPhone("4105551212");
        service1.setPostList(new ArrayList<>());
        service1.setRestaurant(new Restaurant());
        service1.setServiceCategoryId(new ServiceCategory());
        service1.setServiceId(123L);
        service1.setServiceName("Service Name");
        service1.setStatus(1);
        service1.setTaxCode("Tax Code");
        service1.setUtilitiesServiceList(new ArrayList<>());
        Entertainment entertainment = new Entertainment();
        entertainment.setDescription("The characteristics of someone or something");
        entertainment.setDowOpen("Dow Open");
        entertainment.setEntertainmentId(123L);
        entertainment.setEntertainmentType("Entertainment Type");
        entertainment.setPriceTicketAdult(10.0f);
        entertainment.setPriceTicketChildren(10.0f);
        entertainment.setServiceId(service1);
        entertainment.setTimeClose(LocalTime.of(1, 1));
        entertainment.setTimeOpen(LocalTime.of(1, 1));
        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        account3.setCommentList(new ArrayList<>());
        account3.setEmail("jane.doe@example.org");
        account3.setFeedbackList(new ArrayList<>());
        account3.setIsBlock(true);
        account3.setPartner(new Partner());
        account3.setPassWord("Pass Word");
        account3.setRoleId(new Role());
        account3.setTourList(new ArrayList<>());
        account3.setUser(new User());
        account3.setUserBookingList(new ArrayList<>());
        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(new Partner());
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");
        ServiceCategory serviceCategory1 = new ServiceCategory();
        serviceCategory1.setPartnerList(new ArrayList<>());
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        serviceCategory1.setServiceList(new ArrayList<>());
        Partner partner4 = new Partner();
        partner4.setAccountId(account3);
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(companyPartner1);
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(serviceCategory1);
        partner4.setServiceList(new ArrayList<>());
        Service service2 = new Service();
        service2.setAccommodation(new Accommodation());
        service2.setAddress("42 Main St");
        service2.setCity("Oxford");
        service2.setDateRegister(null);
        service2.setEmail("jane.doe@example.org");
        service2.setEntertainment(new Entertainment());
        service2.setFax("Fax");
        service2.setIsActive(true);
        service2.setIsBlock(true);
        service2.setLink("Link");
        service2.setPartnerId(new Partner());
        service2.setPhone("4105551212");
        service2.setPostList(new ArrayList<>());
        service2.setRestaurant(new Restaurant());
        service2.setServiceCategoryId(new ServiceCategory());
        service2.setServiceId(123L);
        service2.setServiceName("Service Name");
        service2.setStatus(1);
        service2.setTaxCode("Tax Code");
        service2.setUtilitiesServiceList(new ArrayList<>());
        Restaurant restaurant = new Restaurant();
        restaurant.setDescription("The characteristics of someone or something");
        restaurant.setRate(10.0f);
        restaurant.setRestaurantId(123L);
        restaurant.setRestaurantServiceType("Restaurant Service Type");
        restaurant.setServiceId(service2);
        restaurant.setTimeClose(LocalTime.of(1, 1));
        restaurant.setTimeOpen(LocalTime.of(1, 1));
        restaurant.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory2 = new ServiceCategory();
        serviceCategory2.setPartnerList(new ArrayList<>());
        serviceCategory2.setServiceCategoryId(123L);
        serviceCategory2.setServiceCategoryName("Service Category Name");
        serviceCategory2.setServiceList(new ArrayList<>());
        Service service3 = new Service();
        service3.setAccommodation(accommodation);
        service3.setAddress("42 Main St");
        service3.setCity("Oxford");
        service3.setDateRegister(LocalDate.ofEpochDay(1L));
        service3.setEmail("jane.doe@example.org");
        service3.setEntertainment(entertainment);
        service3.setFax("Fax");
        service3.setIsActive(true);
        service3.setIsBlock(true);
        service3.setLink("Link");
        service3.setPartnerId(partner4);
        service3.setPhone("4105551212");
        service3.setPostList(new ArrayList<>());
        service3.setRestaurant(restaurant);
        service3.setServiceCategoryId(serviceCategory2);
        service3.setServiceId(123L);
        service3.setServiceName("Service Name");
        service3.setStatus(1);
        service3.setTaxCode("Tax Code");
        service3.setUtilitiesServiceList(new ArrayList<>());
        Topic topic = new Topic();
        topic.setPostList(new ArrayList<>());
        topic.setTopicId(123L);
        topic.setTopicName("Topic Name");
        Post post = new Post();
        post.setContent("Not all who wander are lost");
        post.setDescription("The characteristics of someone or something");
        post.setIsBlock(true);
        post.setIsPublic(true);
        post.setPostId(123L);
        post.setReportPostList(new ArrayList<>());
        post.setServiceId(service3);
        post.setTimePost(LocalDateTime.of(1, 1, 1, 1, 1));
        post.setTitle("Dr");
        post.setTopicId(topic);
        actualReportPost.setPostId(post);
        ReasonReportPost reasonReportPost = new ReasonReportPost();
        reasonReportPost.setReasonReportPostId(123L);
        reasonReportPost.setReasonReportPostName("Just cause");
        reasonReportPost.setReportPostList(new ArrayList<>());
        actualReportPost.setReasonReportPostId(reasonReportPost);
        actualReportPost.setReportPostId(123L);
        assertSame(account2, actualReportPost.getAccountId());
        assertSame(post, actualReportPost.getPostId());
        assertSame(reasonReportPost, actualReportPost.getReasonReportPostId());
        assertEquals(123L, actualReportPost.getReportPostId().longValue());
    }

    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link ReportPost#ReportPost(Long, Post, Account, ReasonReportPost)}
     *   <li>{@link ReportPost#setAccountId(Account)}
     *   <li>{@link ReportPost#setPostId(Post)}
     *   <li>{@link ReportPost#setReasonReportPostId(ReasonReportPost)}
     *   <li>{@link ReportPost#setReportPostId(Long)}
     *   <li>{@link ReportPost#getAccountId()}
     *   <li>{@link ReportPost#getPostId()}
     *   <li>{@link ReportPost#getReasonReportPostId()}
     *   <li>{@link ReportPost#getReportPostId()}
     * </ul>
     */
    @Test
    void testConstructor2() {
        Service service = new Service();
        service.setAccommodation(new Accommodation());
        service.setAddress("42 Main St");
        service.setCity("Oxford");
        service.setDateRegister(null);
        service.setEmail("jane.doe@example.org");
        service.setEntertainment(new Entertainment());
        service.setFax("Fax");
        service.setIsActive(true);
        service.setIsBlock(true);
        service.setLink("Link");
        service.setPartnerId(new Partner());
        service.setPhone("4105551212");
        service.setPostList(new ArrayList<>());
        service.setRestaurant(new Restaurant());
        service.setServiceCategoryId(new ServiceCategory());
        service.setServiceId(123L);
        service.setServiceName("Service Name");
        service.setStatus(1);
        service.setTaxCode("Tax Code");
        service.setUtilitiesServiceList(new ArrayList<>());

        Accommodation accommodation = new Accommodation();
        accommodation.setAccommodationId(123L);
        accommodation.setAccommodationType("Accommodation Type");
        accommodation.setDescription("The characteristics of someone or something");
        accommodation.setNumberFloors(10);
        accommodation.setRate(10.0f);
        accommodation.setRoomList(new ArrayList<>());
        accommodation.setServiceId(service);

        Service service1 = new Service();
        service1.setAccommodation(new Accommodation());
        service1.setAddress("42 Main St");
        service1.setCity("Oxford");
        service1.setDateRegister(null);
        service1.setEmail("jane.doe@example.org");
        service1.setEntertainment(new Entertainment());
        service1.setFax("Fax");
        service1.setIsActive(true);
        service1.setIsBlock(true);
        service1.setLink("Link");
        service1.setPartnerId(new Partner());
        service1.setPhone("4105551212");
        service1.setPostList(new ArrayList<>());
        service1.setRestaurant(new Restaurant());
        service1.setServiceCategoryId(new ServiceCategory());
        service1.setServiceId(123L);
        service1.setServiceName("Service Name");
        service1.setStatus(1);
        service1.setTaxCode("Tax Code");
        service1.setUtilitiesServiceList(new ArrayList<>());

        Entertainment entertainment = new Entertainment();
        entertainment.setDescription("The characteristics of someone or something");
        entertainment.setDowOpen("Dow Open");
        entertainment.setEntertainmentId(123L);
        entertainment.setEntertainmentType("Entertainment Type");
        entertainment.setPriceTicketAdult(10.0f);
        entertainment.setPriceTicketChildren(10.0f);
        entertainment.setServiceId(service1);
        entertainment.setTimeClose(LocalTime.of(1, 1));
        entertainment.setTimeOpen(LocalTime.of(1, 1));

        Account account = new Account();
        account.setAccountId(1234567890L);
        account.setCommentList(new ArrayList<>());
        account.setEmail("jane.doe@example.org");
        account.setFeedbackList(new ArrayList<>());
        account.setIsBlock(true);
        account.setPartner(new Partner());
        account.setPassWord("Pass Word");
        account.setRoleId(new Role());
        account.setTourList(new ArrayList<>());
        account.setUser(new User());
        account.setUserBookingList(new ArrayList<>());

        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(new Partner());
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");

        ServiceCategory serviceCategory = new ServiceCategory();
        serviceCategory.setPartnerList(new ArrayList<>());
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        serviceCategory.setServiceList(new ArrayList<>());

        Partner partner = new Partner();
        partner.setAccountId(account);
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(companyPartner);
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(serviceCategory);
        partner.setServiceList(new ArrayList<>());

        Service service2 = new Service();
        service2.setAccommodation(new Accommodation());
        service2.setAddress("42 Main St");
        service2.setCity("Oxford");
        service2.setDateRegister(null);
        service2.setEmail("jane.doe@example.org");
        service2.setEntertainment(new Entertainment());
        service2.setFax("Fax");
        service2.setIsActive(true);
        service2.setIsBlock(true);
        service2.setLink("Link");
        service2.setPartnerId(new Partner());
        service2.setPhone("4105551212");
        service2.setPostList(new ArrayList<>());
        service2.setRestaurant(new Restaurant());
        service2.setServiceCategoryId(new ServiceCategory());
        service2.setServiceId(123L);
        service2.setServiceName("Service Name");
        service2.setStatus(1);
        service2.setTaxCode("Tax Code");
        service2.setUtilitiesServiceList(new ArrayList<>());

        Restaurant restaurant = new Restaurant();
        restaurant.setDescription("The characteristics of someone or something");
        restaurant.setRate(10.0f);
        restaurant.setRestaurantId(123L);
        restaurant.setRestaurantServiceType("Restaurant Service Type");
        restaurant.setServiceId(service2);
        restaurant.setTimeClose(LocalTime.of(1, 1));
        restaurant.setTimeOpen(LocalTime.of(1, 1));
        restaurant.setTypeOfCuisineServiceList(new ArrayList<>());

        ServiceCategory serviceCategory1 = new ServiceCategory();
        serviceCategory1.setPartnerList(new ArrayList<>());
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        serviceCategory1.setServiceList(new ArrayList<>());

        Service service3 = new Service();
        service3.setAccommodation(accommodation);
        service3.setAddress("42 Main St");
        service3.setCity("Oxford");
        service3.setDateRegister(LocalDate.ofEpochDay(1L));
        service3.setEmail("jane.doe@example.org");
        service3.setEntertainment(entertainment);
        service3.setFax("Fax");
        service3.setIsActive(true);
        service3.setIsBlock(true);
        service3.setLink("Link");
        service3.setPartnerId(partner);
        service3.setPhone("4105551212");
        service3.setPostList(new ArrayList<>());
        service3.setRestaurant(restaurant);
        service3.setServiceCategoryId(serviceCategory1);
        service3.setServiceId(123L);
        service3.setServiceName("Service Name");
        service3.setStatus(1);
        service3.setTaxCode("Tax Code");
        service3.setUtilitiesServiceList(new ArrayList<>());

        Topic topic = new Topic();
        topic.setPostList(new ArrayList<>());
        topic.setTopicId(123L);
        topic.setTopicName("Topic Name");

        Post post = new Post();
        post.setContent("Not all who wander are lost");
        post.setDescription("The characteristics of someone or something");
        post.setIsBlock(true);
        post.setIsPublic(true);
        post.setPostId(123L);
        post.setReportPostList(new ArrayList<>());
        post.setServiceId(service3);
        post.setTimePost(LocalDateTime.of(1, 1, 1, 1, 1));
        post.setTitle("Dr");
        post.setTopicId(topic);

        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        partner1.setServiceList(new ArrayList<>());

        Role role = new Role();
        role.setAccountList(new ArrayList<>());
        role.setRoleId(123);
        role.setRoleName("Role Name");

        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);

        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        account1.setCommentList(new ArrayList<>());
        account1.setEmail("jane.doe@example.org");
        account1.setFeedbackList(new ArrayList<>());
        account1.setIsBlock(true);
        account1.setPartner(partner1);
        account1.setPassWord("Pass Word");
        account1.setRoleId(role);
        account1.setTourList(new ArrayList<>());
        account1.setUser(user);
        account1.setUserBookingList(new ArrayList<>());

        Partner partner2 = new Partner();
        partner2.setAccountId(new Account());
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(new CompanyPartner());
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(new ServiceCategory());
        partner2.setServiceList(new ArrayList<>());

        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(partner2);
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");

        ServiceCategory serviceCategory2 = new ServiceCategory();
        serviceCategory2.setPartnerList(new ArrayList<>());
        serviceCategory2.setServiceCategoryId(123L);
        serviceCategory2.setServiceCategoryName("Service Category Name");
        serviceCategory2.setServiceList(new ArrayList<>());

        Partner partner3 = new Partner();
        partner3.setAccountId(account1);
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(companyPartner1);
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(serviceCategory2);
        partner3.setServiceList(new ArrayList<>());

        Role role1 = new Role();
        role1.setAccountList(new ArrayList<>());
        role1.setRoleId(123);
        role1.setRoleName("Role Name");

        Partner partner4 = new Partner();
        partner4.setAccountId(new Account());
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(new CompanyPartner());
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(new ServiceCategory());
        partner4.setServiceList(new ArrayList<>());

        Role role2 = new Role();
        role2.setAccountList(new ArrayList<>());
        role2.setRoleId(123);
        role2.setRoleName("Role Name");

        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);

        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        account2.setCommentList(new ArrayList<>());
        account2.setEmail("jane.doe@example.org");
        account2.setFeedbackList(new ArrayList<>());
        account2.setIsBlock(true);
        account2.setPartner(partner4);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role2);
        account2.setTourList(new ArrayList<>());
        account2.setUser(user1);
        account2.setUserBookingList(new ArrayList<>());

        User user2 = new User();
        user2.setAccountId(account2);
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);

        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        account3.setCommentList(new ArrayList<>());
        account3.setEmail("jane.doe@example.org");
        account3.setFeedbackList(new ArrayList<>());
        account3.setIsBlock(true);
        account3.setPartner(partner3);
        account3.setPassWord("Pass Word");
        account3.setRoleId(role1);
        account3.setTourList(new ArrayList<>());
        account3.setUser(user2);
        account3.setUserBookingList(new ArrayList<>());

        ReasonReportPost reasonReportPost = new ReasonReportPost();
        reasonReportPost.setReasonReportPostId(123L);
        reasonReportPost.setReasonReportPostName("Just cause");
        reasonReportPost.setReportPostList(new ArrayList<>());
        ReportPost actualReportPost = new ReportPost(123L, post, account3, reasonReportPost);
        Partner partner5 = new Partner();
        partner5.setAccountId(new Account());
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(new CompanyPartner());
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(new ServiceCategory());
        partner5.setServiceList(new ArrayList<>());
        Role role3 = new Role();
        role3.setAccountList(new ArrayList<>());
        role3.setRoleId(123);
        role3.setRoleName("Role Name");
        User user3 = new User();
        user3.setAccountId(new Account());
        user3.setAddress("42 Main St");
        user3.setBirthDate("2020-03-01");
        user3.setCity("Oxford");
        user3.setFirstName("Jane");
        user3.setGender("Gender");
        user3.setIsPrivate(true);
        user3.setLastName("Doe");
        user3.setPhone("4105551212");
        user3.setRankPoint(1);
        user3.setUserId(123L);
        Account account4 = new Account();
        account4.setAccountId(1234567890L);
        account4.setCommentList(new ArrayList<>());
        account4.setEmail("jane.doe@example.org");
        account4.setFeedbackList(new ArrayList<>());
        account4.setIsBlock(true);
        account4.setPartner(partner5);
        account4.setPassWord("Pass Word");
        account4.setRoleId(role3);
        account4.setTourList(new ArrayList<>());
        account4.setUser(user3);
        account4.setUserBookingList(new ArrayList<>());
        Partner partner6 = new Partner();
        partner6.setAccountId(new Account());
        partner6.setAddress("42 Main St");
        partner6.setBirthDate("2020-03-01");
        partner6.setCity("Oxford");
        partner6.setCompanyPartnerId(new CompanyPartner());
        partner6.setDateIssue("2020-03-01");
        partner6.setDepartment("Department");
        partner6.setEmail("jane.doe@example.org");
        partner6.setFirstName("Jane");
        partner6.setGender("Gender");
        partner6.setLastName("Doe");
        partner6.setNumberIdCard("42");
        partner6.setPartnerId(123L);
        partner6.setPhone("4105551212");
        partner6.setPlaceIssue("Place Issue");
        partner6.setPosition("Position");
        partner6.setServiceCategoryId(new ServiceCategory());
        partner6.setServiceList(new ArrayList<>());
        CompanyPartner companyPartner2 = new CompanyPartner();
        companyPartner2.setAddress("42 Main St");
        companyPartner2.setBusinessCode("Business Code");
        companyPartner2.setCity("Oxford");
        companyPartner2.setCompanyName("Company Name");
        companyPartner2.setCompanyPartnerId(123L);
        companyPartner2.setEmail("jane.doe@example.org");
        companyPartner2.setFax("Fax");
        companyPartner2.setIncorporationDate("2020-03-01");
        companyPartner2.setPartnerId(partner6);
        companyPartner2.setPhone("4105551212");
        companyPartner2.setRegistrationDate("2020-03-01");
        companyPartner2.setShortName("Short Name");
        companyPartner2.setTaxCode("Tax Code");
        companyPartner2.setWebsite("Website");
        ServiceCategory serviceCategory3 = new ServiceCategory();
        serviceCategory3.setPartnerList(new ArrayList<>());
        serviceCategory3.setServiceCategoryId(123L);
        serviceCategory3.setServiceCategoryName("Service Category Name");
        serviceCategory3.setServiceList(new ArrayList<>());
        Partner partner7 = new Partner();
        partner7.setAccountId(account4);
        partner7.setAddress("42 Main St");
        partner7.setBirthDate("2020-03-01");
        partner7.setCity("Oxford");
        partner7.setCompanyPartnerId(companyPartner2);
        partner7.setDateIssue("2020-03-01");
        partner7.setDepartment("Department");
        partner7.setEmail("jane.doe@example.org");
        partner7.setFirstName("Jane");
        partner7.setGender("Gender");
        partner7.setLastName("Doe");
        partner7.setNumberIdCard("42");
        partner7.setPartnerId(123L);
        partner7.setPhone("4105551212");
        partner7.setPlaceIssue("Place Issue");
        partner7.setPosition("Position");
        partner7.setServiceCategoryId(serviceCategory3);
        partner7.setServiceList(new ArrayList<>());
        Role role4 = new Role();
        role4.setAccountList(new ArrayList<>());
        role4.setRoleId(123);
        role4.setRoleName("Role Name");
        Partner partner8 = new Partner();
        partner8.setAccountId(new Account());
        partner8.setAddress("42 Main St");
        partner8.setBirthDate("2020-03-01");
        partner8.setCity("Oxford");
        partner8.setCompanyPartnerId(new CompanyPartner());
        partner8.setDateIssue("2020-03-01");
        partner8.setDepartment("Department");
        partner8.setEmail("jane.doe@example.org");
        partner8.setFirstName("Jane");
        partner8.setGender("Gender");
        partner8.setLastName("Doe");
        partner8.setNumberIdCard("42");
        partner8.setPartnerId(123L);
        partner8.setPhone("4105551212");
        partner8.setPlaceIssue("Place Issue");
        partner8.setPosition("Position");
        partner8.setServiceCategoryId(new ServiceCategory());
        partner8.setServiceList(new ArrayList<>());
        Role role5 = new Role();
        role5.setAccountList(new ArrayList<>());
        role5.setRoleId(123);
        role5.setRoleName("Role Name");
        User user4 = new User();
        user4.setAccountId(new Account());
        user4.setAddress("42 Main St");
        user4.setBirthDate("2020-03-01");
        user4.setCity("Oxford");
        user4.setFirstName("Jane");
        user4.setGender("Gender");
        user4.setIsPrivate(true);
        user4.setLastName("Doe");
        user4.setPhone("4105551212");
        user4.setRankPoint(1);
        user4.setUserId(123L);
        Account account5 = new Account();
        account5.setAccountId(1234567890L);
        account5.setCommentList(new ArrayList<>());
        account5.setEmail("jane.doe@example.org");
        account5.setFeedbackList(new ArrayList<>());
        account5.setIsBlock(true);
        account5.setPartner(partner8);
        account5.setPassWord("Pass Word");
        account5.setRoleId(role5);
        account5.setTourList(new ArrayList<>());
        account5.setUser(user4);
        account5.setUserBookingList(new ArrayList<>());
        User user5 = new User();
        user5.setAccountId(account5);
        user5.setAddress("42 Main St");
        user5.setBirthDate("2020-03-01");
        user5.setCity("Oxford");
        user5.setFirstName("Jane");
        user5.setGender("Gender");
        user5.setIsPrivate(true);
        user5.setLastName("Doe");
        user5.setPhone("4105551212");
        user5.setRankPoint(1);
        user5.setUserId(123L);
        Account account6 = new Account();
        account6.setAccountId(1234567890L);
        account6.setCommentList(new ArrayList<>());
        account6.setEmail("jane.doe@example.org");
        account6.setFeedbackList(new ArrayList<>());
        account6.setIsBlock(true);
        account6.setPartner(partner7);
        account6.setPassWord("Pass Word");
        account6.setRoleId(role4);
        account6.setTourList(new ArrayList<>());
        account6.setUser(user5);
        account6.setUserBookingList(new ArrayList<>());
        actualReportPost.setAccountId(account6);
        Service service4 = new Service();
        service4.setAccommodation(new Accommodation());
        service4.setAddress("42 Main St");
        service4.setCity("Oxford");
        service4.setDateRegister(null);
        service4.setEmail("jane.doe@example.org");
        service4.setEntertainment(new Entertainment());
        service4.setFax("Fax");
        service4.setIsActive(true);
        service4.setIsBlock(true);
        service4.setLink("Link");
        service4.setPartnerId(new Partner());
        service4.setPhone("4105551212");
        service4.setPostList(new ArrayList<>());
        service4.setRestaurant(new Restaurant());
        service4.setServiceCategoryId(new ServiceCategory());
        service4.setServiceId(123L);
        service4.setServiceName("Service Name");
        service4.setStatus(1);
        service4.setTaxCode("Tax Code");
        service4.setUtilitiesServiceList(new ArrayList<>());
        Accommodation accommodation1 = new Accommodation();
        accommodation1.setAccommodationId(123L);
        accommodation1.setAccommodationType("Accommodation Type");
        accommodation1.setDescription("The characteristics of someone or something");
        accommodation1.setNumberFloors(10);
        accommodation1.setRate(10.0f);
        accommodation1.setRoomList(new ArrayList<>());
        accommodation1.setServiceId(service4);
        Service service5 = new Service();
        service5.setAccommodation(new Accommodation());
        service5.setAddress("42 Main St");
        service5.setCity("Oxford");
        service5.setDateRegister(null);
        service5.setEmail("jane.doe@example.org");
        service5.setEntertainment(new Entertainment());
        service5.setFax("Fax");
        service5.setIsActive(true);
        service5.setIsBlock(true);
        service5.setLink("Link");
        service5.setPartnerId(new Partner());
        service5.setPhone("4105551212");
        service5.setPostList(new ArrayList<>());
        service5.setRestaurant(new Restaurant());
        service5.setServiceCategoryId(new ServiceCategory());
        service5.setServiceId(123L);
        service5.setServiceName("Service Name");
        service5.setStatus(1);
        service5.setTaxCode("Tax Code");
        service5.setUtilitiesServiceList(new ArrayList<>());
        Entertainment entertainment1 = new Entertainment();
        entertainment1.setDescription("The characteristics of someone or something");
        entertainment1.setDowOpen("Dow Open");
        entertainment1.setEntertainmentId(123L);
        entertainment1.setEntertainmentType("Entertainment Type");
        entertainment1.setPriceTicketAdult(10.0f);
        entertainment1.setPriceTicketChildren(10.0f);
        entertainment1.setServiceId(service5);
        entertainment1.setTimeClose(LocalTime.of(1, 1));
        entertainment1.setTimeOpen(LocalTime.of(1, 1));
        Account account7 = new Account();
        account7.setAccountId(1234567890L);
        account7.setCommentList(new ArrayList<>());
        account7.setEmail("jane.doe@example.org");
        account7.setFeedbackList(new ArrayList<>());
        account7.setIsBlock(true);
        account7.setPartner(new Partner());
        account7.setPassWord("Pass Word");
        account7.setRoleId(new Role());
        account7.setTourList(new ArrayList<>());
        account7.setUser(new User());
        account7.setUserBookingList(new ArrayList<>());
        CompanyPartner companyPartner3 = new CompanyPartner();
        companyPartner3.setAddress("42 Main St");
        companyPartner3.setBusinessCode("Business Code");
        companyPartner3.setCity("Oxford");
        companyPartner3.setCompanyName("Company Name");
        companyPartner3.setCompanyPartnerId(123L);
        companyPartner3.setEmail("jane.doe@example.org");
        companyPartner3.setFax("Fax");
        companyPartner3.setIncorporationDate("2020-03-01");
        companyPartner3.setPartnerId(new Partner());
        companyPartner3.setPhone("4105551212");
        companyPartner3.setRegistrationDate("2020-03-01");
        companyPartner3.setShortName("Short Name");
        companyPartner3.setTaxCode("Tax Code");
        companyPartner3.setWebsite("Website");
        ServiceCategory serviceCategory4 = new ServiceCategory();
        serviceCategory4.setPartnerList(new ArrayList<>());
        serviceCategory4.setServiceCategoryId(123L);
        serviceCategory4.setServiceCategoryName("Service Category Name");
        serviceCategory4.setServiceList(new ArrayList<>());
        Partner partner9 = new Partner();
        partner9.setAccountId(account7);
        partner9.setAddress("42 Main St");
        partner9.setBirthDate("2020-03-01");
        partner9.setCity("Oxford");
        partner9.setCompanyPartnerId(companyPartner3);
        partner9.setDateIssue("2020-03-01");
        partner9.setDepartment("Department");
        partner9.setEmail("jane.doe@example.org");
        partner9.setFirstName("Jane");
        partner9.setGender("Gender");
        partner9.setLastName("Doe");
        partner9.setNumberIdCard("42");
        partner9.setPartnerId(123L);
        partner9.setPhone("4105551212");
        partner9.setPlaceIssue("Place Issue");
        partner9.setPosition("Position");
        partner9.setServiceCategoryId(serviceCategory4);
        partner9.setServiceList(new ArrayList<>());
        Service service6 = new Service();
        service6.setAccommodation(new Accommodation());
        service6.setAddress("42 Main St");
        service6.setCity("Oxford");
        service6.setDateRegister(null);
        service6.setEmail("jane.doe@example.org");
        service6.setEntertainment(new Entertainment());
        service6.setFax("Fax");
        service6.setIsActive(true);
        service6.setIsBlock(true);
        service6.setLink("Link");
        service6.setPartnerId(new Partner());
        service6.setPhone("4105551212");
        service6.setPostList(new ArrayList<>());
        service6.setRestaurant(new Restaurant());
        service6.setServiceCategoryId(new ServiceCategory());
        service6.setServiceId(123L);
        service6.setServiceName("Service Name");
        service6.setStatus(1);
        service6.setTaxCode("Tax Code");
        service6.setUtilitiesServiceList(new ArrayList<>());
        Restaurant restaurant1 = new Restaurant();
        restaurant1.setDescription("The characteristics of someone or something");
        restaurant1.setRate(10.0f);
        restaurant1.setRestaurantId(123L);
        restaurant1.setRestaurantServiceType("Restaurant Service Type");
        restaurant1.setServiceId(service6);
        restaurant1.setTimeClose(LocalTime.of(1, 1));
        restaurant1.setTimeOpen(LocalTime.of(1, 1));
        restaurant1.setTypeOfCuisineServiceList(new ArrayList<>());
        ServiceCategory serviceCategory5 = new ServiceCategory();
        serviceCategory5.setPartnerList(new ArrayList<>());
        serviceCategory5.setServiceCategoryId(123L);
        serviceCategory5.setServiceCategoryName("Service Category Name");
        serviceCategory5.setServiceList(new ArrayList<>());
        Service service7 = new Service();
        service7.setAccommodation(accommodation1);
        service7.setAddress("42 Main St");
        service7.setCity("Oxford");
        service7.setDateRegister(LocalDate.ofEpochDay(1L));
        service7.setEmail("jane.doe@example.org");
        service7.setEntertainment(entertainment1);
        service7.setFax("Fax");
        service7.setIsActive(true);
        service7.setIsBlock(true);
        service7.setLink("Link");
        service7.setPartnerId(partner9);
        service7.setPhone("4105551212");
        service7.setPostList(new ArrayList<>());
        service7.setRestaurant(restaurant1);
        service7.setServiceCategoryId(serviceCategory5);
        service7.setServiceId(123L);
        service7.setServiceName("Service Name");
        service7.setStatus(1);
        service7.setTaxCode("Tax Code");
        service7.setUtilitiesServiceList(new ArrayList<>());
        Topic topic1 = new Topic();
        topic1.setPostList(new ArrayList<>());
        topic1.setTopicId(123L);
        topic1.setTopicName("Topic Name");
        Post post1 = new Post();
        post1.setContent("Not all who wander are lost");
        post1.setDescription("The characteristics of someone or something");
        post1.setIsBlock(true);
        post1.setIsPublic(true);
        post1.setPostId(123L);
        post1.setReportPostList(new ArrayList<>());
        post1.setServiceId(service7);
        post1.setTimePost(LocalDateTime.of(1, 1, 1, 1, 1));
        post1.setTitle("Dr");
        post1.setTopicId(topic1);
        actualReportPost.setPostId(post1);
        ReasonReportPost reasonReportPost1 = new ReasonReportPost();
        reasonReportPost1.setReasonReportPostId(123L);
        reasonReportPost1.setReasonReportPostName("Just cause");
        reasonReportPost1.setReportPostList(new ArrayList<>());
        actualReportPost.setReasonReportPostId(reasonReportPost1);
        actualReportPost.setReportPostId(123L);
        assertSame(account6, actualReportPost.getAccountId());
        assertSame(post1, actualReportPost.getPostId());
        assertSame(reasonReportPost1, actualReportPost.getReasonReportPostId());
        assertEquals(123L, actualReportPost.getReportPostId().longValue());
    }
}

