package com.example.wetravel.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;

import org.junit.jupiter.api.Test;

class ReportFeedbackTest {
    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link ReportFeedback#ReportFeedback()}
     *   <li>{@link ReportFeedback#setAccountId(Account)}
     *   <li>{@link ReportFeedback#setFeedbackId(Feedback)}
     *   <li>{@link ReportFeedback#setReasonReportFeedbackId(ReasonReportFeedback)}
     *   <li>{@link ReportFeedback#setReportFeedbackId(Long)}
     *   <li>{@link ReportFeedback#getAccountId()}
     *   <li>{@link ReportFeedback#getFeedbackId()}
     *   <li>{@link ReportFeedback#getReasonReportFeedbackId()}
     *   <li>{@link ReportFeedback#getReportFeedbackId()}
     * </ul>
     */
    @Test
    void testConstructor() {
        ReportFeedback actualReportFeedback = new ReportFeedback();
        Partner partner = new Partner();
        partner.setAccountId(new Account());
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(new CompanyPartner());
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(new ServiceCategory());
        partner.setServiceList(new ArrayList<>());
        Role role = new Role();
        role.setAccountList(new ArrayList<>());
        role.setRoleId(123);
        role.setRoleName("Role Name");
        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);
        Account account = new Account();
        account.setAccountId(1234567890L);
        account.setCommentList(new ArrayList<>());
        account.setEmail("jane.doe@example.org");
        account.setFeedbackList(new ArrayList<>());
        account.setIsBlock(true);
        account.setPartner(partner);
        account.setPassWord("Pass Word");
        account.setRoleId(role);
        account.setTourList(new ArrayList<>());
        account.setUser(user);
        account.setUserBookingList(new ArrayList<>());
        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        partner1.setServiceList(new ArrayList<>());
        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(partner1);
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");
        ServiceCategory serviceCategory = new ServiceCategory();
        serviceCategory.setPartnerList(new ArrayList<>());
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        serviceCategory.setServiceList(new ArrayList<>());
        Partner partner2 = new Partner();
        partner2.setAccountId(account);
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(companyPartner);
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(serviceCategory);
        partner2.setServiceList(new ArrayList<>());
        Role role1 = new Role();
        role1.setAccountList(new ArrayList<>());
        role1.setRoleId(123);
        role1.setRoleName("Role Name");
        Partner partner3 = new Partner();
        partner3.setAccountId(new Account());
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(new CompanyPartner());
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(new ServiceCategory());
        partner3.setServiceList(new ArrayList<>());
        Role role2 = new Role();
        role2.setAccountList(new ArrayList<>());
        role2.setRoleId(123);
        role2.setRoleName("Role Name");
        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);
        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        account1.setCommentList(new ArrayList<>());
        account1.setEmail("jane.doe@example.org");
        account1.setFeedbackList(new ArrayList<>());
        account1.setIsBlock(true);
        account1.setPartner(partner3);
        account1.setPassWord("Pass Word");
        account1.setRoleId(role2);
        account1.setTourList(new ArrayList<>());
        account1.setUser(user1);
        account1.setUserBookingList(new ArrayList<>());
        User user2 = new User();
        user2.setAccountId(account1);
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);
        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        account2.setCommentList(new ArrayList<>());
        account2.setEmail("jane.doe@example.org");
        account2.setFeedbackList(new ArrayList<>());
        account2.setIsBlock(true);
        account2.setPartner(partner2);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role1);
        account2.setTourList(new ArrayList<>());
        account2.setUser(user2);
        account2.setUserBookingList(new ArrayList<>());
        actualReportFeedback.setAccountId(account2);
        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        account3.setCommentList(new ArrayList<>());
        account3.setEmail("jane.doe@example.org");
        account3.setFeedbackList(new ArrayList<>());
        account3.setIsBlock(true);
        account3.setPartner(new Partner());
        account3.setPassWord("Pass Word");
        account3.setRoleId(new Role());
        account3.setTourList(new ArrayList<>());
        account3.setUser(new User());
        account3.setUserBookingList(new ArrayList<>());
        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(new Partner());
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");
        ServiceCategory serviceCategory1 = new ServiceCategory();
        serviceCategory1.setPartnerList(new ArrayList<>());
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        serviceCategory1.setServiceList(new ArrayList<>());
        Partner partner4 = new Partner();
        partner4.setAccountId(account3);
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(companyPartner1);
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(serviceCategory1);
        partner4.setServiceList(new ArrayList<>());
        Role role3 = new Role();
        role3.setAccountList(new ArrayList<>());
        role3.setRoleId(123);
        role3.setRoleName("Role Name");
        Account account4 = new Account();
        account4.setAccountId(1234567890L);
        account4.setCommentList(new ArrayList<>());
        account4.setEmail("jane.doe@example.org");
        account4.setFeedbackList(new ArrayList<>());
        account4.setIsBlock(true);
        account4.setPartner(new Partner());
        account4.setPassWord("Pass Word");
        account4.setRoleId(new Role());
        account4.setTourList(new ArrayList<>());
        account4.setUser(new User());
        account4.setUserBookingList(new ArrayList<>());
        User user3 = new User();
        user3.setAccountId(account4);
        user3.setAddress("42 Main St");
        user3.setBirthDate("2020-03-01");
        user3.setCity("Oxford");
        user3.setFirstName("Jane");
        user3.setGender("Gender");
        user3.setIsPrivate(true);
        user3.setLastName("Doe");
        user3.setPhone("4105551212");
        user3.setRankPoint(1);
        user3.setUserId(123L);
        Account account5 = new Account();
        account5.setAccountId(1234567890L);
        account5.setCommentList(new ArrayList<>());
        account5.setEmail("jane.doe@example.org");
        account5.setFeedbackList(new ArrayList<>());
        account5.setIsBlock(true);
        account5.setPartner(partner4);
        account5.setPassWord("Pass Word");
        account5.setRoleId(role3);
        account5.setTourList(new ArrayList<>());
        account5.setUser(user3);
        account5.setUserBookingList(new ArrayList<>());
        Partner partner5 = new Partner();
        partner5.setAccountId(new Account());
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(new CompanyPartner());
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(new ServiceCategory());
        partner5.setServiceList(new ArrayList<>());
        Role role4 = new Role();
        role4.setAccountList(new ArrayList<>());
        role4.setRoleId(123);
        role4.setRoleName("Role Name");
        User user4 = new User();
        user4.setAccountId(new Account());
        user4.setAddress("42 Main St");
        user4.setBirthDate("2020-03-01");
        user4.setCity("Oxford");
        user4.setFirstName("Jane");
        user4.setGender("Gender");
        user4.setIsPrivate(true);
        user4.setLastName("Doe");
        user4.setPhone("4105551212");
        user4.setRankPoint(1);
        user4.setUserId(123L);
        Account account6 = new Account();
        account6.setAccountId(1234567890L);
        account6.setCommentList(new ArrayList<>());
        account6.setEmail("jane.doe@example.org");
        account6.setFeedbackList(new ArrayList<>());
        account6.setIsBlock(true);
        account6.setPartner(partner5);
        account6.setPassWord("Pass Word");
        account6.setRoleId(role4);
        account6.setTourList(new ArrayList<>());
        account6.setUser(user4);
        account6.setUserBookingList(new ArrayList<>());
        TourCategory tourCategory = new TourCategory();
        tourCategory.setTourCategoryId(123L);
        tourCategory.setTourCategoryName("Tour Category Name");
        tourCategory.setTourList(new ArrayList<>());
        Tour tour = new Tour();
        tour.setAccountId(new Account());
        tour.setDeposit(10.0f);
        tour.setEndPlace("End Place");
        tour.setEndTime(null);
        tour.setFeedbackList(new ArrayList<>());
        tour.setMaxAdult(3);
        tour.setMaxChildren(3);
        tour.setMinAdult(1);
        tour.setMinChildren(1);
        tour.setMinToStart(1);
        tour.setNote("Note");
        tour.setNumberOfDay(10);
        tour.setNumberOfNight(10);
        tour.setPriceAdult(10.0f);
        tour.setPriceChildren(10.0f);
        tour.setStartDate(null);
        tour.setStartPlace("Start Place");
        tour.setStartTime(null);
        tour.setStatus(1);
        tour.setTotalPrice(10.0f);
        tour.setTourCategoryId(new TourCategory());
        tour.setTourCode("Tour Code");
        tour.setTourDetail(new TourDetail());
        tour.setTourId(123L);
        tour.setTourMode(true);
        tour.setTourName("Tour Name");
        tour.setTourScheduleList(new ArrayList<>());
        tour.setTourType(1);
        tour.setUserBookingList(new ArrayList<>());
        TourDetail tourDetail = new TourDetail();
        tourDetail.setAddressStart("42 Main St");
        tourDetail.setDescription("The characteristics of someone or something");
        tourDetail.setGeneralTerms("General Terms");
        tourDetail.setLatitude(10.0f);
        tourDetail.setLongitude(10.0f);
        tourDetail.setMoreDescription("More Description");
        tourDetail.setTagOfTourList(new ArrayList<>());
        tourDetail.setTourDetailId(123L);
        tourDetail.setTourId(tour);
        tourDetail.setTourInclude("Tour Include");
        tourDetail.setTourIntroduce("Tour Introduce");
        tourDetail.setTourNonInclude("Tour Non Include");
        Tour tour1 = new Tour();
        tour1.setAccountId(account6);
        tour1.setDeposit(10.0f);
        tour1.setEndPlace("End Place");
        tour1.setEndTime(LocalTime.of(1, 1));
        tour1.setFeedbackList(new ArrayList<>());
        tour1.setMaxAdult(3);
        tour1.setMaxChildren(3);
        tour1.setMinAdult(1);
        tour1.setMinChildren(1);
        tour1.setMinToStart(1);
        tour1.setNote("Note");
        tour1.setNumberOfDay(10);
        tour1.setNumberOfNight(10);
        tour1.setPriceAdult(10.0f);
        tour1.setPriceChildren(10.0f);
        tour1.setStartDate(LocalDate.ofEpochDay(1L));
        tour1.setStartPlace("Start Place");
        tour1.setStartTime(LocalTime.of(1, 1));
        tour1.setStatus(1);
        tour1.setTotalPrice(10.0f);
        tour1.setTourCategoryId(tourCategory);
        tour1.setTourCode("Tour Code");
        tour1.setTourDetail(tourDetail);
        tour1.setTourId(123L);
        tour1.setTourMode(true);
        tour1.setTourName("Tour Name");
        tour1.setTourScheduleList(new ArrayList<>());
        tour1.setTourType(1);
        tour1.setUserBookingList(new ArrayList<>());
        Partner partner6 = new Partner();
        partner6.setAccountId(new Account());
        partner6.setAddress("42 Main St");
        partner6.setBirthDate("2020-03-01");
        partner6.setCity("Oxford");
        partner6.setCompanyPartnerId(new CompanyPartner());
        partner6.setDateIssue("2020-03-01");
        partner6.setDepartment("Department");
        partner6.setEmail("jane.doe@example.org");
        partner6.setFirstName("Jane");
        partner6.setGender("Gender");
        partner6.setLastName("Doe");
        partner6.setNumberIdCard("42");
        partner6.setPartnerId(123L);
        partner6.setPhone("4105551212");
        partner6.setPlaceIssue("Place Issue");
        partner6.setPosition("Position");
        partner6.setServiceCategoryId(new ServiceCategory());
        partner6.setServiceList(new ArrayList<>());
        Role role5 = new Role();
        role5.setAccountList(new ArrayList<>());
        role5.setRoleId(123);
        role5.setRoleName("Role Name");
        User user5 = new User();
        user5.setAccountId(new Account());
        user5.setAddress("42 Main St");
        user5.setBirthDate("2020-03-01");
        user5.setCity("Oxford");
        user5.setFirstName("Jane");
        user5.setGender("Gender");
        user5.setIsPrivate(true);
        user5.setLastName("Doe");
        user5.setPhone("4105551212");
        user5.setRankPoint(1);
        user5.setUserId(123L);
        Account account7 = new Account();
        account7.setAccountId(1234567890L);
        account7.setCommentList(new ArrayList<>());
        account7.setEmail("jane.doe@example.org");
        account7.setFeedbackList(new ArrayList<>());
        account7.setIsBlock(true);
        account7.setPartner(partner6);
        account7.setPassWord("Pass Word");
        account7.setRoleId(role5);
        account7.setTourList(new ArrayList<>());
        account7.setUser(user5);
        account7.setUserBookingList(new ArrayList<>());
        Account account8 = new Account();
        account8.setAccountId(1234567890L);
        account8.setCommentList(new ArrayList<>());
        account8.setEmail("jane.doe@example.org");
        account8.setFeedbackList(new ArrayList<>());
        account8.setIsBlock(true);
        account8.setPartner(new Partner());
        account8.setPassWord("Pass Word");
        account8.setRoleId(new Role());
        account8.setTourList(new ArrayList<>());
        account8.setUser(new User());
        account8.setUserBookingList(new ArrayList<>());
        Tour tour2 = new Tour();
        tour2.setAccountId(new Account());
        tour2.setDeposit(10.0f);
        tour2.setEndPlace("End Place");
        tour2.setEndTime(null);
        tour2.setFeedbackList(new ArrayList<>());
        tour2.setMaxAdult(3);
        tour2.setMaxChildren(3);
        tour2.setMinAdult(1);
        tour2.setMinChildren(1);
        tour2.setMinToStart(1);
        tour2.setNote("Note");
        tour2.setNumberOfDay(10);
        tour2.setNumberOfNight(10);
        tour2.setPriceAdult(10.0f);
        tour2.setPriceChildren(10.0f);
        tour2.setStartDate(null);
        tour2.setStartPlace("Start Place");
        tour2.setStartTime(null);
        tour2.setStatus(1);
        tour2.setTotalPrice(10.0f);
        tour2.setTourCategoryId(new TourCategory());
        tour2.setTourCode("Tour Code");
        tour2.setTourDetail(new TourDetail());
        tour2.setTourId(123L);
        tour2.setTourMode(true);
        tour2.setTourName("Tour Name");
        tour2.setTourScheduleList(new ArrayList<>());
        tour2.setTourType(1);
        tour2.setUserBookingList(new ArrayList<>());
        UserBooking userBooking = new UserBooking();
        userBooking.setAccountId(new Account());
        userBooking.setAdultPrice(10.0f);
        userBooking.setBookingDate(null);
        userBooking.setChildrenPrice(10.0f);
        userBooking.setDateOfIssue(null);
        userBooking.setEmail("jane.doe@example.org");
        userBooking.setFeedbackId(new Feedback());
        userBooking.setFullName("Dr Jane Doe");
        userBooking.setIdCard("Id Card");
        userBooking.setIsFeedback(true);
        userBooking.setNumberOfAdult(10);
        userBooking.setNumberOfChildren(10);
        userBooking.setOrderId(123L);
        userBooking.setOrderTitle("Dr");
        userBooking.setPayType("Pay Type");
        userBooking.setPhone("4105551212");
        userBooking.setPlaceOfIssue("Place Of Issue");
        userBooking.setRequest("Request");
        userBooking.setRequestCancelList(new ArrayList<>());
        userBooking.setStartDate(null);
        userBooking.setStatus(1);
        userBooking.setStatusDeposit(true);
        userBooking.setTotalPrice(10.0f);
        userBooking.setTourId(new Tour());
        userBooking.setUserBookingId(123L);
        Feedback feedback = new Feedback();
        feedback.setAccountId(account8);
        feedback.setContent("Not all who wander are lost");
        feedback.setCreateDate(LocalDate.ofEpochDay(1L));
        feedback.setFeedbackId(123L);
        feedback.setIsBlock(true);
        feedback.setReportFeedbackList(new ArrayList<>());
        feedback.setTourId(tour2);
        feedback.setUserBookingId(userBooking);
        Account account9 = new Account();
        account9.setAccountId(1234567890L);
        account9.setCommentList(new ArrayList<>());
        account9.setEmail("jane.doe@example.org");
        account9.setFeedbackList(new ArrayList<>());
        account9.setIsBlock(true);
        account9.setPartner(new Partner());
        account9.setPassWord("Pass Word");
        account9.setRoleId(new Role());
        account9.setTourList(new ArrayList<>());
        account9.setUser(new User());
        account9.setUserBookingList(new ArrayList<>());
        TourCategory tourCategory1 = new TourCategory();
        tourCategory1.setTourCategoryId(123L);
        tourCategory1.setTourCategoryName("Tour Category Name");
        tourCategory1.setTourList(new ArrayList<>());
        TourDetail tourDetail1 = new TourDetail();
        tourDetail1.setAddressStart("42 Main St");
        tourDetail1.setDescription("The characteristics of someone or something");
        tourDetail1.setGeneralTerms("General Terms");
        tourDetail1.setLatitude(10.0f);
        tourDetail1.setLongitude(10.0f);
        tourDetail1.setMoreDescription("More Description");
        tourDetail1.setTagOfTourList(new ArrayList<>());
        tourDetail1.setTourDetailId(123L);
        tourDetail1.setTourId(new Tour());
        tourDetail1.setTourInclude("Tour Include");
        tourDetail1.setTourIntroduce("Tour Introduce");
        tourDetail1.setTourNonInclude("Tour Non Include");
        Tour tour3 = new Tour();
        tour3.setAccountId(account9);
        tour3.setDeposit(10.0f);
        tour3.setEndPlace("End Place");
        tour3.setEndTime(LocalTime.of(1, 1));
        tour3.setFeedbackList(new ArrayList<>());
        tour3.setMaxAdult(3);
        tour3.setMaxChildren(3);
        tour3.setMinAdult(1);
        tour3.setMinChildren(1);
        tour3.setMinToStart(1);
        tour3.setNote("Note");
        tour3.setNumberOfDay(10);
        tour3.setNumberOfNight(10);
        tour3.setPriceAdult(10.0f);
        tour3.setPriceChildren(10.0f);
        tour3.setStartDate(LocalDate.ofEpochDay(1L));
        tour3.setStartPlace("Start Place");
        tour3.setStartTime(LocalTime.of(1, 1));
        tour3.setStatus(1);
        tour3.setTotalPrice(10.0f);
        tour3.setTourCategoryId(tourCategory1);
        tour3.setTourCode("Tour Code");
        tour3.setTourDetail(tourDetail1);
        tour3.setTourId(123L);
        tour3.setTourMode(true);
        tour3.setTourName("Tour Name");
        tour3.setTourScheduleList(new ArrayList<>());
        tour3.setTourType(1);
        tour3.setUserBookingList(new ArrayList<>());
        UserBooking userBooking1 = new UserBooking();
        userBooking1.setAccountId(account7);
        userBooking1.setAdultPrice(10.0f);
        userBooking1.setBookingDate(LocalDate.ofEpochDay(1L));
        userBooking1.setChildrenPrice(10.0f);
        userBooking1.setDateOfIssue(LocalDate.ofEpochDay(1L));
        userBooking1.setEmail("jane.doe@example.org");
        userBooking1.setFeedbackId(feedback);
        userBooking1.setFullName("Dr Jane Doe");
        userBooking1.setIdCard("Id Card");
        userBooking1.setIsFeedback(true);
        userBooking1.setNumberOfAdult(10);
        userBooking1.setNumberOfChildren(10);
        userBooking1.setOrderId(123L);
        userBooking1.setOrderTitle("Dr");
        userBooking1.setPayType("Pay Type");
        userBooking1.setPhone("4105551212");
        userBooking1.setPlaceOfIssue("Place Of Issue");
        userBooking1.setRequest("Request");
        userBooking1.setRequestCancelList(new ArrayList<>());
        userBooking1.setStartDate(LocalDate.ofEpochDay(1L));
        userBooking1.setStatus(1);
        userBooking1.setStatusDeposit(true);
        userBooking1.setTotalPrice(10.0f);
        userBooking1.setTourId(tour3);
        userBooking1.setUserBookingId(123L);
        Feedback feedback1 = new Feedback();
        feedback1.setAccountId(account5);
        feedback1.setContent("Not all who wander are lost");
        feedback1.setCreateDate(LocalDate.ofEpochDay(1L));
        feedback1.setFeedbackId(123L);
        feedback1.setIsBlock(true);
        feedback1.setReportFeedbackList(new ArrayList<>());
        feedback1.setTourId(tour1);
        feedback1.setUserBookingId(userBooking1);
        actualReportFeedback.setFeedbackId(feedback1);
        ReasonReportFeedback reasonReportFeedback = new ReasonReportFeedback();
        reasonReportFeedback.setReasonReportFeedbackId(123L);
        reasonReportFeedback.setReasonReportName("Just cause");
        reasonReportFeedback.setReportFeedbackList(new ArrayList<>());
        actualReportFeedback.setReasonReportFeedbackId(reasonReportFeedback);
        actualReportFeedback.setReportFeedbackId(123L);
        assertSame(account2, actualReportFeedback.getAccountId());
        assertSame(feedback1, actualReportFeedback.getFeedbackId());
        assertSame(reasonReportFeedback, actualReportFeedback.getReasonReportFeedbackId());
        assertEquals(123L, actualReportFeedback.getReportFeedbackId().longValue());
    }

    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link ReportFeedback#ReportFeedback(Long, Account, Feedback, ReasonReportFeedback)}
     *   <li>{@link ReportFeedback#setAccountId(Account)}
     *   <li>{@link ReportFeedback#setFeedbackId(Feedback)}
     *   <li>{@link ReportFeedback#setReasonReportFeedbackId(ReasonReportFeedback)}
     *   <li>{@link ReportFeedback#setReportFeedbackId(Long)}
     *   <li>{@link ReportFeedback#getAccountId()}
     *   <li>{@link ReportFeedback#getFeedbackId()}
     *   <li>{@link ReportFeedback#getReasonReportFeedbackId()}
     *   <li>{@link ReportFeedback#getReportFeedbackId()}
     * </ul>
     */
    @Test
    void testConstructor2() {
        Partner partner = new Partner();
        partner.setAccountId(new Account());
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(new CompanyPartner());
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(new ServiceCategory());
        partner.setServiceList(new ArrayList<>());

        Role role = new Role();
        role.setAccountList(new ArrayList<>());
        role.setRoleId(123);
        role.setRoleName("Role Name");

        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);

        Account account = new Account();
        account.setAccountId(1234567890L);
        account.setCommentList(new ArrayList<>());
        account.setEmail("jane.doe@example.org");
        account.setFeedbackList(new ArrayList<>());
        account.setIsBlock(true);
        account.setPartner(partner);
        account.setPassWord("Pass Word");
        account.setRoleId(role);
        account.setTourList(new ArrayList<>());
        account.setUser(user);
        account.setUserBookingList(new ArrayList<>());

        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        partner1.setServiceList(new ArrayList<>());

        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(partner1);
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");

        ServiceCategory serviceCategory = new ServiceCategory();
        serviceCategory.setPartnerList(new ArrayList<>());
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        serviceCategory.setServiceList(new ArrayList<>());

        Partner partner2 = new Partner();
        partner2.setAccountId(account);
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(companyPartner);
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(serviceCategory);
        partner2.setServiceList(new ArrayList<>());

        Role role1 = new Role();
        role1.setAccountList(new ArrayList<>());
        role1.setRoleId(123);
        role1.setRoleName("Role Name");

        Partner partner3 = new Partner();
        partner3.setAccountId(new Account());
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(new CompanyPartner());
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(new ServiceCategory());
        partner3.setServiceList(new ArrayList<>());

        Role role2 = new Role();
        role2.setAccountList(new ArrayList<>());
        role2.setRoleId(123);
        role2.setRoleName("Role Name");

        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);

        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        account1.setCommentList(new ArrayList<>());
        account1.setEmail("jane.doe@example.org");
        account1.setFeedbackList(new ArrayList<>());
        account1.setIsBlock(true);
        account1.setPartner(partner3);
        account1.setPassWord("Pass Word");
        account1.setRoleId(role2);
        account1.setTourList(new ArrayList<>());
        account1.setUser(user1);
        account1.setUserBookingList(new ArrayList<>());

        User user2 = new User();
        user2.setAccountId(account1);
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);

        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        account2.setCommentList(new ArrayList<>());
        account2.setEmail("jane.doe@example.org");
        account2.setFeedbackList(new ArrayList<>());
        account2.setIsBlock(true);
        account2.setPartner(partner2);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role1);
        account2.setTourList(new ArrayList<>());
        account2.setUser(user2);
        account2.setUserBookingList(new ArrayList<>());

        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        account3.setCommentList(new ArrayList<>());
        account3.setEmail("jane.doe@example.org");
        account3.setFeedbackList(new ArrayList<>());
        account3.setIsBlock(true);
        account3.setPartner(new Partner());
        account3.setPassWord("Pass Word");
        account3.setRoleId(new Role());
        account3.setTourList(new ArrayList<>());
        account3.setUser(new User());
        account3.setUserBookingList(new ArrayList<>());

        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(new Partner());
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");

        ServiceCategory serviceCategory1 = new ServiceCategory();
        serviceCategory1.setPartnerList(new ArrayList<>());
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        serviceCategory1.setServiceList(new ArrayList<>());

        Partner partner4 = new Partner();
        partner4.setAccountId(account3);
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(companyPartner1);
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(serviceCategory1);
        partner4.setServiceList(new ArrayList<>());

        Role role3 = new Role();
        role3.setAccountList(new ArrayList<>());
        role3.setRoleId(123);
        role3.setRoleName("Role Name");

        Account account4 = new Account();
        account4.setAccountId(1234567890L);
        account4.setCommentList(new ArrayList<>());
        account4.setEmail("jane.doe@example.org");
        account4.setFeedbackList(new ArrayList<>());
        account4.setIsBlock(true);
        account4.setPartner(new Partner());
        account4.setPassWord("Pass Word");
        account4.setRoleId(new Role());
        account4.setTourList(new ArrayList<>());
        account4.setUser(new User());
        account4.setUserBookingList(new ArrayList<>());

        User user3 = new User();
        user3.setAccountId(account4);
        user3.setAddress("42 Main St");
        user3.setBirthDate("2020-03-01");
        user3.setCity("Oxford");
        user3.setFirstName("Jane");
        user3.setGender("Gender");
        user3.setIsPrivate(true);
        user3.setLastName("Doe");
        user3.setPhone("4105551212");
        user3.setRankPoint(1);
        user3.setUserId(123L);

        Account account5 = new Account();
        account5.setAccountId(1234567890L);
        account5.setCommentList(new ArrayList<>());
        account5.setEmail("jane.doe@example.org");
        account5.setFeedbackList(new ArrayList<>());
        account5.setIsBlock(true);
        account5.setPartner(partner4);
        account5.setPassWord("Pass Word");
        account5.setRoleId(role3);
        account5.setTourList(new ArrayList<>());
        account5.setUser(user3);
        account5.setUserBookingList(new ArrayList<>());

        Partner partner5 = new Partner();
        partner5.setAccountId(new Account());
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(new CompanyPartner());
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(new ServiceCategory());
        partner5.setServiceList(new ArrayList<>());

        Role role4 = new Role();
        role4.setAccountList(new ArrayList<>());
        role4.setRoleId(123);
        role4.setRoleName("Role Name");

        User user4 = new User();
        user4.setAccountId(new Account());
        user4.setAddress("42 Main St");
        user4.setBirthDate("2020-03-01");
        user4.setCity("Oxford");
        user4.setFirstName("Jane");
        user4.setGender("Gender");
        user4.setIsPrivate(true);
        user4.setLastName("Doe");
        user4.setPhone("4105551212");
        user4.setRankPoint(1);
        user4.setUserId(123L);

        Account account6 = new Account();
        account6.setAccountId(1234567890L);
        account6.setCommentList(new ArrayList<>());
        account6.setEmail("jane.doe@example.org");
        account6.setFeedbackList(new ArrayList<>());
        account6.setIsBlock(true);
        account6.setPartner(partner5);
        account6.setPassWord("Pass Word");
        account6.setRoleId(role4);
        account6.setTourList(new ArrayList<>());
        account6.setUser(user4);
        account6.setUserBookingList(new ArrayList<>());

        TourCategory tourCategory = new TourCategory();
        tourCategory.setTourCategoryId(123L);
        tourCategory.setTourCategoryName("Tour Category Name");
        tourCategory.setTourList(new ArrayList<>());

        Tour tour = new Tour();
        tour.setAccountId(new Account());
        tour.setDeposit(10.0f);
        tour.setEndPlace("End Place");
        tour.setEndTime(null);
        tour.setFeedbackList(new ArrayList<>());
        tour.setMaxAdult(3);
        tour.setMaxChildren(3);
        tour.setMinAdult(1);
        tour.setMinChildren(1);
        tour.setMinToStart(1);
        tour.setNote("Note");
        tour.setNumberOfDay(10);
        tour.setNumberOfNight(10);
        tour.setPriceAdult(10.0f);
        tour.setPriceChildren(10.0f);
        tour.setStartDate(null);
        tour.setStartPlace("Start Place");
        tour.setStartTime(null);
        tour.setStatus(1);
        tour.setTotalPrice(10.0f);
        tour.setTourCategoryId(new TourCategory());
        tour.setTourCode("Tour Code");
        tour.setTourDetail(new TourDetail());
        tour.setTourId(123L);
        tour.setTourMode(true);
        tour.setTourName("Tour Name");
        tour.setTourScheduleList(new ArrayList<>());
        tour.setTourType(1);
        tour.setUserBookingList(new ArrayList<>());

        TourDetail tourDetail = new TourDetail();
        tourDetail.setAddressStart("42 Main St");
        tourDetail.setDescription("The characteristics of someone or something");
        tourDetail.setGeneralTerms("General Terms");
        tourDetail.setLatitude(10.0f);
        tourDetail.setLongitude(10.0f);
        tourDetail.setMoreDescription("More Description");
        tourDetail.setTagOfTourList(new ArrayList<>());
        tourDetail.setTourDetailId(123L);
        tourDetail.setTourId(tour);
        tourDetail.setTourInclude("Tour Include");
        tourDetail.setTourIntroduce("Tour Introduce");
        tourDetail.setTourNonInclude("Tour Non Include");

        Tour tour1 = new Tour();
        tour1.setAccountId(account6);
        tour1.setDeposit(10.0f);
        tour1.setEndPlace("End Place");
        tour1.setEndTime(LocalTime.of(1, 1));
        tour1.setFeedbackList(new ArrayList<>());
        tour1.setMaxAdult(3);
        tour1.setMaxChildren(3);
        tour1.setMinAdult(1);
        tour1.setMinChildren(1);
        tour1.setMinToStart(1);
        tour1.setNote("Note");
        tour1.setNumberOfDay(10);
        tour1.setNumberOfNight(10);
        tour1.setPriceAdult(10.0f);
        tour1.setPriceChildren(10.0f);
        tour1.setStartDate(LocalDate.ofEpochDay(1L));
        tour1.setStartPlace("Start Place");
        tour1.setStartTime(LocalTime.of(1, 1));
        tour1.setStatus(1);
        tour1.setTotalPrice(10.0f);
        tour1.setTourCategoryId(tourCategory);
        tour1.setTourCode("Tour Code");
        tour1.setTourDetail(tourDetail);
        tour1.setTourId(123L);
        tour1.setTourMode(true);
        tour1.setTourName("Tour Name");
        tour1.setTourScheduleList(new ArrayList<>());
        tour1.setTourType(1);
        tour1.setUserBookingList(new ArrayList<>());

        Partner partner6 = new Partner();
        partner6.setAccountId(new Account());
        partner6.setAddress("42 Main St");
        partner6.setBirthDate("2020-03-01");
        partner6.setCity("Oxford");
        partner6.setCompanyPartnerId(new CompanyPartner());
        partner6.setDateIssue("2020-03-01");
        partner6.setDepartment("Department");
        partner6.setEmail("jane.doe@example.org");
        partner6.setFirstName("Jane");
        partner6.setGender("Gender");
        partner6.setLastName("Doe");
        partner6.setNumberIdCard("42");
        partner6.setPartnerId(123L);
        partner6.setPhone("4105551212");
        partner6.setPlaceIssue("Place Issue");
        partner6.setPosition("Position");
        partner6.setServiceCategoryId(new ServiceCategory());
        partner6.setServiceList(new ArrayList<>());

        Role role5 = new Role();
        role5.setAccountList(new ArrayList<>());
        role5.setRoleId(123);
        role5.setRoleName("Role Name");

        User user5 = new User();
        user5.setAccountId(new Account());
        user5.setAddress("42 Main St");
        user5.setBirthDate("2020-03-01");
        user5.setCity("Oxford");
        user5.setFirstName("Jane");
        user5.setGender("Gender");
        user5.setIsPrivate(true);
        user5.setLastName("Doe");
        user5.setPhone("4105551212");
        user5.setRankPoint(1);
        user5.setUserId(123L);

        Account account7 = new Account();
        account7.setAccountId(1234567890L);
        account7.setCommentList(new ArrayList<>());
        account7.setEmail("jane.doe@example.org");
        account7.setFeedbackList(new ArrayList<>());
        account7.setIsBlock(true);
        account7.setPartner(partner6);
        account7.setPassWord("Pass Word");
        account7.setRoleId(role5);
        account7.setTourList(new ArrayList<>());
        account7.setUser(user5);
        account7.setUserBookingList(new ArrayList<>());

        Account account8 = new Account();
        account8.setAccountId(1234567890L);
        account8.setCommentList(new ArrayList<>());
        account8.setEmail("jane.doe@example.org");
        account8.setFeedbackList(new ArrayList<>());
        account8.setIsBlock(true);
        account8.setPartner(new Partner());
        account8.setPassWord("Pass Word");
        account8.setRoleId(new Role());
        account8.setTourList(new ArrayList<>());
        account8.setUser(new User());
        account8.setUserBookingList(new ArrayList<>());

        Tour tour2 = new Tour();
        tour2.setAccountId(new Account());
        tour2.setDeposit(10.0f);
        tour2.setEndPlace("End Place");
        tour2.setEndTime(null);
        tour2.setFeedbackList(new ArrayList<>());
        tour2.setMaxAdult(3);
        tour2.setMaxChildren(3);
        tour2.setMinAdult(1);
        tour2.setMinChildren(1);
        tour2.setMinToStart(1);
        tour2.setNote("Note");
        tour2.setNumberOfDay(10);
        tour2.setNumberOfNight(10);
        tour2.setPriceAdult(10.0f);
        tour2.setPriceChildren(10.0f);
        tour2.setStartDate(null);
        tour2.setStartPlace("Start Place");
        tour2.setStartTime(null);
        tour2.setStatus(1);
        tour2.setTotalPrice(10.0f);
        tour2.setTourCategoryId(new TourCategory());
        tour2.setTourCode("Tour Code");
        tour2.setTourDetail(new TourDetail());
        tour2.setTourId(123L);
        tour2.setTourMode(true);
        tour2.setTourName("Tour Name");
        tour2.setTourScheduleList(new ArrayList<>());
        tour2.setTourType(1);
        tour2.setUserBookingList(new ArrayList<>());

        UserBooking userBooking = new UserBooking();
        userBooking.setAccountId(new Account());
        userBooking.setAdultPrice(10.0f);
        userBooking.setBookingDate(null);
        userBooking.setChildrenPrice(10.0f);
        userBooking.setDateOfIssue(null);
        userBooking.setEmail("jane.doe@example.org");
        userBooking.setFeedbackId(new Feedback());
        userBooking.setFullName("Dr Jane Doe");
        userBooking.setIdCard("Id Card");
        userBooking.setIsFeedback(true);
        userBooking.setNumberOfAdult(10);
        userBooking.setNumberOfChildren(10);
        userBooking.setOrderId(123L);
        userBooking.setOrderTitle("Dr");
        userBooking.setPayType("Pay Type");
        userBooking.setPhone("4105551212");
        userBooking.setPlaceOfIssue("Place Of Issue");
        userBooking.setRequest("Request");
        userBooking.setRequestCancelList(new ArrayList<>());
        userBooking.setStartDate(null);
        userBooking.setStatus(1);
        userBooking.setStatusDeposit(true);
        userBooking.setTotalPrice(10.0f);
        userBooking.setTourId(new Tour());
        userBooking.setUserBookingId(123L);

        Feedback feedback = new Feedback();
        feedback.setAccountId(account8);
        feedback.setContent("Not all who wander are lost");
        feedback.setCreateDate(LocalDate.ofEpochDay(1L));
        feedback.setFeedbackId(123L);
        feedback.setIsBlock(true);
        feedback.setReportFeedbackList(new ArrayList<>());
        feedback.setTourId(tour2);
        feedback.setUserBookingId(userBooking);

        Account account9 = new Account();
        account9.setAccountId(1234567890L);
        account9.setCommentList(new ArrayList<>());
        account9.setEmail("jane.doe@example.org");
        account9.setFeedbackList(new ArrayList<>());
        account9.setIsBlock(true);
        account9.setPartner(new Partner());
        account9.setPassWord("Pass Word");
        account9.setRoleId(new Role());
        account9.setTourList(new ArrayList<>());
        account9.setUser(new User());
        account9.setUserBookingList(new ArrayList<>());

        TourCategory tourCategory1 = new TourCategory();
        tourCategory1.setTourCategoryId(123L);
        tourCategory1.setTourCategoryName("Tour Category Name");
        tourCategory1.setTourList(new ArrayList<>());

        TourDetail tourDetail1 = new TourDetail();
        tourDetail1.setAddressStart("42 Main St");
        tourDetail1.setDescription("The characteristics of someone or something");
        tourDetail1.setGeneralTerms("General Terms");
        tourDetail1.setLatitude(10.0f);
        tourDetail1.setLongitude(10.0f);
        tourDetail1.setMoreDescription("More Description");
        tourDetail1.setTagOfTourList(new ArrayList<>());
        tourDetail1.setTourDetailId(123L);
        tourDetail1.setTourId(new Tour());
        tourDetail1.setTourInclude("Tour Include");
        tourDetail1.setTourIntroduce("Tour Introduce");
        tourDetail1.setTourNonInclude("Tour Non Include");

        Tour tour3 = new Tour();
        tour3.setAccountId(account9);
        tour3.setDeposit(10.0f);
        tour3.setEndPlace("End Place");
        tour3.setEndTime(LocalTime.of(1, 1));
        tour3.setFeedbackList(new ArrayList<>());
        tour3.setMaxAdult(3);
        tour3.setMaxChildren(3);
        tour3.setMinAdult(1);
        tour3.setMinChildren(1);
        tour3.setMinToStart(1);
        tour3.setNote("Note");
        tour3.setNumberOfDay(10);
        tour3.setNumberOfNight(10);
        tour3.setPriceAdult(10.0f);
        tour3.setPriceChildren(10.0f);
        tour3.setStartDate(LocalDate.ofEpochDay(1L));
        tour3.setStartPlace("Start Place");
        tour3.setStartTime(LocalTime.of(1, 1));
        tour3.setStatus(1);
        tour3.setTotalPrice(10.0f);
        tour3.setTourCategoryId(tourCategory1);
        tour3.setTourCode("Tour Code");
        tour3.setTourDetail(tourDetail1);
        tour3.setTourId(123L);
        tour3.setTourMode(true);
        tour3.setTourName("Tour Name");
        tour3.setTourScheduleList(new ArrayList<>());
        tour3.setTourType(1);
        tour3.setUserBookingList(new ArrayList<>());

        UserBooking userBooking1 = new UserBooking();
        userBooking1.setAccountId(account7);
        userBooking1.setAdultPrice(10.0f);
        userBooking1.setBookingDate(LocalDate.ofEpochDay(1L));
        userBooking1.setChildrenPrice(10.0f);
        userBooking1.setDateOfIssue(LocalDate.ofEpochDay(1L));
        userBooking1.setEmail("jane.doe@example.org");
        userBooking1.setFeedbackId(feedback);
        userBooking1.setFullName("Dr Jane Doe");
        userBooking1.setIdCard("Id Card");
        userBooking1.setIsFeedback(true);
        userBooking1.setNumberOfAdult(10);
        userBooking1.setNumberOfChildren(10);
        userBooking1.setOrderId(123L);
        userBooking1.setOrderTitle("Dr");
        userBooking1.setPayType("Pay Type");
        userBooking1.setPhone("4105551212");
        userBooking1.setPlaceOfIssue("Place Of Issue");
        userBooking1.setRequest("Request");
        userBooking1.setRequestCancelList(new ArrayList<>());
        userBooking1.setStartDate(LocalDate.ofEpochDay(1L));
        userBooking1.setStatus(1);
        userBooking1.setStatusDeposit(true);
        userBooking1.setTotalPrice(10.0f);
        userBooking1.setTourId(tour3);
        userBooking1.setUserBookingId(123L);

        Feedback feedback1 = new Feedback();
        feedback1.setAccountId(account5);
        feedback1.setContent("Not all who wander are lost");
        feedback1.setCreateDate(LocalDate.ofEpochDay(1L));
        feedback1.setFeedbackId(123L);
        feedback1.setIsBlock(true);
        feedback1.setReportFeedbackList(new ArrayList<>());
        feedback1.setTourId(tour1);
        feedback1.setUserBookingId(userBooking1);

        ReasonReportFeedback reasonReportFeedback = new ReasonReportFeedback();
        reasonReportFeedback.setReasonReportFeedbackId(123L);
        reasonReportFeedback.setReasonReportName("Just cause");
        reasonReportFeedback.setReportFeedbackList(new ArrayList<>());
        ReportFeedback actualReportFeedback = new ReportFeedback(123L, account2, feedback1, reasonReportFeedback);
        Partner partner7 = new Partner();
        partner7.setAccountId(new Account());
        partner7.setAddress("42 Main St");
        partner7.setBirthDate("2020-03-01");
        partner7.setCity("Oxford");
        partner7.setCompanyPartnerId(new CompanyPartner());
        partner7.setDateIssue("2020-03-01");
        partner7.setDepartment("Department");
        partner7.setEmail("jane.doe@example.org");
        partner7.setFirstName("Jane");
        partner7.setGender("Gender");
        partner7.setLastName("Doe");
        partner7.setNumberIdCard("42");
        partner7.setPartnerId(123L);
        partner7.setPhone("4105551212");
        partner7.setPlaceIssue("Place Issue");
        partner7.setPosition("Position");
        partner7.setServiceCategoryId(new ServiceCategory());
        partner7.setServiceList(new ArrayList<>());
        Role role6 = new Role();
        role6.setAccountList(new ArrayList<>());
        role6.setRoleId(123);
        role6.setRoleName("Role Name");
        User user6 = new User();
        user6.setAccountId(new Account());
        user6.setAddress("42 Main St");
        user6.setBirthDate("2020-03-01");
        user6.setCity("Oxford");
        user6.setFirstName("Jane");
        user6.setGender("Gender");
        user6.setIsPrivate(true);
        user6.setLastName("Doe");
        user6.setPhone("4105551212");
        user6.setRankPoint(1);
        user6.setUserId(123L);
        Account account10 = new Account();
        account10.setAccountId(1234567890L);
        account10.setCommentList(new ArrayList<>());
        account10.setEmail("jane.doe@example.org");
        account10.setFeedbackList(new ArrayList<>());
        account10.setIsBlock(true);
        account10.setPartner(partner7);
        account10.setPassWord("Pass Word");
        account10.setRoleId(role6);
        account10.setTourList(new ArrayList<>());
        account10.setUser(user6);
        account10.setUserBookingList(new ArrayList<>());
        Partner partner8 = new Partner();
        partner8.setAccountId(new Account());
        partner8.setAddress("42 Main St");
        partner8.setBirthDate("2020-03-01");
        partner8.setCity("Oxford");
        partner8.setCompanyPartnerId(new CompanyPartner());
        partner8.setDateIssue("2020-03-01");
        partner8.setDepartment("Department");
        partner8.setEmail("jane.doe@example.org");
        partner8.setFirstName("Jane");
        partner8.setGender("Gender");
        partner8.setLastName("Doe");
        partner8.setNumberIdCard("42");
        partner8.setPartnerId(123L);
        partner8.setPhone("4105551212");
        partner8.setPlaceIssue("Place Issue");
        partner8.setPosition("Position");
        partner8.setServiceCategoryId(new ServiceCategory());
        partner8.setServiceList(new ArrayList<>());
        CompanyPartner companyPartner2 = new CompanyPartner();
        companyPartner2.setAddress("42 Main St");
        companyPartner2.setBusinessCode("Business Code");
        companyPartner2.setCity("Oxford");
        companyPartner2.setCompanyName("Company Name");
        companyPartner2.setCompanyPartnerId(123L);
        companyPartner2.setEmail("jane.doe@example.org");
        companyPartner2.setFax("Fax");
        companyPartner2.setIncorporationDate("2020-03-01");
        companyPartner2.setPartnerId(partner8);
        companyPartner2.setPhone("4105551212");
        companyPartner2.setRegistrationDate("2020-03-01");
        companyPartner2.setShortName("Short Name");
        companyPartner2.setTaxCode("Tax Code");
        companyPartner2.setWebsite("Website");
        ServiceCategory serviceCategory2 = new ServiceCategory();
        serviceCategory2.setPartnerList(new ArrayList<>());
        serviceCategory2.setServiceCategoryId(123L);
        serviceCategory2.setServiceCategoryName("Service Category Name");
        serviceCategory2.setServiceList(new ArrayList<>());
        Partner partner9 = new Partner();
        partner9.setAccountId(account10);
        partner9.setAddress("42 Main St");
        partner9.setBirthDate("2020-03-01");
        partner9.setCity("Oxford");
        partner9.setCompanyPartnerId(companyPartner2);
        partner9.setDateIssue("2020-03-01");
        partner9.setDepartment("Department");
        partner9.setEmail("jane.doe@example.org");
        partner9.setFirstName("Jane");
        partner9.setGender("Gender");
        partner9.setLastName("Doe");
        partner9.setNumberIdCard("42");
        partner9.setPartnerId(123L);
        partner9.setPhone("4105551212");
        partner9.setPlaceIssue("Place Issue");
        partner9.setPosition("Position");
        partner9.setServiceCategoryId(serviceCategory2);
        partner9.setServiceList(new ArrayList<>());
        Role role7 = new Role();
        role7.setAccountList(new ArrayList<>());
        role7.setRoleId(123);
        role7.setRoleName("Role Name");
        Partner partner10 = new Partner();
        partner10.setAccountId(new Account());
        partner10.setAddress("42 Main St");
        partner10.setBirthDate("2020-03-01");
        partner10.setCity("Oxford");
        partner10.setCompanyPartnerId(new CompanyPartner());
        partner10.setDateIssue("2020-03-01");
        partner10.setDepartment("Department");
        partner10.setEmail("jane.doe@example.org");
        partner10.setFirstName("Jane");
        partner10.setGender("Gender");
        partner10.setLastName("Doe");
        partner10.setNumberIdCard("42");
        partner10.setPartnerId(123L);
        partner10.setPhone("4105551212");
        partner10.setPlaceIssue("Place Issue");
        partner10.setPosition("Position");
        partner10.setServiceCategoryId(new ServiceCategory());
        partner10.setServiceList(new ArrayList<>());
        Role role8 = new Role();
        role8.setAccountList(new ArrayList<>());
        role8.setRoleId(123);
        role8.setRoleName("Role Name");
        User user7 = new User();
        user7.setAccountId(new Account());
        user7.setAddress("42 Main St");
        user7.setBirthDate("2020-03-01");
        user7.setCity("Oxford");
        user7.setFirstName("Jane");
        user7.setGender("Gender");
        user7.setIsPrivate(true);
        user7.setLastName("Doe");
        user7.setPhone("4105551212");
        user7.setRankPoint(1);
        user7.setUserId(123L);
        Account account11 = new Account();
        account11.setAccountId(1234567890L);
        account11.setCommentList(new ArrayList<>());
        account11.setEmail("jane.doe@example.org");
        account11.setFeedbackList(new ArrayList<>());
        account11.setIsBlock(true);
        account11.setPartner(partner10);
        account11.setPassWord("Pass Word");
        account11.setRoleId(role8);
        account11.setTourList(new ArrayList<>());
        account11.setUser(user7);
        account11.setUserBookingList(new ArrayList<>());
        User user8 = new User();
        user8.setAccountId(account11);
        user8.setAddress("42 Main St");
        user8.setBirthDate("2020-03-01");
        user8.setCity("Oxford");
        user8.setFirstName("Jane");
        user8.setGender("Gender");
        user8.setIsPrivate(true);
        user8.setLastName("Doe");
        user8.setPhone("4105551212");
        user8.setRankPoint(1);
        user8.setUserId(123L);
        Account account12 = new Account();
        account12.setAccountId(1234567890L);
        account12.setCommentList(new ArrayList<>());
        account12.setEmail("jane.doe@example.org");
        account12.setFeedbackList(new ArrayList<>());
        account12.setIsBlock(true);
        account12.setPartner(partner9);
        account12.setPassWord("Pass Word");
        account12.setRoleId(role7);
        account12.setTourList(new ArrayList<>());
        account12.setUser(user8);
        account12.setUserBookingList(new ArrayList<>());
        actualReportFeedback.setAccountId(account12);
        Account account13 = new Account();
        account13.setAccountId(1234567890L);
        account13.setCommentList(new ArrayList<>());
        account13.setEmail("jane.doe@example.org");
        account13.setFeedbackList(new ArrayList<>());
        account13.setIsBlock(true);
        account13.setPartner(new Partner());
        account13.setPassWord("Pass Word");
        account13.setRoleId(new Role());
        account13.setTourList(new ArrayList<>());
        account13.setUser(new User());
        account13.setUserBookingList(new ArrayList<>());
        CompanyPartner companyPartner3 = new CompanyPartner();
        companyPartner3.setAddress("42 Main St");
        companyPartner3.setBusinessCode("Business Code");
        companyPartner3.setCity("Oxford");
        companyPartner3.setCompanyName("Company Name");
        companyPartner3.setCompanyPartnerId(123L);
        companyPartner3.setEmail("jane.doe@example.org");
        companyPartner3.setFax("Fax");
        companyPartner3.setIncorporationDate("2020-03-01");
        companyPartner3.setPartnerId(new Partner());
        companyPartner3.setPhone("4105551212");
        companyPartner3.setRegistrationDate("2020-03-01");
        companyPartner3.setShortName("Short Name");
        companyPartner3.setTaxCode("Tax Code");
        companyPartner3.setWebsite("Website");
        ServiceCategory serviceCategory3 = new ServiceCategory();
        serviceCategory3.setPartnerList(new ArrayList<>());
        serviceCategory3.setServiceCategoryId(123L);
        serviceCategory3.setServiceCategoryName("Service Category Name");
        serviceCategory3.setServiceList(new ArrayList<>());
        Partner partner11 = new Partner();
        partner11.setAccountId(account13);
        partner11.setAddress("42 Main St");
        partner11.setBirthDate("2020-03-01");
        partner11.setCity("Oxford");
        partner11.setCompanyPartnerId(companyPartner3);
        partner11.setDateIssue("2020-03-01");
        partner11.setDepartment("Department");
        partner11.setEmail("jane.doe@example.org");
        partner11.setFirstName("Jane");
        partner11.setGender("Gender");
        partner11.setLastName("Doe");
        partner11.setNumberIdCard("42");
        partner11.setPartnerId(123L);
        partner11.setPhone("4105551212");
        partner11.setPlaceIssue("Place Issue");
        partner11.setPosition("Position");
        partner11.setServiceCategoryId(serviceCategory3);
        partner11.setServiceList(new ArrayList<>());
        Role role9 = new Role();
        role9.setAccountList(new ArrayList<>());
        role9.setRoleId(123);
        role9.setRoleName("Role Name");
        Account account14 = new Account();
        account14.setAccountId(1234567890L);
        account14.setCommentList(new ArrayList<>());
        account14.setEmail("jane.doe@example.org");
        account14.setFeedbackList(new ArrayList<>());
        account14.setIsBlock(true);
        account14.setPartner(new Partner());
        account14.setPassWord("Pass Word");
        account14.setRoleId(new Role());
        account14.setTourList(new ArrayList<>());
        account14.setUser(new User());
        account14.setUserBookingList(new ArrayList<>());
        User user9 = new User();
        user9.setAccountId(account14);
        user9.setAddress("42 Main St");
        user9.setBirthDate("2020-03-01");
        user9.setCity("Oxford");
        user9.setFirstName("Jane");
        user9.setGender("Gender");
        user9.setIsPrivate(true);
        user9.setLastName("Doe");
        user9.setPhone("4105551212");
        user9.setRankPoint(1);
        user9.setUserId(123L);
        Account account15 = new Account();
        account15.setAccountId(1234567890L);
        account15.setCommentList(new ArrayList<>());
        account15.setEmail("jane.doe@example.org");
        account15.setFeedbackList(new ArrayList<>());
        account15.setIsBlock(true);
        account15.setPartner(partner11);
        account15.setPassWord("Pass Word");
        account15.setRoleId(role9);
        account15.setTourList(new ArrayList<>());
        account15.setUser(user9);
        account15.setUserBookingList(new ArrayList<>());
        Partner partner12 = new Partner();
        partner12.setAccountId(new Account());
        partner12.setAddress("42 Main St");
        partner12.setBirthDate("2020-03-01");
        partner12.setCity("Oxford");
        partner12.setCompanyPartnerId(new CompanyPartner());
        partner12.setDateIssue("2020-03-01");
        partner12.setDepartment("Department");
        partner12.setEmail("jane.doe@example.org");
        partner12.setFirstName("Jane");
        partner12.setGender("Gender");
        partner12.setLastName("Doe");
        partner12.setNumberIdCard("42");
        partner12.setPartnerId(123L);
        partner12.setPhone("4105551212");
        partner12.setPlaceIssue("Place Issue");
        partner12.setPosition("Position");
        partner12.setServiceCategoryId(new ServiceCategory());
        partner12.setServiceList(new ArrayList<>());
        Role role10 = new Role();
        role10.setAccountList(new ArrayList<>());
        role10.setRoleId(123);
        role10.setRoleName("Role Name");
        User user10 = new User();
        user10.setAccountId(new Account());
        user10.setAddress("42 Main St");
        user10.setBirthDate("2020-03-01");
        user10.setCity("Oxford");
        user10.setFirstName("Jane");
        user10.setGender("Gender");
        user10.setIsPrivate(true);
        user10.setLastName("Doe");
        user10.setPhone("4105551212");
        user10.setRankPoint(1);
        user10.setUserId(123L);
        Account account16 = new Account();
        account16.setAccountId(1234567890L);
        account16.setCommentList(new ArrayList<>());
        account16.setEmail("jane.doe@example.org");
        account16.setFeedbackList(new ArrayList<>());
        account16.setIsBlock(true);
        account16.setPartner(partner12);
        account16.setPassWord("Pass Word");
        account16.setRoleId(role10);
        account16.setTourList(new ArrayList<>());
        account16.setUser(user10);
        account16.setUserBookingList(new ArrayList<>());
        TourCategory tourCategory2 = new TourCategory();
        tourCategory2.setTourCategoryId(123L);
        tourCategory2.setTourCategoryName("Tour Category Name");
        tourCategory2.setTourList(new ArrayList<>());
        Tour tour4 = new Tour();
        tour4.setAccountId(new Account());
        tour4.setDeposit(10.0f);
        tour4.setEndPlace("End Place");
        tour4.setEndTime(null);
        tour4.setFeedbackList(new ArrayList<>());
        tour4.setMaxAdult(3);
        tour4.setMaxChildren(3);
        tour4.setMinAdult(1);
        tour4.setMinChildren(1);
        tour4.setMinToStart(1);
        tour4.setNote("Note");
        tour4.setNumberOfDay(10);
        tour4.setNumberOfNight(10);
        tour4.setPriceAdult(10.0f);
        tour4.setPriceChildren(10.0f);
        tour4.setStartDate(null);
        tour4.setStartPlace("Start Place");
        tour4.setStartTime(null);
        tour4.setStatus(1);
        tour4.setTotalPrice(10.0f);
        tour4.setTourCategoryId(new TourCategory());
        tour4.setTourCode("Tour Code");
        tour4.setTourDetail(new TourDetail());
        tour4.setTourId(123L);
        tour4.setTourMode(true);
        tour4.setTourName("Tour Name");
        tour4.setTourScheduleList(new ArrayList<>());
        tour4.setTourType(1);
        tour4.setUserBookingList(new ArrayList<>());
        TourDetail tourDetail2 = new TourDetail();
        tourDetail2.setAddressStart("42 Main St");
        tourDetail2.setDescription("The characteristics of someone or something");
        tourDetail2.setGeneralTerms("General Terms");
        tourDetail2.setLatitude(10.0f);
        tourDetail2.setLongitude(10.0f);
        tourDetail2.setMoreDescription("More Description");
        tourDetail2.setTagOfTourList(new ArrayList<>());
        tourDetail2.setTourDetailId(123L);
        tourDetail2.setTourId(tour4);
        tourDetail2.setTourInclude("Tour Include");
        tourDetail2.setTourIntroduce("Tour Introduce");
        tourDetail2.setTourNonInclude("Tour Non Include");
        Tour tour5 = new Tour();
        tour5.setAccountId(account16);
        tour5.setDeposit(10.0f);
        tour5.setEndPlace("End Place");
        tour5.setEndTime(LocalTime.of(1, 1));
        tour5.setFeedbackList(new ArrayList<>());
        tour5.setMaxAdult(3);
        tour5.setMaxChildren(3);
        tour5.setMinAdult(1);
        tour5.setMinChildren(1);
        tour5.setMinToStart(1);
        tour5.setNote("Note");
        tour5.setNumberOfDay(10);
        tour5.setNumberOfNight(10);
        tour5.setPriceAdult(10.0f);
        tour5.setPriceChildren(10.0f);
        tour5.setStartDate(LocalDate.ofEpochDay(1L));
        tour5.setStartPlace("Start Place");
        tour5.setStartTime(LocalTime.of(1, 1));
        tour5.setStatus(1);
        tour5.setTotalPrice(10.0f);
        tour5.setTourCategoryId(tourCategory2);
        tour5.setTourCode("Tour Code");
        tour5.setTourDetail(tourDetail2);
        tour5.setTourId(123L);
        tour5.setTourMode(true);
        tour5.setTourName("Tour Name");
        tour5.setTourScheduleList(new ArrayList<>());
        tour5.setTourType(1);
        tour5.setUserBookingList(new ArrayList<>());
        Partner partner13 = new Partner();
        partner13.setAccountId(new Account());
        partner13.setAddress("42 Main St");
        partner13.setBirthDate("2020-03-01");
        partner13.setCity("Oxford");
        partner13.setCompanyPartnerId(new CompanyPartner());
        partner13.setDateIssue("2020-03-01");
        partner13.setDepartment("Department");
        partner13.setEmail("jane.doe@example.org");
        partner13.setFirstName("Jane");
        partner13.setGender("Gender");
        partner13.setLastName("Doe");
        partner13.setNumberIdCard("42");
        partner13.setPartnerId(123L);
        partner13.setPhone("4105551212");
        partner13.setPlaceIssue("Place Issue");
        partner13.setPosition("Position");
        partner13.setServiceCategoryId(new ServiceCategory());
        partner13.setServiceList(new ArrayList<>());
        Role role11 = new Role();
        role11.setAccountList(new ArrayList<>());
        role11.setRoleId(123);
        role11.setRoleName("Role Name");
        User user11 = new User();
        user11.setAccountId(new Account());
        user11.setAddress("42 Main St");
        user11.setBirthDate("2020-03-01");
        user11.setCity("Oxford");
        user11.setFirstName("Jane");
        user11.setGender("Gender");
        user11.setIsPrivate(true);
        user11.setLastName("Doe");
        user11.setPhone("4105551212");
        user11.setRankPoint(1);
        user11.setUserId(123L);
        Account account17 = new Account();
        account17.setAccountId(1234567890L);
        account17.setCommentList(new ArrayList<>());
        account17.setEmail("jane.doe@example.org");
        account17.setFeedbackList(new ArrayList<>());
        account17.setIsBlock(true);
        account17.setPartner(partner13);
        account17.setPassWord("Pass Word");
        account17.setRoleId(role11);
        account17.setTourList(new ArrayList<>());
        account17.setUser(user11);
        account17.setUserBookingList(new ArrayList<>());
        Account account18 = new Account();
        account18.setAccountId(1234567890L);
        account18.setCommentList(new ArrayList<>());
        account18.setEmail("jane.doe@example.org");
        account18.setFeedbackList(new ArrayList<>());
        account18.setIsBlock(true);
        account18.setPartner(new Partner());
        account18.setPassWord("Pass Word");
        account18.setRoleId(new Role());
        account18.setTourList(new ArrayList<>());
        account18.setUser(new User());
        account18.setUserBookingList(new ArrayList<>());
        Tour tour6 = new Tour();
        tour6.setAccountId(new Account());
        tour6.setDeposit(10.0f);
        tour6.setEndPlace("End Place");
        tour6.setEndTime(null);
        tour6.setFeedbackList(new ArrayList<>());
        tour6.setMaxAdult(3);
        tour6.setMaxChildren(3);
        tour6.setMinAdult(1);
        tour6.setMinChildren(1);
        tour6.setMinToStart(1);
        tour6.setNote("Note");
        tour6.setNumberOfDay(10);
        tour6.setNumberOfNight(10);
        tour6.setPriceAdult(10.0f);
        tour6.setPriceChildren(10.0f);
        tour6.setStartDate(null);
        tour6.setStartPlace("Start Place");
        tour6.setStartTime(null);
        tour6.setStatus(1);
        tour6.setTotalPrice(10.0f);
        tour6.setTourCategoryId(new TourCategory());
        tour6.setTourCode("Tour Code");
        tour6.setTourDetail(new TourDetail());
        tour6.setTourId(123L);
        tour6.setTourMode(true);
        tour6.setTourName("Tour Name");
        tour6.setTourScheduleList(new ArrayList<>());
        tour6.setTourType(1);
        tour6.setUserBookingList(new ArrayList<>());
        UserBooking userBooking2 = new UserBooking();
        userBooking2.setAccountId(new Account());
        userBooking2.setAdultPrice(10.0f);
        userBooking2.setBookingDate(null);
        userBooking2.setChildrenPrice(10.0f);
        userBooking2.setDateOfIssue(null);
        userBooking2.setEmail("jane.doe@example.org");
        userBooking2.setFeedbackId(new Feedback());
        userBooking2.setFullName("Dr Jane Doe");
        userBooking2.setIdCard("Id Card");
        userBooking2.setIsFeedback(true);
        userBooking2.setNumberOfAdult(10);
        userBooking2.setNumberOfChildren(10);
        userBooking2.setOrderId(123L);
        userBooking2.setOrderTitle("Dr");
        userBooking2.setPayType("Pay Type");
        userBooking2.setPhone("4105551212");
        userBooking2.setPlaceOfIssue("Place Of Issue");
        userBooking2.setRequest("Request");
        userBooking2.setRequestCancelList(new ArrayList<>());
        userBooking2.setStartDate(null);
        userBooking2.setStatus(1);
        userBooking2.setStatusDeposit(true);
        userBooking2.setTotalPrice(10.0f);
        userBooking2.setTourId(new Tour());
        userBooking2.setUserBookingId(123L);
        Feedback feedback2 = new Feedback();
        feedback2.setAccountId(account18);
        feedback2.setContent("Not all who wander are lost");
        feedback2.setCreateDate(LocalDate.ofEpochDay(1L));
        feedback2.setFeedbackId(123L);
        feedback2.setIsBlock(true);
        feedback2.setReportFeedbackList(new ArrayList<>());
        feedback2.setTourId(tour6);
        feedback2.setUserBookingId(userBooking2);
        Account account19 = new Account();
        account19.setAccountId(1234567890L);
        account19.setCommentList(new ArrayList<>());
        account19.setEmail("jane.doe@example.org");
        account19.setFeedbackList(new ArrayList<>());
        account19.setIsBlock(true);
        account19.setPartner(new Partner());
        account19.setPassWord("Pass Word");
        account19.setRoleId(new Role());
        account19.setTourList(new ArrayList<>());
        account19.setUser(new User());
        account19.setUserBookingList(new ArrayList<>());
        TourCategory tourCategory3 = new TourCategory();
        tourCategory3.setTourCategoryId(123L);
        tourCategory3.setTourCategoryName("Tour Category Name");
        tourCategory3.setTourList(new ArrayList<>());
        TourDetail tourDetail3 = new TourDetail();
        tourDetail3.setAddressStart("42 Main St");
        tourDetail3.setDescription("The characteristics of someone or something");
        tourDetail3.setGeneralTerms("General Terms");
        tourDetail3.setLatitude(10.0f);
        tourDetail3.setLongitude(10.0f);
        tourDetail3.setMoreDescription("More Description");
        tourDetail3.setTagOfTourList(new ArrayList<>());
        tourDetail3.setTourDetailId(123L);
        tourDetail3.setTourId(new Tour());
        tourDetail3.setTourInclude("Tour Include");
        tourDetail3.setTourIntroduce("Tour Introduce");
        tourDetail3.setTourNonInclude("Tour Non Include");
        Tour tour7 = new Tour();
        tour7.setAccountId(account19);
        tour7.setDeposit(10.0f);
        tour7.setEndPlace("End Place");
        tour7.setEndTime(LocalTime.of(1, 1));
        tour7.setFeedbackList(new ArrayList<>());
        tour7.setMaxAdult(3);
        tour7.setMaxChildren(3);
        tour7.setMinAdult(1);
        tour7.setMinChildren(1);
        tour7.setMinToStart(1);
        tour7.setNote("Note");
        tour7.setNumberOfDay(10);
        tour7.setNumberOfNight(10);
        tour7.setPriceAdult(10.0f);
        tour7.setPriceChildren(10.0f);
        tour7.setStartDate(LocalDate.ofEpochDay(1L));
        tour7.setStartPlace("Start Place");
        tour7.setStartTime(LocalTime.of(1, 1));
        tour7.setStatus(1);
        tour7.setTotalPrice(10.0f);
        tour7.setTourCategoryId(tourCategory3);
        tour7.setTourCode("Tour Code");
        tour7.setTourDetail(tourDetail3);
        tour7.setTourId(123L);
        tour7.setTourMode(true);
        tour7.setTourName("Tour Name");
        tour7.setTourScheduleList(new ArrayList<>());
        tour7.setTourType(1);
        tour7.setUserBookingList(new ArrayList<>());
        UserBooking userBooking3 = new UserBooking();
        userBooking3.setAccountId(account17);
        userBooking3.setAdultPrice(10.0f);
        userBooking3.setBookingDate(LocalDate.ofEpochDay(1L));
        userBooking3.setChildrenPrice(10.0f);
        userBooking3.setDateOfIssue(LocalDate.ofEpochDay(1L));
        userBooking3.setEmail("jane.doe@example.org");
        userBooking3.setFeedbackId(feedback2);
        userBooking3.setFullName("Dr Jane Doe");
        userBooking3.setIdCard("Id Card");
        userBooking3.setIsFeedback(true);
        userBooking3.setNumberOfAdult(10);
        userBooking3.setNumberOfChildren(10);
        userBooking3.setOrderId(123L);
        userBooking3.setOrderTitle("Dr");
        userBooking3.setPayType("Pay Type");
        userBooking3.setPhone("4105551212");
        userBooking3.setPlaceOfIssue("Place Of Issue");
        userBooking3.setRequest("Request");
        userBooking3.setRequestCancelList(new ArrayList<>());
        userBooking3.setStartDate(LocalDate.ofEpochDay(1L));
        userBooking3.setStatus(1);
        userBooking3.setStatusDeposit(true);
        userBooking3.setTotalPrice(10.0f);
        userBooking3.setTourId(tour7);
        userBooking3.setUserBookingId(123L);
        Feedback feedback3 = new Feedback();
        feedback3.setAccountId(account15);
        feedback3.setContent("Not all who wander are lost");
        feedback3.setCreateDate(LocalDate.ofEpochDay(1L));
        feedback3.setFeedbackId(123L);
        feedback3.setIsBlock(true);
        feedback3.setReportFeedbackList(new ArrayList<>());
        feedback3.setTourId(tour5);
        feedback3.setUserBookingId(userBooking3);
        actualReportFeedback.setFeedbackId(feedback3);
        ReasonReportFeedback reasonReportFeedback1 = new ReasonReportFeedback();
        reasonReportFeedback1.setReasonReportFeedbackId(123L);
        reasonReportFeedback1.setReasonReportName("Just cause");
        reasonReportFeedback1.setReportFeedbackList(new ArrayList<>());
        actualReportFeedback.setReasonReportFeedbackId(reasonReportFeedback1);
        actualReportFeedback.setReportFeedbackId(123L);
        assertSame(account12, actualReportFeedback.getAccountId());
        assertSame(feedback3, actualReportFeedback.getFeedbackId());
        assertSame(reasonReportFeedback1, actualReportFeedback.getReasonReportFeedbackId());
        assertEquals(123L, actualReportFeedback.getReportFeedbackId().longValue());
    }
}

