package com.example.wetravel.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;

import org.junit.jupiter.api.Test;

class RequestCancelTest {
    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link RequestCancel#RequestCancel()}
     *   <li>{@link RequestCancel#setDescription(String)}
     *   <li>{@link RequestCancel#setReasonCancelId(ReasonCancel)}
     *   <li>{@link RequestCancel#setRequestCancelId(Long)}
     *   <li>{@link RequestCancel#setRequestDate(LocalDate)}
     *   <li>{@link RequestCancel#setStatus(Integer)}
     *   <li>{@link RequestCancel#setUserBookingId(UserBooking)}
     *   <li>{@link RequestCancel#getDescription()}
     *   <li>{@link RequestCancel#getReasonCancelId()}
     *   <li>{@link RequestCancel#getRequestCancelId()}
     *   <li>{@link RequestCancel#getRequestDate()}
     *   <li>{@link RequestCancel#getStatus()}
     *   <li>{@link RequestCancel#getUserBookingId()}
     * </ul>
     */
    @Test
    void testConstructor() {
        RequestCancel actualRequestCancel = new RequestCancel();
        actualRequestCancel.setDescription("The characteristics of someone or something");
        ReasonCancel reasonCancel = new ReasonCancel();
        reasonCancel.setReasonCancelId(123L);
        reasonCancel.setReasonCancelName("Just cause");
        reasonCancel.setRequestCancelList(new ArrayList<>());
        actualRequestCancel.setReasonCancelId(reasonCancel);
        actualRequestCancel.setRequestCancelId(123L);
        LocalDate ofEpochDayResult = LocalDate.ofEpochDay(1L);
        actualRequestCancel.setRequestDate(ofEpochDayResult);
        actualRequestCancel.setStatus(1);
        Account account = new Account();
        account.setAccountId(1234567890L);
        account.setCommentList(new ArrayList<>());
        account.setEmail("jane.doe@example.org");
        account.setFeedbackList(new ArrayList<>());
        account.setIsBlock(true);
        account.setPartner(new Partner());
        account.setPassWord("Pass Word");
        account.setRoleId(new Role());
        account.setTourList(new ArrayList<>());
        account.setUser(new User());
        account.setUserBookingList(new ArrayList<>());
        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(new Partner());
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");
        ServiceCategory serviceCategory = new ServiceCategory();
        serviceCategory.setPartnerList(new ArrayList<>());
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        serviceCategory.setServiceList(new ArrayList<>());
        Partner partner = new Partner();
        partner.setAccountId(account);
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(companyPartner);
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(serviceCategory);
        partner.setServiceList(new ArrayList<>());
        Role role = new Role();
        role.setAccountList(new ArrayList<>());
        role.setRoleId(123);
        role.setRoleName("Role Name");
        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        account1.setCommentList(new ArrayList<>());
        account1.setEmail("jane.doe@example.org");
        account1.setFeedbackList(new ArrayList<>());
        account1.setIsBlock(true);
        account1.setPartner(new Partner());
        account1.setPassWord("Pass Word");
        account1.setRoleId(new Role());
        account1.setTourList(new ArrayList<>());
        account1.setUser(new User());
        account1.setUserBookingList(new ArrayList<>());
        User user = new User();
        user.setAccountId(account1);
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);
        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        account2.setCommentList(new ArrayList<>());
        account2.setEmail("jane.doe@example.org");
        account2.setFeedbackList(new ArrayList<>());
        account2.setIsBlock(true);
        account2.setPartner(partner);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role);
        account2.setTourList(new ArrayList<>());
        account2.setUser(user);
        account2.setUserBookingList(new ArrayList<>());
        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        partner1.setServiceList(new ArrayList<>());
        Role role1 = new Role();
        role1.setAccountList(new ArrayList<>());
        role1.setRoleId(123);
        role1.setRoleName("Role Name");
        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);
        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        account3.setCommentList(new ArrayList<>());
        account3.setEmail("jane.doe@example.org");
        account3.setFeedbackList(new ArrayList<>());
        account3.setIsBlock(true);
        account3.setPartner(partner1);
        account3.setPassWord("Pass Word");
        account3.setRoleId(role1);
        account3.setTourList(new ArrayList<>());
        account3.setUser(user1);
        account3.setUserBookingList(new ArrayList<>());
        Account account4 = new Account();
        account4.setAccountId(1234567890L);
        account4.setCommentList(new ArrayList<>());
        account4.setEmail("jane.doe@example.org");
        account4.setFeedbackList(new ArrayList<>());
        account4.setIsBlock(true);
        account4.setPartner(new Partner());
        account4.setPassWord("Pass Word");
        account4.setRoleId(new Role());
        account4.setTourList(new ArrayList<>());
        account4.setUser(new User());
        account4.setUserBookingList(new ArrayList<>());
        TourCategory tourCategory = new TourCategory();
        tourCategory.setTourCategoryId(123L);
        tourCategory.setTourCategoryName("Tour Category Name");
        tourCategory.setTourList(new ArrayList<>());
        TourDetail tourDetail = new TourDetail();
        tourDetail.setAddressStart("42 Main St");
        tourDetail.setDescription("The characteristics of someone or something");
        tourDetail.setGeneralTerms("General Terms");
        tourDetail.setLatitude(10.0f);
        tourDetail.setLongitude(10.0f);
        tourDetail.setMoreDescription("More Description");
        tourDetail.setTagOfTourList(new ArrayList<>());
        tourDetail.setTourDetailId(123L);
        tourDetail.setTourId(new Tour());
        tourDetail.setTourInclude("Tour Include");
        tourDetail.setTourIntroduce("Tour Introduce");
        tourDetail.setTourNonInclude("Tour Non Include");
        Tour tour = new Tour();
        tour.setAccountId(account4);
        tour.setDeposit(10.0f);
        tour.setEndPlace("End Place");
        tour.setEndTime(LocalTime.of(1, 1));
        tour.setFeedbackList(new ArrayList<>());
        tour.setMaxAdult(3);
        tour.setMaxChildren(3);
        tour.setMinAdult(1);
        tour.setMinChildren(1);
        tour.setMinToStart(1);
        tour.setNote("Note");
        tour.setNumberOfDay(10);
        tour.setNumberOfNight(10);
        tour.setPriceAdult(10.0f);
        tour.setPriceChildren(10.0f);
        tour.setStartDate(LocalDate.ofEpochDay(1L));
        tour.setStartPlace("Start Place");
        tour.setStartTime(LocalTime.of(1, 1));
        tour.setStatus(1);
        tour.setTotalPrice(10.0f);
        tour.setTourCategoryId(tourCategory);
        tour.setTourCode("Tour Code");
        tour.setTourDetail(tourDetail);
        tour.setTourId(123L);
        tour.setTourMode(true);
        tour.setTourName("Tour Name");
        tour.setTourScheduleList(new ArrayList<>());
        tour.setTourType(1);
        tour.setUserBookingList(new ArrayList<>());
        Account account5 = new Account();
        account5.setAccountId(1234567890L);
        account5.setCommentList(new ArrayList<>());
        account5.setEmail("jane.doe@example.org");
        account5.setFeedbackList(new ArrayList<>());
        account5.setIsBlock(true);
        account5.setPartner(new Partner());
        account5.setPassWord("Pass Word");
        account5.setRoleId(new Role());
        account5.setTourList(new ArrayList<>());
        account5.setUser(new User());
        account5.setUserBookingList(new ArrayList<>());
        Feedback feedback = new Feedback();
        feedback.setAccountId(new Account());
        feedback.setContent("Not all who wander are lost");
        feedback.setCreateDate(null);
        feedback.setFeedbackId(123L);
        feedback.setIsBlock(true);
        feedback.setReportFeedbackList(new ArrayList<>());
        feedback.setTourId(new Tour());
        feedback.setUserBookingId(new UserBooking());
        Tour tour1 = new Tour();
        tour1.setAccountId(new Account());
        tour1.setDeposit(10.0f);
        tour1.setEndPlace("End Place");
        tour1.setEndTime(null);
        tour1.setFeedbackList(new ArrayList<>());
        tour1.setMaxAdult(3);
        tour1.setMaxChildren(3);
        tour1.setMinAdult(1);
        tour1.setMinChildren(1);
        tour1.setMinToStart(1);
        tour1.setNote("Note");
        tour1.setNumberOfDay(10);
        tour1.setNumberOfNight(10);
        tour1.setPriceAdult(10.0f);
        tour1.setPriceChildren(10.0f);
        tour1.setStartDate(null);
        tour1.setStartPlace("Start Place");
        tour1.setStartTime(null);
        tour1.setStatus(1);
        tour1.setTotalPrice(10.0f);
        tour1.setTourCategoryId(new TourCategory());
        tour1.setTourCode("Tour Code");
        tour1.setTourDetail(new TourDetail());
        tour1.setTourId(123L);
        tour1.setTourMode(true);
        tour1.setTourName("Tour Name");
        tour1.setTourScheduleList(new ArrayList<>());
        tour1.setTourType(1);
        tour1.setUserBookingList(new ArrayList<>());
        UserBooking userBooking = new UserBooking();
        userBooking.setAccountId(account5);
        userBooking.setAdultPrice(10.0f);
        userBooking.setBookingDate(LocalDate.ofEpochDay(1L));
        userBooking.setChildrenPrice(10.0f);
        userBooking.setDateOfIssue(LocalDate.ofEpochDay(1L));
        userBooking.setEmail("jane.doe@example.org");
        userBooking.setFeedbackId(feedback);
        userBooking.setFullName("Dr Jane Doe");
        userBooking.setIdCard("Id Card");
        userBooking.setIsFeedback(true);
        userBooking.setNumberOfAdult(10);
        userBooking.setNumberOfChildren(10);
        userBooking.setOrderId(123L);
        userBooking.setOrderTitle("Dr");
        userBooking.setPayType("Pay Type");
        userBooking.setPhone("4105551212");
        userBooking.setPlaceOfIssue("Place Of Issue");
        userBooking.setRequest("Request");
        userBooking.setRequestCancelList(new ArrayList<>());
        userBooking.setStartDate(LocalDate.ofEpochDay(1L));
        userBooking.setStatus(1);
        userBooking.setStatusDeposit(true);
        userBooking.setTotalPrice(10.0f);
        userBooking.setTourId(tour1);
        userBooking.setUserBookingId(123L);
        Feedback feedback1 = new Feedback();
        feedback1.setAccountId(account3);
        feedback1.setContent("Not all who wander are lost");
        feedback1.setCreateDate(LocalDate.ofEpochDay(1L));
        feedback1.setFeedbackId(123L);
        feedback1.setIsBlock(true);
        feedback1.setReportFeedbackList(new ArrayList<>());
        feedback1.setTourId(tour);
        feedback1.setUserBookingId(userBooking);
        Partner partner2 = new Partner();
        partner2.setAccountId(new Account());
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(new CompanyPartner());
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(new ServiceCategory());
        partner2.setServiceList(new ArrayList<>());
        Role role2 = new Role();
        role2.setAccountList(new ArrayList<>());
        role2.setRoleId(123);
        role2.setRoleName("Role Name");
        User user2 = new User();
        user2.setAccountId(new Account());
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);
        Account account6 = new Account();
        account6.setAccountId(1234567890L);
        account6.setCommentList(new ArrayList<>());
        account6.setEmail("jane.doe@example.org");
        account6.setFeedbackList(new ArrayList<>());
        account6.setIsBlock(true);
        account6.setPartner(partner2);
        account6.setPassWord("Pass Word");
        account6.setRoleId(role2);
        account6.setTourList(new ArrayList<>());
        account6.setUser(user2);
        account6.setUserBookingList(new ArrayList<>());
        TourCategory tourCategory1 = new TourCategory();
        tourCategory1.setTourCategoryId(123L);
        tourCategory1.setTourCategoryName("Tour Category Name");
        tourCategory1.setTourList(new ArrayList<>());
        Tour tour2 = new Tour();
        tour2.setAccountId(new Account());
        tour2.setDeposit(10.0f);
        tour2.setEndPlace("End Place");
        tour2.setEndTime(null);
        tour2.setFeedbackList(new ArrayList<>());
        tour2.setMaxAdult(3);
        tour2.setMaxChildren(3);
        tour2.setMinAdult(1);
        tour2.setMinChildren(1);
        tour2.setMinToStart(1);
        tour2.setNote("Note");
        tour2.setNumberOfDay(10);
        tour2.setNumberOfNight(10);
        tour2.setPriceAdult(10.0f);
        tour2.setPriceChildren(10.0f);
        tour2.setStartDate(null);
        tour2.setStartPlace("Start Place");
        tour2.setStartTime(null);
        tour2.setStatus(1);
        tour2.setTotalPrice(10.0f);
        tour2.setTourCategoryId(new TourCategory());
        tour2.setTourCode("Tour Code");
        tour2.setTourDetail(new TourDetail());
        tour2.setTourId(123L);
        tour2.setTourMode(true);
        tour2.setTourName("Tour Name");
        tour2.setTourScheduleList(new ArrayList<>());
        tour2.setTourType(1);
        tour2.setUserBookingList(new ArrayList<>());
        TourDetail tourDetail1 = new TourDetail();
        tourDetail1.setAddressStart("42 Main St");
        tourDetail1.setDescription("The characteristics of someone or something");
        tourDetail1.setGeneralTerms("General Terms");
        tourDetail1.setLatitude(10.0f);
        tourDetail1.setLongitude(10.0f);
        tourDetail1.setMoreDescription("More Description");
        tourDetail1.setTagOfTourList(new ArrayList<>());
        tourDetail1.setTourDetailId(123L);
        tourDetail1.setTourId(tour2);
        tourDetail1.setTourInclude("Tour Include");
        tourDetail1.setTourIntroduce("Tour Introduce");
        tourDetail1.setTourNonInclude("Tour Non Include");
        Tour tour3 = new Tour();
        tour3.setAccountId(account6);
        tour3.setDeposit(10.0f);
        tour3.setEndPlace("End Place");
        tour3.setEndTime(LocalTime.of(1, 1));
        tour3.setFeedbackList(new ArrayList<>());
        tour3.setMaxAdult(3);
        tour3.setMaxChildren(3);
        tour3.setMinAdult(1);
        tour3.setMinChildren(1);
        tour3.setMinToStart(1);
        tour3.setNote("Note");
        tour3.setNumberOfDay(10);
        tour3.setNumberOfNight(10);
        tour3.setPriceAdult(10.0f);
        tour3.setPriceChildren(10.0f);
        tour3.setStartDate(LocalDate.ofEpochDay(1L));
        tour3.setStartPlace("Start Place");
        tour3.setStartTime(LocalTime.of(1, 1));
        tour3.setStatus(1);
        tour3.setTotalPrice(10.0f);
        tour3.setTourCategoryId(tourCategory1);
        tour3.setTourCode("Tour Code");
        tour3.setTourDetail(tourDetail1);
        tour3.setTourId(123L);
        tour3.setTourMode(true);
        tour3.setTourName("Tour Name");
        tour3.setTourScheduleList(new ArrayList<>());
        tour3.setTourType(1);
        tour3.setUserBookingList(new ArrayList<>());
        UserBooking userBooking1 = new UserBooking();
        userBooking1.setAccountId(account2);
        userBooking1.setAdultPrice(10.0f);
        userBooking1.setBookingDate(LocalDate.ofEpochDay(1L));
        userBooking1.setChildrenPrice(10.0f);
        userBooking1.setDateOfIssue(LocalDate.ofEpochDay(1L));
        userBooking1.setEmail("jane.doe@example.org");
        userBooking1.setFeedbackId(feedback1);
        userBooking1.setFullName("Dr Jane Doe");
        userBooking1.setIdCard("Id Card");
        userBooking1.setIsFeedback(true);
        userBooking1.setNumberOfAdult(10);
        userBooking1.setNumberOfChildren(10);
        userBooking1.setOrderId(123L);
        userBooking1.setOrderTitle("Dr");
        userBooking1.setPayType("Pay Type");
        userBooking1.setPhone("4105551212");
        userBooking1.setPlaceOfIssue("Place Of Issue");
        userBooking1.setRequest("Request");
        userBooking1.setRequestCancelList(new ArrayList<>());
        userBooking1.setStartDate(LocalDate.ofEpochDay(1L));
        userBooking1.setStatus(1);
        userBooking1.setStatusDeposit(true);
        userBooking1.setTotalPrice(10.0f);
        userBooking1.setTourId(tour3);
        userBooking1.setUserBookingId(123L);
        actualRequestCancel.setUserBookingId(userBooking1);
        assertEquals("The characteristics of someone or something", actualRequestCancel.getDescription());
        assertSame(reasonCancel, actualRequestCancel.getReasonCancelId());
        assertEquals(123L, actualRequestCancel.getRequestCancelId().longValue());
        assertSame(ofEpochDayResult, actualRequestCancel.getRequestDate());
        assertEquals(1, actualRequestCancel.getStatus().intValue());
        assertSame(userBooking1, actualRequestCancel.getUserBookingId());
    }

    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link RequestCancel#RequestCancel(Long, UserBooking, ReasonCancel, LocalDate, String, Integer)}
     *   <li>{@link RequestCancel#setDescription(String)}
     *   <li>{@link RequestCancel#setReasonCancelId(ReasonCancel)}
     *   <li>{@link RequestCancel#setRequestCancelId(Long)}
     *   <li>{@link RequestCancel#setRequestDate(LocalDate)}
     *   <li>{@link RequestCancel#setStatus(Integer)}
     *   <li>{@link RequestCancel#setUserBookingId(UserBooking)}
     *   <li>{@link RequestCancel#getDescription()}
     *   <li>{@link RequestCancel#getReasonCancelId()}
     *   <li>{@link RequestCancel#getRequestCancelId()}
     *   <li>{@link RequestCancel#getRequestDate()}
     *   <li>{@link RequestCancel#getStatus()}
     *   <li>{@link RequestCancel#getUserBookingId()}
     * </ul>
     */
    @Test
    void testConstructor2() {
        Account account = new Account();
        account.setAccountId(1234567890L);
        account.setCommentList(new ArrayList<>());
        account.setEmail("jane.doe@example.org");
        account.setFeedbackList(new ArrayList<>());
        account.setIsBlock(true);
        account.setPartner(new Partner());
        account.setPassWord("Pass Word");
        account.setRoleId(new Role());
        account.setTourList(new ArrayList<>());
        account.setUser(new User());
        account.setUserBookingList(new ArrayList<>());

        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(new Partner());
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");

        ServiceCategory serviceCategory = new ServiceCategory();
        serviceCategory.setPartnerList(new ArrayList<>());
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        serviceCategory.setServiceList(new ArrayList<>());

        Partner partner = new Partner();
        partner.setAccountId(account);
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(companyPartner);
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(serviceCategory);
        partner.setServiceList(new ArrayList<>());

        Role role = new Role();
        role.setAccountList(new ArrayList<>());
        role.setRoleId(123);
        role.setRoleName("Role Name");

        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        account1.setCommentList(new ArrayList<>());
        account1.setEmail("jane.doe@example.org");
        account1.setFeedbackList(new ArrayList<>());
        account1.setIsBlock(true);
        account1.setPartner(new Partner());
        account1.setPassWord("Pass Word");
        account1.setRoleId(new Role());
        account1.setTourList(new ArrayList<>());
        account1.setUser(new User());
        account1.setUserBookingList(new ArrayList<>());

        User user = new User();
        user.setAccountId(account1);
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);

        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        account2.setCommentList(new ArrayList<>());
        account2.setEmail("jane.doe@example.org");
        account2.setFeedbackList(new ArrayList<>());
        account2.setIsBlock(true);
        account2.setPartner(partner);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role);
        account2.setTourList(new ArrayList<>());
        account2.setUser(user);
        account2.setUserBookingList(new ArrayList<>());

        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        partner1.setServiceList(new ArrayList<>());

        Role role1 = new Role();
        role1.setAccountList(new ArrayList<>());
        role1.setRoleId(123);
        role1.setRoleName("Role Name");

        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);

        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        account3.setCommentList(new ArrayList<>());
        account3.setEmail("jane.doe@example.org");
        account3.setFeedbackList(new ArrayList<>());
        account3.setIsBlock(true);
        account3.setPartner(partner1);
        account3.setPassWord("Pass Word");
        account3.setRoleId(role1);
        account3.setTourList(new ArrayList<>());
        account3.setUser(user1);
        account3.setUserBookingList(new ArrayList<>());

        Account account4 = new Account();
        account4.setAccountId(1234567890L);
        account4.setCommentList(new ArrayList<>());
        account4.setEmail("jane.doe@example.org");
        account4.setFeedbackList(new ArrayList<>());
        account4.setIsBlock(true);
        account4.setPartner(new Partner());
        account4.setPassWord("Pass Word");
        account4.setRoleId(new Role());
        account4.setTourList(new ArrayList<>());
        account4.setUser(new User());
        account4.setUserBookingList(new ArrayList<>());

        TourCategory tourCategory = new TourCategory();
        tourCategory.setTourCategoryId(123L);
        tourCategory.setTourCategoryName("Tour Category Name");
        tourCategory.setTourList(new ArrayList<>());

        TourDetail tourDetail = new TourDetail();
        tourDetail.setAddressStart("42 Main St");
        tourDetail.setDescription("The characteristics of someone or something");
        tourDetail.setGeneralTerms("General Terms");
        tourDetail.setLatitude(10.0f);
        tourDetail.setLongitude(10.0f);
        tourDetail.setMoreDescription("More Description");
        tourDetail.setTagOfTourList(new ArrayList<>());
        tourDetail.setTourDetailId(123L);
        tourDetail.setTourId(new Tour());
        tourDetail.setTourInclude("Tour Include");
        tourDetail.setTourIntroduce("Tour Introduce");
        tourDetail.setTourNonInclude("Tour Non Include");

        Tour tour = new Tour();
        tour.setAccountId(account4);
        tour.setDeposit(10.0f);
        tour.setEndPlace("End Place");
        tour.setEndTime(LocalTime.of(1, 1));
        tour.setFeedbackList(new ArrayList<>());
        tour.setMaxAdult(3);
        tour.setMaxChildren(3);
        tour.setMinAdult(1);
        tour.setMinChildren(1);
        tour.setMinToStart(1);
        tour.setNote("Note");
        tour.setNumberOfDay(10);
        tour.setNumberOfNight(10);
        tour.setPriceAdult(10.0f);
        tour.setPriceChildren(10.0f);
        tour.setStartDate(LocalDate.ofEpochDay(1L));
        tour.setStartPlace("Start Place");
        tour.setStartTime(LocalTime.of(1, 1));
        tour.setStatus(1);
        tour.setTotalPrice(10.0f);
        tour.setTourCategoryId(tourCategory);
        tour.setTourCode("Tour Code");
        tour.setTourDetail(tourDetail);
        tour.setTourId(123L);
        tour.setTourMode(true);
        tour.setTourName("Tour Name");
        tour.setTourScheduleList(new ArrayList<>());
        tour.setTourType(1);
        tour.setUserBookingList(new ArrayList<>());

        Account account5 = new Account();
        account5.setAccountId(1234567890L);
        account5.setCommentList(new ArrayList<>());
        account5.setEmail("jane.doe@example.org");
        account5.setFeedbackList(new ArrayList<>());
        account5.setIsBlock(true);
        account5.setPartner(new Partner());
        account5.setPassWord("Pass Word");
        account5.setRoleId(new Role());
        account5.setTourList(new ArrayList<>());
        account5.setUser(new User());
        account5.setUserBookingList(new ArrayList<>());

        Feedback feedback = new Feedback();
        feedback.setAccountId(new Account());
        feedback.setContent("Not all who wander are lost");
        feedback.setCreateDate(null);
        feedback.setFeedbackId(123L);
        feedback.setIsBlock(true);
        feedback.setReportFeedbackList(new ArrayList<>());
        feedback.setTourId(new Tour());
        feedback.setUserBookingId(new UserBooking());

        Tour tour1 = new Tour();
        tour1.setAccountId(new Account());
        tour1.setDeposit(10.0f);
        tour1.setEndPlace("End Place");
        tour1.setEndTime(null);
        tour1.setFeedbackList(new ArrayList<>());
        tour1.setMaxAdult(3);
        tour1.setMaxChildren(3);
        tour1.setMinAdult(1);
        tour1.setMinChildren(1);
        tour1.setMinToStart(1);
        tour1.setNote("Note");
        tour1.setNumberOfDay(10);
        tour1.setNumberOfNight(10);
        tour1.setPriceAdult(10.0f);
        tour1.setPriceChildren(10.0f);
        tour1.setStartDate(null);
        tour1.setStartPlace("Start Place");
        tour1.setStartTime(null);
        tour1.setStatus(1);
        tour1.setTotalPrice(10.0f);
        tour1.setTourCategoryId(new TourCategory());
        tour1.setTourCode("Tour Code");
        tour1.setTourDetail(new TourDetail());
        tour1.setTourId(123L);
        tour1.setTourMode(true);
        tour1.setTourName("Tour Name");
        tour1.setTourScheduleList(new ArrayList<>());
        tour1.setTourType(1);
        tour1.setUserBookingList(new ArrayList<>());

        UserBooking userBooking = new UserBooking();
        userBooking.setAccountId(account5);
        userBooking.setAdultPrice(10.0f);
        userBooking.setBookingDate(LocalDate.ofEpochDay(1L));
        userBooking.setChildrenPrice(10.0f);
        userBooking.setDateOfIssue(LocalDate.ofEpochDay(1L));
        userBooking.setEmail("jane.doe@example.org");
        userBooking.setFeedbackId(feedback);
        userBooking.setFullName("Dr Jane Doe");
        userBooking.setIdCard("Id Card");
        userBooking.setIsFeedback(true);
        userBooking.setNumberOfAdult(10);
        userBooking.setNumberOfChildren(10);
        userBooking.setOrderId(123L);
        userBooking.setOrderTitle("Dr");
        userBooking.setPayType("Pay Type");
        userBooking.setPhone("4105551212");
        userBooking.setPlaceOfIssue("Place Of Issue");
        userBooking.setRequest("Request");
        userBooking.setRequestCancelList(new ArrayList<>());
        userBooking.setStartDate(LocalDate.ofEpochDay(1L));
        userBooking.setStatus(1);
        userBooking.setStatusDeposit(true);
        userBooking.setTotalPrice(10.0f);
        userBooking.setTourId(tour1);
        userBooking.setUserBookingId(123L);

        Feedback feedback1 = new Feedback();
        feedback1.setAccountId(account3);
        feedback1.setContent("Not all who wander are lost");
        feedback1.setCreateDate(LocalDate.ofEpochDay(1L));
        feedback1.setFeedbackId(123L);
        feedback1.setIsBlock(true);
        feedback1.setReportFeedbackList(new ArrayList<>());
        feedback1.setTourId(tour);
        feedback1.setUserBookingId(userBooking);

        Partner partner2 = new Partner();
        partner2.setAccountId(new Account());
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(new CompanyPartner());
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(new ServiceCategory());
        partner2.setServiceList(new ArrayList<>());

        Role role2 = new Role();
        role2.setAccountList(new ArrayList<>());
        role2.setRoleId(123);
        role2.setRoleName("Role Name");

        User user2 = new User();
        user2.setAccountId(new Account());
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);

        Account account6 = new Account();
        account6.setAccountId(1234567890L);
        account6.setCommentList(new ArrayList<>());
        account6.setEmail("jane.doe@example.org");
        account6.setFeedbackList(new ArrayList<>());
        account6.setIsBlock(true);
        account6.setPartner(partner2);
        account6.setPassWord("Pass Word");
        account6.setRoleId(role2);
        account6.setTourList(new ArrayList<>());
        account6.setUser(user2);
        account6.setUserBookingList(new ArrayList<>());

        TourCategory tourCategory1 = new TourCategory();
        tourCategory1.setTourCategoryId(123L);
        tourCategory1.setTourCategoryName("Tour Category Name");
        tourCategory1.setTourList(new ArrayList<>());

        Tour tour2 = new Tour();
        tour2.setAccountId(new Account());
        tour2.setDeposit(10.0f);
        tour2.setEndPlace("End Place");
        tour2.setEndTime(null);
        tour2.setFeedbackList(new ArrayList<>());
        tour2.setMaxAdult(3);
        tour2.setMaxChildren(3);
        tour2.setMinAdult(1);
        tour2.setMinChildren(1);
        tour2.setMinToStart(1);
        tour2.setNote("Note");
        tour2.setNumberOfDay(10);
        tour2.setNumberOfNight(10);
        tour2.setPriceAdult(10.0f);
        tour2.setPriceChildren(10.0f);
        tour2.setStartDate(null);
        tour2.setStartPlace("Start Place");
        tour2.setStartTime(null);
        tour2.setStatus(1);
        tour2.setTotalPrice(10.0f);
        tour2.setTourCategoryId(new TourCategory());
        tour2.setTourCode("Tour Code");
        tour2.setTourDetail(new TourDetail());
        tour2.setTourId(123L);
        tour2.setTourMode(true);
        tour2.setTourName("Tour Name");
        tour2.setTourScheduleList(new ArrayList<>());
        tour2.setTourType(1);
        tour2.setUserBookingList(new ArrayList<>());

        TourDetail tourDetail1 = new TourDetail();
        tourDetail1.setAddressStart("42 Main St");
        tourDetail1.setDescription("The characteristics of someone or something");
        tourDetail1.setGeneralTerms("General Terms");
        tourDetail1.setLatitude(10.0f);
        tourDetail1.setLongitude(10.0f);
        tourDetail1.setMoreDescription("More Description");
        tourDetail1.setTagOfTourList(new ArrayList<>());
        tourDetail1.setTourDetailId(123L);
        tourDetail1.setTourId(tour2);
        tourDetail1.setTourInclude("Tour Include");
        tourDetail1.setTourIntroduce("Tour Introduce");
        tourDetail1.setTourNonInclude("Tour Non Include");

        Tour tour3 = new Tour();
        tour3.setAccountId(account6);
        tour3.setDeposit(10.0f);
        tour3.setEndPlace("End Place");
        tour3.setEndTime(LocalTime.of(1, 1));
        tour3.setFeedbackList(new ArrayList<>());
        tour3.setMaxAdult(3);
        tour3.setMaxChildren(3);
        tour3.setMinAdult(1);
        tour3.setMinChildren(1);
        tour3.setMinToStart(1);
        tour3.setNote("Note");
        tour3.setNumberOfDay(10);
        tour3.setNumberOfNight(10);
        tour3.setPriceAdult(10.0f);
        tour3.setPriceChildren(10.0f);
        tour3.setStartDate(LocalDate.ofEpochDay(1L));
        tour3.setStartPlace("Start Place");
        tour3.setStartTime(LocalTime.of(1, 1));
        tour3.setStatus(1);
        tour3.setTotalPrice(10.0f);
        tour3.setTourCategoryId(tourCategory1);
        tour3.setTourCode("Tour Code");
        tour3.setTourDetail(tourDetail1);
        tour3.setTourId(123L);
        tour3.setTourMode(true);
        tour3.setTourName("Tour Name");
        tour3.setTourScheduleList(new ArrayList<>());
        tour3.setTourType(1);
        tour3.setUserBookingList(new ArrayList<>());

        UserBooking userBooking1 = new UserBooking();
        userBooking1.setAccountId(account2);
        userBooking1.setAdultPrice(10.0f);
        userBooking1.setBookingDate(LocalDate.ofEpochDay(1L));
        userBooking1.setChildrenPrice(10.0f);
        userBooking1.setDateOfIssue(LocalDate.ofEpochDay(1L));
        userBooking1.setEmail("jane.doe@example.org");
        userBooking1.setFeedbackId(feedback1);
        userBooking1.setFullName("Dr Jane Doe");
        userBooking1.setIdCard("Id Card");
        userBooking1.setIsFeedback(true);
        userBooking1.setNumberOfAdult(10);
        userBooking1.setNumberOfChildren(10);
        userBooking1.setOrderId(123L);
        userBooking1.setOrderTitle("Dr");
        userBooking1.setPayType("Pay Type");
        userBooking1.setPhone("4105551212");
        userBooking1.setPlaceOfIssue("Place Of Issue");
        userBooking1.setRequest("Request");
        userBooking1.setRequestCancelList(new ArrayList<>());
        userBooking1.setStartDate(LocalDate.ofEpochDay(1L));
        userBooking1.setStatus(1);
        userBooking1.setStatusDeposit(true);
        userBooking1.setTotalPrice(10.0f);
        userBooking1.setTourId(tour3);
        userBooking1.setUserBookingId(123L);

        ReasonCancel reasonCancel = new ReasonCancel();
        reasonCancel.setReasonCancelId(123L);
        reasonCancel.setReasonCancelName("Just cause");
        reasonCancel.setRequestCancelList(new ArrayList<>());
        RequestCancel actualRequestCancel = new RequestCancel(123L, userBooking1, reasonCancel, LocalDate.ofEpochDay(1L),
                "The characteristics of someone or something", 1);
        actualRequestCancel.setDescription("The characteristics of someone or something");
        ReasonCancel reasonCancel1 = new ReasonCancel();
        reasonCancel1.setReasonCancelId(123L);
        reasonCancel1.setReasonCancelName("Just cause");
        reasonCancel1.setRequestCancelList(new ArrayList<>());
        actualRequestCancel.setReasonCancelId(reasonCancel1);
        actualRequestCancel.setRequestCancelId(123L);
        LocalDate ofEpochDayResult = LocalDate.ofEpochDay(1L);
        actualRequestCancel.setRequestDate(ofEpochDayResult);
        actualRequestCancel.setStatus(1);
        Account account7 = new Account();
        account7.setAccountId(1234567890L);
        account7.setCommentList(new ArrayList<>());
        account7.setEmail("jane.doe@example.org");
        account7.setFeedbackList(new ArrayList<>());
        account7.setIsBlock(true);
        account7.setPartner(new Partner());
        account7.setPassWord("Pass Word");
        account7.setRoleId(new Role());
        account7.setTourList(new ArrayList<>());
        account7.setUser(new User());
        account7.setUserBookingList(new ArrayList<>());
        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(new Partner());
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");
        ServiceCategory serviceCategory1 = new ServiceCategory();
        serviceCategory1.setPartnerList(new ArrayList<>());
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        serviceCategory1.setServiceList(new ArrayList<>());
        Partner partner3 = new Partner();
        partner3.setAccountId(account7);
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(companyPartner1);
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(serviceCategory1);
        partner3.setServiceList(new ArrayList<>());
        Role role3 = new Role();
        role3.setAccountList(new ArrayList<>());
        role3.setRoleId(123);
        role3.setRoleName("Role Name");
        Account account8 = new Account();
        account8.setAccountId(1234567890L);
        account8.setCommentList(new ArrayList<>());
        account8.setEmail("jane.doe@example.org");
        account8.setFeedbackList(new ArrayList<>());
        account8.setIsBlock(true);
        account8.setPartner(new Partner());
        account8.setPassWord("Pass Word");
        account8.setRoleId(new Role());
        account8.setTourList(new ArrayList<>());
        account8.setUser(new User());
        account8.setUserBookingList(new ArrayList<>());
        User user3 = new User();
        user3.setAccountId(account8);
        user3.setAddress("42 Main St");
        user3.setBirthDate("2020-03-01");
        user3.setCity("Oxford");
        user3.setFirstName("Jane");
        user3.setGender("Gender");
        user3.setIsPrivate(true);
        user3.setLastName("Doe");
        user3.setPhone("4105551212");
        user3.setRankPoint(1);
        user3.setUserId(123L);
        Account account9 = new Account();
        account9.setAccountId(1234567890L);
        account9.setCommentList(new ArrayList<>());
        account9.setEmail("jane.doe@example.org");
        account9.setFeedbackList(new ArrayList<>());
        account9.setIsBlock(true);
        account9.setPartner(partner3);
        account9.setPassWord("Pass Word");
        account9.setRoleId(role3);
        account9.setTourList(new ArrayList<>());
        account9.setUser(user3);
        account9.setUserBookingList(new ArrayList<>());
        Partner partner4 = new Partner();
        partner4.setAccountId(new Account());
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(new CompanyPartner());
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(new ServiceCategory());
        partner4.setServiceList(new ArrayList<>());
        Role role4 = new Role();
        role4.setAccountList(new ArrayList<>());
        role4.setRoleId(123);
        role4.setRoleName("Role Name");
        User user4 = new User();
        user4.setAccountId(new Account());
        user4.setAddress("42 Main St");
        user4.setBirthDate("2020-03-01");
        user4.setCity("Oxford");
        user4.setFirstName("Jane");
        user4.setGender("Gender");
        user4.setIsPrivate(true);
        user4.setLastName("Doe");
        user4.setPhone("4105551212");
        user4.setRankPoint(1);
        user4.setUserId(123L);
        Account account10 = new Account();
        account10.setAccountId(1234567890L);
        account10.setCommentList(new ArrayList<>());
        account10.setEmail("jane.doe@example.org");
        account10.setFeedbackList(new ArrayList<>());
        account10.setIsBlock(true);
        account10.setPartner(partner4);
        account10.setPassWord("Pass Word");
        account10.setRoleId(role4);
        account10.setTourList(new ArrayList<>());
        account10.setUser(user4);
        account10.setUserBookingList(new ArrayList<>());
        Account account11 = new Account();
        account11.setAccountId(1234567890L);
        account11.setCommentList(new ArrayList<>());
        account11.setEmail("jane.doe@example.org");
        account11.setFeedbackList(new ArrayList<>());
        account11.setIsBlock(true);
        account11.setPartner(new Partner());
        account11.setPassWord("Pass Word");
        account11.setRoleId(new Role());
        account11.setTourList(new ArrayList<>());
        account11.setUser(new User());
        account11.setUserBookingList(new ArrayList<>());
        TourCategory tourCategory2 = new TourCategory();
        tourCategory2.setTourCategoryId(123L);
        tourCategory2.setTourCategoryName("Tour Category Name");
        tourCategory2.setTourList(new ArrayList<>());
        TourDetail tourDetail2 = new TourDetail();
        tourDetail2.setAddressStart("42 Main St");
        tourDetail2.setDescription("The characteristics of someone or something");
        tourDetail2.setGeneralTerms("General Terms");
        tourDetail2.setLatitude(10.0f);
        tourDetail2.setLongitude(10.0f);
        tourDetail2.setMoreDescription("More Description");
        tourDetail2.setTagOfTourList(new ArrayList<>());
        tourDetail2.setTourDetailId(123L);
        tourDetail2.setTourId(new Tour());
        tourDetail2.setTourInclude("Tour Include");
        tourDetail2.setTourIntroduce("Tour Introduce");
        tourDetail2.setTourNonInclude("Tour Non Include");
        Tour tour4 = new Tour();
        tour4.setAccountId(account11);
        tour4.setDeposit(10.0f);
        tour4.setEndPlace("End Place");
        tour4.setEndTime(LocalTime.of(1, 1));
        tour4.setFeedbackList(new ArrayList<>());
        tour4.setMaxAdult(3);
        tour4.setMaxChildren(3);
        tour4.setMinAdult(1);
        tour4.setMinChildren(1);
        tour4.setMinToStart(1);
        tour4.setNote("Note");
        tour4.setNumberOfDay(10);
        tour4.setNumberOfNight(10);
        tour4.setPriceAdult(10.0f);
        tour4.setPriceChildren(10.0f);
        tour4.setStartDate(LocalDate.ofEpochDay(1L));
        tour4.setStartPlace("Start Place");
        tour4.setStartTime(LocalTime.of(1, 1));
        tour4.setStatus(1);
        tour4.setTotalPrice(10.0f);
        tour4.setTourCategoryId(tourCategory2);
        tour4.setTourCode("Tour Code");
        tour4.setTourDetail(tourDetail2);
        tour4.setTourId(123L);
        tour4.setTourMode(true);
        tour4.setTourName("Tour Name");
        tour4.setTourScheduleList(new ArrayList<>());
        tour4.setTourType(1);
        tour4.setUserBookingList(new ArrayList<>());
        Account account12 = new Account();
        account12.setAccountId(1234567890L);
        account12.setCommentList(new ArrayList<>());
        account12.setEmail("jane.doe@example.org");
        account12.setFeedbackList(new ArrayList<>());
        account12.setIsBlock(true);
        account12.setPartner(new Partner());
        account12.setPassWord("Pass Word");
        account12.setRoleId(new Role());
        account12.setTourList(new ArrayList<>());
        account12.setUser(new User());
        account12.setUserBookingList(new ArrayList<>());
        Feedback feedback2 = new Feedback();
        feedback2.setAccountId(new Account());
        feedback2.setContent("Not all who wander are lost");
        feedback2.setCreateDate(null);
        feedback2.setFeedbackId(123L);
        feedback2.setIsBlock(true);
        feedback2.setReportFeedbackList(new ArrayList<>());
        feedback2.setTourId(new Tour());
        feedback2.setUserBookingId(new UserBooking());
        Tour tour5 = new Tour();
        tour5.setAccountId(new Account());
        tour5.setDeposit(10.0f);
        tour5.setEndPlace("End Place");
        tour5.setEndTime(null);
        tour5.setFeedbackList(new ArrayList<>());
        tour5.setMaxAdult(3);
        tour5.setMaxChildren(3);
        tour5.setMinAdult(1);
        tour5.setMinChildren(1);
        tour5.setMinToStart(1);
        tour5.setNote("Note");
        tour5.setNumberOfDay(10);
        tour5.setNumberOfNight(10);
        tour5.setPriceAdult(10.0f);
        tour5.setPriceChildren(10.0f);
        tour5.setStartDate(null);
        tour5.setStartPlace("Start Place");
        tour5.setStartTime(null);
        tour5.setStatus(1);
        tour5.setTotalPrice(10.0f);
        tour5.setTourCategoryId(new TourCategory());
        tour5.setTourCode("Tour Code");
        tour5.setTourDetail(new TourDetail());
        tour5.setTourId(123L);
        tour5.setTourMode(true);
        tour5.setTourName("Tour Name");
        tour5.setTourScheduleList(new ArrayList<>());
        tour5.setTourType(1);
        tour5.setUserBookingList(new ArrayList<>());
        UserBooking userBooking2 = new UserBooking();
        userBooking2.setAccountId(account12);
        userBooking2.setAdultPrice(10.0f);
        userBooking2.setBookingDate(LocalDate.ofEpochDay(1L));
        userBooking2.setChildrenPrice(10.0f);
        userBooking2.setDateOfIssue(LocalDate.ofEpochDay(1L));
        userBooking2.setEmail("jane.doe@example.org");
        userBooking2.setFeedbackId(feedback2);
        userBooking2.setFullName("Dr Jane Doe");
        userBooking2.setIdCard("Id Card");
        userBooking2.setIsFeedback(true);
        userBooking2.setNumberOfAdult(10);
        userBooking2.setNumberOfChildren(10);
        userBooking2.setOrderId(123L);
        userBooking2.setOrderTitle("Dr");
        userBooking2.setPayType("Pay Type");
        userBooking2.setPhone("4105551212");
        userBooking2.setPlaceOfIssue("Place Of Issue");
        userBooking2.setRequest("Request");
        userBooking2.setRequestCancelList(new ArrayList<>());
        userBooking2.setStartDate(LocalDate.ofEpochDay(1L));
        userBooking2.setStatus(1);
        userBooking2.setStatusDeposit(true);
        userBooking2.setTotalPrice(10.0f);
        userBooking2.setTourId(tour5);
        userBooking2.setUserBookingId(123L);
        Feedback feedback3 = new Feedback();
        feedback3.setAccountId(account10);
        feedback3.setContent("Not all who wander are lost");
        feedback3.setCreateDate(LocalDate.ofEpochDay(1L));
        feedback3.setFeedbackId(123L);
        feedback3.setIsBlock(true);
        feedback3.setReportFeedbackList(new ArrayList<>());
        feedback3.setTourId(tour4);
        feedback3.setUserBookingId(userBooking2);
        Partner partner5 = new Partner();
        partner5.setAccountId(new Account());
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(new CompanyPartner());
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(new ServiceCategory());
        partner5.setServiceList(new ArrayList<>());
        Role role5 = new Role();
        role5.setAccountList(new ArrayList<>());
        role5.setRoleId(123);
        role5.setRoleName("Role Name");
        User user5 = new User();
        user5.setAccountId(new Account());
        user5.setAddress("42 Main St");
        user5.setBirthDate("2020-03-01");
        user5.setCity("Oxford");
        user5.setFirstName("Jane");
        user5.setGender("Gender");
        user5.setIsPrivate(true);
        user5.setLastName("Doe");
        user5.setPhone("4105551212");
        user5.setRankPoint(1);
        user5.setUserId(123L);
        Account account13 = new Account();
        account13.setAccountId(1234567890L);
        account13.setCommentList(new ArrayList<>());
        account13.setEmail("jane.doe@example.org");
        account13.setFeedbackList(new ArrayList<>());
        account13.setIsBlock(true);
        account13.setPartner(partner5);
        account13.setPassWord("Pass Word");
        account13.setRoleId(role5);
        account13.setTourList(new ArrayList<>());
        account13.setUser(user5);
        account13.setUserBookingList(new ArrayList<>());
        TourCategory tourCategory3 = new TourCategory();
        tourCategory3.setTourCategoryId(123L);
        tourCategory3.setTourCategoryName("Tour Category Name");
        tourCategory3.setTourList(new ArrayList<>());
        Tour tour6 = new Tour();
        tour6.setAccountId(new Account());
        tour6.setDeposit(10.0f);
        tour6.setEndPlace("End Place");
        tour6.setEndTime(null);
        tour6.setFeedbackList(new ArrayList<>());
        tour6.setMaxAdult(3);
        tour6.setMaxChildren(3);
        tour6.setMinAdult(1);
        tour6.setMinChildren(1);
        tour6.setMinToStart(1);
        tour6.setNote("Note");
        tour6.setNumberOfDay(10);
        tour6.setNumberOfNight(10);
        tour6.setPriceAdult(10.0f);
        tour6.setPriceChildren(10.0f);
        tour6.setStartDate(null);
        tour6.setStartPlace("Start Place");
        tour6.setStartTime(null);
        tour6.setStatus(1);
        tour6.setTotalPrice(10.0f);
        tour6.setTourCategoryId(new TourCategory());
        tour6.setTourCode("Tour Code");
        tour6.setTourDetail(new TourDetail());
        tour6.setTourId(123L);
        tour6.setTourMode(true);
        tour6.setTourName("Tour Name");
        tour6.setTourScheduleList(new ArrayList<>());
        tour6.setTourType(1);
        tour6.setUserBookingList(new ArrayList<>());
        TourDetail tourDetail3 = new TourDetail();
        tourDetail3.setAddressStart("42 Main St");
        tourDetail3.setDescription("The characteristics of someone or something");
        tourDetail3.setGeneralTerms("General Terms");
        tourDetail3.setLatitude(10.0f);
        tourDetail3.setLongitude(10.0f);
        tourDetail3.setMoreDescription("More Description");
        tourDetail3.setTagOfTourList(new ArrayList<>());
        tourDetail3.setTourDetailId(123L);
        tourDetail3.setTourId(tour6);
        tourDetail3.setTourInclude("Tour Include");
        tourDetail3.setTourIntroduce("Tour Introduce");
        tourDetail3.setTourNonInclude("Tour Non Include");
        Tour tour7 = new Tour();
        tour7.setAccountId(account13);
        tour7.setDeposit(10.0f);
        tour7.setEndPlace("End Place");
        tour7.setEndTime(LocalTime.of(1, 1));
        tour7.setFeedbackList(new ArrayList<>());
        tour7.setMaxAdult(3);
        tour7.setMaxChildren(3);
        tour7.setMinAdult(1);
        tour7.setMinChildren(1);
        tour7.setMinToStart(1);
        tour7.setNote("Note");
        tour7.setNumberOfDay(10);
        tour7.setNumberOfNight(10);
        tour7.setPriceAdult(10.0f);
        tour7.setPriceChildren(10.0f);
        tour7.setStartDate(LocalDate.ofEpochDay(1L));
        tour7.setStartPlace("Start Place");
        tour7.setStartTime(LocalTime.of(1, 1));
        tour7.setStatus(1);
        tour7.setTotalPrice(10.0f);
        tour7.setTourCategoryId(tourCategory3);
        tour7.setTourCode("Tour Code");
        tour7.setTourDetail(tourDetail3);
        tour7.setTourId(123L);
        tour7.setTourMode(true);
        tour7.setTourName("Tour Name");
        tour7.setTourScheduleList(new ArrayList<>());
        tour7.setTourType(1);
        tour7.setUserBookingList(new ArrayList<>());
        UserBooking userBooking3 = new UserBooking();
        userBooking3.setAccountId(account9);
        userBooking3.setAdultPrice(10.0f);
        userBooking3.setBookingDate(LocalDate.ofEpochDay(1L));
        userBooking3.setChildrenPrice(10.0f);
        userBooking3.setDateOfIssue(LocalDate.ofEpochDay(1L));
        userBooking3.setEmail("jane.doe@example.org");
        userBooking3.setFeedbackId(feedback3);
        userBooking3.setFullName("Dr Jane Doe");
        userBooking3.setIdCard("Id Card");
        userBooking3.setIsFeedback(true);
        userBooking3.setNumberOfAdult(10);
        userBooking3.setNumberOfChildren(10);
        userBooking3.setOrderId(123L);
        userBooking3.setOrderTitle("Dr");
        userBooking3.setPayType("Pay Type");
        userBooking3.setPhone("4105551212");
        userBooking3.setPlaceOfIssue("Place Of Issue");
        userBooking3.setRequest("Request");
        userBooking3.setRequestCancelList(new ArrayList<>());
        userBooking3.setStartDate(LocalDate.ofEpochDay(1L));
        userBooking3.setStatus(1);
        userBooking3.setStatusDeposit(true);
        userBooking3.setTotalPrice(10.0f);
        userBooking3.setTourId(tour7);
        userBooking3.setUserBookingId(123L);
        actualRequestCancel.setUserBookingId(userBooking3);
        assertEquals("The characteristics of someone or something", actualRequestCancel.getDescription());
        assertSame(reasonCancel1, actualRequestCancel.getReasonCancelId());
        assertEquals(123L, actualRequestCancel.getRequestCancelId().longValue());
        assertSame(ofEpochDayResult, actualRequestCancel.getRequestDate());
        assertEquals(1, actualRequestCancel.getStatus().intValue());
        assertSame(userBooking3, actualRequestCancel.getUserBookingId());
    }
}

