package com.example.wetravel.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Test;

class RestaurantTest {
    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link Restaurant#Restaurant()}
     *   <li>{@link Restaurant#setDescription(String)}
     *   <li>{@link Restaurant#setRate(Float)}
     *   <li>{@link Restaurant#setRestaurantId(Long)}
     *   <li>{@link Restaurant#setRestaurantServiceType(String)}
     *   <li>{@link Restaurant#setServiceId(Service)}
     *   <li>{@link Restaurant#setTimeClose(LocalTime)}
     *   <li>{@link Restaurant#setTimeOpen(LocalTime)}
     *   <li>{@link Restaurant#setTypeOfCuisineServiceList(List)}
     *   <li>{@link Restaurant#getDescription()}
     *   <li>{@link Restaurant#getServiceId()}
     *   <li>{@link Restaurant#getRate()}
     *   <li>{@link Restaurant#getRestaurantId()}
     *   <li>{@link Restaurant#getRestaurantServiceType()}
     *   <li>{@link Restaurant#getTimeClose()}
     *   <li>{@link Restaurant#getTimeOpen()}
     *   <li>{@link Restaurant#getTypeOfCuisineServiceList()}
     * </ul>
     */
    @Test
    void testConstructor() {
        Restaurant actualRestaurant = new Restaurant();
        actualRestaurant.setDescription("The characteristics of someone or something");
        actualRestaurant.setRate(10.0f);
        actualRestaurant.setRestaurantId(123L);
        actualRestaurant.setRestaurantServiceType("Restaurant Service Type");
        Accommodation accommodation = new Accommodation();
        accommodation.setAccommodationId(123L);
        accommodation.setAccommodationType("Accommodation Type");
        accommodation.setDescription("The characteristics of someone or something");
        accommodation.setNumberFloors(10);
        accommodation.setRate(10.0f);
        ArrayList<Room> roomList = new ArrayList<>();
        accommodation.setRoomList(roomList);
        accommodation.setServiceId(new Service());
        Entertainment entertainment = new Entertainment();
        entertainment.setDescription("The characteristics of someone or something");
        entertainment.setDowOpen("Dow Open");
        entertainment.setEntertainmentId(123L);
        entertainment.setEntertainmentType("Entertainment Type");
        entertainment.setPriceTicketAdult(10.0f);
        entertainment.setPriceTicketChildren(10.0f);
        entertainment.setServiceId(new Service());
        entertainment.setTimeClose(null);
        entertainment.setTimeOpen(null);
        Partner partner = new Partner();
        partner.setAccountId(new Account());
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(new CompanyPartner());
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList = new ArrayList<>();
        partner.setServiceList(serviceList);
        Restaurant restaurant = new Restaurant();
        restaurant.setDescription("The characteristics of someone or something");
        restaurant.setRate(10.0f);
        restaurant.setRestaurantId(123L);
        restaurant.setRestaurantServiceType("Restaurant Service Type");
        restaurant.setServiceId(new Service());
        restaurant.setTimeClose(null);
        restaurant.setTimeOpen(null);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList = new ArrayList<>();
        restaurant.setTypeOfCuisineServiceList(typeOfCuisineServiceList);
        ServiceCategory serviceCategory = new ServiceCategory();
        ArrayList<Partner> partnerList = new ArrayList<>();
        serviceCategory.setPartnerList(partnerList);
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList1 = new ArrayList<>();
        serviceCategory.setServiceList(serviceList1);
        Service service = new Service();
        service.setAccommodation(accommodation);
        service.setAddress("42 Main St");
        service.setCity("Oxford");
        service.setDateRegister(LocalDate.ofEpochDay(1L));
        service.setEmail("jane.doe@example.org");
        service.setEntertainment(entertainment);
        service.setFax("Fax");
        service.setIsActive(true);
        service.setIsBlock(true);
        service.setLink("Link");
        service.setPartnerId(partner);
        service.setPhone("4105551212");
        ArrayList<Post> postList = new ArrayList<>();
        service.setPostList(postList);
        service.setRestaurant(restaurant);
        service.setServiceCategoryId(serviceCategory);
        service.setServiceId(123L);
        service.setServiceName("Service Name");
        service.setStatus(1);
        service.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList = new ArrayList<>();
        service.setUtilitiesServiceList(utilitiesServiceList);
        Accommodation accommodation1 = new Accommodation();
        accommodation1.setAccommodationId(123L);
        accommodation1.setAccommodationType("Accommodation Type");
        accommodation1.setDescription("The characteristics of someone or something");
        accommodation1.setNumberFloors(10);
        accommodation1.setRate(10.0f);
        ArrayList<Room> roomList1 = new ArrayList<>();
        accommodation1.setRoomList(roomList1);
        accommodation1.setServiceId(service);
        Accommodation accommodation2 = new Accommodation();
        accommodation2.setAccommodationId(123L);
        accommodation2.setAccommodationType("Accommodation Type");
        accommodation2.setDescription("The characteristics of someone or something");
        accommodation2.setNumberFloors(10);
        accommodation2.setRate(10.0f);
        ArrayList<Room> roomList2 = new ArrayList<>();
        accommodation2.setRoomList(roomList2);
        accommodation2.setServiceId(new Service());
        Entertainment entertainment1 = new Entertainment();
        entertainment1.setDescription("The characteristics of someone or something");
        entertainment1.setDowOpen("Dow Open");
        entertainment1.setEntertainmentId(123L);
        entertainment1.setEntertainmentType("Entertainment Type");
        entertainment1.setPriceTicketAdult(10.0f);
        entertainment1.setPriceTicketChildren(10.0f);
        entertainment1.setServiceId(new Service());
        entertainment1.setTimeClose(null);
        entertainment1.setTimeOpen(null);
        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList2 = new ArrayList<>();
        partner1.setServiceList(serviceList2);
        Restaurant restaurant1 = new Restaurant();
        restaurant1.setDescription("The characteristics of someone or something");
        restaurant1.setRate(10.0f);
        restaurant1.setRestaurantId(123L);
        restaurant1.setRestaurantServiceType("Restaurant Service Type");
        restaurant1.setServiceId(new Service());
        restaurant1.setTimeClose(null);
        restaurant1.setTimeOpen(null);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList1 = new ArrayList<>();
        restaurant1.setTypeOfCuisineServiceList(typeOfCuisineServiceList1);
        ServiceCategory serviceCategory1 = new ServiceCategory();
        ArrayList<Partner> partnerList1 = new ArrayList<>();
        serviceCategory1.setPartnerList(partnerList1);
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList3 = new ArrayList<>();
        serviceCategory1.setServiceList(serviceList3);
        Service service1 = new Service();
        service1.setAccommodation(accommodation2);
        service1.setAddress("42 Main St");
        service1.setCity("Oxford");
        service1.setDateRegister(LocalDate.ofEpochDay(1L));
        service1.setEmail("jane.doe@example.org");
        service1.setEntertainment(entertainment1);
        service1.setFax("Fax");
        service1.setIsActive(true);
        service1.setIsBlock(true);
        service1.setLink("Link");
        service1.setPartnerId(partner1);
        service1.setPhone("4105551212");
        ArrayList<Post> postList1 = new ArrayList<>();
        service1.setPostList(postList1);
        service1.setRestaurant(restaurant1);
        service1.setServiceCategoryId(serviceCategory1);
        service1.setServiceId(123L);
        service1.setServiceName("Service Name");
        service1.setStatus(1);
        service1.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList1 = new ArrayList<>();
        service1.setUtilitiesServiceList(utilitiesServiceList1);
        Entertainment entertainment2 = new Entertainment();
        entertainment2.setDescription("The characteristics of someone or something");
        entertainment2.setDowOpen("Dow Open");
        entertainment2.setEntertainmentId(123L);
        entertainment2.setEntertainmentType("Entertainment Type");
        entertainment2.setPriceTicketAdult(10.0f);
        entertainment2.setPriceTicketChildren(10.0f);
        entertainment2.setServiceId(service1);
        entertainment2.setTimeClose(LocalTime.of(1, 1));
        entertainment2.setTimeOpen(LocalTime.of(1, 1));
        Partner partner2 = new Partner();
        partner2.setAccountId(new Account());
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(new CompanyPartner());
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList4 = new ArrayList<>();
        partner2.setServiceList(serviceList4);
        Role role = new Role();
        ArrayList<Account> accountList = new ArrayList<>();
        role.setAccountList(accountList);
        role.setRoleId(123);
        role.setRoleName("Role Name");
        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);
        Account account = new Account();
        account.setAccountId(1234567890L);
        ArrayList<Comment> commentList = new ArrayList<>();
        account.setCommentList(commentList);
        account.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList = new ArrayList<>();
        account.setFeedbackList(feedbackList);
        account.setIsBlock(true);
        account.setPartner(partner2);
        account.setPassWord("Pass Word");
        account.setRoleId(role);
        ArrayList<Tour> tourList = new ArrayList<>();
        account.setTourList(tourList);
        account.setUser(user);
        ArrayList<UserBooking> userBookingList = new ArrayList<>();
        account.setUserBookingList(userBookingList);
        Partner partner3 = new Partner();
        partner3.setAccountId(new Account());
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(new CompanyPartner());
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList5 = new ArrayList<>();
        partner3.setServiceList(serviceList5);
        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(partner3);
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");
        ServiceCategory serviceCategory2 = new ServiceCategory();
        ArrayList<Partner> partnerList2 = new ArrayList<>();
        serviceCategory2.setPartnerList(partnerList2);
        serviceCategory2.setServiceCategoryId(123L);
        serviceCategory2.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList6 = new ArrayList<>();
        serviceCategory2.setServiceList(serviceList6);
        Partner partner4 = new Partner();
        partner4.setAccountId(account);
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(companyPartner);
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(serviceCategory2);
        ArrayList<Service> serviceList7 = new ArrayList<>();
        partner4.setServiceList(serviceList7);
        Accommodation accommodation3 = new Accommodation();
        accommodation3.setAccommodationId(123L);
        accommodation3.setAccommodationType("Accommodation Type");
        accommodation3.setDescription("The characteristics of someone or something");
        accommodation3.setNumberFloors(10);
        accommodation3.setRate(10.0f);
        ArrayList<Room> roomList3 = new ArrayList<>();
        accommodation3.setRoomList(roomList3);
        accommodation3.setServiceId(new Service());
        Entertainment entertainment3 = new Entertainment();
        entertainment3.setDescription("The characteristics of someone or something");
        entertainment3.setDowOpen("Dow Open");
        entertainment3.setEntertainmentId(123L);
        entertainment3.setEntertainmentType("Entertainment Type");
        entertainment3.setPriceTicketAdult(10.0f);
        entertainment3.setPriceTicketChildren(10.0f);
        entertainment3.setServiceId(new Service());
        entertainment3.setTimeClose(null);
        entertainment3.setTimeOpen(null);
        Partner partner5 = new Partner();
        partner5.setAccountId(new Account());
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(new CompanyPartner());
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList8 = new ArrayList<>();
        partner5.setServiceList(serviceList8);
        Restaurant restaurant2 = new Restaurant();
        restaurant2.setDescription("The characteristics of someone or something");
        restaurant2.setRate(10.0f);
        restaurant2.setRestaurantId(123L);
        restaurant2.setRestaurantServiceType("Restaurant Service Type");
        restaurant2.setServiceId(new Service());
        restaurant2.setTimeClose(null);
        restaurant2.setTimeOpen(null);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList2 = new ArrayList<>();
        restaurant2.setTypeOfCuisineServiceList(typeOfCuisineServiceList2);
        ServiceCategory serviceCategory3 = new ServiceCategory();
        ArrayList<Partner> partnerList3 = new ArrayList<>();
        serviceCategory3.setPartnerList(partnerList3);
        serviceCategory3.setServiceCategoryId(123L);
        serviceCategory3.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList9 = new ArrayList<>();
        serviceCategory3.setServiceList(serviceList9);
        Service service2 = new Service();
        service2.setAccommodation(accommodation3);
        service2.setAddress("42 Main St");
        service2.setCity("Oxford");
        service2.setDateRegister(LocalDate.ofEpochDay(1L));
        service2.setEmail("jane.doe@example.org");
        service2.setEntertainment(entertainment3);
        service2.setFax("Fax");
        service2.setIsActive(true);
        service2.setIsBlock(true);
        service2.setLink("Link");
        service2.setPartnerId(partner5);
        service2.setPhone("4105551212");
        ArrayList<Post> postList2 = new ArrayList<>();
        service2.setPostList(postList2);
        service2.setRestaurant(restaurant2);
        service2.setServiceCategoryId(serviceCategory3);
        service2.setServiceId(123L);
        service2.setServiceName("Service Name");
        service2.setStatus(1);
        service2.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList2 = new ArrayList<>();
        service2.setUtilitiesServiceList(utilitiesServiceList2);
        Restaurant restaurant3 = new Restaurant();
        restaurant3.setDescription("The characteristics of someone or something");
        restaurant3.setRate(10.0f);
        restaurant3.setRestaurantId(123L);
        restaurant3.setRestaurantServiceType("Restaurant Service Type");
        restaurant3.setServiceId(service2);
        LocalTime ofResult = LocalTime.of(1, 1);
        restaurant3.setTimeClose(ofResult);
        LocalTime ofResult1 = LocalTime.of(1, 1);
        restaurant3.setTimeOpen(ofResult1);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList3 = new ArrayList<>();
        restaurant3.setTypeOfCuisineServiceList(typeOfCuisineServiceList3);
        ServiceCategory serviceCategory4 = new ServiceCategory();
        ArrayList<Partner> partnerList4 = new ArrayList<>();
        serviceCategory4.setPartnerList(partnerList4);
        serviceCategory4.setServiceCategoryId(123L);
        serviceCategory4.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList10 = new ArrayList<>();
        serviceCategory4.setServiceList(serviceList10);
        Service service3 = new Service();
        service3.setAccommodation(accommodation1);
        service3.setAddress("42 Main St");
        service3.setCity("Oxford");
        service3.setDateRegister(LocalDate.ofEpochDay(1L));
        service3.setEmail("jane.doe@example.org");
        service3.setEntertainment(entertainment2);
        service3.setFax("Fax");
        service3.setIsActive(true);
        service3.setIsBlock(true);
        service3.setLink("Link");
        service3.setPartnerId(partner4);
        service3.setPhone("4105551212");
        ArrayList<Post> postList3 = new ArrayList<>();
        service3.setPostList(postList3);
        service3.setRestaurant(restaurant3);
        service3.setServiceCategoryId(serviceCategory4);
        service3.setServiceId(123L);
        service3.setServiceName("Service Name");
        service3.setStatus(1);
        service3.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList3 = new ArrayList<>();
        service3.setUtilitiesServiceList(utilitiesServiceList3);
        actualRestaurant.setServiceId(service3);
        LocalTime ofResult2 = LocalTime.of(1, 1);
        actualRestaurant.setTimeClose(ofResult2);
        LocalTime ofResult3 = LocalTime.of(1, 1);
        actualRestaurant.setTimeOpen(ofResult3);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList4 = new ArrayList<>();
        actualRestaurant.setTypeOfCuisineServiceList(typeOfCuisineServiceList4);
        assertEquals("The characteristics of someone or something", actualRestaurant.getDescription());
        Service serviceId = actualRestaurant.getServiceId();
        Restaurant restaurant4 = serviceId.getRestaurant();
        assertEquals("The characteristics of someone or something", restaurant4.getDescription());
        assertEquals(10.0f, actualRestaurant.getRate().floatValue());
        assertEquals(10.0f, restaurant4.getRate().floatValue());
        assertEquals(123L, actualRestaurant.getRestaurantId().longValue());
        assertEquals(123L, restaurant4.getRestaurantId().longValue());
        assertEquals("Restaurant Service Type", actualRestaurant.getRestaurantServiceType());
        assertEquals("Restaurant Service Type", restaurant4.getRestaurantServiceType());
        assertSame(service3, serviceId);
        assertSame(service2, restaurant4.getServiceId());
        assertSame(ofResult2, actualRestaurant.getTimeClose());
        assertSame(ofResult, restaurant4.getTimeClose());
        assertSame(ofResult3, actualRestaurant.getTimeOpen());
        assertSame(ofResult1, restaurant4.getTimeOpen());
        List<TypeOfCuisineService> typeOfCuisineServiceList5 = actualRestaurant.getTypeOfCuisineServiceList();
        assertSame(typeOfCuisineServiceList4, typeOfCuisineServiceList5);
        assertEquals(roomList1, typeOfCuisineServiceList5);
        assertEquals(roomList, typeOfCuisineServiceList5);
        assertEquals(serviceList, typeOfCuisineServiceList5);
        assertEquals(postList, typeOfCuisineServiceList5);
        assertEquals(typeOfCuisineServiceList, typeOfCuisineServiceList5);
        assertEquals(partnerList, typeOfCuisineServiceList5);
        assertEquals(serviceList1, typeOfCuisineServiceList5);
        assertEquals(utilitiesServiceList, typeOfCuisineServiceList5);
        assertEquals(roomList2, typeOfCuisineServiceList5);
        assertEquals(serviceList2, typeOfCuisineServiceList5);
        assertEquals(postList1, typeOfCuisineServiceList5);
        assertEquals(typeOfCuisineServiceList1, typeOfCuisineServiceList5);
        assertEquals(partnerList1, typeOfCuisineServiceList5);
        assertEquals(serviceList3, typeOfCuisineServiceList5);
        assertEquals(utilitiesServiceList1, typeOfCuisineServiceList5);
        assertEquals(commentList, typeOfCuisineServiceList5);
        assertEquals(feedbackList, typeOfCuisineServiceList5);
        assertEquals(serviceList4, typeOfCuisineServiceList5);
        assertEquals(accountList, typeOfCuisineServiceList5);
        assertEquals(tourList, typeOfCuisineServiceList5);
        assertEquals(userBookingList, typeOfCuisineServiceList5);
        assertEquals(serviceList5, typeOfCuisineServiceList5);
        assertEquals(partnerList2, typeOfCuisineServiceList5);
        assertEquals(serviceList6, typeOfCuisineServiceList5);
        assertEquals(serviceList7, typeOfCuisineServiceList5);
        assertEquals(postList3, typeOfCuisineServiceList5);
        assertEquals(roomList3, typeOfCuisineServiceList5);
        assertEquals(serviceList8, typeOfCuisineServiceList5);
        assertEquals(postList2, typeOfCuisineServiceList5);
        assertEquals(typeOfCuisineServiceList2, typeOfCuisineServiceList5);
        assertEquals(partnerList3, typeOfCuisineServiceList5);
        assertEquals(serviceList9, typeOfCuisineServiceList5);
        assertEquals(utilitiesServiceList2, typeOfCuisineServiceList5);
        assertEquals(typeOfCuisineServiceList3, typeOfCuisineServiceList5);
        assertEquals(partnerList4, typeOfCuisineServiceList5);
        assertEquals(serviceList10, typeOfCuisineServiceList5);
        assertEquals(utilitiesServiceList3, typeOfCuisineServiceList5);
        List<TypeOfCuisineService> typeOfCuisineServiceList6 = restaurant4.getTypeOfCuisineServiceList();
        assertSame(typeOfCuisineServiceList3, typeOfCuisineServiceList6);
        assertEquals(roomList, typeOfCuisineServiceList6);
        assertEquals(serviceList, typeOfCuisineServiceList6);
        assertEquals(postList, typeOfCuisineServiceList6);
        assertEquals(typeOfCuisineServiceList, typeOfCuisineServiceList6);
        assertEquals(partnerList, typeOfCuisineServiceList6);
        assertEquals(serviceList1, typeOfCuisineServiceList6);
        assertEquals(utilitiesServiceList, typeOfCuisineServiceList6);
        assertEquals(roomList2, typeOfCuisineServiceList6);
        assertEquals(serviceList2, typeOfCuisineServiceList6);
        assertEquals(postList1, typeOfCuisineServiceList6);
        assertEquals(typeOfCuisineServiceList1, typeOfCuisineServiceList6);
        assertEquals(partnerList1, typeOfCuisineServiceList6);
        assertEquals(serviceList3, typeOfCuisineServiceList6);
        assertEquals(utilitiesServiceList1, typeOfCuisineServiceList6);
        assertEquals(commentList, typeOfCuisineServiceList6);
        assertEquals(feedbackList, typeOfCuisineServiceList6);
        assertEquals(serviceList4, typeOfCuisineServiceList6);
        assertEquals(accountList, typeOfCuisineServiceList6);
        assertEquals(tourList, typeOfCuisineServiceList6);
        assertEquals(userBookingList, typeOfCuisineServiceList6);
        assertEquals(serviceList5, typeOfCuisineServiceList6);
        assertEquals(partnerList2, typeOfCuisineServiceList6);
        assertEquals(serviceList6, typeOfCuisineServiceList6);
        assertEquals(serviceList7, typeOfCuisineServiceList6);
        assertEquals(roomList3, typeOfCuisineServiceList6);
        assertEquals(serviceList8, typeOfCuisineServiceList6);
        assertEquals(postList2, typeOfCuisineServiceList6);
        assertEquals(typeOfCuisineServiceList2, typeOfCuisineServiceList6);
        assertEquals(partnerList3, typeOfCuisineServiceList6);
        assertEquals(serviceList9, typeOfCuisineServiceList6);
        assertEquals(utilitiesServiceList2, typeOfCuisineServiceList6);
        assertEquals(typeOfCuisineServiceList5, typeOfCuisineServiceList6);
        assertEquals(serviceId.getPostList(), typeOfCuisineServiceList6);
        assertEquals(serviceId.getUtilitiesServiceList(), typeOfCuisineServiceList6);
        ServiceCategory serviceCategoryId = serviceId.getServiceCategoryId();
        assertEquals(serviceCategoryId.getPartnerList(), typeOfCuisineServiceList6);
        assertEquals(serviceCategoryId.getServiceList(), typeOfCuisineServiceList6);
        assertEquals(serviceId.getAccommodation().getRoomList(), typeOfCuisineServiceList6);
    }

    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link Restaurant#Restaurant(Long, String, LocalTime, LocalTime, String, Float, Service, List)}
     *   <li>{@link Restaurant#Restaurant()}
     *   <li>{@link Restaurant#setDescription(String)}
     *   <li>{@link Restaurant#setRate(Float)}
     *   <li>{@link Restaurant#setRestaurantId(Long)}
     *   <li>{@link Restaurant#setRestaurantServiceType(String)}
     *   <li>{@link Restaurant#setServiceId(Service)}
     *   <li>{@link Restaurant#setTimeClose(LocalTime)}
     *   <li>{@link Restaurant#setTimeOpen(LocalTime)}
     *   <li>{@link Restaurant#setTypeOfCuisineServiceList(List)}
     *   <li>{@link Restaurant#getDescription()}
     *   <li>{@link Restaurant#getServiceId()}
     *   <li>{@link Restaurant#getRate()}
     *   <li>{@link Restaurant#getRestaurantId()}
     *   <li>{@link Restaurant#getRestaurantServiceType()}
     *   <li>{@link Restaurant#getTimeClose()}
     *   <li>{@link Restaurant#getTimeOpen()}
     *   <li>{@link Restaurant#getTypeOfCuisineServiceList()}
     * </ul>
     */
    @Test
    void testConstructor2() {
        LocalTime timeOpen = LocalTime.of(1, 1);
        LocalTime timeClose = LocalTime.of(1, 1);

        Accommodation accommodation = new Accommodation();
        accommodation.setAccommodationId(123L);
        accommodation.setAccommodationType("Accommodation Type");
        accommodation.setDescription("The characteristics of someone or something");
        accommodation.setNumberFloors(10);
        accommodation.setRate(10.0f);
        ArrayList<Room> roomList = new ArrayList<>();
        accommodation.setRoomList(roomList);
        accommodation.setServiceId(new Service());

        Entertainment entertainment = new Entertainment();
        entertainment.setDescription("The characteristics of someone or something");
        entertainment.setDowOpen("Dow Open");
        entertainment.setEntertainmentId(123L);
        entertainment.setEntertainmentType("Entertainment Type");
        entertainment.setPriceTicketAdult(10.0f);
        entertainment.setPriceTicketChildren(10.0f);
        entertainment.setServiceId(new Service());
        entertainment.setTimeClose(null);
        entertainment.setTimeOpen(null);

        Partner partner = new Partner();
        partner.setAccountId(new Account());
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(new CompanyPartner());
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList = new ArrayList<>();
        partner.setServiceList(serviceList);

        Restaurant restaurant = new Restaurant();
        restaurant.setDescription("The characteristics of someone or something");
        restaurant.setRate(10.0f);
        restaurant.setRestaurantId(123L);
        restaurant.setRestaurantServiceType("Restaurant Service Type");
        restaurant.setServiceId(new Service());
        restaurant.setTimeClose(null);
        restaurant.setTimeOpen(null);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList = new ArrayList<>();
        restaurant.setTypeOfCuisineServiceList(typeOfCuisineServiceList);

        ServiceCategory serviceCategory = new ServiceCategory();
        ArrayList<Partner> partnerList = new ArrayList<>();
        serviceCategory.setPartnerList(partnerList);
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList1 = new ArrayList<>();
        serviceCategory.setServiceList(serviceList1);

        Service service = new Service();
        service.setAccommodation(accommodation);
        service.setAddress("42 Main St");
        service.setCity("Oxford");
        service.setDateRegister(LocalDate.ofEpochDay(1L));
        service.setEmail("jane.doe@example.org");
        service.setEntertainment(entertainment);
        service.setFax("Fax");
        service.setIsActive(true);
        service.setIsBlock(true);
        service.setLink("Link");
        service.setPartnerId(partner);
        service.setPhone("4105551212");
        ArrayList<Post> postList = new ArrayList<>();
        service.setPostList(postList);
        service.setRestaurant(restaurant);
        service.setServiceCategoryId(serviceCategory);
        service.setServiceId(123L);
        service.setServiceName("Service Name");
        service.setStatus(1);
        service.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList = new ArrayList<>();
        service.setUtilitiesServiceList(utilitiesServiceList);

        Accommodation accommodation1 = new Accommodation();
        accommodation1.setAccommodationId(123L);
        accommodation1.setAccommodationType("Accommodation Type");
        accommodation1.setDescription("The characteristics of someone or something");
        accommodation1.setNumberFloors(10);
        accommodation1.setRate(10.0f);
        ArrayList<Room> roomList1 = new ArrayList<>();
        accommodation1.setRoomList(roomList1);
        accommodation1.setServiceId(service);

        Accommodation accommodation2 = new Accommodation();
        accommodation2.setAccommodationId(123L);
        accommodation2.setAccommodationType("Accommodation Type");
        accommodation2.setDescription("The characteristics of someone or something");
        accommodation2.setNumberFloors(10);
        accommodation2.setRate(10.0f);
        ArrayList<Room> roomList2 = new ArrayList<>();
        accommodation2.setRoomList(roomList2);
        accommodation2.setServiceId(new Service());

        Entertainment entertainment1 = new Entertainment();
        entertainment1.setDescription("The characteristics of someone or something");
        entertainment1.setDowOpen("Dow Open");
        entertainment1.setEntertainmentId(123L);
        entertainment1.setEntertainmentType("Entertainment Type");
        entertainment1.setPriceTicketAdult(10.0f);
        entertainment1.setPriceTicketChildren(10.0f);
        entertainment1.setServiceId(new Service());
        entertainment1.setTimeClose(null);
        entertainment1.setTimeOpen(null);

        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList2 = new ArrayList<>();
        partner1.setServiceList(serviceList2);

        Restaurant restaurant1 = new Restaurant();
        restaurant1.setDescription("The characteristics of someone or something");
        restaurant1.setRate(10.0f);
        restaurant1.setRestaurantId(123L);
        restaurant1.setRestaurantServiceType("Restaurant Service Type");
        restaurant1.setServiceId(new Service());
        restaurant1.setTimeClose(null);
        restaurant1.setTimeOpen(null);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList1 = new ArrayList<>();
        restaurant1.setTypeOfCuisineServiceList(typeOfCuisineServiceList1);

        ServiceCategory serviceCategory1 = new ServiceCategory();
        ArrayList<Partner> partnerList1 = new ArrayList<>();
        serviceCategory1.setPartnerList(partnerList1);
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList3 = new ArrayList<>();
        serviceCategory1.setServiceList(serviceList3);

        Service service1 = new Service();
        service1.setAccommodation(accommodation2);
        service1.setAddress("42 Main St");
        service1.setCity("Oxford");
        service1.setDateRegister(LocalDate.ofEpochDay(1L));
        service1.setEmail("jane.doe@example.org");
        service1.setEntertainment(entertainment1);
        service1.setFax("Fax");
        service1.setIsActive(true);
        service1.setIsBlock(true);
        service1.setLink("Link");
        service1.setPartnerId(partner1);
        service1.setPhone("4105551212");
        ArrayList<Post> postList1 = new ArrayList<>();
        service1.setPostList(postList1);
        service1.setRestaurant(restaurant1);
        service1.setServiceCategoryId(serviceCategory1);
        service1.setServiceId(123L);
        service1.setServiceName("Service Name");
        service1.setStatus(1);
        service1.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList1 = new ArrayList<>();
        service1.setUtilitiesServiceList(utilitiesServiceList1);

        Entertainment entertainment2 = new Entertainment();
        entertainment2.setDescription("The characteristics of someone or something");
        entertainment2.setDowOpen("Dow Open");
        entertainment2.setEntertainmentId(123L);
        entertainment2.setEntertainmentType("Entertainment Type");
        entertainment2.setPriceTicketAdult(10.0f);
        entertainment2.setPriceTicketChildren(10.0f);
        entertainment2.setServiceId(service1);
        entertainment2.setTimeClose(LocalTime.of(1, 1));
        entertainment2.setTimeOpen(LocalTime.of(1, 1));

        Partner partner2 = new Partner();
        partner2.setAccountId(new Account());
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(new CompanyPartner());
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList4 = new ArrayList<>();
        partner2.setServiceList(serviceList4);

        Role role = new Role();
        ArrayList<Account> accountList = new ArrayList<>();
        role.setAccountList(accountList);
        role.setRoleId(123);
        role.setRoleName("Role Name");

        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);

        Account account = new Account();
        account.setAccountId(1234567890L);
        ArrayList<Comment> commentList = new ArrayList<>();
        account.setCommentList(commentList);
        account.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList = new ArrayList<>();
        account.setFeedbackList(feedbackList);
        account.setIsBlock(true);
        account.setPartner(partner2);
        account.setPassWord("Pass Word");
        account.setRoleId(role);
        ArrayList<Tour> tourList = new ArrayList<>();
        account.setTourList(tourList);
        account.setUser(user);
        ArrayList<UserBooking> userBookingList = new ArrayList<>();
        account.setUserBookingList(userBookingList);

        Partner partner3 = new Partner();
        partner3.setAccountId(new Account());
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(new CompanyPartner());
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList5 = new ArrayList<>();
        partner3.setServiceList(serviceList5);

        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(partner3);
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");

        ServiceCategory serviceCategory2 = new ServiceCategory();
        ArrayList<Partner> partnerList2 = new ArrayList<>();
        serviceCategory2.setPartnerList(partnerList2);
        serviceCategory2.setServiceCategoryId(123L);
        serviceCategory2.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList6 = new ArrayList<>();
        serviceCategory2.setServiceList(serviceList6);

        Partner partner4 = new Partner();
        partner4.setAccountId(account);
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(companyPartner);
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(serviceCategory2);
        ArrayList<Service> serviceList7 = new ArrayList<>();
        partner4.setServiceList(serviceList7);

        Accommodation accommodation3 = new Accommodation();
        accommodation3.setAccommodationId(123L);
        accommodation3.setAccommodationType("Accommodation Type");
        accommodation3.setDescription("The characteristics of someone or something");
        accommodation3.setNumberFloors(10);
        accommodation3.setRate(10.0f);
        ArrayList<Room> roomList3 = new ArrayList<>();
        accommodation3.setRoomList(roomList3);
        accommodation3.setServiceId(new Service());

        Entertainment entertainment3 = new Entertainment();
        entertainment3.setDescription("The characteristics of someone or something");
        entertainment3.setDowOpen("Dow Open");
        entertainment3.setEntertainmentId(123L);
        entertainment3.setEntertainmentType("Entertainment Type");
        entertainment3.setPriceTicketAdult(10.0f);
        entertainment3.setPriceTicketChildren(10.0f);
        entertainment3.setServiceId(new Service());
        entertainment3.setTimeClose(null);
        entertainment3.setTimeOpen(null);

        Partner partner5 = new Partner();
        partner5.setAccountId(new Account());
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(new CompanyPartner());
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList8 = new ArrayList<>();
        partner5.setServiceList(serviceList8);

        Restaurant restaurant2 = new Restaurant();
        restaurant2.setDescription("The characteristics of someone or something");
        restaurant2.setRate(10.0f);
        restaurant2.setRestaurantId(123L);
        restaurant2.setRestaurantServiceType("Restaurant Service Type");
        restaurant2.setServiceId(new Service());
        restaurant2.setTimeClose(null);
        restaurant2.setTimeOpen(null);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList2 = new ArrayList<>();
        restaurant2.setTypeOfCuisineServiceList(typeOfCuisineServiceList2);

        ServiceCategory serviceCategory3 = new ServiceCategory();
        ArrayList<Partner> partnerList3 = new ArrayList<>();
        serviceCategory3.setPartnerList(partnerList3);
        serviceCategory3.setServiceCategoryId(123L);
        serviceCategory3.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList9 = new ArrayList<>();
        serviceCategory3.setServiceList(serviceList9);

        Service service2 = new Service();
        service2.setAccommodation(accommodation3);
        service2.setAddress("42 Main St");
        service2.setCity("Oxford");
        service2.setDateRegister(LocalDate.ofEpochDay(1L));
        service2.setEmail("jane.doe@example.org");
        service2.setEntertainment(entertainment3);
        service2.setFax("Fax");
        service2.setIsActive(true);
        service2.setIsBlock(true);
        service2.setLink("Link");
        service2.setPartnerId(partner5);
        service2.setPhone("4105551212");
        ArrayList<Post> postList2 = new ArrayList<>();
        service2.setPostList(postList2);
        service2.setRestaurant(restaurant2);
        service2.setServiceCategoryId(serviceCategory3);
        service2.setServiceId(123L);
        service2.setServiceName("Service Name");
        service2.setStatus(1);
        service2.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList2 = new ArrayList<>();
        service2.setUtilitiesServiceList(utilitiesServiceList2);

        Restaurant restaurant3 = new Restaurant();
        restaurant3.setDescription("The characteristics of someone or something");
        restaurant3.setRate(10.0f);
        restaurant3.setRestaurantId(123L);
        restaurant3.setRestaurantServiceType("Restaurant Service Type");
        restaurant3.setServiceId(service2);
        restaurant3.setTimeClose(LocalTime.of(1, 1));
        restaurant3.setTimeOpen(LocalTime.of(1, 1));
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList3 = new ArrayList<>();
        restaurant3.setTypeOfCuisineServiceList(typeOfCuisineServiceList3);

        ServiceCategory serviceCategory4 = new ServiceCategory();
        ArrayList<Partner> partnerList4 = new ArrayList<>();
        serviceCategory4.setPartnerList(partnerList4);
        serviceCategory4.setServiceCategoryId(123L);
        serviceCategory4.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList10 = new ArrayList<>();
        serviceCategory4.setServiceList(serviceList10);

        Service service3 = new Service();
        service3.setAccommodation(accommodation1);
        service3.setAddress("42 Main St");
        service3.setCity("Oxford");
        service3.setDateRegister(LocalDate.ofEpochDay(1L));
        service3.setEmail("jane.doe@example.org");
        service3.setEntertainment(entertainment2);
        service3.setFax("Fax");
        service3.setIsActive(true);
        service3.setIsBlock(true);
        service3.setLink("Link");
        service3.setPartnerId(partner4);
        service3.setPhone("4105551212");
        ArrayList<Post> postList3 = new ArrayList<>();
        service3.setPostList(postList3);
        service3.setRestaurant(restaurant3);
        service3.setServiceCategoryId(serviceCategory4);
        service3.setServiceId(123L);
        service3.setServiceName("Service Name");
        service3.setStatus(1);
        service3.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList3 = new ArrayList<>();
        service3.setUtilitiesServiceList(utilitiesServiceList3);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList4 = new ArrayList<>();
        Restaurant actualRestaurant = new Restaurant(123L, "Restaurant Service Type", timeOpen, timeClose,
                "The characteristics of someone or something", 10.0f, service3, typeOfCuisineServiceList4);
        actualRestaurant.setDescription("The characteristics of someone or something");
        actualRestaurant.setRate(10.0f);
        actualRestaurant.setRestaurantId(123L);
        actualRestaurant.setRestaurantServiceType("Restaurant Service Type");
        Accommodation accommodation4 = new Accommodation();
        accommodation4.setAccommodationId(123L);
        accommodation4.setAccommodationType("Accommodation Type");
        accommodation4.setDescription("The characteristics of someone or something");
        accommodation4.setNumberFloors(10);
        accommodation4.setRate(10.0f);
        ArrayList<Room> roomList4 = new ArrayList<>();
        accommodation4.setRoomList(roomList4);
        accommodation4.setServiceId(new Service());
        Entertainment entertainment4 = new Entertainment();
        entertainment4.setDescription("The characteristics of someone or something");
        entertainment4.setDowOpen("Dow Open");
        entertainment4.setEntertainmentId(123L);
        entertainment4.setEntertainmentType("Entertainment Type");
        entertainment4.setPriceTicketAdult(10.0f);
        entertainment4.setPriceTicketChildren(10.0f);
        entertainment4.setServiceId(new Service());
        entertainment4.setTimeClose(null);
        entertainment4.setTimeOpen(null);
        Partner partner6 = new Partner();
        partner6.setAccountId(new Account());
        partner6.setAddress("42 Main St");
        partner6.setBirthDate("2020-03-01");
        partner6.setCity("Oxford");
        partner6.setCompanyPartnerId(new CompanyPartner());
        partner6.setDateIssue("2020-03-01");
        partner6.setDepartment("Department");
        partner6.setEmail("jane.doe@example.org");
        partner6.setFirstName("Jane");
        partner6.setGender("Gender");
        partner6.setLastName("Doe");
        partner6.setNumberIdCard("42");
        partner6.setPartnerId(123L);
        partner6.setPhone("4105551212");
        partner6.setPlaceIssue("Place Issue");
        partner6.setPosition("Position");
        partner6.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList11 = new ArrayList<>();
        partner6.setServiceList(serviceList11);
        Restaurant restaurant4 = new Restaurant();
        restaurant4.setDescription("The characteristics of someone or something");
        restaurant4.setRate(10.0f);
        restaurant4.setRestaurantId(123L);
        restaurant4.setRestaurantServiceType("Restaurant Service Type");
        restaurant4.setServiceId(new Service());
        restaurant4.setTimeClose(null);
        restaurant4.setTimeOpen(null);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList5 = new ArrayList<>();
        restaurant4.setTypeOfCuisineServiceList(typeOfCuisineServiceList5);
        ServiceCategory serviceCategory5 = new ServiceCategory();
        ArrayList<Partner> partnerList5 = new ArrayList<>();
        serviceCategory5.setPartnerList(partnerList5);
        serviceCategory5.setServiceCategoryId(123L);
        serviceCategory5.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList12 = new ArrayList<>();
        serviceCategory5.setServiceList(serviceList12);
        Service service4 = new Service();
        service4.setAccommodation(accommodation4);
        service4.setAddress("42 Main St");
        service4.setCity("Oxford");
        service4.setDateRegister(LocalDate.ofEpochDay(1L));
        service4.setEmail("jane.doe@example.org");
        service4.setEntertainment(entertainment4);
        service4.setFax("Fax");
        service4.setIsActive(true);
        service4.setIsBlock(true);
        service4.setLink("Link");
        service4.setPartnerId(partner6);
        service4.setPhone("4105551212");
        ArrayList<Post> postList4 = new ArrayList<>();
        service4.setPostList(postList4);
        service4.setRestaurant(restaurant4);
        service4.setServiceCategoryId(serviceCategory5);
        service4.setServiceId(123L);
        service4.setServiceName("Service Name");
        service4.setStatus(1);
        service4.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList4 = new ArrayList<>();
        service4.setUtilitiesServiceList(utilitiesServiceList4);
        Accommodation accommodation5 = new Accommodation();
        accommodation5.setAccommodationId(123L);
        accommodation5.setAccommodationType("Accommodation Type");
        accommodation5.setDescription("The characteristics of someone or something");
        accommodation5.setNumberFloors(10);
        accommodation5.setRate(10.0f);
        ArrayList<Room> roomList5 = new ArrayList<>();
        accommodation5.setRoomList(roomList5);
        accommodation5.setServiceId(service4);
        Accommodation accommodation6 = new Accommodation();
        accommodation6.setAccommodationId(123L);
        accommodation6.setAccommodationType("Accommodation Type");
        accommodation6.setDescription("The characteristics of someone or something");
        accommodation6.setNumberFloors(10);
        accommodation6.setRate(10.0f);
        ArrayList<Room> roomList6 = new ArrayList<>();
        accommodation6.setRoomList(roomList6);
        accommodation6.setServiceId(new Service());
        Entertainment entertainment5 = new Entertainment();
        entertainment5.setDescription("The characteristics of someone or something");
        entertainment5.setDowOpen("Dow Open");
        entertainment5.setEntertainmentId(123L);
        entertainment5.setEntertainmentType("Entertainment Type");
        entertainment5.setPriceTicketAdult(10.0f);
        entertainment5.setPriceTicketChildren(10.0f);
        entertainment5.setServiceId(new Service());
        entertainment5.setTimeClose(null);
        entertainment5.setTimeOpen(null);
        Partner partner7 = new Partner();
        partner7.setAccountId(new Account());
        partner7.setAddress("42 Main St");
        partner7.setBirthDate("2020-03-01");
        partner7.setCity("Oxford");
        partner7.setCompanyPartnerId(new CompanyPartner());
        partner7.setDateIssue("2020-03-01");
        partner7.setDepartment("Department");
        partner7.setEmail("jane.doe@example.org");
        partner7.setFirstName("Jane");
        partner7.setGender("Gender");
        partner7.setLastName("Doe");
        partner7.setNumberIdCard("42");
        partner7.setPartnerId(123L);
        partner7.setPhone("4105551212");
        partner7.setPlaceIssue("Place Issue");
        partner7.setPosition("Position");
        partner7.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList13 = new ArrayList<>();
        partner7.setServiceList(serviceList13);
        Restaurant restaurant5 = new Restaurant();
        restaurant5.setDescription("The characteristics of someone or something");
        restaurant5.setRate(10.0f);
        restaurant5.setRestaurantId(123L);
        restaurant5.setRestaurantServiceType("Restaurant Service Type");
        restaurant5.setServiceId(new Service());
        restaurant5.setTimeClose(null);
        restaurant5.setTimeOpen(null);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList6 = new ArrayList<>();
        restaurant5.setTypeOfCuisineServiceList(typeOfCuisineServiceList6);
        ServiceCategory serviceCategory6 = new ServiceCategory();
        ArrayList<Partner> partnerList6 = new ArrayList<>();
        serviceCategory6.setPartnerList(partnerList6);
        serviceCategory6.setServiceCategoryId(123L);
        serviceCategory6.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList14 = new ArrayList<>();
        serviceCategory6.setServiceList(serviceList14);
        Service service5 = new Service();
        service5.setAccommodation(accommodation6);
        service5.setAddress("42 Main St");
        service5.setCity("Oxford");
        service5.setDateRegister(LocalDate.ofEpochDay(1L));
        service5.setEmail("jane.doe@example.org");
        service5.setEntertainment(entertainment5);
        service5.setFax("Fax");
        service5.setIsActive(true);
        service5.setIsBlock(true);
        service5.setLink("Link");
        service5.setPartnerId(partner7);
        service5.setPhone("4105551212");
        ArrayList<Post> postList5 = new ArrayList<>();
        service5.setPostList(postList5);
        service5.setRestaurant(restaurant5);
        service5.setServiceCategoryId(serviceCategory6);
        service5.setServiceId(123L);
        service5.setServiceName("Service Name");
        service5.setStatus(1);
        service5.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList5 = new ArrayList<>();
        service5.setUtilitiesServiceList(utilitiesServiceList5);
        Entertainment entertainment6 = new Entertainment();
        entertainment6.setDescription("The characteristics of someone or something");
        entertainment6.setDowOpen("Dow Open");
        entertainment6.setEntertainmentId(123L);
        entertainment6.setEntertainmentType("Entertainment Type");
        entertainment6.setPriceTicketAdult(10.0f);
        entertainment6.setPriceTicketChildren(10.0f);
        entertainment6.setServiceId(service5);
        entertainment6.setTimeClose(LocalTime.of(1, 1));
        entertainment6.setTimeOpen(LocalTime.of(1, 1));
        Partner partner8 = new Partner();
        partner8.setAccountId(new Account());
        partner8.setAddress("42 Main St");
        partner8.setBirthDate("2020-03-01");
        partner8.setCity("Oxford");
        partner8.setCompanyPartnerId(new CompanyPartner());
        partner8.setDateIssue("2020-03-01");
        partner8.setDepartment("Department");
        partner8.setEmail("jane.doe@example.org");
        partner8.setFirstName("Jane");
        partner8.setGender("Gender");
        partner8.setLastName("Doe");
        partner8.setNumberIdCard("42");
        partner8.setPartnerId(123L);
        partner8.setPhone("4105551212");
        partner8.setPlaceIssue("Place Issue");
        partner8.setPosition("Position");
        partner8.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList15 = new ArrayList<>();
        partner8.setServiceList(serviceList15);
        Role role1 = new Role();
        ArrayList<Account> accountList1 = new ArrayList<>();
        role1.setAccountList(accountList1);
        role1.setRoleId(123);
        role1.setRoleName("Role Name");
        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);
        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        ArrayList<Comment> commentList1 = new ArrayList<>();
        account1.setCommentList(commentList1);
        account1.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList1 = new ArrayList<>();
        account1.setFeedbackList(feedbackList1);
        account1.setIsBlock(true);
        account1.setPartner(partner8);
        account1.setPassWord("Pass Word");
        account1.setRoleId(role1);
        ArrayList<Tour> tourList1 = new ArrayList<>();
        account1.setTourList(tourList1);
        account1.setUser(user1);
        ArrayList<UserBooking> userBookingList1 = new ArrayList<>();
        account1.setUserBookingList(userBookingList1);
        Partner partner9 = new Partner();
        partner9.setAccountId(new Account());
        partner9.setAddress("42 Main St");
        partner9.setBirthDate("2020-03-01");
        partner9.setCity("Oxford");
        partner9.setCompanyPartnerId(new CompanyPartner());
        partner9.setDateIssue("2020-03-01");
        partner9.setDepartment("Department");
        partner9.setEmail("jane.doe@example.org");
        partner9.setFirstName("Jane");
        partner9.setGender("Gender");
        partner9.setLastName("Doe");
        partner9.setNumberIdCard("42");
        partner9.setPartnerId(123L);
        partner9.setPhone("4105551212");
        partner9.setPlaceIssue("Place Issue");
        partner9.setPosition("Position");
        partner9.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList16 = new ArrayList<>();
        partner9.setServiceList(serviceList16);
        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(partner9);
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");
        ServiceCategory serviceCategory7 = new ServiceCategory();
        ArrayList<Partner> partnerList7 = new ArrayList<>();
        serviceCategory7.setPartnerList(partnerList7);
        serviceCategory7.setServiceCategoryId(123L);
        serviceCategory7.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList17 = new ArrayList<>();
        serviceCategory7.setServiceList(serviceList17);
        Partner partner10 = new Partner();
        partner10.setAccountId(account1);
        partner10.setAddress("42 Main St");
        partner10.setBirthDate("2020-03-01");
        partner10.setCity("Oxford");
        partner10.setCompanyPartnerId(companyPartner1);
        partner10.setDateIssue("2020-03-01");
        partner10.setDepartment("Department");
        partner10.setEmail("jane.doe@example.org");
        partner10.setFirstName("Jane");
        partner10.setGender("Gender");
        partner10.setLastName("Doe");
        partner10.setNumberIdCard("42");
        partner10.setPartnerId(123L);
        partner10.setPhone("4105551212");
        partner10.setPlaceIssue("Place Issue");
        partner10.setPosition("Position");
        partner10.setServiceCategoryId(serviceCategory7);
        ArrayList<Service> serviceList18 = new ArrayList<>();
        partner10.setServiceList(serviceList18);
        Accommodation accommodation7 = new Accommodation();
        accommodation7.setAccommodationId(123L);
        accommodation7.setAccommodationType("Accommodation Type");
        accommodation7.setDescription("The characteristics of someone or something");
        accommodation7.setNumberFloors(10);
        accommodation7.setRate(10.0f);
        ArrayList<Room> roomList7 = new ArrayList<>();
        accommodation7.setRoomList(roomList7);
        accommodation7.setServiceId(new Service());
        Entertainment entertainment7 = new Entertainment();
        entertainment7.setDescription("The characteristics of someone or something");
        entertainment7.setDowOpen("Dow Open");
        entertainment7.setEntertainmentId(123L);
        entertainment7.setEntertainmentType("Entertainment Type");
        entertainment7.setPriceTicketAdult(10.0f);
        entertainment7.setPriceTicketChildren(10.0f);
        entertainment7.setServiceId(new Service());
        entertainment7.setTimeClose(null);
        entertainment7.setTimeOpen(null);
        Partner partner11 = new Partner();
        partner11.setAccountId(new Account());
        partner11.setAddress("42 Main St");
        partner11.setBirthDate("2020-03-01");
        partner11.setCity("Oxford");
        partner11.setCompanyPartnerId(new CompanyPartner());
        partner11.setDateIssue("2020-03-01");
        partner11.setDepartment("Department");
        partner11.setEmail("jane.doe@example.org");
        partner11.setFirstName("Jane");
        partner11.setGender("Gender");
        partner11.setLastName("Doe");
        partner11.setNumberIdCard("42");
        partner11.setPartnerId(123L);
        partner11.setPhone("4105551212");
        partner11.setPlaceIssue("Place Issue");
        partner11.setPosition("Position");
        partner11.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList19 = new ArrayList<>();
        partner11.setServiceList(serviceList19);
        Restaurant restaurant6 = new Restaurant();
        restaurant6.setDescription("The characteristics of someone or something");
        restaurant6.setRate(10.0f);
        restaurant6.setRestaurantId(123L);
        restaurant6.setRestaurantServiceType("Restaurant Service Type");
        restaurant6.setServiceId(new Service());
        restaurant6.setTimeClose(null);
        restaurant6.setTimeOpen(null);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList7 = new ArrayList<>();
        restaurant6.setTypeOfCuisineServiceList(typeOfCuisineServiceList7);
        ServiceCategory serviceCategory8 = new ServiceCategory();
        ArrayList<Partner> partnerList8 = new ArrayList<>();
        serviceCategory8.setPartnerList(partnerList8);
        serviceCategory8.setServiceCategoryId(123L);
        serviceCategory8.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList20 = new ArrayList<>();
        serviceCategory8.setServiceList(serviceList20);
        Service service6 = new Service();
        service6.setAccommodation(accommodation7);
        service6.setAddress("42 Main St");
        service6.setCity("Oxford");
        service6.setDateRegister(LocalDate.ofEpochDay(1L));
        service6.setEmail("jane.doe@example.org");
        service6.setEntertainment(entertainment7);
        service6.setFax("Fax");
        service6.setIsActive(true);
        service6.setIsBlock(true);
        service6.setLink("Link");
        service6.setPartnerId(partner11);
        service6.setPhone("4105551212");
        ArrayList<Post> postList6 = new ArrayList<>();
        service6.setPostList(postList6);
        service6.setRestaurant(restaurant6);
        service6.setServiceCategoryId(serviceCategory8);
        service6.setServiceId(123L);
        service6.setServiceName("Service Name");
        service6.setStatus(1);
        service6.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList6 = new ArrayList<>();
        service6.setUtilitiesServiceList(utilitiesServiceList6);
        Restaurant restaurant7 = new Restaurant();
        restaurant7.setDescription("The characteristics of someone or something");
        restaurant7.setRate(10.0f);
        restaurant7.setRestaurantId(123L);
        restaurant7.setRestaurantServiceType("Restaurant Service Type");
        restaurant7.setServiceId(service6);
        LocalTime ofResult = LocalTime.of(1, 1);
        restaurant7.setTimeClose(ofResult);
        LocalTime ofResult1 = LocalTime.of(1, 1);
        restaurant7.setTimeOpen(ofResult1);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList8 = new ArrayList<>();
        restaurant7.setTypeOfCuisineServiceList(typeOfCuisineServiceList8);
        ServiceCategory serviceCategory9 = new ServiceCategory();
        ArrayList<Partner> partnerList9 = new ArrayList<>();
        serviceCategory9.setPartnerList(partnerList9);
        serviceCategory9.setServiceCategoryId(123L);
        serviceCategory9.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList21 = new ArrayList<>();
        serviceCategory9.setServiceList(serviceList21);
        Service service7 = new Service();
        service7.setAccommodation(accommodation5);
        service7.setAddress("42 Main St");
        service7.setCity("Oxford");
        service7.setDateRegister(LocalDate.ofEpochDay(1L));
        service7.setEmail("jane.doe@example.org");
        service7.setEntertainment(entertainment6);
        service7.setFax("Fax");
        service7.setIsActive(true);
        service7.setIsBlock(true);
        service7.setLink("Link");
        service7.setPartnerId(partner10);
        service7.setPhone("4105551212");
        ArrayList<Post> postList7 = new ArrayList<>();
        service7.setPostList(postList7);
        service7.setRestaurant(restaurant7);
        service7.setServiceCategoryId(serviceCategory9);
        service7.setServiceId(123L);
        service7.setServiceName("Service Name");
        service7.setStatus(1);
        service7.setTaxCode("Tax Code");
        ArrayList<UtilitiesService> utilitiesServiceList7 = new ArrayList<>();
        service7.setUtilitiesServiceList(utilitiesServiceList7);
        actualRestaurant.setServiceId(service7);
        LocalTime ofResult2 = LocalTime.of(1, 1);
        actualRestaurant.setTimeClose(ofResult2);
        LocalTime ofResult3 = LocalTime.of(1, 1);
        actualRestaurant.setTimeOpen(ofResult3);
        ArrayList<TypeOfCuisineService> typeOfCuisineServiceList9 = new ArrayList<>();
        actualRestaurant.setTypeOfCuisineServiceList(typeOfCuisineServiceList9);
        assertEquals("The characteristics of someone or something", actualRestaurant.getDescription());
        Service serviceId = actualRestaurant.getServiceId();
        Restaurant restaurant8 = serviceId.getRestaurant();
        assertEquals("The characteristics of someone or something", restaurant8.getDescription());
        assertEquals(10.0f, actualRestaurant.getRate().floatValue());
        assertEquals(10.0f, restaurant8.getRate().floatValue());
        assertEquals(123L, actualRestaurant.getRestaurantId().longValue());
        assertEquals(123L, restaurant8.getRestaurantId().longValue());
        assertEquals("Restaurant Service Type", actualRestaurant.getRestaurantServiceType());
        assertEquals("Restaurant Service Type", restaurant8.getRestaurantServiceType());
        assertSame(service7, serviceId);
        assertSame(service6, restaurant8.getServiceId());
        assertSame(ofResult2, actualRestaurant.getTimeClose());
        assertSame(ofResult, restaurant8.getTimeClose());
        assertSame(ofResult3, actualRestaurant.getTimeOpen());
        assertSame(ofResult1, restaurant8.getTimeOpen());
        List<TypeOfCuisineService> typeOfCuisineServiceList10 = actualRestaurant.getTypeOfCuisineServiceList();
        assertSame(typeOfCuisineServiceList9, typeOfCuisineServiceList10);
        assertEquals(roomList1, typeOfCuisineServiceList10);
        assertEquals(roomList, typeOfCuisineServiceList10);
        assertEquals(serviceList, typeOfCuisineServiceList10);
        assertEquals(postList, typeOfCuisineServiceList10);
        assertEquals(typeOfCuisineServiceList, typeOfCuisineServiceList10);
        assertEquals(partnerList, typeOfCuisineServiceList10);
        assertEquals(serviceList1, typeOfCuisineServiceList10);
        assertEquals(utilitiesServiceList, typeOfCuisineServiceList10);
        assertEquals(roomList2, typeOfCuisineServiceList10);
        assertEquals(serviceList2, typeOfCuisineServiceList10);
        assertEquals(postList1, typeOfCuisineServiceList10);
        assertEquals(typeOfCuisineServiceList1, typeOfCuisineServiceList10);
        assertEquals(partnerList1, typeOfCuisineServiceList10);
        assertEquals(serviceList3, typeOfCuisineServiceList10);
        assertEquals(utilitiesServiceList1, typeOfCuisineServiceList10);
        assertEquals(commentList, typeOfCuisineServiceList10);
        assertEquals(feedbackList, typeOfCuisineServiceList10);
        assertEquals(serviceList4, typeOfCuisineServiceList10);
        assertEquals(accountList, typeOfCuisineServiceList10);
        assertEquals(tourList, typeOfCuisineServiceList10);
        assertEquals(userBookingList, typeOfCuisineServiceList10);
        assertEquals(serviceList5, typeOfCuisineServiceList10);
        assertEquals(partnerList2, typeOfCuisineServiceList10);
        assertEquals(serviceList6, typeOfCuisineServiceList10);
        assertEquals(serviceList7, typeOfCuisineServiceList10);
        assertEquals(postList3, typeOfCuisineServiceList10);
        assertEquals(roomList3, typeOfCuisineServiceList10);
        assertEquals(serviceList8, typeOfCuisineServiceList10);
        assertEquals(postList2, typeOfCuisineServiceList10);
        assertEquals(typeOfCuisineServiceList2, typeOfCuisineServiceList10);
        assertEquals(partnerList3, typeOfCuisineServiceList10);
        assertEquals(serviceList9, typeOfCuisineServiceList10);
        assertEquals(utilitiesServiceList2, typeOfCuisineServiceList10);
        assertEquals(typeOfCuisineServiceList3, typeOfCuisineServiceList10);
        assertEquals(partnerList4, typeOfCuisineServiceList10);
        assertEquals(serviceList10, typeOfCuisineServiceList10);
        assertEquals(utilitiesServiceList3, typeOfCuisineServiceList10);
        assertEquals(typeOfCuisineServiceList4, typeOfCuisineServiceList10);
        assertEquals(roomList5, typeOfCuisineServiceList10);
        assertEquals(roomList4, typeOfCuisineServiceList10);
        assertEquals(serviceList11, typeOfCuisineServiceList10);
        assertEquals(postList4, typeOfCuisineServiceList10);
        assertEquals(typeOfCuisineServiceList5, typeOfCuisineServiceList10);
        assertEquals(partnerList5, typeOfCuisineServiceList10);
        assertEquals(serviceList12, typeOfCuisineServiceList10);
        assertEquals(utilitiesServiceList4, typeOfCuisineServiceList10);
        assertEquals(roomList6, typeOfCuisineServiceList10);
        assertEquals(serviceList13, typeOfCuisineServiceList10);
        assertEquals(postList5, typeOfCuisineServiceList10);
        assertEquals(typeOfCuisineServiceList6, typeOfCuisineServiceList10);
        assertEquals(partnerList6, typeOfCuisineServiceList10);
        assertEquals(serviceList14, typeOfCuisineServiceList10);
        assertEquals(utilitiesServiceList5, typeOfCuisineServiceList10);
        assertEquals(commentList1, typeOfCuisineServiceList10);
        assertEquals(feedbackList1, typeOfCuisineServiceList10);
        assertEquals(serviceList15, typeOfCuisineServiceList10);
        assertEquals(accountList1, typeOfCuisineServiceList10);
        assertEquals(tourList1, typeOfCuisineServiceList10);
        assertEquals(userBookingList1, typeOfCuisineServiceList10);
        assertEquals(serviceList16, typeOfCuisineServiceList10);
        assertEquals(partnerList7, typeOfCuisineServiceList10);
        assertEquals(serviceList17, typeOfCuisineServiceList10);
        assertEquals(serviceList18, typeOfCuisineServiceList10);
        assertEquals(postList7, typeOfCuisineServiceList10);
        assertEquals(roomList7, typeOfCuisineServiceList10);
        assertEquals(serviceList19, typeOfCuisineServiceList10);
        assertEquals(postList6, typeOfCuisineServiceList10);
        assertEquals(typeOfCuisineServiceList7, typeOfCuisineServiceList10);
        assertEquals(partnerList8, typeOfCuisineServiceList10);
        assertEquals(serviceList20, typeOfCuisineServiceList10);
        assertEquals(utilitiesServiceList6, typeOfCuisineServiceList10);
        assertEquals(typeOfCuisineServiceList8, typeOfCuisineServiceList10);
        assertEquals(partnerList9, typeOfCuisineServiceList10);
        assertEquals(serviceList21, typeOfCuisineServiceList10);
        assertEquals(utilitiesServiceList7, typeOfCuisineServiceList10);
        List<TypeOfCuisineService> typeOfCuisineServiceList11 = restaurant8.getTypeOfCuisineServiceList();
        assertSame(typeOfCuisineServiceList8, typeOfCuisineServiceList11);
        assertEquals(roomList1, typeOfCuisineServiceList11);
        assertEquals(roomList, typeOfCuisineServiceList11);
        assertEquals(serviceList, typeOfCuisineServiceList11);
        assertEquals(postList, typeOfCuisineServiceList11);
        assertEquals(typeOfCuisineServiceList, typeOfCuisineServiceList11);
        assertEquals(partnerList, typeOfCuisineServiceList11);
        assertEquals(serviceList1, typeOfCuisineServiceList11);
        assertEquals(utilitiesServiceList, typeOfCuisineServiceList11);
        assertEquals(roomList2, typeOfCuisineServiceList11);
        assertEquals(serviceList2, typeOfCuisineServiceList11);
        assertEquals(postList1, typeOfCuisineServiceList11);
        assertEquals(typeOfCuisineServiceList1, typeOfCuisineServiceList11);
        assertEquals(partnerList1, typeOfCuisineServiceList11);
        assertEquals(serviceList3, typeOfCuisineServiceList11);
        assertEquals(utilitiesServiceList1, typeOfCuisineServiceList11);
        assertEquals(commentList, typeOfCuisineServiceList11);
        assertEquals(feedbackList, typeOfCuisineServiceList11);
        assertEquals(serviceList4, typeOfCuisineServiceList11);
        assertEquals(accountList, typeOfCuisineServiceList11);
        assertEquals(tourList, typeOfCuisineServiceList11);
        assertEquals(userBookingList, typeOfCuisineServiceList11);
        assertEquals(serviceList5, typeOfCuisineServiceList11);
        assertEquals(partnerList2, typeOfCuisineServiceList11);
        assertEquals(serviceList6, typeOfCuisineServiceList11);
        assertEquals(serviceList7, typeOfCuisineServiceList11);
        assertEquals(postList3, typeOfCuisineServiceList11);
        assertEquals(roomList3, typeOfCuisineServiceList11);
        assertEquals(serviceList8, typeOfCuisineServiceList11);
        assertEquals(postList2, typeOfCuisineServiceList11);
        assertEquals(typeOfCuisineServiceList2, typeOfCuisineServiceList11);
        assertEquals(partnerList3, typeOfCuisineServiceList11);
        assertEquals(serviceList9, typeOfCuisineServiceList11);
        assertEquals(utilitiesServiceList2, typeOfCuisineServiceList11);
        assertEquals(typeOfCuisineServiceList3, typeOfCuisineServiceList11);
        assertEquals(partnerList4, typeOfCuisineServiceList11);
        assertEquals(serviceList10, typeOfCuisineServiceList11);
        assertEquals(utilitiesServiceList3, typeOfCuisineServiceList11);
        assertEquals(typeOfCuisineServiceList4, typeOfCuisineServiceList11);
        assertEquals(roomList4, typeOfCuisineServiceList11);
        assertEquals(serviceList11, typeOfCuisineServiceList11);
        assertEquals(postList4, typeOfCuisineServiceList11);
        assertEquals(typeOfCuisineServiceList5, typeOfCuisineServiceList11);
        assertEquals(partnerList5, typeOfCuisineServiceList11);
        assertEquals(serviceList12, typeOfCuisineServiceList11);
        assertEquals(utilitiesServiceList4, typeOfCuisineServiceList11);
        assertEquals(roomList6, typeOfCuisineServiceList11);
        assertEquals(serviceList13, typeOfCuisineServiceList11);
        assertEquals(postList5, typeOfCuisineServiceList11);
        assertEquals(typeOfCuisineServiceList6, typeOfCuisineServiceList11);
        assertEquals(partnerList6, typeOfCuisineServiceList11);
        assertEquals(serviceList14, typeOfCuisineServiceList11);
        assertEquals(utilitiesServiceList5, typeOfCuisineServiceList11);
        assertEquals(commentList1, typeOfCuisineServiceList11);
        assertEquals(feedbackList1, typeOfCuisineServiceList11);
        assertEquals(serviceList15, typeOfCuisineServiceList11);
        assertEquals(accountList1, typeOfCuisineServiceList11);
        assertEquals(tourList1, typeOfCuisineServiceList11);
        assertEquals(userBookingList1, typeOfCuisineServiceList11);
        assertEquals(serviceList16, typeOfCuisineServiceList11);
        assertEquals(partnerList7, typeOfCuisineServiceList11);
        assertEquals(serviceList17, typeOfCuisineServiceList11);
        assertEquals(serviceList18, typeOfCuisineServiceList11);
        assertEquals(roomList7, typeOfCuisineServiceList11);
        assertEquals(serviceList19, typeOfCuisineServiceList11);
        assertEquals(postList6, typeOfCuisineServiceList11);
        assertEquals(typeOfCuisineServiceList7, typeOfCuisineServiceList11);
        assertEquals(partnerList8, typeOfCuisineServiceList11);
        assertEquals(serviceList20, typeOfCuisineServiceList11);
        assertEquals(utilitiesServiceList6, typeOfCuisineServiceList11);
        assertEquals(typeOfCuisineServiceList10, typeOfCuisineServiceList11);
        assertEquals(serviceId.getPostList(), typeOfCuisineServiceList11);
        assertEquals(serviceId.getUtilitiesServiceList(), typeOfCuisineServiceList11);
        ServiceCategory serviceCategoryId = serviceId.getServiceCategoryId();
        assertEquals(serviceCategoryId.getPartnerList(), typeOfCuisineServiceList11);
        assertEquals(serviceCategoryId.getServiceList(), typeOfCuisineServiceList11);
        assertEquals(serviceId.getAccommodation().getRoomList(), typeOfCuisineServiceList11);
    }
}

