package com.example.wetravel.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Test;

class TourDetailTest {
    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link TourDetail#TourDetail()}
     *   <li>{@link TourDetail#setAddressStart(String)}
     *   <li>{@link TourDetail#setDescription(String)}
     *   <li>{@link TourDetail#setGeneralTerms(String)}
     *   <li>{@link TourDetail#setLatitude(Float)}
     *   <li>{@link TourDetail#setLongitude(Float)}
     *   <li>{@link TourDetail#setMoreDescription(String)}
     *   <li>{@link TourDetail#setTagOfTourList(List)}
     *   <li>{@link TourDetail#setTourDetailId(Long)}
     *   <li>{@link TourDetail#setTourId(Tour)}
     *   <li>{@link TourDetail#setTourInclude(String)}
     *   <li>{@link TourDetail#setTourIntroduce(String)}
     *   <li>{@link TourDetail#setTourNonInclude(String)}
     *   <li>{@link TourDetail#getAddressStart()}
     *   <li>{@link TourDetail#getTourId()}
     *   <li>{@link TourDetail#getDescription()}
     *   <li>{@link TourDetail#getGeneralTerms()}
     *   <li>{@link TourDetail#getLatitude()}
     *   <li>{@link TourDetail#getLongitude()}
     *   <li>{@link TourDetail#getMoreDescription()}
     *   <li>{@link TourDetail#getTagOfTourList()}
     *   <li>{@link TourDetail#getTourDetailId()}
     *   <li>{@link TourDetail#getTourInclude()}
     *   <li>{@link TourDetail#getTourIntroduce()}
     *   <li>{@link TourDetail#getTourNonInclude()}
     * </ul>
     */
    @Test
    void testConstructor() {
        TourDetail actualTourDetail = new TourDetail();
        actualTourDetail.setAddressStart("42 Main St");
        actualTourDetail.setDescription("The characteristics of someone or something");
        actualTourDetail.setGeneralTerms("General Terms");
        actualTourDetail.setLatitude(10.0f);
        actualTourDetail.setLongitude(10.0f);
        actualTourDetail.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList = new ArrayList<>();
        actualTourDetail.setTagOfTourList(tagOfTourList);
        actualTourDetail.setTourDetailId(123L);
        Account account = new Account();
        account.setAccountId(1234567890L);
        ArrayList<Comment> commentList = new ArrayList<>();
        account.setCommentList(commentList);
        account.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList = new ArrayList<>();
        account.setFeedbackList(feedbackList);
        account.setIsBlock(true);
        account.setPartner(new Partner());
        account.setPassWord("Pass Word");
        account.setRoleId(new Role());
        ArrayList<Tour> tourList = new ArrayList<>();
        account.setTourList(tourList);
        account.setUser(new User());
        ArrayList<UserBooking> userBookingList = new ArrayList<>();
        account.setUserBookingList(userBookingList);
        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(new Partner());
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");
        ServiceCategory serviceCategory = new ServiceCategory();
        ArrayList<Partner> partnerList = new ArrayList<>();
        serviceCategory.setPartnerList(partnerList);
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList = new ArrayList<>();
        serviceCategory.setServiceList(serviceList);
        Partner partner = new Partner();
        partner.setAccountId(account);
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(companyPartner);
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(serviceCategory);
        ArrayList<Service> serviceList1 = new ArrayList<>();
        partner.setServiceList(serviceList1);
        Role role = new Role();
        ArrayList<Account> accountList = new ArrayList<>();
        role.setAccountList(accountList);
        role.setRoleId(123);
        role.setRoleName("Role Name");
        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        ArrayList<Comment> commentList1 = new ArrayList<>();
        account1.setCommentList(commentList1);
        account1.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList1 = new ArrayList<>();
        account1.setFeedbackList(feedbackList1);
        account1.setIsBlock(true);
        account1.setPartner(new Partner());
        account1.setPassWord("Pass Word");
        account1.setRoleId(new Role());
        ArrayList<Tour> tourList1 = new ArrayList<>();
        account1.setTourList(tourList1);
        account1.setUser(new User());
        ArrayList<UserBooking> userBookingList1 = new ArrayList<>();
        account1.setUserBookingList(userBookingList1);
        User user = new User();
        user.setAccountId(account1);
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);
        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        ArrayList<Comment> commentList2 = new ArrayList<>();
        account2.setCommentList(commentList2);
        account2.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList2 = new ArrayList<>();
        account2.setFeedbackList(feedbackList2);
        account2.setIsBlock(true);
        account2.setPartner(partner);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role);
        ArrayList<Tour> tourList2 = new ArrayList<>();
        account2.setTourList(tourList2);
        account2.setUser(user);
        ArrayList<UserBooking> userBookingList2 = new ArrayList<>();
        account2.setUserBookingList(userBookingList2);
        TourCategory tourCategory = new TourCategory();
        tourCategory.setTourCategoryId(123L);
        tourCategory.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList3 = new ArrayList<>();
        tourCategory.setTourList(tourList3);
        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        ArrayList<Comment> commentList3 = new ArrayList<>();
        account3.setCommentList(commentList3);
        account3.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList3 = new ArrayList<>();
        account3.setFeedbackList(feedbackList3);
        account3.setIsBlock(true);
        account3.setPartner(new Partner());
        account3.setPassWord("Pass Word");
        account3.setRoleId(new Role());
        ArrayList<Tour> tourList4 = new ArrayList<>();
        account3.setTourList(tourList4);
        account3.setUser(new User());
        ArrayList<UserBooking> userBookingList3 = new ArrayList<>();
        account3.setUserBookingList(userBookingList3);
        TourCategory tourCategory1 = new TourCategory();
        tourCategory1.setTourCategoryId(123L);
        tourCategory1.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList5 = new ArrayList<>();
        tourCategory1.setTourList(tourList5);
        TourDetail tourDetail = new TourDetail();
        tourDetail.setAddressStart("42 Main St");
        tourDetail.setDescription("The characteristics of someone or something");
        tourDetail.setGeneralTerms("General Terms");
        tourDetail.setLatitude(10.0f);
        tourDetail.setLongitude(10.0f);
        tourDetail.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList1 = new ArrayList<>();
        tourDetail.setTagOfTourList(tagOfTourList1);
        tourDetail.setTourDetailId(123L);
        tourDetail.setTourId(new Tour());
        tourDetail.setTourInclude("Tour Include");
        tourDetail.setTourIntroduce("Tour Introduce");
        tourDetail.setTourNonInclude("Tour Non Include");
        Tour tour = new Tour();
        tour.setAccountId(account3);
        tour.setDeposit(10.0f);
        tour.setEndPlace("End Place");
        tour.setEndTime(LocalTime.of(1, 1));
        ArrayList<Feedback> feedbackList4 = new ArrayList<>();
        tour.setFeedbackList(feedbackList4);
        tour.setMaxAdult(3);
        tour.setMaxChildren(3);
        tour.setMinAdult(1);
        tour.setMinChildren(1);
        tour.setMinToStart(1);
        tour.setNote("Note");
        tour.setNumberOfDay(10);
        tour.setNumberOfNight(10);
        tour.setPriceAdult(10.0f);
        tour.setPriceChildren(10.0f);
        tour.setStartDate(LocalDate.ofEpochDay(1L));
        tour.setStartPlace("Start Place");
        tour.setStartTime(LocalTime.of(1, 1));
        tour.setStatus(1);
        tour.setTotalPrice(10.0f);
        tour.setTourCategoryId(tourCategory1);
        tour.setTourCode("Tour Code");
        tour.setTourDetail(tourDetail);
        tour.setTourId(123L);
        tour.setTourMode(true);
        tour.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList = new ArrayList<>();
        tour.setTourScheduleList(tourScheduleList);
        tour.setTourType(1);
        ArrayList<UserBooking> userBookingList4 = new ArrayList<>();
        tour.setUserBookingList(userBookingList4);
        TourDetail tourDetail1 = new TourDetail();
        tourDetail1.setAddressStart("42 Main St");
        tourDetail1.setDescription("The characteristics of someone or something");
        tourDetail1.setGeneralTerms("General Terms");
        tourDetail1.setLatitude(10.0f);
        tourDetail1.setLongitude(10.0f);
        tourDetail1.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList2 = new ArrayList<>();
        tourDetail1.setTagOfTourList(tagOfTourList2);
        tourDetail1.setTourDetailId(123L);
        tourDetail1.setTourId(tour);
        tourDetail1.setTourInclude("Tour Include");
        tourDetail1.setTourIntroduce("Tour Introduce");
        tourDetail1.setTourNonInclude("Tour Non Include");
        Tour tour1 = new Tour();
        tour1.setAccountId(account2);
        tour1.setDeposit(10.0f);
        tour1.setEndPlace("End Place");
        tour1.setEndTime(LocalTime.of(1, 1));
        ArrayList<Feedback> feedbackList5 = new ArrayList<>();
        tour1.setFeedbackList(feedbackList5);
        tour1.setMaxAdult(3);
        tour1.setMaxChildren(3);
        tour1.setMinAdult(1);
        tour1.setMinChildren(1);
        tour1.setMinToStart(1);
        tour1.setNote("Note");
        tour1.setNumberOfDay(10);
        tour1.setNumberOfNight(10);
        tour1.setPriceAdult(10.0f);
        tour1.setPriceChildren(10.0f);
        tour1.setStartDate(LocalDate.ofEpochDay(1L));
        tour1.setStartPlace("Start Place");
        tour1.setStartTime(LocalTime.of(1, 1));
        tour1.setStatus(1);
        tour1.setTotalPrice(10.0f);
        tour1.setTourCategoryId(tourCategory);
        tour1.setTourCode("Tour Code");
        tour1.setTourDetail(tourDetail1);
        tour1.setTourId(123L);
        tour1.setTourMode(true);
        tour1.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList1 = new ArrayList<>();
        tour1.setTourScheduleList(tourScheduleList1);
        tour1.setTourType(1);
        ArrayList<UserBooking> userBookingList5 = new ArrayList<>();
        tour1.setUserBookingList(userBookingList5);
        actualTourDetail.setTourId(tour1);
        actualTourDetail.setTourInclude("Tour Include");
        actualTourDetail.setTourIntroduce("Tour Introduce");
        actualTourDetail.setTourNonInclude("Tour Non Include");
        assertEquals("42 Main St", actualTourDetail.getAddressStart());
        Tour tourId = actualTourDetail.getTourId();
        TourDetail tourDetail2 = tourId.getTourDetail();
        assertEquals("42 Main St", tourDetail2.getAddressStart());
        assertEquals("The characteristics of someone or something", actualTourDetail.getDescription());
        assertEquals("The characteristics of someone or something", tourDetail2.getDescription());
        assertEquals("General Terms", actualTourDetail.getGeneralTerms());
        assertEquals("General Terms", tourDetail2.getGeneralTerms());
        assertEquals(10.0f, actualTourDetail.getLatitude().floatValue());
        assertEquals(10.0f, tourDetail2.getLatitude().floatValue());
        assertEquals(10.0f, actualTourDetail.getLongitude().floatValue());
        assertEquals(10.0f, tourDetail2.getLongitude().floatValue());
        assertEquals("More Description", actualTourDetail.getMoreDescription());
        assertEquals("More Description", tourDetail2.getMoreDescription());
        List<TagOfTour> tagOfTourList3 = actualTourDetail.getTagOfTourList();
        assertSame(tagOfTourList, tagOfTourList3);
        assertEquals(commentList2, tagOfTourList3);
        assertEquals(feedbackList2, tagOfTourList3);
        assertEquals(commentList, tagOfTourList3);
        assertEquals(feedbackList, tagOfTourList3);
        assertEquals(tourList, tagOfTourList3);
        assertEquals(userBookingList, tagOfTourList3);
        assertEquals(partnerList, tagOfTourList3);
        assertEquals(serviceList, tagOfTourList3);
        assertEquals(serviceList1, tagOfTourList3);
        assertEquals(accountList, tagOfTourList3);
        assertEquals(tourList2, tagOfTourList3);
        assertEquals(commentList1, tagOfTourList3);
        assertEquals(feedbackList1, tagOfTourList3);
        assertEquals(tourList1, tagOfTourList3);
        assertEquals(userBookingList1, tagOfTourList3);
        assertEquals(userBookingList2, tagOfTourList3);
        assertEquals(feedbackList5, tagOfTourList3);
        assertEquals(tourList3, tagOfTourList3);
        assertEquals(tagOfTourList2, tagOfTourList3);
        assertEquals(commentList3, tagOfTourList3);
        assertEquals(feedbackList3, tagOfTourList3);
        assertEquals(tourList4, tagOfTourList3);
        assertEquals(userBookingList3, tagOfTourList3);
        assertEquals(feedbackList4, tagOfTourList3);
        assertEquals(tourList5, tagOfTourList3);
        assertEquals(tagOfTourList1, tagOfTourList3);
        assertEquals(tourScheduleList, tagOfTourList3);
        assertEquals(userBookingList4, tagOfTourList3);
        assertEquals(tourScheduleList1, tagOfTourList3);
        assertEquals(userBookingList5, tagOfTourList3);
        List<TagOfTour> tagOfTourList4 = tourDetail2.getTagOfTourList();
        assertSame(tagOfTourList2, tagOfTourList4);
        assertEquals(commentList2, tagOfTourList4);
        assertEquals(feedbackList2, tagOfTourList4);
        assertEquals(commentList, tagOfTourList4);
        assertEquals(feedbackList, tagOfTourList4);
        assertEquals(tourList, tagOfTourList4);
        assertEquals(userBookingList, tagOfTourList4);
        assertEquals(partnerList, tagOfTourList4);
        assertEquals(serviceList, tagOfTourList4);
        assertEquals(serviceList1, tagOfTourList4);
        assertEquals(accountList, tagOfTourList4);
        assertEquals(tourList2, tagOfTourList4);
        assertEquals(commentList1, tagOfTourList4);
        assertEquals(feedbackList1, tagOfTourList4);
        assertEquals(tourList1, tagOfTourList4);
        assertEquals(userBookingList1, tagOfTourList4);
        assertEquals(userBookingList2, tagOfTourList4);
        assertEquals(tourList3, tagOfTourList4);
        assertEquals(commentList3, tagOfTourList4);
        assertEquals(feedbackList3, tagOfTourList4);
        assertEquals(tourList4, tagOfTourList4);
        assertEquals(userBookingList3, tagOfTourList4);
        assertEquals(feedbackList4, tagOfTourList4);
        assertEquals(tourList5, tagOfTourList4);
        assertEquals(tagOfTourList1, tagOfTourList4);
        assertEquals(tourScheduleList, tagOfTourList4);
        assertEquals(userBookingList4, tagOfTourList4);
        assertEquals(tagOfTourList3, tagOfTourList4);
        assertEquals(tourId.getFeedbackList(), tagOfTourList4);
        assertEquals(tourId.getTourScheduleList(), tagOfTourList4);
        assertEquals(tourId.getUserBookingList(), tagOfTourList4);
        assertEquals(123L, actualTourDetail.getTourDetailId().longValue());
        assertSame(tour1, tourId);
        assertEquals("Tour Include", actualTourDetail.getTourInclude());
        assertEquals("Tour Introduce", actualTourDetail.getTourIntroduce());
        assertEquals("Tour Non Include", actualTourDetail.getTourNonInclude());
    }

    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link TourDetail#TourDetail(Long, String, String, String, String, String, String, String, Float, Float, Tour, List)}
     *   <li>{@link TourDetail#TourDetail()}
     *   <li>{@link TourDetail#setAddressStart(String)}
     *   <li>{@link TourDetail#setDescription(String)}
     *   <li>{@link TourDetail#setGeneralTerms(String)}
     *   <li>{@link TourDetail#setLatitude(Float)}
     *   <li>{@link TourDetail#setLongitude(Float)}
     *   <li>{@link TourDetail#setMoreDescription(String)}
     *   <li>{@link TourDetail#setTagOfTourList(List)}
     *   <li>{@link TourDetail#setTourDetailId(Long)}
     *   <li>{@link TourDetail#setTourId(Tour)}
     *   <li>{@link TourDetail#setTourInclude(String)}
     *   <li>{@link TourDetail#setTourIntroduce(String)}
     *   <li>{@link TourDetail#setTourNonInclude(String)}
     *   <li>{@link TourDetail#getAddressStart()}
     *   <li>{@link TourDetail#getTourId()}
     *   <li>{@link TourDetail#getDescription()}
     *   <li>{@link TourDetail#getGeneralTerms()}
     *   <li>{@link TourDetail#getLatitude()}
     *   <li>{@link TourDetail#getLongitude()}
     *   <li>{@link TourDetail#getMoreDescription()}
     *   <li>{@link TourDetail#getTagOfTourList()}
     *   <li>{@link TourDetail#getTourDetailId()}
     *   <li>{@link TourDetail#getTourInclude()}
     *   <li>{@link TourDetail#getTourIntroduce()}
     *   <li>{@link TourDetail#getTourNonInclude()}
     * </ul>
     */
    @Test
    void testConstructor2() {
        Account account = new Account();
        account.setAccountId(1234567890L);
        ArrayList<Comment> commentList = new ArrayList<>();
        account.setCommentList(commentList);
        account.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList = new ArrayList<>();
        account.setFeedbackList(feedbackList);
        account.setIsBlock(true);
        account.setPartner(new Partner());
        account.setPassWord("Pass Word");
        account.setRoleId(new Role());
        ArrayList<Tour> tourList = new ArrayList<>();
        account.setTourList(tourList);
        account.setUser(new User());
        ArrayList<UserBooking> userBookingList = new ArrayList<>();
        account.setUserBookingList(userBookingList);

        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(new Partner());
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");

        ServiceCategory serviceCategory = new ServiceCategory();
        ArrayList<Partner> partnerList = new ArrayList<>();
        serviceCategory.setPartnerList(partnerList);
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList = new ArrayList<>();
        serviceCategory.setServiceList(serviceList);

        Partner partner = new Partner();
        partner.setAccountId(account);
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(companyPartner);
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(serviceCategory);
        ArrayList<Service> serviceList1 = new ArrayList<>();
        partner.setServiceList(serviceList1);

        Role role = new Role();
        ArrayList<Account> accountList = new ArrayList<>();
        role.setAccountList(accountList);
        role.setRoleId(123);
        role.setRoleName("Role Name");

        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        ArrayList<Comment> commentList1 = new ArrayList<>();
        account1.setCommentList(commentList1);
        account1.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList1 = new ArrayList<>();
        account1.setFeedbackList(feedbackList1);
        account1.setIsBlock(true);
        account1.setPartner(new Partner());
        account1.setPassWord("Pass Word");
        account1.setRoleId(new Role());
        ArrayList<Tour> tourList1 = new ArrayList<>();
        account1.setTourList(tourList1);
        account1.setUser(new User());
        ArrayList<UserBooking> userBookingList1 = new ArrayList<>();
        account1.setUserBookingList(userBookingList1);

        User user = new User();
        user.setAccountId(account1);
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);

        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        ArrayList<Comment> commentList2 = new ArrayList<>();
        account2.setCommentList(commentList2);
        account2.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList2 = new ArrayList<>();
        account2.setFeedbackList(feedbackList2);
        account2.setIsBlock(true);
        account2.setPartner(partner);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role);
        ArrayList<Tour> tourList2 = new ArrayList<>();
        account2.setTourList(tourList2);
        account2.setUser(user);
        ArrayList<UserBooking> userBookingList2 = new ArrayList<>();
        account2.setUserBookingList(userBookingList2);

        TourCategory tourCategory = new TourCategory();
        tourCategory.setTourCategoryId(123L);
        tourCategory.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList3 = new ArrayList<>();
        tourCategory.setTourList(tourList3);

        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        ArrayList<Comment> commentList3 = new ArrayList<>();
        account3.setCommentList(commentList3);
        account3.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList3 = new ArrayList<>();
        account3.setFeedbackList(feedbackList3);
        account3.setIsBlock(true);
        account3.setPartner(new Partner());
        account3.setPassWord("Pass Word");
        account3.setRoleId(new Role());
        ArrayList<Tour> tourList4 = new ArrayList<>();
        account3.setTourList(tourList4);
        account3.setUser(new User());
        ArrayList<UserBooking> userBookingList3 = new ArrayList<>();
        account3.setUserBookingList(userBookingList3);

        TourCategory tourCategory1 = new TourCategory();
        tourCategory1.setTourCategoryId(123L);
        tourCategory1.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList5 = new ArrayList<>();
        tourCategory1.setTourList(tourList5);

        TourDetail tourDetail = new TourDetail();
        tourDetail.setAddressStart("42 Main St");
        tourDetail.setDescription("The characteristics of someone or something");
        tourDetail.setGeneralTerms("General Terms");
        tourDetail.setLatitude(10.0f);
        tourDetail.setLongitude(10.0f);
        tourDetail.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList = new ArrayList<>();
        tourDetail.setTagOfTourList(tagOfTourList);
        tourDetail.setTourDetailId(123L);
        tourDetail.setTourId(new Tour());
        tourDetail.setTourInclude("Tour Include");
        tourDetail.setTourIntroduce("Tour Introduce");
        tourDetail.setTourNonInclude("Tour Non Include");

        Tour tour = new Tour();
        tour.setAccountId(account3);
        tour.setDeposit(10.0f);
        tour.setEndPlace("End Place");
        tour.setEndTime(LocalTime.of(1, 1));
        ArrayList<Feedback> feedbackList4 = new ArrayList<>();
        tour.setFeedbackList(feedbackList4);
        tour.setMaxAdult(3);
        tour.setMaxChildren(3);
        tour.setMinAdult(1);
        tour.setMinChildren(1);
        tour.setMinToStart(1);
        tour.setNote("Note");
        tour.setNumberOfDay(10);
        tour.setNumberOfNight(10);
        tour.setPriceAdult(10.0f);
        tour.setPriceChildren(10.0f);
        tour.setStartDate(LocalDate.ofEpochDay(1L));
        tour.setStartPlace("Start Place");
        tour.setStartTime(LocalTime.of(1, 1));
        tour.setStatus(1);
        tour.setTotalPrice(10.0f);
        tour.setTourCategoryId(tourCategory1);
        tour.setTourCode("Tour Code");
        tour.setTourDetail(tourDetail);
        tour.setTourId(123L);
        tour.setTourMode(true);
        tour.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList = new ArrayList<>();
        tour.setTourScheduleList(tourScheduleList);
        tour.setTourType(1);
        ArrayList<UserBooking> userBookingList4 = new ArrayList<>();
        tour.setUserBookingList(userBookingList4);

        TourDetail tourDetail1 = new TourDetail();
        tourDetail1.setAddressStart("42 Main St");
        tourDetail1.setDescription("The characteristics of someone or something");
        tourDetail1.setGeneralTerms("General Terms");
        tourDetail1.setLatitude(10.0f);
        tourDetail1.setLongitude(10.0f);
        tourDetail1.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList1 = new ArrayList<>();
        tourDetail1.setTagOfTourList(tagOfTourList1);
        tourDetail1.setTourDetailId(123L);
        tourDetail1.setTourId(tour);
        tourDetail1.setTourInclude("Tour Include");
        tourDetail1.setTourIntroduce("Tour Introduce");
        tourDetail1.setTourNonInclude("Tour Non Include");

        Tour tour1 = new Tour();
        tour1.setAccountId(account2);
        tour1.setDeposit(10.0f);
        tour1.setEndPlace("End Place");
        tour1.setEndTime(LocalTime.of(1, 1));
        ArrayList<Feedback> feedbackList5 = new ArrayList<>();
        tour1.setFeedbackList(feedbackList5);
        tour1.setMaxAdult(3);
        tour1.setMaxChildren(3);
        tour1.setMinAdult(1);
        tour1.setMinChildren(1);
        tour1.setMinToStart(1);
        tour1.setNote("Note");
        tour1.setNumberOfDay(10);
        tour1.setNumberOfNight(10);
        tour1.setPriceAdult(10.0f);
        tour1.setPriceChildren(10.0f);
        tour1.setStartDate(LocalDate.ofEpochDay(1L));
        tour1.setStartPlace("Start Place");
        tour1.setStartTime(LocalTime.of(1, 1));
        tour1.setStatus(1);
        tour1.setTotalPrice(10.0f);
        tour1.setTourCategoryId(tourCategory);
        tour1.setTourCode("Tour Code");
        tour1.setTourDetail(tourDetail1);
        tour1.setTourId(123L);
        tour1.setTourMode(true);
        tour1.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList1 = new ArrayList<>();
        tour1.setTourScheduleList(tourScheduleList1);
        tour1.setTourType(1);
        ArrayList<UserBooking> userBookingList5 = new ArrayList<>();
        tour1.setUserBookingList(userBookingList5);
        ArrayList<TagOfTour> tagOfTourList2 = new ArrayList<>();
        TourDetail actualTourDetail = new TourDetail(123L, "Tour Introduce", "Tour Include", "Tour Non Include",
                "General Terms", "42 Main St", "The characteristics of someone or something", "More Description", 10.0f,
                10.0f, tour1, tagOfTourList2);
        actualTourDetail.setAddressStart("42 Main St");
        actualTourDetail.setDescription("The characteristics of someone or something");
        actualTourDetail.setGeneralTerms("General Terms");
        actualTourDetail.setLatitude(10.0f);
        actualTourDetail.setLongitude(10.0f);
        actualTourDetail.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList3 = new ArrayList<>();
        actualTourDetail.setTagOfTourList(tagOfTourList3);
        actualTourDetail.setTourDetailId(123L);
        Account account4 = new Account();
        account4.setAccountId(1234567890L);
        ArrayList<Comment> commentList4 = new ArrayList<>();
        account4.setCommentList(commentList4);
        account4.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList6 = new ArrayList<>();
        account4.setFeedbackList(feedbackList6);
        account4.setIsBlock(true);
        account4.setPartner(new Partner());
        account4.setPassWord("Pass Word");
        account4.setRoleId(new Role());
        ArrayList<Tour> tourList6 = new ArrayList<>();
        account4.setTourList(tourList6);
        account4.setUser(new User());
        ArrayList<UserBooking> userBookingList6 = new ArrayList<>();
        account4.setUserBookingList(userBookingList6);
        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(new Partner());
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");
        ServiceCategory serviceCategory1 = new ServiceCategory();
        ArrayList<Partner> partnerList1 = new ArrayList<>();
        serviceCategory1.setPartnerList(partnerList1);
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList2 = new ArrayList<>();
        serviceCategory1.setServiceList(serviceList2);
        Partner partner1 = new Partner();
        partner1.setAccountId(account4);
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(companyPartner1);
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(serviceCategory1);
        ArrayList<Service> serviceList3 = new ArrayList<>();
        partner1.setServiceList(serviceList3);
        Role role1 = new Role();
        ArrayList<Account> accountList1 = new ArrayList<>();
        role1.setAccountList(accountList1);
        role1.setRoleId(123);
        role1.setRoleName("Role Name");
        Account account5 = new Account();
        account5.setAccountId(1234567890L);
        ArrayList<Comment> commentList5 = new ArrayList<>();
        account5.setCommentList(commentList5);
        account5.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList7 = new ArrayList<>();
        account5.setFeedbackList(feedbackList7);
        account5.setIsBlock(true);
        account5.setPartner(new Partner());
        account5.setPassWord("Pass Word");
        account5.setRoleId(new Role());
        ArrayList<Tour> tourList7 = new ArrayList<>();
        account5.setTourList(tourList7);
        account5.setUser(new User());
        ArrayList<UserBooking> userBookingList7 = new ArrayList<>();
        account5.setUserBookingList(userBookingList7);
        User user1 = new User();
        user1.setAccountId(account5);
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);
        Account account6 = new Account();
        account6.setAccountId(1234567890L);
        ArrayList<Comment> commentList6 = new ArrayList<>();
        account6.setCommentList(commentList6);
        account6.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList8 = new ArrayList<>();
        account6.setFeedbackList(feedbackList8);
        account6.setIsBlock(true);
        account6.setPartner(partner1);
        account6.setPassWord("Pass Word");
        account6.setRoleId(role1);
        ArrayList<Tour> tourList8 = new ArrayList<>();
        account6.setTourList(tourList8);
        account6.setUser(user1);
        ArrayList<UserBooking> userBookingList8 = new ArrayList<>();
        account6.setUserBookingList(userBookingList8);
        TourCategory tourCategory2 = new TourCategory();
        tourCategory2.setTourCategoryId(123L);
        tourCategory2.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList9 = new ArrayList<>();
        tourCategory2.setTourList(tourList9);
        Account account7 = new Account();
        account7.setAccountId(1234567890L);
        ArrayList<Comment> commentList7 = new ArrayList<>();
        account7.setCommentList(commentList7);
        account7.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList9 = new ArrayList<>();
        account7.setFeedbackList(feedbackList9);
        account7.setIsBlock(true);
        account7.setPartner(new Partner());
        account7.setPassWord("Pass Word");
        account7.setRoleId(new Role());
        ArrayList<Tour> tourList10 = new ArrayList<>();
        account7.setTourList(tourList10);
        account7.setUser(new User());
        ArrayList<UserBooking> userBookingList9 = new ArrayList<>();
        account7.setUserBookingList(userBookingList9);
        TourCategory tourCategory3 = new TourCategory();
        tourCategory3.setTourCategoryId(123L);
        tourCategory3.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList11 = new ArrayList<>();
        tourCategory3.setTourList(tourList11);
        TourDetail tourDetail2 = new TourDetail();
        tourDetail2.setAddressStart("42 Main St");
        tourDetail2.setDescription("The characteristics of someone or something");
        tourDetail2.setGeneralTerms("General Terms");
        tourDetail2.setLatitude(10.0f);
        tourDetail2.setLongitude(10.0f);
        tourDetail2.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList4 = new ArrayList<>();
        tourDetail2.setTagOfTourList(tagOfTourList4);
        tourDetail2.setTourDetailId(123L);
        tourDetail2.setTourId(new Tour());
        tourDetail2.setTourInclude("Tour Include");
        tourDetail2.setTourIntroduce("Tour Introduce");
        tourDetail2.setTourNonInclude("Tour Non Include");
        Tour tour2 = new Tour();
        tour2.setAccountId(account7);
        tour2.setDeposit(10.0f);
        tour2.setEndPlace("End Place");
        tour2.setEndTime(LocalTime.of(1, 1));
        ArrayList<Feedback> feedbackList10 = new ArrayList<>();
        tour2.setFeedbackList(feedbackList10);
        tour2.setMaxAdult(3);
        tour2.setMaxChildren(3);
        tour2.setMinAdult(1);
        tour2.setMinChildren(1);
        tour2.setMinToStart(1);
        tour2.setNote("Note");
        tour2.setNumberOfDay(10);
        tour2.setNumberOfNight(10);
        tour2.setPriceAdult(10.0f);
        tour2.setPriceChildren(10.0f);
        tour2.setStartDate(LocalDate.ofEpochDay(1L));
        tour2.setStartPlace("Start Place");
        tour2.setStartTime(LocalTime.of(1, 1));
        tour2.setStatus(1);
        tour2.setTotalPrice(10.0f);
        tour2.setTourCategoryId(tourCategory3);
        tour2.setTourCode("Tour Code");
        tour2.setTourDetail(tourDetail2);
        tour2.setTourId(123L);
        tour2.setTourMode(true);
        tour2.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList2 = new ArrayList<>();
        tour2.setTourScheduleList(tourScheduleList2);
        tour2.setTourType(1);
        ArrayList<UserBooking> userBookingList10 = new ArrayList<>();
        tour2.setUserBookingList(userBookingList10);
        TourDetail tourDetail3 = new TourDetail();
        tourDetail3.setAddressStart("42 Main St");
        tourDetail3.setDescription("The characteristics of someone or something");
        tourDetail3.setGeneralTerms("General Terms");
        tourDetail3.setLatitude(10.0f);
        tourDetail3.setLongitude(10.0f);
        tourDetail3.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList5 = new ArrayList<>();
        tourDetail3.setTagOfTourList(tagOfTourList5);
        tourDetail3.setTourDetailId(123L);
        tourDetail3.setTourId(tour2);
        tourDetail3.setTourInclude("Tour Include");
        tourDetail3.setTourIntroduce("Tour Introduce");
        tourDetail3.setTourNonInclude("Tour Non Include");
        Tour tour3 = new Tour();
        tour3.setAccountId(account6);
        tour3.setDeposit(10.0f);
        tour3.setEndPlace("End Place");
        tour3.setEndTime(LocalTime.of(1, 1));
        ArrayList<Feedback> feedbackList11 = new ArrayList<>();
        tour3.setFeedbackList(feedbackList11);
        tour3.setMaxAdult(3);
        tour3.setMaxChildren(3);
        tour3.setMinAdult(1);
        tour3.setMinChildren(1);
        tour3.setMinToStart(1);
        tour3.setNote("Note");
        tour3.setNumberOfDay(10);
        tour3.setNumberOfNight(10);
        tour3.setPriceAdult(10.0f);
        tour3.setPriceChildren(10.0f);
        tour3.setStartDate(LocalDate.ofEpochDay(1L));
        tour3.setStartPlace("Start Place");
        tour3.setStartTime(LocalTime.of(1, 1));
        tour3.setStatus(1);
        tour3.setTotalPrice(10.0f);
        tour3.setTourCategoryId(tourCategory2);
        tour3.setTourCode("Tour Code");
        tour3.setTourDetail(tourDetail3);
        tour3.setTourId(123L);
        tour3.setTourMode(true);
        tour3.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList3 = new ArrayList<>();
        tour3.setTourScheduleList(tourScheduleList3);
        tour3.setTourType(1);
        ArrayList<UserBooking> userBookingList11 = new ArrayList<>();
        tour3.setUserBookingList(userBookingList11);
        actualTourDetail.setTourId(tour3);
        actualTourDetail.setTourInclude("Tour Include");
        actualTourDetail.setTourIntroduce("Tour Introduce");
        actualTourDetail.setTourNonInclude("Tour Non Include");
        assertEquals("42 Main St", actualTourDetail.getAddressStart());
        Tour tourId = actualTourDetail.getTourId();
        TourDetail tourDetail4 = tourId.getTourDetail();
        assertEquals("42 Main St", tourDetail4.getAddressStart());
        assertEquals("The characteristics of someone or something", actualTourDetail.getDescription());
        assertEquals("The characteristics of someone or something", tourDetail4.getDescription());
        assertEquals("General Terms", actualTourDetail.getGeneralTerms());
        assertEquals("General Terms", tourDetail4.getGeneralTerms());
        assertEquals(10.0f, actualTourDetail.getLatitude().floatValue());
        assertEquals(10.0f, tourDetail4.getLatitude().floatValue());
        assertEquals(10.0f, actualTourDetail.getLongitude().floatValue());
        assertEquals(10.0f, tourDetail4.getLongitude().floatValue());
        assertEquals("More Description", actualTourDetail.getMoreDescription());
        assertEquals("More Description", tourDetail4.getMoreDescription());
        List<TagOfTour> tagOfTourList6 = actualTourDetail.getTagOfTourList();
        assertSame(tagOfTourList3, tagOfTourList6);
        assertEquals(commentList2, tagOfTourList6);
        assertEquals(feedbackList2, tagOfTourList6);
        assertEquals(commentList, tagOfTourList6);
        assertEquals(feedbackList, tagOfTourList6);
        assertEquals(tourList, tagOfTourList6);
        assertEquals(userBookingList, tagOfTourList6);
        assertEquals(partnerList, tagOfTourList6);
        assertEquals(serviceList, tagOfTourList6);
        assertEquals(serviceList1, tagOfTourList6);
        assertEquals(accountList, tagOfTourList6);
        assertEquals(tourList2, tagOfTourList6);
        assertEquals(commentList1, tagOfTourList6);
        assertEquals(feedbackList1, tagOfTourList6);
        assertEquals(tourList1, tagOfTourList6);
        assertEquals(userBookingList1, tagOfTourList6);
        assertEquals(userBookingList2, tagOfTourList6);
        assertEquals(feedbackList5, tagOfTourList6);
        assertEquals(tourList3, tagOfTourList6);
        assertEquals(tagOfTourList1, tagOfTourList6);
        assertEquals(commentList3, tagOfTourList6);
        assertEquals(feedbackList3, tagOfTourList6);
        assertEquals(tourList4, tagOfTourList6);
        assertEquals(userBookingList3, tagOfTourList6);
        assertEquals(feedbackList4, tagOfTourList6);
        assertEquals(tourList5, tagOfTourList6);
        assertEquals(tagOfTourList, tagOfTourList6);
        assertEquals(tourScheduleList, tagOfTourList6);
        assertEquals(userBookingList4, tagOfTourList6);
        assertEquals(tourScheduleList1, tagOfTourList6);
        assertEquals(userBookingList5, tagOfTourList6);
        assertEquals(tagOfTourList2, tagOfTourList6);
        assertEquals(commentList6, tagOfTourList6);
        assertEquals(feedbackList8, tagOfTourList6);
        assertEquals(commentList4, tagOfTourList6);
        assertEquals(feedbackList6, tagOfTourList6);
        assertEquals(tourList6, tagOfTourList6);
        assertEquals(userBookingList6, tagOfTourList6);
        assertEquals(partnerList1, tagOfTourList6);
        assertEquals(serviceList2, tagOfTourList6);
        assertEquals(serviceList3, tagOfTourList6);
        assertEquals(accountList1, tagOfTourList6);
        assertEquals(tourList8, tagOfTourList6);
        assertEquals(commentList5, tagOfTourList6);
        assertEquals(feedbackList7, tagOfTourList6);
        assertEquals(tourList7, tagOfTourList6);
        assertEquals(userBookingList7, tagOfTourList6);
        assertEquals(userBookingList8, tagOfTourList6);
        assertEquals(feedbackList11, tagOfTourList6);
        assertEquals(tourList9, tagOfTourList6);
        assertEquals(tagOfTourList5, tagOfTourList6);
        assertEquals(commentList7, tagOfTourList6);
        assertEquals(feedbackList9, tagOfTourList6);
        assertEquals(tourList10, tagOfTourList6);
        assertEquals(userBookingList9, tagOfTourList6);
        assertEquals(feedbackList10, tagOfTourList6);
        assertEquals(tourList11, tagOfTourList6);
        assertEquals(tagOfTourList4, tagOfTourList6);
        assertEquals(tourScheduleList2, tagOfTourList6);
        assertEquals(userBookingList10, tagOfTourList6);
        assertEquals(tourScheduleList3, tagOfTourList6);
        assertEquals(userBookingList11, tagOfTourList6);
        List<TagOfTour> tagOfTourList7 = tourDetail4.getTagOfTourList();
        assertSame(tagOfTourList5, tagOfTourList7);
        assertEquals(commentList2, tagOfTourList7);
        assertEquals(feedbackList2, tagOfTourList7);
        assertEquals(commentList, tagOfTourList7);
        assertEquals(feedbackList, tagOfTourList7);
        assertEquals(tourList, tagOfTourList7);
        assertEquals(userBookingList, tagOfTourList7);
        assertEquals(partnerList, tagOfTourList7);
        assertEquals(serviceList, tagOfTourList7);
        assertEquals(serviceList1, tagOfTourList7);
        assertEquals(accountList, tagOfTourList7);
        assertEquals(tourList2, tagOfTourList7);
        assertEquals(commentList1, tagOfTourList7);
        assertEquals(feedbackList1, tagOfTourList7);
        assertEquals(tourList1, tagOfTourList7);
        assertEquals(userBookingList1, tagOfTourList7);
        assertEquals(userBookingList2, tagOfTourList7);
        assertEquals(feedbackList5, tagOfTourList7);
        assertEquals(tourList3, tagOfTourList7);
        assertEquals(tagOfTourList1, tagOfTourList7);
        assertEquals(commentList3, tagOfTourList7);
        assertEquals(feedbackList3, tagOfTourList7);
        assertEquals(tourList4, tagOfTourList7);
        assertEquals(userBookingList3, tagOfTourList7);
        assertEquals(feedbackList4, tagOfTourList7);
        assertEquals(tourList5, tagOfTourList7);
        assertEquals(tagOfTourList, tagOfTourList7);
        assertEquals(tourScheduleList, tagOfTourList7);
        assertEquals(userBookingList4, tagOfTourList7);
        assertEquals(tourScheduleList1, tagOfTourList7);
        assertEquals(userBookingList5, tagOfTourList7);
        assertEquals(tagOfTourList2, tagOfTourList7);
        assertEquals(commentList6, tagOfTourList7);
        assertEquals(feedbackList8, tagOfTourList7);
        assertEquals(commentList4, tagOfTourList7);
        assertEquals(feedbackList6, tagOfTourList7);
        assertEquals(tourList6, tagOfTourList7);
        assertEquals(userBookingList6, tagOfTourList7);
        assertEquals(partnerList1, tagOfTourList7);
        assertEquals(serviceList2, tagOfTourList7);
        assertEquals(serviceList3, tagOfTourList7);
        assertEquals(accountList1, tagOfTourList7);
        assertEquals(tourList8, tagOfTourList7);
        assertEquals(commentList5, tagOfTourList7);
        assertEquals(feedbackList7, tagOfTourList7);
        assertEquals(tourList7, tagOfTourList7);
        assertEquals(userBookingList7, tagOfTourList7);
        assertEquals(userBookingList8, tagOfTourList7);
        assertEquals(tourList9, tagOfTourList7);
        assertEquals(commentList7, tagOfTourList7);
        assertEquals(feedbackList9, tagOfTourList7);
        assertEquals(tourList10, tagOfTourList7);
        assertEquals(userBookingList9, tagOfTourList7);
        assertEquals(feedbackList10, tagOfTourList7);
        assertEquals(tourList11, tagOfTourList7);
        assertEquals(tagOfTourList4, tagOfTourList7);
        assertEquals(tourScheduleList2, tagOfTourList7);
        assertEquals(userBookingList10, tagOfTourList7);
        assertEquals(tagOfTourList6, tagOfTourList7);
        assertEquals(tourId.getFeedbackList(), tagOfTourList7);
        assertEquals(tourId.getTourScheduleList(), tagOfTourList7);
        assertEquals(tourId.getUserBookingList(), tagOfTourList7);
        assertEquals(123L, actualTourDetail.getTourDetailId().longValue());
        assertSame(tour3, tourId);
        assertEquals("Tour Include", actualTourDetail.getTourInclude());
        assertEquals("Tour Introduce", actualTourDetail.getTourIntroduce());
        assertEquals("Tour Non Include", actualTourDetail.getTourNonInclude());
    }
}

