package com.example.wetravel.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Test;

class TourTest {
    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link Tour#Tour()}
     *   <li>{@link Tour#setAccountId(Account)}
     *   <li>{@link Tour#setDeposit(Float)}
     *   <li>{@link Tour#setEndPlace(String)}
     *   <li>{@link Tour#setEndTime(LocalTime)}
     *   <li>{@link Tour#setFeedbackList(List)}
     *   <li>{@link Tour#setMaxAdult(Integer)}
     *   <li>{@link Tour#setMaxChildren(Integer)}
     *   <li>{@link Tour#setMinAdult(Integer)}
     *   <li>{@link Tour#setMinChildren(Integer)}
     *   <li>{@link Tour#setMinToStart(Integer)}
     *   <li>{@link Tour#setNote(String)}
     *   <li>{@link Tour#setNumberOfDay(Integer)}
     *   <li>{@link Tour#setNumberOfNight(Integer)}
     *   <li>{@link Tour#setPriceAdult(Float)}
     *   <li>{@link Tour#setPriceChildren(Float)}
     *   <li>{@link Tour#setStartDate(LocalDate)}
     *   <li>{@link Tour#setStartPlace(String)}
     *   <li>{@link Tour#setStartTime(LocalTime)}
     *   <li>{@link Tour#setStatus(Integer)}
     *   <li>{@link Tour#setTotalPrice(Float)}
     *   <li>{@link Tour#setTourCategoryId(TourCategory)}
     *   <li>{@link Tour#setTourCode(String)}
     *   <li>{@link Tour#setTourDetail(TourDetail)}
     *   <li>{@link Tour#setTourId(Long)}
     *   <li>{@link Tour#setTourMode(Boolean)}
     *   <li>{@link Tour#setTourName(String)}
     *   <li>{@link Tour#setTourScheduleList(List)}
     *   <li>{@link Tour#setTourType(Integer)}
     *   <li>{@link Tour#setUserBookingList(List)}
     *   <li>{@link Tour#getAccountId()}
     *   <li>{@link Tour#getDeposit()}
     *   <li>{@link Tour#getEndPlace()}
     *   <li>{@link Tour#getEndTime()}
     *   <li>{@link Tour#getFeedbackList()}
     *   <li>{@link Tour#getUserBookingList()}
     *   <li>{@link Tour#getMaxAdult()}
     *   <li>{@link Tour#getMaxChildren()}
     *   <li>{@link Tour#getMinAdult()}
     *   <li>{@link Tour#getMinChildren()}
     *   <li>{@link Tour#getMinToStart()}
     *   <li>{@link Tour#getNote()}
     *   <li>{@link Tour#getNumberOfDay()}
     *   <li>{@link Tour#getNumberOfNight()}
     *   <li>{@link Tour#getPriceAdult()}
     *   <li>{@link Tour#getPriceChildren()}
     *   <li>{@link Tour#getStartDate()}
     *   <li>{@link Tour#getStartPlace()}
     *   <li>{@link Tour#getStartTime()}
     *   <li>{@link Tour#getStatus()}
     *   <li>{@link Tour#getTotalPrice()}
     *   <li>{@link Tour#getTourCategoryId()}
     *   <li>{@link Tour#getTourCode()}
     *   <li>{@link Tour#getTourDetail()}
     *   <li>{@link Tour#getTourId()}
     *   <li>{@link Tour#getTourMode()}
     *   <li>{@link Tour#getTourName()}
     *   <li>{@link Tour#getTourScheduleList()}
     *   <li>{@link Tour#getTourType()}
     * </ul>
     */
    @Test
    void testConstructor() {
        Tour actualTour = new Tour();
        Partner partner = new Partner();
        partner.setAccountId(new Account());
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(new CompanyPartner());
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList = new ArrayList<>();
        partner.setServiceList(serviceList);
        Role role = new Role();
        ArrayList<Account> accountList = new ArrayList<>();
        role.setAccountList(accountList);
        role.setRoleId(123);
        role.setRoleName("Role Name");
        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);
        Account account = new Account();
        account.setAccountId(1234567890L);
        ArrayList<Comment> commentList = new ArrayList<>();
        account.setCommentList(commentList);
        account.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList = new ArrayList<>();
        account.setFeedbackList(feedbackList);
        account.setIsBlock(true);
        account.setPartner(partner);
        account.setPassWord("Pass Word");
        account.setRoleId(role);
        ArrayList<Tour> tourList = new ArrayList<>();
        account.setTourList(tourList);
        account.setUser(user);
        ArrayList<UserBooking> userBookingList = new ArrayList<>();
        account.setUserBookingList(userBookingList);
        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList1 = new ArrayList<>();
        partner1.setServiceList(serviceList1);
        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(partner1);
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");
        ServiceCategory serviceCategory = new ServiceCategory();
        ArrayList<Partner> partnerList = new ArrayList<>();
        serviceCategory.setPartnerList(partnerList);
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList2 = new ArrayList<>();
        serviceCategory.setServiceList(serviceList2);
        Partner partner2 = new Partner();
        partner2.setAccountId(account);
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(companyPartner);
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(serviceCategory);
        ArrayList<Service> serviceList3 = new ArrayList<>();
        partner2.setServiceList(serviceList3);
        Role role1 = new Role();
        ArrayList<Account> accountList1 = new ArrayList<>();
        role1.setAccountList(accountList1);
        role1.setRoleId(123);
        role1.setRoleName("Role Name");
        Partner partner3 = new Partner();
        partner3.setAccountId(new Account());
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(new CompanyPartner());
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList4 = new ArrayList<>();
        partner3.setServiceList(serviceList4);
        Role role2 = new Role();
        ArrayList<Account> accountList2 = new ArrayList<>();
        role2.setAccountList(accountList2);
        role2.setRoleId(123);
        role2.setRoleName("Role Name");
        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);
        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        ArrayList<Comment> commentList1 = new ArrayList<>();
        account1.setCommentList(commentList1);
        account1.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList1 = new ArrayList<>();
        account1.setFeedbackList(feedbackList1);
        account1.setIsBlock(true);
        account1.setPartner(partner3);
        account1.setPassWord("Pass Word");
        account1.setRoleId(role2);
        ArrayList<Tour> tourList1 = new ArrayList<>();
        account1.setTourList(tourList1);
        account1.setUser(user1);
        ArrayList<UserBooking> userBookingList1 = new ArrayList<>();
        account1.setUserBookingList(userBookingList1);
        User user2 = new User();
        user2.setAccountId(account1);
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);
        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        ArrayList<Comment> commentList2 = new ArrayList<>();
        account2.setCommentList(commentList2);
        account2.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList2 = new ArrayList<>();
        account2.setFeedbackList(feedbackList2);
        account2.setIsBlock(true);
        account2.setPartner(partner2);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role1);
        ArrayList<Tour> tourList2 = new ArrayList<>();
        account2.setTourList(tourList2);
        account2.setUser(user2);
        ArrayList<UserBooking> userBookingList2 = new ArrayList<>();
        account2.setUserBookingList(userBookingList2);
        actualTour.setAccountId(account2);
        actualTour.setDeposit(10.0f);
        actualTour.setEndPlace("End Place");
        LocalTime ofResult = LocalTime.of(1, 1);
        actualTour.setEndTime(ofResult);
        ArrayList<Feedback> feedbackList3 = new ArrayList<>();
        actualTour.setFeedbackList(feedbackList3);
        actualTour.setMaxAdult(3);
        actualTour.setMaxChildren(3);
        actualTour.setMinAdult(1);
        actualTour.setMinChildren(1);
        actualTour.setMinToStart(1);
        actualTour.setNote("Note");
        actualTour.setNumberOfDay(10);
        actualTour.setNumberOfNight(10);
        actualTour.setPriceAdult(10.0f);
        actualTour.setPriceChildren(10.0f);
        LocalDate ofEpochDayResult = LocalDate.ofEpochDay(1L);
        actualTour.setStartDate(ofEpochDayResult);
        actualTour.setStartPlace("Start Place");
        LocalTime ofResult1 = LocalTime.of(1, 1);
        actualTour.setStartTime(ofResult1);
        actualTour.setStatus(1);
        actualTour.setTotalPrice(10.0f);
        TourCategory tourCategory = new TourCategory();
        tourCategory.setTourCategoryId(123L);
        tourCategory.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList3 = new ArrayList<>();
        tourCategory.setTourList(tourList3);
        actualTour.setTourCategoryId(tourCategory);
        actualTour.setTourCode("Tour Code");
        Partner partner4 = new Partner();
        partner4.setAccountId(new Account());
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(new CompanyPartner());
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList5 = new ArrayList<>();
        partner4.setServiceList(serviceList5);
        Role role3 = new Role();
        ArrayList<Account> accountList3 = new ArrayList<>();
        role3.setAccountList(accountList3);
        role3.setRoleId(123);
        role3.setRoleName("Role Name");
        User user3 = new User();
        user3.setAccountId(new Account());
        user3.setAddress("42 Main St");
        user3.setBirthDate("2020-03-01");
        user3.setCity("Oxford");
        user3.setFirstName("Jane");
        user3.setGender("Gender");
        user3.setIsPrivate(true);
        user3.setLastName("Doe");
        user3.setPhone("4105551212");
        user3.setRankPoint(1);
        user3.setUserId(123L);
        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        ArrayList<Comment> commentList3 = new ArrayList<>();
        account3.setCommentList(commentList3);
        account3.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList4 = new ArrayList<>();
        account3.setFeedbackList(feedbackList4);
        account3.setIsBlock(true);
        account3.setPartner(partner4);
        account3.setPassWord("Pass Word");
        account3.setRoleId(role3);
        ArrayList<Tour> tourList4 = new ArrayList<>();
        account3.setTourList(tourList4);
        account3.setUser(user3);
        ArrayList<UserBooking> userBookingList3 = new ArrayList<>();
        account3.setUserBookingList(userBookingList3);
        TourCategory tourCategory1 = new TourCategory();
        tourCategory1.setTourCategoryId(123L);
        tourCategory1.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList5 = new ArrayList<>();
        tourCategory1.setTourList(tourList5);
        Tour tour = new Tour();
        tour.setAccountId(new Account());
        tour.setDeposit(10.0f);
        tour.setEndPlace("End Place");
        tour.setEndTime(null);
        ArrayList<Feedback> feedbackList5 = new ArrayList<>();
        tour.setFeedbackList(feedbackList5);
        tour.setMaxAdult(3);
        tour.setMaxChildren(3);
        tour.setMinAdult(1);
        tour.setMinChildren(1);
        tour.setMinToStart(1);
        tour.setNote("Note");
        tour.setNumberOfDay(10);
        tour.setNumberOfNight(10);
        tour.setPriceAdult(10.0f);
        tour.setPriceChildren(10.0f);
        tour.setStartDate(null);
        tour.setStartPlace("Start Place");
        tour.setStartTime(null);
        tour.setStatus(1);
        tour.setTotalPrice(10.0f);
        tour.setTourCategoryId(new TourCategory());
        tour.setTourCode("Tour Code");
        tour.setTourDetail(new TourDetail());
        tour.setTourId(123L);
        tour.setTourMode(true);
        tour.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList = new ArrayList<>();
        tour.setTourScheduleList(tourScheduleList);
        tour.setTourType(1);
        ArrayList<UserBooking> userBookingList4 = new ArrayList<>();
        tour.setUserBookingList(userBookingList4);
        TourDetail tourDetail = new TourDetail();
        tourDetail.setAddressStart("42 Main St");
        tourDetail.setDescription("The characteristics of someone or something");
        tourDetail.setGeneralTerms("General Terms");
        tourDetail.setLatitude(10.0f);
        tourDetail.setLongitude(10.0f);
        tourDetail.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList = new ArrayList<>();
        tourDetail.setTagOfTourList(tagOfTourList);
        tourDetail.setTourDetailId(123L);
        tourDetail.setTourId(tour);
        tourDetail.setTourInclude("Tour Include");
        tourDetail.setTourIntroduce("Tour Introduce");
        tourDetail.setTourNonInclude("Tour Non Include");
        Tour tour1 = new Tour();
        tour1.setAccountId(account3);
        tour1.setDeposit(10.0f);
        tour1.setEndPlace("End Place");
        tour1.setEndTime(LocalTime.of(1, 1));
        ArrayList<Feedback> feedbackList6 = new ArrayList<>();
        tour1.setFeedbackList(feedbackList6);
        tour1.setMaxAdult(3);
        tour1.setMaxChildren(3);
        tour1.setMinAdult(1);
        tour1.setMinChildren(1);
        tour1.setMinToStart(1);
        tour1.setNote("Note");
        tour1.setNumberOfDay(10);
        tour1.setNumberOfNight(10);
        tour1.setPriceAdult(10.0f);
        tour1.setPriceChildren(10.0f);
        tour1.setStartDate(LocalDate.ofEpochDay(1L));
        tour1.setStartPlace("Start Place");
        tour1.setStartTime(LocalTime.of(1, 1));
        tour1.setStatus(1);
        tour1.setTotalPrice(10.0f);
        tour1.setTourCategoryId(tourCategory1);
        tour1.setTourCode("Tour Code");
        tour1.setTourDetail(tourDetail);
        tour1.setTourId(123L);
        tour1.setTourMode(true);
        tour1.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList1 = new ArrayList<>();
        tour1.setTourScheduleList(tourScheduleList1);
        tour1.setTourType(1);
        ArrayList<UserBooking> userBookingList5 = new ArrayList<>();
        tour1.setUserBookingList(userBookingList5);
        TourDetail tourDetail1 = new TourDetail();
        tourDetail1.setAddressStart("42 Main St");
        tourDetail1.setDescription("The characteristics of someone or something");
        tourDetail1.setGeneralTerms("General Terms");
        tourDetail1.setLatitude(10.0f);
        tourDetail1.setLongitude(10.0f);
        tourDetail1.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList1 = new ArrayList<>();
        tourDetail1.setTagOfTourList(tagOfTourList1);
        tourDetail1.setTourDetailId(123L);
        tourDetail1.setTourId(tour1);
        tourDetail1.setTourInclude("Tour Include");
        tourDetail1.setTourIntroduce("Tour Introduce");
        tourDetail1.setTourNonInclude("Tour Non Include");
        actualTour.setTourDetail(tourDetail1);
        actualTour.setTourId(123L);
        actualTour.setTourMode(true);
        actualTour.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList2 = new ArrayList<>();
        actualTour.setTourScheduleList(tourScheduleList2);
        actualTour.setTourType(1);
        ArrayList<UserBooking> userBookingList6 = new ArrayList<>();
        actualTour.setUserBookingList(userBookingList6);
        assertSame(account2, actualTour.getAccountId());
        assertEquals(10.0f, actualTour.getDeposit().floatValue());
        assertEquals("End Place", actualTour.getEndPlace());
        assertSame(ofResult, actualTour.getEndTime());
        List<Feedback> feedbackList7 = actualTour.getFeedbackList();
        assertSame(feedbackList3, feedbackList7);
        assertEquals(commentList2, feedbackList7);
        assertEquals(feedbackList2, feedbackList7);
        assertEquals(commentList, feedbackList7);
        assertEquals(feedbackList, feedbackList7);
        assertEquals(serviceList, feedbackList7);
        assertEquals(accountList, feedbackList7);
        assertEquals(tourList, feedbackList7);
        assertEquals(userBookingList, feedbackList7);
        assertEquals(serviceList1, feedbackList7);
        assertEquals(partnerList, feedbackList7);
        assertEquals(serviceList2, feedbackList7);
        assertEquals(serviceList3, feedbackList7);
        assertEquals(accountList1, feedbackList7);
        assertEquals(tourList2, feedbackList7);
        assertEquals(commentList1, feedbackList7);
        assertEquals(feedbackList1, feedbackList7);
        assertEquals(serviceList4, feedbackList7);
        assertEquals(accountList2, feedbackList7);
        assertEquals(tourList1, feedbackList7);
        assertEquals(userBookingList1, feedbackList7);
        assertEquals(userBookingList2, feedbackList7);
        assertEquals(tourList3, feedbackList7);
        assertEquals(tagOfTourList1, feedbackList7);
        assertEquals(commentList3, feedbackList7);
        assertEquals(feedbackList4, feedbackList7);
        assertEquals(serviceList5, feedbackList7);
        assertEquals(accountList3, feedbackList7);
        assertEquals(tourList4, feedbackList7);
        assertEquals(userBookingList3, feedbackList7);
        assertEquals(feedbackList6, feedbackList7);
        assertEquals(tourList5, feedbackList7);
        assertEquals(tagOfTourList, feedbackList7);
        assertEquals(feedbackList5, feedbackList7);
        assertEquals(tourScheduleList, feedbackList7);
        assertEquals(userBookingList4, feedbackList7);
        assertEquals(tourScheduleList1, feedbackList7);
        assertEquals(userBookingList5, feedbackList7);
        assertEquals(tourScheduleList2, feedbackList7);
        List<UserBooking> userBookingList7 = actualTour.getUserBookingList();
        assertEquals(userBookingList7, feedbackList7);
        assertEquals(3, actualTour.getMaxAdult().intValue());
        assertEquals(3, actualTour.getMaxChildren().intValue());
        assertEquals(1, actualTour.getMinAdult().intValue());
        assertEquals(1, actualTour.getMinChildren().intValue());
        assertEquals(1, actualTour.getMinToStart().intValue());
        assertEquals("Note", actualTour.getNote());
        assertEquals(10, actualTour.getNumberOfDay().intValue());
        assertEquals(10, actualTour.getNumberOfNight().intValue());
        assertEquals(10.0f, actualTour.getPriceAdult().floatValue());
        assertEquals(10.0f, actualTour.getPriceChildren().floatValue());
        assertSame(ofEpochDayResult, actualTour.getStartDate());
        assertEquals("Start Place", actualTour.getStartPlace());
        assertSame(ofResult1, actualTour.getStartTime());
        assertEquals(1, actualTour.getStatus().intValue());
        assertEquals(10.0f, actualTour.getTotalPrice().floatValue());
        assertSame(tourCategory, actualTour.getTourCategoryId());
        assertEquals("Tour Code", actualTour.getTourCode());
        assertSame(tourDetail1, actualTour.getTourDetail());
        assertEquals(123L, actualTour.getTourId().longValue());
        assertTrue(actualTour.getTourMode());
        assertEquals("Tour Name", actualTour.getTourName());
        List<TourSchedule> tourScheduleList3 = actualTour.getTourScheduleList();
        assertSame(tourScheduleList2, tourScheduleList3);
        assertEquals(commentList2, tourScheduleList3);
        assertEquals(feedbackList2, tourScheduleList3);
        assertEquals(commentList, tourScheduleList3);
        assertEquals(feedbackList, tourScheduleList3);
        assertEquals(serviceList, tourScheduleList3);
        assertEquals(accountList, tourScheduleList3);
        assertEquals(tourList, tourScheduleList3);
        assertEquals(userBookingList, tourScheduleList3);
        assertEquals(serviceList1, tourScheduleList3);
        assertEquals(partnerList, tourScheduleList3);
        assertEquals(serviceList2, tourScheduleList3);
        assertEquals(serviceList3, tourScheduleList3);
        assertEquals(accountList1, tourScheduleList3);
        assertEquals(tourList2, tourScheduleList3);
        assertEquals(commentList1, tourScheduleList3);
        assertEquals(feedbackList1, tourScheduleList3);
        assertEquals(serviceList4, tourScheduleList3);
        assertEquals(accountList2, tourScheduleList3);
        assertEquals(tourList1, tourScheduleList3);
        assertEquals(userBookingList1, tourScheduleList3);
        assertEquals(userBookingList2, tourScheduleList3);
        assertEquals(tourList3, tourScheduleList3);
        assertEquals(tagOfTourList1, tourScheduleList3);
        assertEquals(commentList3, tourScheduleList3);
        assertEquals(feedbackList4, tourScheduleList3);
        assertEquals(serviceList5, tourScheduleList3);
        assertEquals(accountList3, tourScheduleList3);
        assertEquals(tourList4, tourScheduleList3);
        assertEquals(userBookingList3, tourScheduleList3);
        assertEquals(feedbackList6, tourScheduleList3);
        assertEquals(tourList5, tourScheduleList3);
        assertEquals(tagOfTourList, tourScheduleList3);
        assertEquals(feedbackList5, tourScheduleList3);
        assertEquals(tourScheduleList, tourScheduleList3);
        assertEquals(userBookingList4, tourScheduleList3);
        assertEquals(tourScheduleList1, tourScheduleList3);
        assertEquals(userBookingList5, tourScheduleList3);
        assertEquals(feedbackList7, tourScheduleList3);
        assertEquals(userBookingList7, tourScheduleList3);
        assertEquals(1, actualTour.getTourType().intValue());
        assertSame(userBookingList6, userBookingList7);
        assertEquals(commentList2, userBookingList7);
        assertEquals(feedbackList2, userBookingList7);
        assertEquals(commentList, userBookingList7);
        assertEquals(feedbackList, userBookingList7);
        assertEquals(serviceList, userBookingList7);
        assertEquals(accountList, userBookingList7);
        assertEquals(tourList, userBookingList7);
        assertEquals(userBookingList, userBookingList7);
        assertEquals(serviceList1, userBookingList7);
        assertEquals(partnerList, userBookingList7);
        assertEquals(serviceList2, userBookingList7);
        assertEquals(serviceList3, userBookingList7);
        assertEquals(accountList1, userBookingList7);
        assertEquals(tourList2, userBookingList7);
        assertEquals(commentList1, userBookingList7);
        assertEquals(feedbackList1, userBookingList7);
        assertEquals(serviceList4, userBookingList7);
        assertEquals(accountList2, userBookingList7);
        assertEquals(tourList1, userBookingList7);
        assertEquals(userBookingList1, userBookingList7);
        assertEquals(userBookingList2, userBookingList7);
        assertEquals(feedbackList3, userBookingList7);
        assertEquals(tourList3, userBookingList7);
        assertEquals(tagOfTourList1, userBookingList7);
        assertEquals(commentList3, userBookingList7);
        assertEquals(feedbackList4, userBookingList7);
        assertEquals(serviceList5, userBookingList7);
        assertEquals(accountList3, userBookingList7);
        assertEquals(tourList4, userBookingList7);
        assertEquals(userBookingList3, userBookingList7);
        assertEquals(feedbackList6, userBookingList7);
        assertEquals(tourList5, userBookingList7);
        assertEquals(tagOfTourList, userBookingList7);
        assertEquals(feedbackList5, userBookingList7);
        assertEquals(tourScheduleList, userBookingList7);
        assertEquals(userBookingList4, userBookingList7);
        assertEquals(tourScheduleList1, userBookingList7);
        assertEquals(userBookingList5, userBookingList7);
        assertEquals(tourScheduleList2, userBookingList7);
    }

    /**
     * Methods under test:
     *
     * <ul>
     *   <li>{@link Tour#Tour(Long, String, String, String, String, Integer, Integer, Boolean, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Float, Float, String, LocalDate, LocalTime, LocalTime, Float, Float, Account, TourCategory, List, TourDetail, List, List)}
     *   <li>{@link Tour#Tour()}
     *   <li>{@link Tour#setAccountId(Account)}
     *   <li>{@link Tour#setDeposit(Float)}
     *   <li>{@link Tour#setEndPlace(String)}
     *   <li>{@link Tour#setEndTime(LocalTime)}
     *   <li>{@link Tour#setFeedbackList(List)}
     *   <li>{@link Tour#setMaxAdult(Integer)}
     *   <li>{@link Tour#setMaxChildren(Integer)}
     *   <li>{@link Tour#setMinAdult(Integer)}
     *   <li>{@link Tour#setMinChildren(Integer)}
     *   <li>{@link Tour#setMinToStart(Integer)}
     *   <li>{@link Tour#setNote(String)}
     *   <li>{@link Tour#setNumberOfDay(Integer)}
     *   <li>{@link Tour#setNumberOfNight(Integer)}
     *   <li>{@link Tour#setPriceAdult(Float)}
     *   <li>{@link Tour#setPriceChildren(Float)}
     *   <li>{@link Tour#setStartDate(LocalDate)}
     *   <li>{@link Tour#setStartPlace(String)}
     *   <li>{@link Tour#setStartTime(LocalTime)}
     *   <li>{@link Tour#setStatus(Integer)}
     *   <li>{@link Tour#setTotalPrice(Float)}
     *   <li>{@link Tour#setTourCategoryId(TourCategory)}
     *   <li>{@link Tour#setTourCode(String)}
     *   <li>{@link Tour#setTourDetail(TourDetail)}
     *   <li>{@link Tour#setTourId(Long)}
     *   <li>{@link Tour#setTourMode(Boolean)}
     *   <li>{@link Tour#setTourName(String)}
     *   <li>{@link Tour#setTourScheduleList(List)}
     *   <li>{@link Tour#setTourType(Integer)}
     *   <li>{@link Tour#setUserBookingList(List)}
     *   <li>{@link Tour#getAccountId()}
     *   <li>{@link Tour#getDeposit()}
     *   <li>{@link Tour#getEndPlace()}
     *   <li>{@link Tour#getEndTime()}
     *   <li>{@link Tour#getFeedbackList()}
     *   <li>{@link Tour#getUserBookingList()}
     *   <li>{@link Tour#getMaxAdult()}
     *   <li>{@link Tour#getMaxChildren()}
     *   <li>{@link Tour#getMinAdult()}
     *   <li>{@link Tour#getMinChildren()}
     *   <li>{@link Tour#getMinToStart()}
     *   <li>{@link Tour#getNote()}
     *   <li>{@link Tour#getNumberOfDay()}
     *   <li>{@link Tour#getNumberOfNight()}
     *   <li>{@link Tour#getPriceAdult()}
     *   <li>{@link Tour#getPriceChildren()}
     *   <li>{@link Tour#getStartDate()}
     *   <li>{@link Tour#getStartPlace()}
     *   <li>{@link Tour#getStartTime()}
     *   <li>{@link Tour#getStatus()}
     *   <li>{@link Tour#getTotalPrice()}
     *   <li>{@link Tour#getTourCategoryId()}
     *   <li>{@link Tour#getTourCode()}
     *   <li>{@link Tour#getTourDetail()}
     *   <li>{@link Tour#getTourId()}
     *   <li>{@link Tour#getTourMode()}
     *   <li>{@link Tour#getTourName()}
     *   <li>{@link Tour#getTourScheduleList()}
     *   <li>{@link Tour#getTourType()}
     * </ul>
     */
    @Test
    void testConstructor2() {
        LocalDate startDate = LocalDate.ofEpochDay(1L);
        LocalTime startTime = LocalTime.of(1, 1);
        LocalTime endTime = LocalTime.of(1, 1);

        Partner partner = new Partner();
        partner.setAccountId(new Account());
        partner.setAddress("42 Main St");
        partner.setBirthDate("2020-03-01");
        partner.setCity("Oxford");
        partner.setCompanyPartnerId(new CompanyPartner());
        partner.setDateIssue("2020-03-01");
        partner.setDepartment("Department");
        partner.setEmail("jane.doe@example.org");
        partner.setFirstName("Jane");
        partner.setGender("Gender");
        partner.setLastName("Doe");
        partner.setNumberIdCard("42");
        partner.setPartnerId(123L);
        partner.setPhone("4105551212");
        partner.setPlaceIssue("Place Issue");
        partner.setPosition("Position");
        partner.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList = new ArrayList<>();
        partner.setServiceList(serviceList);

        Role role = new Role();
        ArrayList<Account> accountList = new ArrayList<>();
        role.setAccountList(accountList);
        role.setRoleId(123);
        role.setRoleName("Role Name");

        User user = new User();
        user.setAccountId(new Account());
        user.setAddress("42 Main St");
        user.setBirthDate("2020-03-01");
        user.setCity("Oxford");
        user.setFirstName("Jane");
        user.setGender("Gender");
        user.setIsPrivate(true);
        user.setLastName("Doe");
        user.setPhone("4105551212");
        user.setRankPoint(1);
        user.setUserId(123L);

        Account account = new Account();
        account.setAccountId(1234567890L);
        ArrayList<Comment> commentList = new ArrayList<>();
        account.setCommentList(commentList);
        account.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList = new ArrayList<>();
        account.setFeedbackList(feedbackList);
        account.setIsBlock(true);
        account.setPartner(partner);
        account.setPassWord("Pass Word");
        account.setRoleId(role);
        ArrayList<Tour> tourList = new ArrayList<>();
        account.setTourList(tourList);
        account.setUser(user);
        ArrayList<UserBooking> userBookingList = new ArrayList<>();
        account.setUserBookingList(userBookingList);

        Partner partner1 = new Partner();
        partner1.setAccountId(new Account());
        partner1.setAddress("42 Main St");
        partner1.setBirthDate("2020-03-01");
        partner1.setCity("Oxford");
        partner1.setCompanyPartnerId(new CompanyPartner());
        partner1.setDateIssue("2020-03-01");
        partner1.setDepartment("Department");
        partner1.setEmail("jane.doe@example.org");
        partner1.setFirstName("Jane");
        partner1.setGender("Gender");
        partner1.setLastName("Doe");
        partner1.setNumberIdCard("42");
        partner1.setPartnerId(123L);
        partner1.setPhone("4105551212");
        partner1.setPlaceIssue("Place Issue");
        partner1.setPosition("Position");
        partner1.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList1 = new ArrayList<>();
        partner1.setServiceList(serviceList1);

        CompanyPartner companyPartner = new CompanyPartner();
        companyPartner.setAddress("42 Main St");
        companyPartner.setBusinessCode("Business Code");
        companyPartner.setCity("Oxford");
        companyPartner.setCompanyName("Company Name");
        companyPartner.setCompanyPartnerId(123L);
        companyPartner.setEmail("jane.doe@example.org");
        companyPartner.setFax("Fax");
        companyPartner.setIncorporationDate("2020-03-01");
        companyPartner.setPartnerId(partner1);
        companyPartner.setPhone("4105551212");
        companyPartner.setRegistrationDate("2020-03-01");
        companyPartner.setShortName("Short Name");
        companyPartner.setTaxCode("Tax Code");
        companyPartner.setWebsite("Website");

        ServiceCategory serviceCategory = new ServiceCategory();
        ArrayList<Partner> partnerList = new ArrayList<>();
        serviceCategory.setPartnerList(partnerList);
        serviceCategory.setServiceCategoryId(123L);
        serviceCategory.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList2 = new ArrayList<>();
        serviceCategory.setServiceList(serviceList2);

        Partner partner2 = new Partner();
        partner2.setAccountId(account);
        partner2.setAddress("42 Main St");
        partner2.setBirthDate("2020-03-01");
        partner2.setCity("Oxford");
        partner2.setCompanyPartnerId(companyPartner);
        partner2.setDateIssue("2020-03-01");
        partner2.setDepartment("Department");
        partner2.setEmail("jane.doe@example.org");
        partner2.setFirstName("Jane");
        partner2.setGender("Gender");
        partner2.setLastName("Doe");
        partner2.setNumberIdCard("42");
        partner2.setPartnerId(123L);
        partner2.setPhone("4105551212");
        partner2.setPlaceIssue("Place Issue");
        partner2.setPosition("Position");
        partner2.setServiceCategoryId(serviceCategory);
        ArrayList<Service> serviceList3 = new ArrayList<>();
        partner2.setServiceList(serviceList3);

        Role role1 = new Role();
        ArrayList<Account> accountList1 = new ArrayList<>();
        role1.setAccountList(accountList1);
        role1.setRoleId(123);
        role1.setRoleName("Role Name");

        Partner partner3 = new Partner();
        partner3.setAccountId(new Account());
        partner3.setAddress("42 Main St");
        partner3.setBirthDate("2020-03-01");
        partner3.setCity("Oxford");
        partner3.setCompanyPartnerId(new CompanyPartner());
        partner3.setDateIssue("2020-03-01");
        partner3.setDepartment("Department");
        partner3.setEmail("jane.doe@example.org");
        partner3.setFirstName("Jane");
        partner3.setGender("Gender");
        partner3.setLastName("Doe");
        partner3.setNumberIdCard("42");
        partner3.setPartnerId(123L);
        partner3.setPhone("4105551212");
        partner3.setPlaceIssue("Place Issue");
        partner3.setPosition("Position");
        partner3.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList4 = new ArrayList<>();
        partner3.setServiceList(serviceList4);

        Role role2 = new Role();
        ArrayList<Account> accountList2 = new ArrayList<>();
        role2.setAccountList(accountList2);
        role2.setRoleId(123);
        role2.setRoleName("Role Name");

        User user1 = new User();
        user1.setAccountId(new Account());
        user1.setAddress("42 Main St");
        user1.setBirthDate("2020-03-01");
        user1.setCity("Oxford");
        user1.setFirstName("Jane");
        user1.setGender("Gender");
        user1.setIsPrivate(true);
        user1.setLastName("Doe");
        user1.setPhone("4105551212");
        user1.setRankPoint(1);
        user1.setUserId(123L);

        Account account1 = new Account();
        account1.setAccountId(1234567890L);
        ArrayList<Comment> commentList1 = new ArrayList<>();
        account1.setCommentList(commentList1);
        account1.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList1 = new ArrayList<>();
        account1.setFeedbackList(feedbackList1);
        account1.setIsBlock(true);
        account1.setPartner(partner3);
        account1.setPassWord("Pass Word");
        account1.setRoleId(role2);
        ArrayList<Tour> tourList1 = new ArrayList<>();
        account1.setTourList(tourList1);
        account1.setUser(user1);
        ArrayList<UserBooking> userBookingList1 = new ArrayList<>();
        account1.setUserBookingList(userBookingList1);

        User user2 = new User();
        user2.setAccountId(account1);
        user2.setAddress("42 Main St");
        user2.setBirthDate("2020-03-01");
        user2.setCity("Oxford");
        user2.setFirstName("Jane");
        user2.setGender("Gender");
        user2.setIsPrivate(true);
        user2.setLastName("Doe");
        user2.setPhone("4105551212");
        user2.setRankPoint(1);
        user2.setUserId(123L);

        Account account2 = new Account();
        account2.setAccountId(1234567890L);
        ArrayList<Comment> commentList2 = new ArrayList<>();
        account2.setCommentList(commentList2);
        account2.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList2 = new ArrayList<>();
        account2.setFeedbackList(feedbackList2);
        account2.setIsBlock(true);
        account2.setPartner(partner2);
        account2.setPassWord("Pass Word");
        account2.setRoleId(role1);
        ArrayList<Tour> tourList2 = new ArrayList<>();
        account2.setTourList(tourList2);
        account2.setUser(user2);
        ArrayList<UserBooking> userBookingList2 = new ArrayList<>();
        account2.setUserBookingList(userBookingList2);

        TourCategory tourCategory = new TourCategory();
        tourCategory.setTourCategoryId(123L);
        tourCategory.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList3 = new ArrayList<>();
        tourCategory.setTourList(tourList3);
        ArrayList<TourSchedule> tourScheduleList = new ArrayList<>();

        Partner partner4 = new Partner();
        partner4.setAccountId(new Account());
        partner4.setAddress("42 Main St");
        partner4.setBirthDate("2020-03-01");
        partner4.setCity("Oxford");
        partner4.setCompanyPartnerId(new CompanyPartner());
        partner4.setDateIssue("2020-03-01");
        partner4.setDepartment("Department");
        partner4.setEmail("jane.doe@example.org");
        partner4.setFirstName("Jane");
        partner4.setGender("Gender");
        partner4.setLastName("Doe");
        partner4.setNumberIdCard("42");
        partner4.setPartnerId(123L);
        partner4.setPhone("4105551212");
        partner4.setPlaceIssue("Place Issue");
        partner4.setPosition("Position");
        partner4.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList5 = new ArrayList<>();
        partner4.setServiceList(serviceList5);

        Role role3 = new Role();
        ArrayList<Account> accountList3 = new ArrayList<>();
        role3.setAccountList(accountList3);
        role3.setRoleId(123);
        role3.setRoleName("Role Name");

        User user3 = new User();
        user3.setAccountId(new Account());
        user3.setAddress("42 Main St");
        user3.setBirthDate("2020-03-01");
        user3.setCity("Oxford");
        user3.setFirstName("Jane");
        user3.setGender("Gender");
        user3.setIsPrivate(true);
        user3.setLastName("Doe");
        user3.setPhone("4105551212");
        user3.setRankPoint(1);
        user3.setUserId(123L);

        Account account3 = new Account();
        account3.setAccountId(1234567890L);
        ArrayList<Comment> commentList3 = new ArrayList<>();
        account3.setCommentList(commentList3);
        account3.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList3 = new ArrayList<>();
        account3.setFeedbackList(feedbackList3);
        account3.setIsBlock(true);
        account3.setPartner(partner4);
        account3.setPassWord("Pass Word");
        account3.setRoleId(role3);
        ArrayList<Tour> tourList4 = new ArrayList<>();
        account3.setTourList(tourList4);
        account3.setUser(user3);
        ArrayList<UserBooking> userBookingList3 = new ArrayList<>();
        account3.setUserBookingList(userBookingList3);

        TourCategory tourCategory1 = new TourCategory();
        tourCategory1.setTourCategoryId(123L);
        tourCategory1.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList5 = new ArrayList<>();
        tourCategory1.setTourList(tourList5);

        Tour tour = new Tour();
        tour.setAccountId(new Account());
        tour.setDeposit(10.0f);
        tour.setEndPlace("End Place");
        tour.setEndTime(null);
        ArrayList<Feedback> feedbackList4 = new ArrayList<>();
        tour.setFeedbackList(feedbackList4);
        tour.setMaxAdult(3);
        tour.setMaxChildren(3);
        tour.setMinAdult(1);
        tour.setMinChildren(1);
        tour.setMinToStart(1);
        tour.setNote("Note");
        tour.setNumberOfDay(10);
        tour.setNumberOfNight(10);
        tour.setPriceAdult(10.0f);
        tour.setPriceChildren(10.0f);
        tour.setStartDate(null);
        tour.setStartPlace("Start Place");
        tour.setStartTime(null);
        tour.setStatus(1);
        tour.setTotalPrice(10.0f);
        tour.setTourCategoryId(new TourCategory());
        tour.setTourCode("Tour Code");
        tour.setTourDetail(new TourDetail());
        tour.setTourId(123L);
        tour.setTourMode(true);
        tour.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList1 = new ArrayList<>();
        tour.setTourScheduleList(tourScheduleList1);
        tour.setTourType(1);
        ArrayList<UserBooking> userBookingList4 = new ArrayList<>();
        tour.setUserBookingList(userBookingList4);

        TourDetail tourDetail = new TourDetail();
        tourDetail.setAddressStart("42 Main St");
        tourDetail.setDescription("The characteristics of someone or something");
        tourDetail.setGeneralTerms("General Terms");
        tourDetail.setLatitude(10.0f);
        tourDetail.setLongitude(10.0f);
        tourDetail.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList = new ArrayList<>();
        tourDetail.setTagOfTourList(tagOfTourList);
        tourDetail.setTourDetailId(123L);
        tourDetail.setTourId(tour);
        tourDetail.setTourInclude("Tour Include");
        tourDetail.setTourIntroduce("Tour Introduce");
        tourDetail.setTourNonInclude("Tour Non Include");

        Tour tour1 = new Tour();
        tour1.setAccountId(account3);
        tour1.setDeposit(10.0f);
        tour1.setEndPlace("End Place");
        tour1.setEndTime(LocalTime.of(1, 1));
        ArrayList<Feedback> feedbackList5 = new ArrayList<>();
        tour1.setFeedbackList(feedbackList5);
        tour1.setMaxAdult(3);
        tour1.setMaxChildren(3);
        tour1.setMinAdult(1);
        tour1.setMinChildren(1);
        tour1.setMinToStart(1);
        tour1.setNote("Note");
        tour1.setNumberOfDay(10);
        tour1.setNumberOfNight(10);
        tour1.setPriceAdult(10.0f);
        tour1.setPriceChildren(10.0f);
        tour1.setStartDate(LocalDate.ofEpochDay(1L));
        tour1.setStartPlace("Start Place");
        tour1.setStartTime(LocalTime.of(1, 1));
        tour1.setStatus(1);
        tour1.setTotalPrice(10.0f);
        tour1.setTourCategoryId(tourCategory1);
        tour1.setTourCode("Tour Code");
        tour1.setTourDetail(tourDetail);
        tour1.setTourId(123L);
        tour1.setTourMode(true);
        tour1.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList2 = new ArrayList<>();
        tour1.setTourScheduleList(tourScheduleList2);
        tour1.setTourType(1);
        ArrayList<UserBooking> userBookingList5 = new ArrayList<>();
        tour1.setUserBookingList(userBookingList5);

        TourDetail tourDetail1 = new TourDetail();
        tourDetail1.setAddressStart("42 Main St");
        tourDetail1.setDescription("The characteristics of someone or something");
        tourDetail1.setGeneralTerms("General Terms");
        tourDetail1.setLatitude(10.0f);
        tourDetail1.setLongitude(10.0f);
        tourDetail1.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList1 = new ArrayList<>();
        tourDetail1.setTagOfTourList(tagOfTourList1);
        tourDetail1.setTourDetailId(123L);
        tourDetail1.setTourId(tour1);
        tourDetail1.setTourInclude("Tour Include");
        tourDetail1.setTourIntroduce("Tour Introduce");
        tourDetail1.setTourNonInclude("Tour Non Include");
        ArrayList<UserBooking> userBookingList6 = new ArrayList<>();
        ArrayList<Feedback> feedbackList6 = new ArrayList<>();
        Tour actualTour = new Tour(123L, "Tour Name", "Tour Code", "Start Place", "End Place", 1, 1, true, 10, 10, 1, 3,
                1, 3, 1, 10.0f, 10.0f, "Note", startDate, startTime, endTime, 10.0f, 10.0f, account2, tourCategory,
                tourScheduleList, tourDetail1, userBookingList6, feedbackList6);
        Partner partner5 = new Partner();
        partner5.setAccountId(new Account());
        partner5.setAddress("42 Main St");
        partner5.setBirthDate("2020-03-01");
        partner5.setCity("Oxford");
        partner5.setCompanyPartnerId(new CompanyPartner());
        partner5.setDateIssue("2020-03-01");
        partner5.setDepartment("Department");
        partner5.setEmail("jane.doe@example.org");
        partner5.setFirstName("Jane");
        partner5.setGender("Gender");
        partner5.setLastName("Doe");
        partner5.setNumberIdCard("42");
        partner5.setPartnerId(123L);
        partner5.setPhone("4105551212");
        partner5.setPlaceIssue("Place Issue");
        partner5.setPosition("Position");
        partner5.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList6 = new ArrayList<>();
        partner5.setServiceList(serviceList6);
        Role role4 = new Role();
        ArrayList<Account> accountList4 = new ArrayList<>();
        role4.setAccountList(accountList4);
        role4.setRoleId(123);
        role4.setRoleName("Role Name");
        User user4 = new User();
        user4.setAccountId(new Account());
        user4.setAddress("42 Main St");
        user4.setBirthDate("2020-03-01");
        user4.setCity("Oxford");
        user4.setFirstName("Jane");
        user4.setGender("Gender");
        user4.setIsPrivate(true);
        user4.setLastName("Doe");
        user4.setPhone("4105551212");
        user4.setRankPoint(1);
        user4.setUserId(123L);
        Account account4 = new Account();
        account4.setAccountId(1234567890L);
        ArrayList<Comment> commentList4 = new ArrayList<>();
        account4.setCommentList(commentList4);
        account4.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList7 = new ArrayList<>();
        account4.setFeedbackList(feedbackList7);
        account4.setIsBlock(true);
        account4.setPartner(partner5);
        account4.setPassWord("Pass Word");
        account4.setRoleId(role4);
        ArrayList<Tour> tourList6 = new ArrayList<>();
        account4.setTourList(tourList6);
        account4.setUser(user4);
        ArrayList<UserBooking> userBookingList7 = new ArrayList<>();
        account4.setUserBookingList(userBookingList7);
        Partner partner6 = new Partner();
        partner6.setAccountId(new Account());
        partner6.setAddress("42 Main St");
        partner6.setBirthDate("2020-03-01");
        partner6.setCity("Oxford");
        partner6.setCompanyPartnerId(new CompanyPartner());
        partner6.setDateIssue("2020-03-01");
        partner6.setDepartment("Department");
        partner6.setEmail("jane.doe@example.org");
        partner6.setFirstName("Jane");
        partner6.setGender("Gender");
        partner6.setLastName("Doe");
        partner6.setNumberIdCard("42");
        partner6.setPartnerId(123L);
        partner6.setPhone("4105551212");
        partner6.setPlaceIssue("Place Issue");
        partner6.setPosition("Position");
        partner6.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList7 = new ArrayList<>();
        partner6.setServiceList(serviceList7);
        CompanyPartner companyPartner1 = new CompanyPartner();
        companyPartner1.setAddress("42 Main St");
        companyPartner1.setBusinessCode("Business Code");
        companyPartner1.setCity("Oxford");
        companyPartner1.setCompanyName("Company Name");
        companyPartner1.setCompanyPartnerId(123L);
        companyPartner1.setEmail("jane.doe@example.org");
        companyPartner1.setFax("Fax");
        companyPartner1.setIncorporationDate("2020-03-01");
        companyPartner1.setPartnerId(partner6);
        companyPartner1.setPhone("4105551212");
        companyPartner1.setRegistrationDate("2020-03-01");
        companyPartner1.setShortName("Short Name");
        companyPartner1.setTaxCode("Tax Code");
        companyPartner1.setWebsite("Website");
        ServiceCategory serviceCategory1 = new ServiceCategory();
        ArrayList<Partner> partnerList1 = new ArrayList<>();
        serviceCategory1.setPartnerList(partnerList1);
        serviceCategory1.setServiceCategoryId(123L);
        serviceCategory1.setServiceCategoryName("Service Category Name");
        ArrayList<Service> serviceList8 = new ArrayList<>();
        serviceCategory1.setServiceList(serviceList8);
        Partner partner7 = new Partner();
        partner7.setAccountId(account4);
        partner7.setAddress("42 Main St");
        partner7.setBirthDate("2020-03-01");
        partner7.setCity("Oxford");
        partner7.setCompanyPartnerId(companyPartner1);
        partner7.setDateIssue("2020-03-01");
        partner7.setDepartment("Department");
        partner7.setEmail("jane.doe@example.org");
        partner7.setFirstName("Jane");
        partner7.setGender("Gender");
        partner7.setLastName("Doe");
        partner7.setNumberIdCard("42");
        partner7.setPartnerId(123L);
        partner7.setPhone("4105551212");
        partner7.setPlaceIssue("Place Issue");
        partner7.setPosition("Position");
        partner7.setServiceCategoryId(serviceCategory1);
        ArrayList<Service> serviceList9 = new ArrayList<>();
        partner7.setServiceList(serviceList9);
        Role role5 = new Role();
        ArrayList<Account> accountList5 = new ArrayList<>();
        role5.setAccountList(accountList5);
        role5.setRoleId(123);
        role5.setRoleName("Role Name");
        Partner partner8 = new Partner();
        partner8.setAccountId(new Account());
        partner8.setAddress("42 Main St");
        partner8.setBirthDate("2020-03-01");
        partner8.setCity("Oxford");
        partner8.setCompanyPartnerId(new CompanyPartner());
        partner8.setDateIssue("2020-03-01");
        partner8.setDepartment("Department");
        partner8.setEmail("jane.doe@example.org");
        partner8.setFirstName("Jane");
        partner8.setGender("Gender");
        partner8.setLastName("Doe");
        partner8.setNumberIdCard("42");
        partner8.setPartnerId(123L);
        partner8.setPhone("4105551212");
        partner8.setPlaceIssue("Place Issue");
        partner8.setPosition("Position");
        partner8.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList10 = new ArrayList<>();
        partner8.setServiceList(serviceList10);
        Role role6 = new Role();
        ArrayList<Account> accountList6 = new ArrayList<>();
        role6.setAccountList(accountList6);
        role6.setRoleId(123);
        role6.setRoleName("Role Name");
        User user5 = new User();
        user5.setAccountId(new Account());
        user5.setAddress("42 Main St");
        user5.setBirthDate("2020-03-01");
        user5.setCity("Oxford");
        user5.setFirstName("Jane");
        user5.setGender("Gender");
        user5.setIsPrivate(true);
        user5.setLastName("Doe");
        user5.setPhone("4105551212");
        user5.setRankPoint(1);
        user5.setUserId(123L);
        Account account5 = new Account();
        account5.setAccountId(1234567890L);
        ArrayList<Comment> commentList5 = new ArrayList<>();
        account5.setCommentList(commentList5);
        account5.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList8 = new ArrayList<>();
        account5.setFeedbackList(feedbackList8);
        account5.setIsBlock(true);
        account5.setPartner(partner8);
        account5.setPassWord("Pass Word");
        account5.setRoleId(role6);
        ArrayList<Tour> tourList7 = new ArrayList<>();
        account5.setTourList(tourList7);
        account5.setUser(user5);
        ArrayList<UserBooking> userBookingList8 = new ArrayList<>();
        account5.setUserBookingList(userBookingList8);
        User user6 = new User();
        user6.setAccountId(account5);
        user6.setAddress("42 Main St");
        user6.setBirthDate("2020-03-01");
        user6.setCity("Oxford");
        user6.setFirstName("Jane");
        user6.setGender("Gender");
        user6.setIsPrivate(true);
        user6.setLastName("Doe");
        user6.setPhone("4105551212");
        user6.setRankPoint(1);
        user6.setUserId(123L);
        Account account6 = new Account();
        account6.setAccountId(1234567890L);
        ArrayList<Comment> commentList6 = new ArrayList<>();
        account6.setCommentList(commentList6);
        account6.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList9 = new ArrayList<>();
        account6.setFeedbackList(feedbackList9);
        account6.setIsBlock(true);
        account6.setPartner(partner7);
        account6.setPassWord("Pass Word");
        account6.setRoleId(role5);
        ArrayList<Tour> tourList8 = new ArrayList<>();
        account6.setTourList(tourList8);
        account6.setUser(user6);
        ArrayList<UserBooking> userBookingList9 = new ArrayList<>();
        account6.setUserBookingList(userBookingList9);
        actualTour.setAccountId(account6);
        actualTour.setDeposit(10.0f);
        actualTour.setEndPlace("End Place");
        LocalTime ofResult = LocalTime.of(1, 1);
        actualTour.setEndTime(ofResult);
        ArrayList<Feedback> feedbackList10 = new ArrayList<>();
        actualTour.setFeedbackList(feedbackList10);
        actualTour.setMaxAdult(3);
        actualTour.setMaxChildren(3);
        actualTour.setMinAdult(1);
        actualTour.setMinChildren(1);
        actualTour.setMinToStart(1);
        actualTour.setNote("Note");
        actualTour.setNumberOfDay(10);
        actualTour.setNumberOfNight(10);
        actualTour.setPriceAdult(10.0f);
        actualTour.setPriceChildren(10.0f);
        LocalDate ofEpochDayResult = LocalDate.ofEpochDay(1L);
        actualTour.setStartDate(ofEpochDayResult);
        actualTour.setStartPlace("Start Place");
        LocalTime ofResult1 = LocalTime.of(1, 1);
        actualTour.setStartTime(ofResult1);
        actualTour.setStatus(1);
        actualTour.setTotalPrice(10.0f);
        TourCategory tourCategory2 = new TourCategory();
        tourCategory2.setTourCategoryId(123L);
        tourCategory2.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList9 = new ArrayList<>();
        tourCategory2.setTourList(tourList9);
        actualTour.setTourCategoryId(tourCategory2);
        actualTour.setTourCode("Tour Code");
        Partner partner9 = new Partner();
        partner9.setAccountId(new Account());
        partner9.setAddress("42 Main St");
        partner9.setBirthDate("2020-03-01");
        partner9.setCity("Oxford");
        partner9.setCompanyPartnerId(new CompanyPartner());
        partner9.setDateIssue("2020-03-01");
        partner9.setDepartment("Department");
        partner9.setEmail("jane.doe@example.org");
        partner9.setFirstName("Jane");
        partner9.setGender("Gender");
        partner9.setLastName("Doe");
        partner9.setNumberIdCard("42");
        partner9.setPartnerId(123L);
        partner9.setPhone("4105551212");
        partner9.setPlaceIssue("Place Issue");
        partner9.setPosition("Position");
        partner9.setServiceCategoryId(new ServiceCategory());
        ArrayList<Service> serviceList11 = new ArrayList<>();
        partner9.setServiceList(serviceList11);
        Role role7 = new Role();
        ArrayList<Account> accountList7 = new ArrayList<>();
        role7.setAccountList(accountList7);
        role7.setRoleId(123);
        role7.setRoleName("Role Name");
        User user7 = new User();
        user7.setAccountId(new Account());
        user7.setAddress("42 Main St");
        user7.setBirthDate("2020-03-01");
        user7.setCity("Oxford");
        user7.setFirstName("Jane");
        user7.setGender("Gender");
        user7.setIsPrivate(true);
        user7.setLastName("Doe");
        user7.setPhone("4105551212");
        user7.setRankPoint(1);
        user7.setUserId(123L);
        Account account7 = new Account();
        account7.setAccountId(1234567890L);
        ArrayList<Comment> commentList7 = new ArrayList<>();
        account7.setCommentList(commentList7);
        account7.setEmail("jane.doe@example.org");
        ArrayList<Feedback> feedbackList11 = new ArrayList<>();
        account7.setFeedbackList(feedbackList11);
        account7.setIsBlock(true);
        account7.setPartner(partner9);
        account7.setPassWord("Pass Word");
        account7.setRoleId(role7);
        ArrayList<Tour> tourList10 = new ArrayList<>();
        account7.setTourList(tourList10);
        account7.setUser(user7);
        ArrayList<UserBooking> userBookingList10 = new ArrayList<>();
        account7.setUserBookingList(userBookingList10);
        TourCategory tourCategory3 = new TourCategory();
        tourCategory3.setTourCategoryId(123L);
        tourCategory3.setTourCategoryName("Tour Category Name");
        ArrayList<Tour> tourList11 = new ArrayList<>();
        tourCategory3.setTourList(tourList11);
        Tour tour2 = new Tour();
        tour2.setAccountId(new Account());
        tour2.setDeposit(10.0f);
        tour2.setEndPlace("End Place");
        tour2.setEndTime(null);
        ArrayList<Feedback> feedbackList12 = new ArrayList<>();
        tour2.setFeedbackList(feedbackList12);
        tour2.setMaxAdult(3);
        tour2.setMaxChildren(3);
        tour2.setMinAdult(1);
        tour2.setMinChildren(1);
        tour2.setMinToStart(1);
        tour2.setNote("Note");
        tour2.setNumberOfDay(10);
        tour2.setNumberOfNight(10);
        tour2.setPriceAdult(10.0f);
        tour2.setPriceChildren(10.0f);
        tour2.setStartDate(null);
        tour2.setStartPlace("Start Place");
        tour2.setStartTime(null);
        tour2.setStatus(1);
        tour2.setTotalPrice(10.0f);
        tour2.setTourCategoryId(new TourCategory());
        tour2.setTourCode("Tour Code");
        tour2.setTourDetail(new TourDetail());
        tour2.setTourId(123L);
        tour2.setTourMode(true);
        tour2.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList3 = new ArrayList<>();
        tour2.setTourScheduleList(tourScheduleList3);
        tour2.setTourType(1);
        ArrayList<UserBooking> userBookingList11 = new ArrayList<>();
        tour2.setUserBookingList(userBookingList11);
        TourDetail tourDetail2 = new TourDetail();
        tourDetail2.setAddressStart("42 Main St");
        tourDetail2.setDescription("The characteristics of someone or something");
        tourDetail2.setGeneralTerms("General Terms");
        tourDetail2.setLatitude(10.0f);
        tourDetail2.setLongitude(10.0f);
        tourDetail2.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList2 = new ArrayList<>();
        tourDetail2.setTagOfTourList(tagOfTourList2);
        tourDetail2.setTourDetailId(123L);
        tourDetail2.setTourId(tour2);
        tourDetail2.setTourInclude("Tour Include");
        tourDetail2.setTourIntroduce("Tour Introduce");
        tourDetail2.setTourNonInclude("Tour Non Include");
        Tour tour3 = new Tour();
        tour3.setAccountId(account7);
        tour3.setDeposit(10.0f);
        tour3.setEndPlace("End Place");
        tour3.setEndTime(LocalTime.of(1, 1));
        ArrayList<Feedback> feedbackList13 = new ArrayList<>();
        tour3.setFeedbackList(feedbackList13);
        tour3.setMaxAdult(3);
        tour3.setMaxChildren(3);
        tour3.setMinAdult(1);
        tour3.setMinChildren(1);
        tour3.setMinToStart(1);
        tour3.setNote("Note");
        tour3.setNumberOfDay(10);
        tour3.setNumberOfNight(10);
        tour3.setPriceAdult(10.0f);
        tour3.setPriceChildren(10.0f);
        tour3.setStartDate(LocalDate.ofEpochDay(1L));
        tour3.setStartPlace("Start Place");
        tour3.setStartTime(LocalTime.of(1, 1));
        tour3.setStatus(1);
        tour3.setTotalPrice(10.0f);
        tour3.setTourCategoryId(tourCategory3);
        tour3.setTourCode("Tour Code");
        tour3.setTourDetail(tourDetail2);
        tour3.setTourId(123L);
        tour3.setTourMode(true);
        tour3.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList4 = new ArrayList<>();
        tour3.setTourScheduleList(tourScheduleList4);
        tour3.setTourType(1);
        ArrayList<UserBooking> userBookingList12 = new ArrayList<>();
        tour3.setUserBookingList(userBookingList12);
        TourDetail tourDetail3 = new TourDetail();
        tourDetail3.setAddressStart("42 Main St");
        tourDetail3.setDescription("The characteristics of someone or something");
        tourDetail3.setGeneralTerms("General Terms");
        tourDetail3.setLatitude(10.0f);
        tourDetail3.setLongitude(10.0f);
        tourDetail3.setMoreDescription("More Description");
        ArrayList<TagOfTour> tagOfTourList3 = new ArrayList<>();
        tourDetail3.setTagOfTourList(tagOfTourList3);
        tourDetail3.setTourDetailId(123L);
        tourDetail3.setTourId(tour3);
        tourDetail3.setTourInclude("Tour Include");
        tourDetail3.setTourIntroduce("Tour Introduce");
        tourDetail3.setTourNonInclude("Tour Non Include");
        actualTour.setTourDetail(tourDetail3);
        actualTour.setTourId(123L);
        actualTour.setTourMode(true);
        actualTour.setTourName("Tour Name");
        ArrayList<TourSchedule> tourScheduleList5 = new ArrayList<>();
        actualTour.setTourScheduleList(tourScheduleList5);
        actualTour.setTourType(1);
        ArrayList<UserBooking> userBookingList13 = new ArrayList<>();
        actualTour.setUserBookingList(userBookingList13);
        assertSame(account6, actualTour.getAccountId());
        assertEquals(10.0f, actualTour.getDeposit().floatValue());
        assertEquals("End Place", actualTour.getEndPlace());
        assertSame(ofResult, actualTour.getEndTime());
        List<Feedback> feedbackList14 = actualTour.getFeedbackList();
        assertSame(feedbackList10, feedbackList14);
        assertEquals(commentList2, feedbackList14);
        assertEquals(feedbackList2, feedbackList14);
        assertEquals(commentList, feedbackList14);
        assertEquals(feedbackList, feedbackList14);
        assertEquals(serviceList, feedbackList14);
        assertEquals(accountList, feedbackList14);
        assertEquals(tourList, feedbackList14);
        assertEquals(userBookingList, feedbackList14);
        assertEquals(serviceList1, feedbackList14);
        assertEquals(partnerList, feedbackList14);
        assertEquals(serviceList2, feedbackList14);
        assertEquals(serviceList3, feedbackList14);
        assertEquals(accountList1, feedbackList14);
        assertEquals(tourList2, feedbackList14);
        assertEquals(commentList1, feedbackList14);
        assertEquals(feedbackList1, feedbackList14);
        assertEquals(serviceList4, feedbackList14);
        assertEquals(accountList2, feedbackList14);
        assertEquals(tourList1, feedbackList14);
        assertEquals(userBookingList1, feedbackList14);
        assertEquals(userBookingList2, feedbackList14);
        assertEquals(tourList3, feedbackList14);
        assertEquals(tourScheduleList, feedbackList14);
        assertEquals(tagOfTourList1, feedbackList14);
        assertEquals(commentList3, feedbackList14);
        assertEquals(feedbackList3, feedbackList14);
        assertEquals(serviceList5, feedbackList14);
        assertEquals(accountList3, feedbackList14);
        assertEquals(tourList4, feedbackList14);
        assertEquals(userBookingList3, feedbackList14);
        assertEquals(feedbackList5, feedbackList14);
        assertEquals(tourList5, feedbackList14);
        assertEquals(tagOfTourList, feedbackList14);
        assertEquals(feedbackList4, feedbackList14);
        assertEquals(tourScheduleList1, feedbackList14);
        assertEquals(userBookingList4, feedbackList14);
        assertEquals(tourScheduleList2, feedbackList14);
        assertEquals(userBookingList5, feedbackList14);
        assertEquals(userBookingList6, feedbackList14);
        assertEquals(feedbackList6, feedbackList14);
        assertEquals(commentList6, feedbackList14);
        assertEquals(feedbackList9, feedbackList14);
        assertEquals(commentList4, feedbackList14);
        assertEquals(feedbackList7, feedbackList14);
        assertEquals(serviceList6, feedbackList14);
        assertEquals(accountList4, feedbackList14);
        assertEquals(tourList6, feedbackList14);
        assertEquals(userBookingList7, feedbackList14);
        assertEquals(serviceList7, feedbackList14);
        assertEquals(partnerList1, feedbackList14);
        assertEquals(serviceList8, feedbackList14);
        assertEquals(serviceList9, feedbackList14);
        assertEquals(accountList5, feedbackList14);
        assertEquals(tourList8, feedbackList14);
        assertEquals(commentList5, feedbackList14);
        assertEquals(feedbackList8, feedbackList14);
        assertEquals(serviceList10, feedbackList14);
        assertEquals(accountList6, feedbackList14);
        assertEquals(tourList7, feedbackList14);
        assertEquals(userBookingList8, feedbackList14);
        assertEquals(userBookingList9, feedbackList14);
        assertEquals(tourList9, feedbackList14);
        assertEquals(tagOfTourList3, feedbackList14);
        assertEquals(commentList7, feedbackList14);
        assertEquals(feedbackList11, feedbackList14);
        assertEquals(serviceList11, feedbackList14);
        assertEquals(accountList7, feedbackList14);
        assertEquals(tourList10, feedbackList14);
        assertEquals(userBookingList10, feedbackList14);
        assertEquals(feedbackList13, feedbackList14);
        assertEquals(tourList11, feedbackList14);
        assertEquals(tagOfTourList2, feedbackList14);
        assertEquals(feedbackList12, feedbackList14);
        assertEquals(tourScheduleList3, feedbackList14);
        assertEquals(userBookingList11, feedbackList14);
        assertEquals(tourScheduleList4, feedbackList14);
        assertEquals(userBookingList12, feedbackList14);
        assertEquals(tourScheduleList5, feedbackList14);
        List<UserBooking> userBookingList14 = actualTour.getUserBookingList();
        assertEquals(userBookingList14, feedbackList14);
        assertEquals(3, actualTour.getMaxAdult().intValue());
        assertEquals(3, actualTour.getMaxChildren().intValue());
        assertEquals(1, actualTour.getMinAdult().intValue());
        assertEquals(1, actualTour.getMinChildren().intValue());
        assertEquals(1, actualTour.getMinToStart().intValue());
        assertEquals("Note", actualTour.getNote());
        assertEquals(10, actualTour.getNumberOfDay().intValue());
        assertEquals(10, actualTour.getNumberOfNight().intValue());
        assertEquals(10.0f, actualTour.getPriceAdult().floatValue());
        assertEquals(10.0f, actualTour.getPriceChildren().floatValue());
        assertSame(ofEpochDayResult, actualTour.getStartDate());
        assertEquals("Start Place", actualTour.getStartPlace());
        assertSame(ofResult1, actualTour.getStartTime());
        assertEquals(1, actualTour.getStatus().intValue());
        assertEquals(10.0f, actualTour.getTotalPrice().floatValue());
        assertSame(tourCategory2, actualTour.getTourCategoryId());
        assertEquals("Tour Code", actualTour.getTourCode());
        assertSame(tourDetail3, actualTour.getTourDetail());
        assertEquals(123L, actualTour.getTourId().longValue());
        assertTrue(actualTour.getTourMode());
        assertEquals("Tour Name", actualTour.getTourName());
        List<TourSchedule> tourScheduleList6 = actualTour.getTourScheduleList();
        assertSame(tourScheduleList5, tourScheduleList6);
        assertEquals(commentList2, tourScheduleList6);
        assertEquals(feedbackList2, tourScheduleList6);
        assertEquals(commentList, tourScheduleList6);
        assertEquals(feedbackList, tourScheduleList6);
        assertEquals(serviceList, tourScheduleList6);
        assertEquals(accountList, tourScheduleList6);
        assertEquals(tourList, tourScheduleList6);
        assertEquals(userBookingList, tourScheduleList6);
        assertEquals(serviceList1, tourScheduleList6);
        assertEquals(partnerList, tourScheduleList6);
        assertEquals(serviceList2, tourScheduleList6);
        assertEquals(serviceList3, tourScheduleList6);
        assertEquals(accountList1, tourScheduleList6);
        assertEquals(tourList2, tourScheduleList6);
        assertEquals(commentList1, tourScheduleList6);
        assertEquals(feedbackList1, tourScheduleList6);
        assertEquals(serviceList4, tourScheduleList6);
        assertEquals(accountList2, tourScheduleList6);
        assertEquals(tourList1, tourScheduleList6);
        assertEquals(userBookingList1, tourScheduleList6);
        assertEquals(userBookingList2, tourScheduleList6);
        assertEquals(tourList3, tourScheduleList6);
        assertEquals(tourScheduleList, tourScheduleList6);
        assertEquals(tagOfTourList1, tourScheduleList6);
        assertEquals(commentList3, tourScheduleList6);
        assertEquals(feedbackList3, tourScheduleList6);
        assertEquals(serviceList5, tourScheduleList6);
        assertEquals(accountList3, tourScheduleList6);
        assertEquals(tourList4, tourScheduleList6);
        assertEquals(userBookingList3, tourScheduleList6);
        assertEquals(feedbackList5, tourScheduleList6);
        assertEquals(tourList5, tourScheduleList6);
        assertEquals(tagOfTourList, tourScheduleList6);
        assertEquals(feedbackList4, tourScheduleList6);
        assertEquals(tourScheduleList1, tourScheduleList6);
        assertEquals(userBookingList4, tourScheduleList6);
        assertEquals(tourScheduleList2, tourScheduleList6);
        assertEquals(userBookingList5, tourScheduleList6);
        assertEquals(userBookingList6, tourScheduleList6);
        assertEquals(feedbackList6, tourScheduleList6);
        assertEquals(commentList6, tourScheduleList6);
        assertEquals(feedbackList9, tourScheduleList6);
        assertEquals(commentList4, tourScheduleList6);
        assertEquals(feedbackList7, tourScheduleList6);
        assertEquals(serviceList6, tourScheduleList6);
        assertEquals(accountList4, tourScheduleList6);
        assertEquals(tourList6, tourScheduleList6);
        assertEquals(userBookingList7, tourScheduleList6);
        assertEquals(serviceList7, tourScheduleList6);
        assertEquals(partnerList1, tourScheduleList6);
        assertEquals(serviceList8, tourScheduleList6);
        assertEquals(serviceList9, tourScheduleList6);
        assertEquals(accountList5, tourScheduleList6);
        assertEquals(tourList8, tourScheduleList6);
        assertEquals(commentList5, tourScheduleList6);
        assertEquals(feedbackList8, tourScheduleList6);
        assertEquals(serviceList10, tourScheduleList6);
        assertEquals(accountList6, tourScheduleList6);
        assertEquals(tourList7, tourScheduleList6);
        assertEquals(userBookingList8, tourScheduleList6);
        assertEquals(userBookingList9, tourScheduleList6);
        assertEquals(tourList9, tourScheduleList6);
        assertEquals(tagOfTourList3, tourScheduleList6);
        assertEquals(commentList7, tourScheduleList6);
        assertEquals(feedbackList11, tourScheduleList6);
        assertEquals(serviceList11, tourScheduleList6);
        assertEquals(accountList7, tourScheduleList6);
        assertEquals(tourList10, tourScheduleList6);
        assertEquals(userBookingList10, tourScheduleList6);
        assertEquals(feedbackList13, tourScheduleList6);
        assertEquals(tourList11, tourScheduleList6);
        assertEquals(tagOfTourList2, tourScheduleList6);
        assertEquals(feedbackList12, tourScheduleList6);
        assertEquals(tourScheduleList3, tourScheduleList6);
        assertEquals(userBookingList11, tourScheduleList6);
        assertEquals(tourScheduleList4, tourScheduleList6);
        assertEquals(userBookingList12, tourScheduleList6);
        assertEquals(feedbackList14, tourScheduleList6);
        assertEquals(userBookingList14, tourScheduleList6);
        assertEquals(1, actualTour.getTourType().intValue());
        assertSame(userBookingList13, userBookingList14);
        assertEquals(commentList2, userBookingList14);
        assertEquals(feedbackList2, userBookingList14);
        assertEquals(commentList, userBookingList14);
        assertEquals(feedbackList, userBookingList14);
        assertEquals(serviceList, userBookingList14);
        assertEquals(accountList, userBookingList14);
        assertEquals(tourList, userBookingList14);
        assertEquals(userBookingList, userBookingList14);
        assertEquals(serviceList1, userBookingList14);
        assertEquals(partnerList, userBookingList14);
        assertEquals(serviceList2, userBookingList14);
        assertEquals(serviceList3, userBookingList14);
        assertEquals(accountList1, userBookingList14);
        assertEquals(tourList2, userBookingList14);
        assertEquals(commentList1, userBookingList14);
        assertEquals(feedbackList1, userBookingList14);
        assertEquals(serviceList4, userBookingList14);
        assertEquals(accountList2, userBookingList14);
        assertEquals(tourList1, userBookingList14);
        assertEquals(userBookingList1, userBookingList14);
        assertEquals(userBookingList2, userBookingList14);
        assertEquals(tourList3, userBookingList14);
        assertEquals(tourScheduleList, userBookingList14);
        assertEquals(tagOfTourList1, userBookingList14);
        assertEquals(commentList3, userBookingList14);
        assertEquals(feedbackList3, userBookingList14);
        assertEquals(serviceList5, userBookingList14);
        assertEquals(accountList3, userBookingList14);
        assertEquals(tourList4, userBookingList14);
        assertEquals(userBookingList3, userBookingList14);
        assertEquals(feedbackList5, userBookingList14);
        assertEquals(tourList5, userBookingList14);
        assertEquals(tagOfTourList, userBookingList14);
        assertEquals(feedbackList4, userBookingList14);
        assertEquals(tourScheduleList1, userBookingList14);
        assertEquals(userBookingList4, userBookingList14);
        assertEquals(tourScheduleList2, userBookingList14);
        assertEquals(userBookingList5, userBookingList14);
        assertEquals(userBookingList6, userBookingList14);
        assertEquals(feedbackList6, userBookingList14);
        assertEquals(commentList6, userBookingList14);
        assertEquals(feedbackList9, userBookingList14);
        assertEquals(commentList4, userBookingList14);
        assertEquals(feedbackList7, userBookingList14);
        assertEquals(serviceList6, userBookingList14);
        assertEquals(accountList4, userBookingList14);
        assertEquals(tourList6, userBookingList14);
        assertEquals(userBookingList7, userBookingList14);
        assertEquals(serviceList7, userBookingList14);
        assertEquals(partnerList1, userBookingList14);
        assertEquals(serviceList8, userBookingList14);
        assertEquals(serviceList9, userBookingList14);
        assertEquals(accountList5, userBookingList14);
        assertEquals(tourList8, userBookingList14);
        assertEquals(commentList5, userBookingList14);
        assertEquals(feedbackList8, userBookingList14);
        assertEquals(serviceList10, userBookingList14);
        assertEquals(accountList6, userBookingList14);
        assertEquals(tourList7, userBookingList14);
        assertEquals(userBookingList8, userBookingList14);
        assertEquals(userBookingList9, userBookingList14);
        assertEquals(feedbackList10, userBookingList14);
        assertEquals(tourList9, userBookingList14);
        assertEquals(tagOfTourList3, userBookingList14);
        assertEquals(commentList7, userBookingList14);
        assertEquals(feedbackList11, userBookingList14);
        assertEquals(serviceList11, userBookingList14);
        assertEquals(accountList7, userBookingList14);
        assertEquals(tourList10, userBookingList14);
        assertEquals(userBookingList10, userBookingList14);
        assertEquals(feedbackList13, userBookingList14);
        assertEquals(tourList11, userBookingList14);
        assertEquals(tagOfTourList2, userBookingList14);
        assertEquals(feedbackList12, userBookingList14);
        assertEquals(tourScheduleList3, userBookingList14);
        assertEquals(userBookingList11, userBookingList14);
        assertEquals(tourScheduleList4, userBookingList14);
        assertEquals(userBookingList12, userBookingList14);
        assertEquals(tourScheduleList5, userBookingList14);
    }
}

